### ISSUE TITLE
[Feature] Update Trakt-library automatically

### ISSUE THREAD

**Issue by eyk107** [jurialmunkey/plugin.video.themoviedb.helper#1000]
### Describe the feature that you'd like

It would be nice to run the sync automaticlly every hour or after watching content of the library.

### Why is this feature needed? What problem does it solve?

It is possible to update the Trakt-library manually or at a specific time (e.g. 12AM). But my device is not running 24/7 and so it will not sync the library when it is not running. It would be nice to run the sync automaticlly every hour or after watching content of the library to get the "watched"-status on all other devices

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Updating your library has nothing to do with watched status. That is not what the library function does. 

All the library update function does is adds items from a Trakt list to your library so that you have links to TMDbHelper player functionality from the library for those items. That is all. It has nothing to do with watched status syncing.
