### ISSUE TITLE
[BUG] Metadata in the wrong place

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1006]
### Describe the bug

In many addons when is focus on search menu or genres or some other it shows data from some movies and it shouldn't do that.
Here, for example, I enter in elementum and when the focus is on the search icon, it displays data from the movie.
![Untitled1](https://user-images.githubusercontent.com/74268331/218729923-22d0d0d3-38ae-42a1-ac8e-c4b9071e7c46.png)
Here the focus is on the action icon and it shows the data from the movie again.
![Untitled2](https://user-images.githubusercontent.com/74268331/218730323-5a19a7c1-fc42-42a1-812c-557400a1c51d.png)
I started ah2 to show you, but the same thing happens with my skin, titan bingie mod.

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Probably addon setting incorrect dbtype or container content.

What is listitem.dbtype and container.content here?

Not much I can do if plugin authors use the wrong content type

**Comment by matke-84** [comment]
Hmmm. I didn't have this problem while using the skin helper service. Also, it doesn't just happen in this situation. For example, if the focus is on the next page button, some metadata is also obtained, and it should not be, and not only in this addon.

**Comment by jurialmunkey** [comment]
Again, what is the ListItem.DBType and container.content here? I don't use this addon.

TMDbHelper is not SkinHelper... Why is what SkinHelper does relevant at all? These addons do not share code.

**Comment by matke-84** [comment]
I have no idea. How can I check? The addon is not written in Python. But let's say in Fen, when I'm in the container where the movies are, when the focus is on the next page button, I get some nonsensical plot.
I used the skin helper service for all metadata. Then I switched to tmdb helper. What do you mean it's not relevant? Aren't they both doing the same job in the field of monitoring and scraping data?

**Comment by jurialmunkey** [comment]
> I have no idea. How can I check?

The normal way you check any infolabel in a skin
```
$INFO[Container.Content]
$INFO[ListItem.DBType]
```

> What do you mean it's not relevant? Aren't they both doing the same job in the field of monitoring and scraping data?

Horses and cars can both be used to pull wagons and transport people. It doesn't mean you should feed a horse petrol or fill a car with hay and expect it to work. Two things can have a similar function and output but require very different inputs and setup.

**Comment by matke-84** [comment]
Sorry for the late reply. I completely misunderstood what you needed.
In the example for the elementum, container content is movies, listitem dbtype is empty.
For example in fen, when I enter the folder with movies, when the focus is on the next button, I also get some plot text, listitem dbtype is empty.
![fen](https://user-images.githubusercontent.com/74268331/223640506-936c1fa1-b970-4036-b9a9-7515db53888d.png)
It very often happens when I move to the next page with the next button (even in tmdb helper) that some information remains visible for a second or two and then disappears.
It's a bit of a strange situation, because if I restrict the display plot or any other listitem (which I use from tmdb helper) only for movies and tv shows, I don't have this problems. Ok if it has to be like this, but it would be great if it could be solved on tmdb helper side as well.
I understand that tmdb helper and skin helper service are different plugins, but still they share some similar features, that's why I compared them.

**Comment by jurialmunkey** [comment]
>  In the example for the elementum, container content is movies, listitem dbtype is empty.

In this instance, it is a case of wrong container content type. The plugin is setting "movies" so TMDbHelper is looking up movies. You can see it is picking matches of popular movies close to the name (e.g. Last Action Hero for Action)

There's not much I can do about plugins not setting correct content type.

The genres directory should have container content of "genres" not "movies"
The base dir directory with search should have container content as "none" not "movies".

>  For example in fen, when I enter the folder with movies, when the focus is on the next button, I also get some plot text, listitem dbtype is empty.

This one is TMDbHelper's fault but a bit difficult to manage.

TMDbHelper does check if the label is "Next page" and will ignore if it is. However, it needs to be an exact match. As you can see in the screenshot, the page item is "Next page (2) >>>" so it doesn't match.

I could probably do a string.startswith() here for this scenario. There's no great solution but it is possibly better than nothing.

>  It very often happens when I move to the next page with the next button (even in tmdb helper) that some information remains visible for a second or two and then disappears.

This happens with all items, you just don't notice it as much going between two movie items because the metadata is being updated rather than cleared. 

There is no solution from TMDbHelper's side because if there is any hold up then it must wait for the previous process to finish before it can begin clearing the item.
