### ISSUE TITLE
[BUG] Unable to filter by language

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1009]
`plugin://plugin.video.themoviedb.helper/?info=trakt_anticipated&amp;tmdb_type=tv&amp;filter_key=language.1.iso&amp;filter_value=en`

I'm pretty sure this use to work, returning only English language shows, but now it doesn't. Could this be a bug or am I doing something wrong?

**Comment by jurialmunkey** [comment]
Try add `&detailed=true` to the path. Iterative properties are only added to items if the flag is specified.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Additional-Params#additional-widget-parameters
 

Sometimes kodi hits a random bottleneck with setproperties (most items fast then one randomly will take 500ms to use setproperties) so I try to minimise that by limiting how many need to be added.

**Comment by roidy** [comment]
D'oh! My bad, I completely forgot `detailed` needs to be set. Thanks 👍

**Comment by roidy** [comment]
Quick follow up, does `without_genres` work for Trakt lists?

The following doesn't work:-

`plugin://plugin.video.themoviedb.helper/?info=trakt_anticipated&amp;tmdb_type=tv&amp;detailed=true&amp;with_id=true&amp;without_genres=99 / 10763 / 10764 / 10767&amp;with_separator=OR`

**Comment by jurialmunkey** [comment]
with_ and without_ are specific to TMDb discover

you can do an exclusion filter though:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Lists-Additional-Params#optional-exclusion-and-filter-parameters

`&amp;exclude_key=genre&amp;exclude_value=Documentary / News / Reality / Talk`

Should exclude any items with any of those genres. The exclusion filter is applied ~both before and~ after pagination + item details lookup. ~However, since Trakt lists don't have genres supplied in the intitial list then this will only happen after pagination in this case~ EDIT: Correction -- Not applied before on this particular list but ultimately same point still stands.

**Comment by roidy** [comment]
Thanks 👍
