### ISSUE TITLE
[BUG] Episodes Missing OMDb Ratings

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/plugin.video.themoviedb.helper#1013]
### Describe the bug

After the update from Matrix to Nexus, any episodes not previously cached only display Trakt and TMDb ratings, typically with TMDb showing 0. Ratings such as IMDb and Awards don't appear. Not sure if TMDbHelper or Arctic Horizon 2. My guess was TMDbHelper due to the changes in tmdb_id. 

The ratings populate fine for shows and movies, it is just episodes in particular. My OMDb key is filled in, and it's definitely not reached the API limit, because a new movie query still showed IMDb and Rotten Tomatoes.

Any episodes from before the update that are still in my widgets still contain the OMDb ratings.

There was a previous bug mentioning ratings missing for episodes, but it is resolved, and does not appear to have the same cause.

TMDbHelper version: v5.0.53~nexus
Arctic Horizon 2 version: v0.8.9

### Steps To Reproduce

1. Browse to episodes in a show list.
2. Check the ratings for the inidivual episodes.
3. Episodes not previously cached are missing data. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [x] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Debug log? Ratings work perfectly fine for me. 

It is worth deleting your entire tmdbhelper database cache and going for a fresh start.
Close Kodi
Delete userdata/addon_data/plugin.video.themoviedb.helper/database_v6
Start Kodi

Also make certain that you're running the Nexus version of TMDbhelper. It will have ~nexus on the end of the version number.

Due to the way Kodi versioning works, the matrix version currently has a higher version. My repo wont automatically install the nexus version if you updated Kodi over the top of an existing install and the matrix version is there.

The recent additions to the tmdb ID lookup shouldn't affect anything *unless* your library scraper or plugin is putting the wrong ID in the field. If it is blank, tmdbhelper uses the previous lookup method. The only reason there was the issue for matrix player originally is because the function didn't exist at all so it raised an exception which stopped the script. The ID being blank won't do that, it will just fall back to the old lookup method.

**Comment by Kayzels** [comment]
[Log file](https://paste.kodi.tv/umevifuxux.kodi)

There was a lot of old stuff I no longer use that was having issues, but I got my Kodi cleaned up. It seems to be the rating lookup might have the wrong url.

It was not a cache issue - I deleted the folder you said above, but the same still happens.

It is not with all shows, though. Some shows find the rating, and others don't.

Ones that find the rating:
- House of the Dragon
- Critical Role
- Kaleidoscope

Ones that don't find the rating:
- Jack Ryan
- Julie and the Phantoms
- Once Upon a Time in Wonderland

**Comment by jurialmunkey** [comment]
Hmmm, are you looking at the above shows in that log? Because those 404 lookups are for things like "Ellen" and "Today Show" which would indicate that whatever addon you're using is putting the wrong ID in the tmdb field.

I assume you're able to get the output of `$INFO[ListItem.UniqueID(tmdb)]` -- could you get the value of it for these shows in the addon you're having problems with? Also maybe `$INFO[ListItem.TVShowTitle]` `$INFO[ListItem.Title]` and `$INFO[ListItem.Year]`. That will give a better indication of if it's an issue with the metadata in the plugin or if something else is going wrong.

My best guess is likely the plugin you're using is putting the TVDb ID into the TMDb field -- since they're both numbers you end up with the wrong thing.

These are all working for me using TMDbHelper to search.

![Screenshot_20230222_013706](https://user-images.githubusercontent.com/4618719/220507425-07bde013-7e86-4917-8217-d74274dd480e.png)

![Screenshot_20230222_013744](https://user-images.githubusercontent.com/4618719/220507432-72d1b621-c91f-4900-b2b5-7b8b73f70f27.png)

![Screenshot_20230222_013818](https://user-images.githubusercontent.com/4618719/220507443-c6d168d9-3130-4e96-b749-afc7986a047f.png)

**Comment by jurialmunkey** [comment]
Wait, is this in one of the calendar views for TMDbHelper? (e.g. Your Next Episodes, Last Fornight etc.). I realised I made the same dumb mistake I'm complaining about about putting the wrong ID into UniqueID(tmdb). 

Can you test v5.0.55 and see if that helps? You'll need to restart Kodi after updating to make sure the service monitor restarts.

For some reason in the calendar views I was overriding the episode ID with the tvshow ID. I'm assuming I had good reason for doing that originally but this new patch is the correct behaviour -- better to break things now and address subsequent issues that arise rather than working around it. I didn't see any breaking behaviour when testing. I have a feeling it's some legacy code for details lookup prior to when I added the item builder code but I forgot to remove it when I made those changes.

**Comment by xyzfre** [comment]
I see a new setting in TMDb for all API keys and Trakt,Allow 3rd party plugin access to API key/token , what is this setting for,, if using a plugin with TMDb for (example) like Fen is this something we should enable ,,thank you @jurialmunkey

**Comment by Kayzels** [comment]
> Wait, is this in one of the calendar views for TMDbHelper? (e.g. Your Next Episodes, Last Fornight etc.).

Yes, was with Your Next Episodes.

> Can you test v5.0.55 and see if that helps? You'll need to restart Kodi after updating to make sure the service monitor restarts.

Can confirm that this is fixed in v5.1.0.

> For some reason in the calendar views I was overriding the episode ID with the tvshow ID. I'm assuming I had good reason for doing that originally but this new patch is the correct behaviour -- better to break things now and address subsequent issues that arise rather than working around it. I didn't see any breaking behaviour when testing. I have a feeling it's some legacy code for details lookup prior to when I added the item builder code but I forgot to remove it when I made those changes.

I think this might have been to do with clearlogos. For episodes with their own ids, it wasn't finding the clearlogo associated with the show. I could be very wrong, though.

**Comment by jurialmunkey** [comment]
> I see a new setting in TMDb for all API keys and Trakt,Allow 3rd party plugin access to API key/token , what is this setting for,, if using a plugin with TMDb for (example) like Fen is this something we should enable ,,thank you @jurialmunkey

No you do not need to enable this setting and should not do so.

A recent PR allows TMDbhelper code to be reused by other plugins as a module. The setting  controls whether other plugins have permission to access the authentication token for your account when importing those modules. 

For instance, another plugin might decide to use Tmdbhelper's trakt module rather than write their own. The setting controls whether other plugins are permitted to access your account.

The feature is currently not used by any plugins and importing the trakt module is currently disabled, so there is no reason to enable the setting.

**Comment by jurialmunkey** [comment]
> > Wait, is this in one of the calendar views for TMDbHelper? (e.g. Your Next Episodes, Last Fornight etc.).
> 
> Yes, was with Your Next Episodes.
> 
> > Can you test v5.0.55 and see if that helps? You'll need to restart Kodi after updating to make sure the service monitor restarts.
> 
> Can confirm that this is fixed in v5.1.0.
> 
> > For some reason in the calendar views I was overriding the episode ID with the tvshow ID. I'm assuming I had good reason for doing that originally but this new patch is the correct behaviour -- better to break things now and address subsequent issues that arise rather than working around it. I didn't see any breaking behaviour when testing. I have a feeling it's some legacy code for details lookup prior to when I added the item builder code but I forgot to remove it when I made those changes.
> 
> I think this might have been to do with clearlogos. For episodes with their own ids, it wasn't finding the clearlogo associated with the show. I could be very wrong, though.

Yeah I assume I was using it to simplify a lookup somewhere. All the items have a separate tvshow id anyway (tvshow.tmdb) so I can easily get from the item details if something breaks somewhere.
