### ISSUE TITLE
[Feature] Action to force refresh widgets

### ISSUE THREAD

**Issue by sam-o** [jurialmunkey/plugin.video.themoviedb.helper#1023]
### Describe the feature that you'd like

Add the ability to force refresh a widget or all widgets as an action or part of an action.

Examples for use:
1. Setup an action on the TV Shows menu item that force refreshes all TV Shows widgets (or just all widgets across all menus). In particular this will update any newly added items to the Trakt watch list.
2. Setup an action on the TV Shows menu item that opens a list of TV shows with random genre and force refreshes each time. At the moment if you go back to the menu and run the action again the random genre is not updated. This would allow you to: 1. Run action to get list of tv shows with random genre. 2. If you don't like the genre, go back to the menu and run the action again to get a new randomised genre.

### Why is this feature needed? What problem does it solve?

1. When adding items to a Trakt watch list it can take a while for the widget to be updated because it doesn't refresh on it's own.
2. The randomised action caches the genre so if it is rerun without changing menu items the same results are presented instead of a fresh set of random results.

### Steps to reproduce.

Trakt Movies Still to Watch and TV shows Still to Watch refresh:
1. Setup a Movies Still to Watch or TV shows Still to Watch widget.
2. Add an item to your Trakt watch list from the phone app or website.
3. The Movies Still to Watch or TV shows Still to Watch widget is not updated automatically.

Randomised genre not refreshing:
1. Setup an action on a menu item to open the Random Movies Genre or Random TV shows Genre item.
2. Click on the menu item to open a list of random movies or TV shows from a random genre.
3. Return to the menu item and click it again. The same list is displayed for a while instead of showing a new list for a new genre.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You can refresh widgets by changing the property `TMDbHelper.Widgets.Reload` 
(as long as you haven't deleted this property from your widget path).

e.g. This action will force all your widgets to reload because the time will have changed:
`SetProperty(TMDbHelper.Widgets.Reload,$INFO[System.Time(hh:mm:ss)],Home)`

You can force Kodi to refresh a container path on re-entry using a similar trick by adding an `&reload=$INFO[System.Time(hh:mm:ss)]` to the shortcut action.

e.g. change your menu action shortcut like so:
`ActivateWindow(videos,"plugin://plugin.video.themoviedb.helper/?info=random_genres&tmdb_type=movie&reload=$INFO[System.Time(hh:mm:ss)]",return)`

Next time you open the path the time will have changed so Kodi will consider it a new directory and refresh the container listing. TMDbHelper ignores whatever is in the reload param so it won't affect TMDbHelper functionality at all.

**Comment by sam-o** [comment]
Thanks for the quick reply!

The force reload when activating a menu item worked.

FYI I couldn't get the refresh on re-entry working when adding &reload. It opened the Videos item instead of the random genres results. I'm happy with the force reload functionality so happy to close this.
