### ISSUE TITLE
[BUG] incorrect studio logos, trakt progress next episodes

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/plugin.video.themoviedb.helper#1033]
### Describe the bug

Hi there I originally posted this on the Auramod github and was told its a new bug with the tmdb service monitor so was advised to report the bug here, recently I've noticed my trakt next episodes are displaying incorrect studio logos, In the photos here "You" being a Netflix exclusive is showing Channel 4 and "Servant" being an Apple TV exclusive as BBC, I've been told version v5.0.47 was working as intended, I've attached some images

### Steps To Reproduce

Widget bar, and Netflix showcase view Auramod is the skin I'm using

### Screenshots and Additional Info

![20230321_222400](https://user-images.githubusercontent.com/76907836/226828420-891ae44b-3866-4340-9e35-7574c004e988.jpg)
![20230321_222438](https://user-images.githubusercontent.com/76907836/226828429-65ec3904-a79a-42c1-a16a-9200cfe72d1c.jpg)

Kind regards 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by inb4after** [comment]
https://github.com/SerpentDrago/skin.auramod/issues/282

Through testing, this is a bug with TMDBHelper service monitor and was introduced in TMDBHelper v5.0.52. The previous version v5.0.47 works as intended.

More specifically, a single line change in this commit is the cause:

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/207a62c6ce9bf24d5094eea58443b26666c961eb#diff-b603d8df897798deb41106c854019ab6abb61feb5c7d2fdba9334391608afc40R82

**Comment by jurialmunkey** [comment]
> More specifically, a single line change in this commit is the cause: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/207a62c6ce9bf24d5094eea58443b26666c961eb#diff-b603d8df897798deb41106c854019ab6abb61feb5c7d2fdba9334391608afc40R82


Unlikely. You're just changing the cache name and using old cached entries.


> "Servant" being an Apple TV exclusive as BBC,

This works fine for me

![screenshot00308](https://user-images.githubusercontent.com/4618719/226904161-d2e6e0b8-94ad-4acb-a216-0ef2a7ff5bd4.jpg)


>"You" being a Netflix exclusive

Incorrect. You is made by "Lifetime" in conjuction with Netflix
https://www.themoviedb.org/tv/78191-you

![Screenshot (3)](https://user-images.githubusercontent.com/4618719/226904818-eb5e19fb-aa86-4bea-a4f2-e298a4e18698.jpg)

**Comment by JFG1000** [comment]
Is there anything i can do my end to get rid of old cached entrires? They display fine on everything else apart from trakt progress

**Comment by JFG1000** [comment]
It also showed "the godfather of harlem" as ITV, I don't think that's correct

**Comment by jurialmunkey** [comment]
I'm not saying the issue is cached items, I'm saying that reverting that line in that commit is simply changing the cache back to previous version.

I cannot reproduce this problem using TMDbHelper.

If this issue began appearing with that commit then the likely culprit is the plugin you're using setting an incorrect value for ListITem.UniqueID(tmdb) because that commit change lookups to first use stored TMDb ID values from the item and then only do a lookup based upon name if no ID exists.

**Comment by jurialmunkey** [comment]
Most likely the plugin being used is putting the *tvshow* TMDb ID into the *episode* instead of the episode ID.

For instance, You's *tvshow* TMDb ID is 78191. However, the TMDb *episode* ID for 78191 corresponds to an episode for the TV Show Brookside:

```
{
  "url": "search/tmdb/78191?type=episode",
  "log_request": "trakt",
  "response": [
    {
      "type": "episode",
      "score": 1000,
      "episode": {
        "season": 22,
        "number": 33,
        "title": "Mutual Ground",
        "ids": {
          "trakt": 3374664,
          "tvdb": 7033976,
          "imdb": null,
          "tmdb": 78191,
          "tvrage": 552641
        }
      },
      "show": {
        "title": "Brookside",
        "year": 1982,
        "ids": {
          "trakt": 1515,
          "slug": "brookside",
          "tvdb": 71570,
          "imdb": "tt0083392",
          "tmdb": 1526,
          "tvrage": 114
        }
      }
    }
  ]
}
```


The TV Show Brookside is made by Channel 4
https://www.themoviedb.org/tv/1526-brookside



Likewise, the TV Show Servant has the TMDb ID 88055. However, because this list is designating an *episode* DBType that TMDb ID for that *episode* corresponds to the show "Softly, Softly". That show is made by the BBC
https://www.themoviedb.org/tv/1704-softly-softly

```
{
  "url": "search/tmdb/88055?type=episode",
  "log_request": "trakt",
  "response": [
    {
      "type": "episode",
      "score": 1000,
      "episode": {
        "season": 8,
        "number": 13,
        "title": "Conversion",
        "ids": {
          "trakt": 2443265,
          "tvdb": 280674,
          "imdb": null,
          "tmdb": 88055,
          "tvrage": 296935
        }
      },
      "show": {
        "title": "Softly, Softly",
        "year": 1966,
        "ids": {
          "trakt": 5072,
          "slug": "softly-softly",
          "tvdb": 78325,
          "imdb": "tt0129717",
          "tmdb": 1704,
          "tvrage": null
        }
      }
    }
  ]
}
```

TMDbHelper is functioning correctly. The end plugin is designating an *episode* with those IDs, so TMDbHelper is looking up those episode IDs.

**Comment by JFG1000** [comment]
Thanks for clarifying, I've reported this to Tiki with a link to this, so I'm hoping he can possibly take a look

**Comment by jurialmunkey** [comment]
BTW this can be easily addressed without changing the end plugin behaviour significantly by the end plugin simply also putting the tvshow TMDb ID in UniqueID(tvshow.tmdb) for episodes. 

If UniqueID(tvshow.tmdb) is available then TMDbHelper will use that directly instead of using UniqueID(tmdb) to lookup the episode and find the tvshow ID.

The "tvshow." prefix will indicate that the ID is for the parent tvshow and not the episode.

**Comment by JFG1000** [comment]
@jurialmunkey i finally made the switch to AH2 and I'm loving it, many thanks. Just out of curiosity is it normal for the picture to stutter when bringing up the osd menu during 4k video playback?

**Comment by jurialmunkey** [comment]
> @jurialmunkey i finally made the switch to AH2 and I'm loving it, many thanks. Just out of curiosity is it normal for the picture to stutter when bringing up the osd menu during 4k video playback?

I don't experience it personally but there's an issue about it on the AH2 github from other users. I'm not quite sure what the cause is but packing the media folder into a Textures.xbt does seem to help somewhat.

**Comment by JFG1000** [comment]
Is this something you could apply in an update?
