### ISSUE TITLE
[BUG] GetDirectory error

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1046]
`plugin://plugin.video.themoviedb.helper?info=search&amp;type=person&amp;query=Ron,&amp;nextpage=false&amp;fanarttv=false&amp;cacheonly=true`

Returns a list of results but given the following error in the Kodi log:-

`error <general>: GetDirectory - Error getting Ron`

**Comment by jurialmunkey** [comment]
I can't reproduce. 

Sounds like an error in your skin code. Likely a variable not being filled correctly.

You wouldn't get an `error getting Ron` error with a plugin:// path because you'd see the full url in the error message: 

`GetDirectory - Error getting plugin://plugin.video.themoviedb.helper?info=search&amp;type=person&amp;query=Ron,&amp;nextpage=false&amp;fanarttv=false&amp;cacheonly=true`

For example:
```
error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=wrong
```

Also these aren't generated by the plugin. These are Kodi errors to say that the directory got no content.

**Comment by roidy** [comment]
Yep, sorry I traced the error to my own custom script that handles the text input..... Apologies.
