### ISSUE TITLE
Information about the option - ignore regional filter

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#1049]
### Describe the feature that you'd like

Hi there 👋
I have a question...
So this is not an issue or a feature request. I hope it's ok to leave it here ;)

I can't find out what effect this option has if activated or not activated..
(in english i guess it's ''ignore regional filter'')

Here in Settings > general:

![Screenshot_20230421-085229](https://user-images.githubusercontent.com/49578130/233641112-48d14eb5-a571-4e49-9bb4-a91743fb5725.png)

### Why is this feature needed? What problem does it solve?

N/A

### Steps to reproduce.

N/A

### Screenshots and Additional Info

N/A

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
So by default TMDB api only returns results that have been released in your region (the "France" part of the language setting). Ignoring the regional filter will mean that items not released in your region are also shown (ie you will see movies that were never released in France). 

Most regions it is better for the setting to be off (ie regional filter enabled) because you don't want to see random movies/shows only released in some random country and nowhere else 

However, some regions have very limited number of released items (eg in Saudi Arabi) and so they benefit from disabling the region filter.

**Comment by alKODIque** [comment]
Thank you!
Now I understand ;)
