### ISSUE TITLE
Please see issue #944

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/plugin.video.themoviedb.helper#1050]
### Describe the bug

Hi

Issue #944 returned with latest versions of plugin.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/944#issue-1464850008

### Steps To Reproduce

See #944

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Do you know which version it stopped working in? (original fix was added in 5.1.5).

I haven't changed the multisearch code since then, so it should still work as it originally did to remove the parentheses before doing the lookup. If there's a problem now then it is likely a different issue. Narrowing down which version will help identify exactly what change/issue.
