### ISSUE TITLE
[Enhancement] Add "Favorites" User List under "Your Lists"

### ISSUE THREAD

**Issue by Sea-Wolfe** [jurialmunkey/plugin.video.themoviedb.helper#1068]
### Describe the feature that you'd like

Trakt has changed one of it's default/pre-created user lists, the "Recommended" List to "Favorites."
This request is to make this list visible at the following path: TheMovieDbHelper>Trakt>Your Lists>Favorites

Additionally, Trakt has added the ability to save a "Note/Comment" to each "Favorited" item.  If it doesn't require any major reworking, it would be nice to have a way to see these notes in TMDBHelper.

### Why is this feature needed? What problem does it solve?

Having access to all of your Trakt lists is an obvious plus.  Now, that Trakt has enabled a comment/notes field for Favorites, it would be awesome to note favorite seasons, or episodes of a show etc., and have it visible when navigating in TMDBHelper. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
This was already added in 5.1.20
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/ec546aebd66b05999e129066035fe51d4a9c0421

It is under "Trakt - TV Show favourites" (or Movies Favourites for movies). 

The trakt options menu has also been updated to allow adding and removing items. 

It won't show in "your lists" because it is now a sync list in the api and not a standard list like recommendations was (you'll see on the website favourites also doesn't show in lists there either) 

Notes are available via  listitem.property(trakt_notes) but requires skin support

**Comment by Sea-Wolfe** [comment]
Thank you!!
