### ISSUE TITLE
[BUG] Metadata and posters dissapering 

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/plugin.video.themoviedb.helper#1080]
### Describe the bug

When I play a movie via a tmdb helper widget I don't have a poster or any meta information in the OSD Display.

However if I go into tmdb helper and play the movie from there I do get the poster and meta information in the OSD Display.

Is there a setting I need to change or anything I can do to fix this? 

I have tried it on several skins and the issue remains and I have tried it with two players and the issue remains.

Also when in the tmdb add on if I click a movie the artwork and metainfo disappeares if I refresh details the information comes back I'm not sure if this issue is related to just thought I'd mention it.

I have included some photos.

Also after some extensive testing I have noticed the issue only happens when player URL resolver is set to true.

Please help me tmdb helper is my favourite add on I use it for everything.

### Steps To Reproduce

Play movie via widget after afew seconds of the movie playing the meta information and poster disappeares.

I'm using trakt watchlist widget.

This issues doesn't happen when going direct via the tmdb helper addon to play a movie however If I click a movie to view it's information then go back the movie information and metadata disappeares. I think this could be related.

### Screenshots and Additional Info

![20230716_012418](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/121204283/0f6df62d-54d0-4ad9-9953-b952ea686a6a)
![20230716_012603](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/121204283/00e531b2-a200-4fb7-8fd9-f9505f2701ed)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by SJ1O** [comment]
Here is another photo of the other issue I described about data dissapering after viewing movie information page.
![20230716_014332](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/121204283/c1816c72-4a61-470f-9b80-02136438a206)

**Comment by jurialmunkey** [comment]
What are you playing this content via? TMDbHelper doesn't provide playable content directly. 
Without knowing what addon you're using it is difficult to guess what the issue might be.

>Also after some extensive testing I have noticed the issue only happens when player URL resolver is set to true.

So why not set it to false then? 
It sounds like the addons you are using are not compatible with this setting, which is why it is optional.

> Here is another photo of the other issue I described about data dissapering after viewing movie information page.

Once items are on screen, the plugin is no longer responsible for how they display. Any issue with display of items after they've been created is either a skin or Kodi issue. 

Most likely this is a common Kodi bug where random items appear blank due to resume points manually set by plugins. Disabling the option to retrieve resume points from Trakt will likely fix this issue (which is why it is labelled as an *experimental* feature)

**Comment by SJ1O** [comment]
What are you playing this content via? TMDbHelper doesn't provide playable content directly. 

I enter the tmdb helper addon directly rather than using a widget and it works fine. Using the same players and player settings. So it's really strange then the issue only happens when playing content from a tmdb helper widget.

Without knowing what addon you're using it is difficult to guess what the issue might be. 

I have tested it with Ezra, seren and umbrella. It happens most frequently on seren and umbrella when I use them as the player.

So why not set it to false then?
It sounds like the addons you are using are not compatible with this setting, which is why it is optional.

Well I have temporarily set it to false for the sauce select players however I only have the issue when playing content from the tmdb helper widgets not if I go into the tmdb helper addon so this has made me think having it set to true is fine? If I have it set to true it literally loads the player, scrapes and plays within seconds. When something first starts playing I see the metainfo and poster then after afew seconds it vanishes.

Once items are on screen, the plugin is no longer responsible for how they display. Any issue with display of items after they've been created is either a skin or Kodi issue.

I was thinking maybe it's was a cache issue or something as I have changed the artwork provider several times however I have deleted the cache for artwork in the tmdb helper addon and my player add-ons.

Most likely this is a common Kodi bug where random items appear blank due to resume points manually set by plugins. Disabling the option to retrieve resume points from Trakt will likely fix this issue (which is why it is labelled as an experimental feature)

I have spent alot of time trying to find out if anyone has had this issue but it seems it's not been reported by anyone. I will disable the trakt option and see if that helps. To be honest tho it's not to much of a issue as I can just refresh the data. I just thought this issue could be related as the metadata and poster just vanishes right infornt off my eyes the same was it does when viewing it in the OSD menu when content is playing.

Everything is on the latest version and upto date.

If there is anything I can do to narrow a cause down that would be good.

I only have one skin installed now as well as the default Kodi skins and I only have around 5 add-ons for my content the rest of the add-ons are dependency add-ons that are required.

I will probably just start fresh today if that's what's recommended. If you have never heard of this issue before then I think one of my past add-ons or skins may have caused the issue.

Thanks for taking the time to reply it's very much appreciated.

Cheers
Sam

**Comment by SJ1O** [comment]
I didn't mean to close the issue clicked the wrong button

**Comment by jurialmunkey** [comment]
> I have tested it with Ezra, seren and umbrella.

Assuming you are using players available from reddit, these players do not work with setresolvedURL.

> I enter the tmdb helper addon directly rather than using a widget and it works fine

You can have mixed results because setresolvedURL still causes the end plugin code to execute. The issue is that these plugins do not return a playable URL to allow Kodi to manage playback. Instead they hack the player to start playback directly.

This causes Kodi to think the playback of the item failed. When Kodi fails to start playback, it does a reattempt. The reattempt causes current playback to be stopped. You end up with a race where sometimes Kodi wins, and sometimes the plugin wins.

> If there is anything I can do to narrow a cause down that would be good.

If you have resume points from Trakt then it is the cause of blank listitems. There is nothing to narrow down.

As I said, the feature is labelled experimental because of a Kodi bug with the method to set resume points. There is nothing for me to fix. I use the method correctly. Kodi has a bug - either you enable the setting and accept you will see this Kodi bug, or you disable it so that you don't see this bug.

**Comment by SJ1O** [comment]
I can confirm that your correct it's the trakt resume points that causes the issues I was having. Turned it off and everything works perfectly now. Thanks very much for your help and time. Just a quick question regarding this setting. The trakt resume points is just for the resume / Inrogress indicators? As I can still resume a movie where left off just the indicators are not showing just wondering if it does anything els?

Cheers
Sam

**Comment by jurialmunkey** [comment]
Yes, it only retrieves the progress from Trakt to set the resume point to the TMDbHelper item. 

If the end plugin you use for playback manages its own resume points then it will do nothing. 
It will also do nothing if the end plugin is incompatible with setresolvedurl as it requires Kodi to handle playback to handle the resume point.

**Comment by SJ1O** [comment]
Ok well I'll just leave it off for now I don't really need indicators to show the progress anyway. And I noticed my hole skin loads alot quicker without them. Well thanks for your help and time appreciate all the work you have put into the addon. If I could buy you a drink I'd be happy Todo so. Kind regards sam

**Comment by Peter3344** [comment]
Hello @jurialmunkey i know it's a Kodi issue but there is no workaround to fix 🙏🙏
