### ISSUE TITLE
[BUG] Do you need both year and episode_year for episode cast lookup?

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1081]
### Describe the bug

`?info=cast&tmdb_type=tv&query=The Equalizer&episode_year=2021&season=1&episode=3`
This returns cast for the original 1985 series.

`?info=cast&tmdb_type=tv&query=The Equalizer&episode_year=2021&season=1&episode=3&year=2021`
This works and returns cast for the new series.

That's fine but for other shows adding the year breaks episode cast lookup:-

`?info=cast&tmdb_type=tv&query=Foundation&episode_year=2023&season=2&episode=1`
This works and return the cast

`?info=cast&tmdb_type=tv&query=Foundation&episode_year=2023&season=2&episode=1year=2023`
This fails and returns nothing.

Should you need to include 'year' in episode cast lookups and if so how do you know when to include it?

### Steps To Reproduce

No steps.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by roidy** [comment]
Update:- This seems to be really hit and miss. Some episodes return cast if I include both 'year' and 'episode_year' while others will only return cast if I omit 'year' and just use 'episode_year'. Just to be clear all the episodes I'm checking have cast.

**Comment by jurialmunkey** [comment]
No. It's an either/or type of thing where episode_year is a fuzzy match whilst year is a stricter match.

For "episode_year" it returns first tvshow for `query` where release year is *less than or equal to* episode_year
For "year" it returns first tvshow for `query` where release year is *equal* to year

The reason episode_year exists is because episodes in later seasons have later years which wont match the tvshow year.
-- e.g. Breaking Bad was released 2008 but season five is 2013 so `query=Breaking Bad&year=$INFO[ListItem.Year]` is going to fail for all episodes/seasons later than season one, whilst `episode_year=$INFO[ListItem.Year]` will still match

**Comment by roidy** [comment]
Ok, so do I solve it for my 'The Equalizer' example?

`?info=cast&tmdb_type=tv&query=The Equalizer&episode_year=2021&season=1&episode=3`

returns cast for the original 1985 series when it should be returning cast for the 2021 series.

**Comment by roidy** [comment]
The annoying thing is I have the id for the episode, ListItem.IMDBNumber for some reason returns the TMDB episode id of 2719512 but I can't use it.

`?info=cast&tmdb_type=tv&tmdb_id=2719512`
returns nothing.

**Comment by jurialmunkey** [comment]
> returns cast for the original 1985 series when it should be returning cast for the 2021 series.

It's because the space in the title is causing a mismatch due to character encoding. If no matches are found it picks the first search result (which is the 1985 show for some reason).

Try the above commit, should fix it.

> The annoying thing is I have the id for the episode, ListItem.IMDBNumber for some reason returns the TMDB episode id of 2719512 but I can use it.

TMDb Episode ID is useless. The API doesn't use it at all and you can't search by it.
Any episode lookups use show ID with season/episode numbers.

**Comment by roidy** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/516fea77eb761e136ae5e589b736ac8b8b77d99f

That works perfect, thanks 👍
