### ISSUE TITLE
[QUESTION] log_tagger?

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1082]
In my addon_data I've got a directory called log_tagger that is filled with json files that contain no data just the json opening and closing tags {}.

What is the purpose of these files?

**Comment by jurialmunkey** [comment]
It's just a log file. If you monitor trakt lists with the tmdbhelper library function, it will tag items in your library from those lists with the list name so that it can create a smart playlist.

If it's blank, it just means nothing was tagged. I think I must've forgot to check that the log wasn't empty before writing it out (routine runs after a library update but if you aren't using the library integration it does nothing and returns an empty log). I'll fix that up soon.
