### ISSUE TITLE
TMDBHelper library not updating

### ISSUE THREAD

**Issue by Paultl** [jurialmunkey/plugin.video.themoviedb.helper#1084]
### Describe the bug

I've been using TMDB helper for some time without issue.
Recently however, I've noticed no new episodes are being added to the library.
I can see them I the relevant folder but the file name seems off. For example, the latest episode of ST Strange New Worlds displays as S02E06 - Charades.strm
I've tried cleaning the library and forcing an update with no effect.

### Steps To Reproduce

Removed titles from library.
Re-added
Title shows but there are no episodes
This is the same for new titles

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Log?

**Comment by Paultl** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/12105651/kodi.log)

**Comment by Paultl** [comment]
Apologies, added now

**Comment by jurialmunkey** [comment]
Monitored list details missing from settings

You can see in this error that the user name and list name are blank.

```
HTTP Error Code: 405
Request: https://api.trakt.tv//users//lists//items
```

**Comment by jurialmunkey** [comment]
Additionally, you are missing Trakt authorisation. Trakt is not listed as authorised in your log.

**Comment by Paultl** [comment]
Does it need trakt authorisation? I've been using it fine without it since I installed it.

**Comment by jurialmunkey** [comment]
How can you monitor your Trakt lists without authorisation? Regardless your settings for monitoring a list are blank so there is no list to monitor.

**Comment by Paultl** [comment]
Hi, I've added Trakt and set it to update from my watch list. It's populated some new shows but still has no episodes available.

New log attached.
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/12114184/kodi.log)

**Comment by jurialmunkey** [comment]
You're getting a lot of network connection errors e.g.

```
2023-07-13 01:18:57.439 T:16723    info <general>: [plugin.video.themoviedb.helper]
                                                   ConnectionError: Not connected. Check network settings.
```

I can also see your library scraper failing to scrape shows because it cannot connect:

```
2023-07-13 01:18:56.121 T:24592   error <general>: Run: Unable to parse web site
2023-07-13 01:18:56.121 T:24592 warning <general>: No information found for item 'special://profile/addon_data/plugin.video.themoviedb.helper/tvshows/Silo (2023)/', it won't be added to the library.
2023-07-13 01:18:56.196 T:24592   error <general>: CCurlFile::CReadState::FillBuffer - (0x2264dd8970) Failed: Couldn't resolve host name(6)
```

This is a network issue.

**Comment by jurialmunkey** [comment]
You can find logs for exactly what TMDbHelper added as .strm in 
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/`

Once the item is added as a strm, it is up to your library scraper to add it to your library. If the .strm is there then TMDbHelper did its job. If a .strm is missing you can read the logs in the log_library directory to find out more about why it skipped that item

I can see in the log that TMDbHelper is correctly creating .strm files for Strange New Worlds with the correct file names:
```
ADD LIBRARY -- Successfully added:
                                                   special://profile/addon_data/plugin.video.themoviedb.helper/tvshows/Star Trek Strange New Worlds (2022)/Season 2/S02E05 - Charades.strm

ADD LIBRARY -- Successfully added:
                                                   special://profile/addon_data/plugin.video.themoviedb.helper/tvshows/Star Trek Strange New Worlds (2022)/Season 2/S02E06 - Lost In Translation.strm
```

If the files are in the directory, then the problem is either: your scraper is not setup correctly; there's some issue with your library; you are not pointing your library source at the correct location; or you have a network issue and the scraper is failing.

From the log I can see that TMDbHelper is definitely adding the items to the folder though and these are named correctly (possibly the previous incorrect name was from incorrect details on TMDb being later corrected - but it is listing the correct name and number in your log).

**Comment by Paultl** [comment]
Ok that's great, thanks for your help, I'll do some digging.
Or just nuke it and start again!
Appreciate you taking the time to look.
