### ISSUE TITLE
Failed to install script 

### ISSUE THREAD

**Issue by thefrench1** [jurialmunkey/plugin.video.themoviedb.helper#1093]
### Describe the bug

Hi I'm trying to run the update on  20.2 but keep getting failed to install script when I go to install. Have tried on a fresh Kodi install and get the same issue. I'm I doing something wrong. 

### Steps To Reproduce

Installed repo
Then went to install the tmdb

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by alKODIque** [comment]
Since TMDbH and some dependencies are included in the official Kodi repository, you have to set 'install from any repository' in Kodi add-ons settings:
So this is not a bug ;)

![Screenshot_20230802-175056](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/49578130/17aa6e38-da33-4f99-abbb-6f3bdc9c5c04)

**Comment by thefrench1** [comment]
Hi. Thank you for the swift reply above. That's fixed the issue.
