### ISSUE TITLE
[Feature] Request for a new Lists Discover parameter '&amp;with_networks='

### ISSUE THREAD

**Issue by realcopacetic** [jurialmunkey/plugin.video.themoviedb.helper#1100]
### Describe the feature that you'd like

The Lists Discover is great for creating lists of movies from the same studio using &amp;with_companies=

However, for tv shows, the added complication of having networks and studios makes it very difficult to reliably pull the results people would expect to see for the big networks/streamers. Because individual shows will be made by a bunch of different production companies and some of those may or may not be companies owned by and named similarly to the networks, e.g. AMC / AMC Studios. 

### Why is this feature needed? What problem does it solve?

Being able to filter discovery lists by network instead of by company would allow for more expected results to be shown by TV shows, e.g. if a ListItem is from AMC, we would then be able to return these results:

https://www.themoviedb.org/network/174

instead of these ones:

https://www.themoviedb.org/company/194389/movie

The latter appearing to be the first studio result for a search on AMC.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You can already use `with_networks=` -- you just need to know the ID of the network since TMDb doesnt offer a search endpoint like it does with companies:

![image](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/4618719/c09b02db-823f-497a-a9d9-2afd95b1d88e)

When you pass a company name to `with_companies=` what TMDbHelper is doing behind the scenes is use the company search endpoint to translate the name of the company into an ID
https://developer.themoviedb.org/reference/search-company

Because there's no equivalent for networks it can't do that same process.

The only way I could think of doing that is downloading the full daily export of networks, reconfiguring it into a lookup dictionary and then grabbing the ID that way -- definitely possible but not exactly efficient with 7000+ networks.

It'll be much quicker if you use the service monitor to grab the network ID

**Comment by realcopacetic** [comment]
Ahh cool, thanks for taking the time to explain this. Much appreciated!!
