### ISSUE TITLE
More of a question than a feature. 

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/plugin.video.themoviedb.helper#1115]
### Describe the feature that you'd like

@jurialmunkey this is a question to do with players. With tmdb helper fetching movie and or TV content,  if you want to stream something you see, what player do you have tmdb hooked upto?  Or do you use it in this way at all?

I ask because I try to play my own content but I need to streamline so hooking tmdb upto play content looks good but I wonder do I need a third addon with a player ior could tmdb do it alone?

### Why is this feature needed? What problem does it solve?

Want to know the best way to make tmdb streamlined. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
TMDbH doesn't play any content. The content needs to be either in your library or provided via an addon. 

A player is essentially a series of rules which helps TMDbHelper to find that content on another addon -- with a little bit of effort its possible to make a player for practically any addon. 

For myself, I use it so that I can watch things in my library and from other addons all from the same place -- I tend to cycle between subscriptions for Netflix, Disney, Stan, Binge etc. depending on what shows I'm watching, so it saves me having to setup different widgets when I cancel one service and switch to another. 

I also watch a lot of British panelshows which I can generally only find on Youtube, so it saves me having to open up Youtube; and there are some other free Australian tv streaming services I use where I've made some of my own custom players to play some local content.

That way my entire TV watching is done through Kodi via TMDbHelper without ever needing to switch to another app or even another addon -- I rarely ever open another addon, and that's generally only for things where TMDb simply won't have data on it at all (e.g. podcasts or live tv etc.)

**Comment by DROIDshield** [comment]
Thanks for the explanation. At the moment I use another addonl... (Um)... to connect to the outside, but like you i want tmdb to be a stand alone and play stuff from Samsung, pluto, kodi etc if you could point me to a site or where I can learn abit more about creating my own player to link me to legit site's or a tutorial that would be helpful but if you think it cuts abit too Indepth don't worry... I will figure something out..  I usually do.☺👍

**Comment by jurialmunkey** [comment]
TMDbH has templates for creating new players in the player configuration dialog
`TMDbHelper Settings > Players > Configure players > Create new player`

The keyboard_default template will work for plugins that have a standard approach of:
`Search > Input Title in Keyboard > Select Show > Select Season > Select Episode`

The Wiki contains more detailed documentation including advanced functionality:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

I recommend starting with trying to make a few players using the keyboard_default template. It will work for a lot of plugins without modification and for others it will serve as a good starting point for further modification with reference to the wiki. 

If you get stuck or have a plugin that's a bit more unconventional, then I'm happy to help out as long as its not a banned addon.

And there's also quite a few packs of 3rd party players of varying degrees of quality floating around on the internet. Players can only run Kodi commands and they'll only run when you specifically select them, so they are relatively safe to install (but obviously anything from the internet inherently carries some risk). The quality can vary a bit as some are clearly made by people just plugging things in until it kinda works rather than really understanding what they're doing -- but at worst that'll just mean the player fails or gets bad matches more often.

**Comment by DROIDshield** [comment]
Wow thanks for the effort and input, I'll go away and some reading/research and see if I can create what I'm hoping for...Thanks a million.
