### ISSUE TITLE
[Feature] Integration into PVR

### ISSUE THREAD

**Issue by PostTraumaticOS** [jurialmunkey/plugin.video.themoviedb.helper#1125]
### Describe the feature that you'd like

It would be great if you could integrate "Select Player" menu option into PVR Guide context menu when long-pressing on a EPG item.

### Why is this feature needed? What problem does it solve?

If you have that program in your local library or potentially available on any integrated player.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
It's not a bad idea, but there simply isn't any good way to identify whether PVR items are movies or episodes or something else. Until Kodi PVR provides this data in a reliable way, it is too dangerous to provide context menu items based on guesswork.

You can see how problematic this gets with the PVR service monitor lookups where they will frequently get the wrong results or for a different episode/season etc. because it has to guess what the item is due to a lack of clear data. It's fine when we are talking about a fanart background -- much more problematic when it is about sync data with Trakt (e.g. you mark an entirely different show as watched).

It's just not feasible with the data available to do it in a reliable way.
