### ISSUE TITLE
[BUG] tmdbhelper hangs on “loading”

### ISSUE THREAD

**Issue by timmyrocks26** [jurialmunkey/plugin.video.themoviedb.helper#1128]
### Describe the bug

This has been going on for a long time. Since kodi 19. I just never bothered to diagnose it. 

Aftwe playing a few streams through tmdb it shows an error notification. Eventually after 2-4 streams it just hangs up on loading when you try to play a file. 

You can cancel out of that process, but it will happen again when you try to play any other stream.  The fix is to close and restart kodi. 

AppleTV 4K V 17.0
Kodi 20.2
Tmdbhelper V.5.1.45
Connects to Seren V.3

### Steps To Reproduce

1. Open kodi
2. Play any movie or tv stream using tmdbhelper widget
3. Stop file.  Play another stream
4. After two or three streams a tmdbhelper error notification will appear. 
5. After approx 4-6 attempts the tmdbhelper notification will hang on “loading” in the notification 
6. The file will never play. 

### Debug log

https://paste.kodi.tv/inexamoqod

### Screenshots and Additional Info

![IMG_0615](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/57125318/c8d2cbdf-74e0-478c-b65f-fa92744772b2)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Thread error in python multithreading module on tvOS

Have you tried reducing the max concurrent threads in TMDbHelper Settings?
TMDbHelper > Settings > Expert > Max concurrent threads

Reduce that to 30, hit OK in settings dialog to save the settings and then restart Kodi (make sure you exit Kodi properly rather than force quit to make sure settings are saved).

Let me know if you still experience this issue after reducing the max threads.

**Comment by timmyrocks26** [comment]
Hi Jurialmunkey, thanks so much for the quick reply!
I changed the concurrent threads. Shut down kodi. 

Unfortunately still having the same issue. 
[](https://paste.kodi.tv/urimidihes) 

I tried it a few times.  Cleared off as many caches as I could find.  Rinsed and repeated but still getting this error.

**Comment by jurialmunkey** [comment]
Can you install v0.1.11 of script.module.jurialmunkey and see if that helps. Should be up on my repo now or can get it manually from here: https://github.com/jurialmunkey/script.module.jurialmunkey/releases/tag/v0.1.11

**Comment by timmyrocks26** [comment]
so sorry for the delay.  This seems to work great.  It has since had the same issue pop up again but far less frequently, and certainly nothing to complain about, but I’m sharing the log with if you if it is of any further interest at all. 

https://paste.kodi.tv/ifukalafif

I had read that the appletv will always have some issues more open source devices won’t so I’m sure this could fall under that. 

Regardless. Amazing.  Thank you so much for your time and help!!!

**Comment by manolischania** [comment]
> Can you install v0.1.11 of script.module.jurialmunkey and see if that helps. Should be up on my repo now or can get it manually from here: https://github.com/jurialmunkey/script.module.jurialmunkey/releases/tag/v0.1.11

Hi after the last update it shows that the problem is back for android tv OS ( the script.module ver is 0.1.17)
Thanks in advance

**Comment by jurialmunkey** [comment]
@manolischania debug log please.

**Comment by RemcoSlimmerit** [comment]
v5.2.8 fixed this issue for me.

Thanks Jurialmunkey!

**Comment by jurialmunkey** [comment]
> v5.2.8 fixed this issue for me.
> 
> Thanks Jurialmunkey!

Not this issue then as that was an entirely separate matter.

**Comment by Getterbetter** [comment]
I'd like to reopen this thread, but please let me know if I should raise a new bug.

Firstly, let me start with a huge thanks. Arctic Horizon 2 is truly incredible skin, I couldn't believe what I was seeing when I used it for the first time, especially the widgets!

**Describe the issue**

I've created a single home page view that shows a number of TV & Movie shows via widgets from add-on 'POV'. There is a total of 3 widgets.

I've reopened this case because I'm also receiving the "can't start new thread" error in the logs but the behaviour is different. In my case, it basically causes the widgets not to load, i.e. no title (e.g. "next episodes") and no shows / movies are populated in the widget. If I kill Kodi and start again, then most of the time it'll all load as normal.

Apple TV 4K v17.5.1
Kodi v21.0
TMDB Helper v5.2.28
Script Module v0.1.18
POV v4.07.25

**Steps to reproduce**

I've found this difficult to reproduce as sometimes Kodi will crash, other times I'll receive an error notification pointing to TheMovieDB Helper. Most recently, I adjusted the 'style' of the 'Next Episodes' widget from POV from Landscape to Poster and I received the error notification.

But to reproduce the behaviour is easier and more consistent. To do so:

1. Create a widget pointing to POV -> TV Shows -> Next Episodes
2. Use the widget to play the next episode of a TV show
3. After 5 - 10 seconds, close the stream

This will normally cause the Next Episodes widget from the home page to disappear. Other widgets may be impacted also.

**Logs**

Sorry, I didn't have debug logs enabled but I'd be happy to do that if that'd be helpful.
https://paste.kodi.tv/tirobapuyu

**Comment by jurialmunkey** [comment]
@Getterbetter - Please disable readahead caching.
`TMDbHelper Settings > Other > Readahead caching of service listitems`

Make sure to press ok to save your settings and then restart Kodi.

**Comment by Getterbetter** [comment]
Sorry for the late reply and thanks for responding so quickly @jurialmunkey. You’re a genius, that stopped the error from appearing.

There’s no need to keep this open but I thought to share my findings. Whilst the error has stopped, there is still an intermittent issue I believe to be between AH2, TMDB and POV on a ATV4 whereby widgets linked to POV fail to load. This happens most with ‘Next Episodes’ but can also happen within movie sections. I decided to reconfigure Home page and connect it to afFENity and there is no issue. I’ve tried every which way I can think to configure POV, AH2 & TMDB to overcome the issue (I realize not listing the ways doesn’t help, but I’ve genuinely forgotten as I’ve tried so many) inc. wiping Kodi and starting again many times but to no avail. AfFENity is a great add-on so no complaints using it this way, but I thought to share for general curiosity.
