### ISSUE TITLE
[BUG] Something is wrong with artworks with last update

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#1131]
### Describe the bug

I think you messed something up with the artworks with the last update. What I noticed is that clearlogo no longer pulls from tmdb, only from fanart. There is no tmdb clearlogo also when you want to change the clearlogo ftom artwork manager. Also, I can't remember if in previous versions when selecting artwork from artwork manager, it dropped artworks in all languages ​​or only in the set language. All in all, check litle artworks since you've been code refactoring, some error always sneaks in. Thank you in advance.

### Steps To Reproduce

-

### Debug log

-

### Screenshots and Additional Info

-

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Please describe exact steps to reproduce issue.

**Comment by matke-84** [comment]
I installed the whole kodi from scratch, installed my skin which has full integration with tmdb helper. Until yesterday, tmdb clearlogo appeared by default, now with the new version it doesn't anymore. If I turn on the option in the tmdb helper to pull from the fanart.tv artworks, then it is there. Then, if you go to manage artwork/select artwork/clerlogo, you will see that you have the option to select only clearlogo from fanart. tv but not from tmdb.

**Comment by matke-84** [comment]
I'd say it's ok now. Thank you.

**Comment by jurialmunkey** [comment]
For future bug reports, please make sure to fill out the "Steps to reproduce" section. That's the most important part of the bug report because I need to reproduce the issue to fix it. Otherwise I waste a lot of time trying to understand the bug.

And when I say I need *exact* steps, I mean give me a specific test case to demonstrate the issue, for example:

1. Set language to English and disable Fanart TV lookups
2. Goto TMDbHelper > Top Rated > Lord of the Rings
3. Note that Service Monitor does not display clearlogo
4. Open Context Menu > Select Artwork > Clearlogo
5. Note that TMDb clearlogos are missing from list.

This approach gives a clear and an easily understandable process of the exact issue and a quick way for me to try to reproduce the issue myself. It also gives me a test case to make sure any fix is working.

**Comment by matke-84** [comment]
Ok. Sorry. Next time I will try to be as precise as possible.
