### ISSUE TITLE
[BUG] Error..

### ISSUE THREAD

**Issue by BrownQ8** [jurialmunkey/plugin.video.themoviedb.helper#1132]
### Describe the bug

Sometimes when i open kodi

### Steps To Reproduce

Startup kodi

### Debug log

https://pastebin.ubuntu.com/p/Pq8CDpy52s/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What error?

I cannot open your debug log because I do not have an Ubuntu account. Please use Kodi pastebin https://paste.kodi.tv/

**Comment by BrownQ8** [comment]
Sorry for being late .. https://paste.kodi.tv/ovizejulox

**Comment by jurialmunkey** [comment]
Oh this was due to a typo in the skin with the default setting for the spotlight widget path. It was fixed in the skin but I can't change the setting if the default was already set on your machine.

All you need to do is change your spotlight widget to something else. Can do that in:
`Skin Settings > Menus > Home > Spotlight`

Possibly might have to do the same for movies and tvshows sections too.
