### ISSUE TITLE
[Bug] Unwatched episode counts on widgets not automatically updating after watching

### ISSUE THREAD

**Issue by tjamieg** [jurialmunkey/plugin.video.themoviedb.helper#114]
After watching 1 or more episodes of a particular TV show, I have to manually open the TV show then go back to the home screen and reload the skin in order for the unwatched episode number to update itself.

**Comment by jurialmunkey** [comment]
TMDbHelper doesn't update watched counts - that's done by whatever add-on used to watch the content. Also, plugins don't control when containers refresh - that's done by Kodi.

**Comment by tjamieg** [comment]
Sorry for digging up an old post, but this is still an issue for me, let me see if I can explain it more clearly.

My problem is when I watch episodes via an external player like, for example, the Wako app, or when I simply mark episodes as watched via Trakt.

The unwatched episode count indicator doesn’t change because it is cached in TMDb Helper for 14 days (I think)...

**Comment by drinfernoo** [comment]
Unwatched counts aren't part of what gets cached by TMDbHelper. Those lookups are done fresh each time, from what I understand.

**Comment by tjamieg** [comment]
Ahh okay fair enough then, it’s just bugging me that’s all.. don’t quote me on it but I’m sure my old Seren widgets used to update without clicking on them to do a fresh lookup though? 🤔

On 21 May 2020, at 00:00, drinfernoo <notifications@github.com> wrote:

﻿

Unwatched counts aren't part of what gets cached by TMDbHelper. Those lookups are done fresh each time, from what I understand.

**Comment by drinfernoo** [comment]
@tjamieg Not sure, it's all up to the skin usually.

**Comment by jurialmunkey** [comment]
> Ahh okay fair enough then, it’s just bugging me that’s all.. don’t quote me on it but I’m sure my old Seren widgets used to update without clicking on them to do a fresh lookup though?

That's either because the addon is resolving the item in the list to a playable object which Kodi will mark as watched when playback stops (and so is marked as watched in the list inside that addon), or the addon itself keeps track of watched items.

It's not really possible to resolve to a playable object for TMDbHelper because Kodi doesn't have a method to retrieve the resolved url from another plugin (plugin resolves url and passes it directly to videoplayer at which point it's too late since the video is already playing). Also, there are many addons that don't directly resolve to a playable url and instead provide a list of sources; or the addon needs to manage some type of connection/authentication; or there is some type of special input stream handling such as widevine DRM.

So our only option is to rely on Trakt watched status. The problem there is that many addons only update Trakt watched status after a specified interval (e.g. they might store all the watched values and then send these to Trakt every 2 hours). So not only do we need to wait for the data to complete it's trip (i.e be sent to Trakt, updated in their database, and then returned when requested), we are also at the Mercy of when the addon sends that updated data.

**Comment by tjamieg** [comment]
Thank you very much for detailed reply!

> So our only option is to rely on Trakt watched status. The problem there is that many addons only update Trakt watched status after a specified interval (e.g. they might store all the watched values and then send these to Trakt every 2 hours). So not only do we need to wait for the data to complete it's trip (i.e be sent to Trakt, updated in their database, and then returned when requested), we are also at the Mercy of when the addon sends that updated data.

This is the part that interests me... so I guess my question is - does TMDb Helper check Trakt’s watched status at any fixed interval? If not, would it be possible? Maybe even if it did this in the background, like every 2 hours or even once a day or something, that way the episode numbers on the next up widget would only take a day to update, instead of me having to physically click into them to do a fresh lookup or wait a couple of weeks.
