### ISSUE TITLE
TMDB Error

### ISSUE THREAD

**Issue by dc0x** [jurialmunkey/plugin.video.themoviedb.helper#1140]
### Describe the bug

On clicking the options in TMDB helper (like top rated, popular etc) an error is produced stating "Connection Error: TMDB, Suppressing retries for 30 seconds. Same error is not produced in trakt options under TMDB helper.

### Steps To Reproduce

Install TMDB Helper
Open TMDB helper
Click any one the options (excluding search)

### Debug log

https://paste.kodi.tv/raw/dehevuxula

### Screenshots and Additional Info

![Screenshot 2023-12-04 033856](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/152091777/248f9fbf-afa9-4f5c-8dbf-14e4f36e9869)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
This means TMDB's servers rejected your request or something else along the way blocked the request (eg your ISP or your router or firewall etc.). 

Could be caused by several things eg if you constantly delete cache and cause lots of requests, they will block you temporarily thinking you are trying to ddos them; or if the connection is too slow so they'll time out the connection; or they're having an issue with their server;or there's something on your network not letting the request go through properly; or your ISP is blocking TMDb etc. 

Nothing I can do about it as these are all external factors.

**Comment by kalaksi** [comment]
@jurialmunkey sorry for posting to a closed issue but when searching about this problem, this github issue comes up often so I thought this is a good place to collect some more info.

So, I'm facing the same issue with a setup that has limited network access and basically I'm asking if there is a way to disable that error notification?
