### ISSUE TITLE
[BUG] ListItem.getUniqueID()

### ISSUE THREAD

**Issue by Peter3344** [jurialmunkey/plugin.video.themoviedb.helper#1144]
### Describe the bug

i don't know where I should post the issue here or in skin fuse but every time i try to use tmdbhelper option and choose artwork i got this warning message 
`ListItem.getUniqueID() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.getUniqueID().`
the artwork if the showtitle written in English the artwork dialog open with no issue and i can choose the art work
but if the showtitle written in arabic it open but when i click on choose artwork i get nothing

### Steps To Reproduce

1-open tmdbhelper
2: search tv show for tvshow title:زينهم
3-open context menu 
4-tmdbhelper options 
5-mange artwork 
6-select artwork 

### Debug log

https://paste.kodi.tv/eyuqibokib.kodi

https://paste.kodi.tv/qupevadoxu.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
The warning is not important, it is simply because the context menu addon is old and designed for Matrix. It is not meant to be used on Omega. 

Those entries in that tmdbhelper options subfolder from the context addon are only there to be used with **other** addons not TMDbhelper itself.

For TMDbhelper, a proper manage artwork entry exists in the  **main** context menu near the top. Use that. It will work much better. It has direct access to the item properties instead of trying to guess the ID from the name like the context addon does (which as you're discovering has issues with rtl like Arabic and Hebrew).

Please try the proper manage artwork option (not the one in the tmdbhelper context addon subfolder) and let me know if it works.

**Comment by bassemhelal18** [comment]
It's the same problem when I use the main can you check the steps and try it

**Comment by Peter3344** [comment]
It’s the same problem when I used the Main can you check the steps and try I can’t select artwork it won’t open 
thank you

**Comment by jurialmunkey** [comment]
I see the issue. TMDb does not have TVDb ID for this show which means it cannot lookup artwork on FanartTV.

I can set it to use only TMDb artwork in this case but there's not much artwork for this show on TMDb.

**Comment by ambulancePilot** [comment]
I just uninstalled the tmdb context menu because I'm dumb and now I can't find it in your repo. Was it discontinued?

I really enjoyed having it because without it there's no way for me to access the artwork management for a widget item that doesn't belong to tmdb helper. Unless I'm missing something?

EDIT: now I understand it's not available for omega, however I was able to download the zip and install it anyway and seems to be working okay.

**Comment by jurialmunkey** [comment]
@ambulancePilot yeah context addon should still work for the most part if you install manually. I didn't include it on my omega repo as I need to look at it a bit closer and haven't had time yet - mostly a "probably still works but use at your own risk" cover type of thing!
