### ISSUE TITLE
[BUG] The dependency on script.module.jurialmunkey 0.1.14 could not be satisfied.

### ISSUE THREAD

**Issue by I-JMC** [jurialmunkey/plugin.video.themoviedb.helper#1155]
### Describe the bug

The dependency on script.module.jurialmunkey 0.1.14 could not be satisfied.

### Steps To Reproduce

1. Download from zip the latest version of the moviedb helper (5.2.14)
2. And tada

### Debug log

https://paste.kodi.tv/nuweqavago.kodi

### Screenshots and Additional Info

At first, it tried to download this from a Skin named Titan BINGIE MOD which wanted to download the 5.2.12 versions which is not on the GitHub maybe it's a custom thing, but had exactly the same error code.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by I-JMC** [comment]
Maybe because my requests “dependency” is outdated ?
![image](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/99205448/498b2f70-391f-49fd-95de-2ba408be8ed5)

**Comment by adamosborne83** [comment]
Have you got the Jurial Repo installed and tried updating from there?
I couldn't see it in your log that's all.

**Comment by jurialmunkey** [comment]
This is not a bug. The error message tells you exactly what's wrong - to install the newest version of TMDbhelper you need to install a higher version of script.module.jurialmunkey than is available on the official repo. 

You must use my repo to install newer versions of TMDbhelper so that you have all required dependencies. 

Kodi File Manager Source:
https://jurialmunkey.github.io/repository.jurialmunkey/

Direct ZIP Install:
https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-3.4.zip

Instructions:
1. Enable "Unknown Sources" in Kodi Settings > System > Add-ons
2. Enable "Update official add-ons from: Any repositories" in Kodi Settings > System > Add-ons
3. Install my repository using either the zip or file manager source linked above
4. Install latest version of tmdbhelper from my repo

**Comment by I-JMC** [comment]
Thank you very much !!!
