### ISSUE TITLE
[Feature] Option to show Tv Show Information screen on select

### ISSUE THREAD

**Issue by xpeiro** [jurialmunkey/plugin.video.themoviedb.helper#1165]
### Describe the feature that you'd like

Basically the same functionality that the kodi default select action = "Show Information" does for movies but for Tv shows. To be precise if this option where activated in the addon settings, when pressing select on a tv show in the addon or in a widget of the addon, instead of going directly to the "Seasons" view, the "information" screen of the tv show would come up as if you had pressed the context menu button and selected "information". This can _almost_ be achieved now by using the option in Navigation to set "default select action in addon" to "browse" in addition to the kodi default select action "show information". But this has the side effect (unintended for me) that when you then click on an episode or movie,  the context menu pops up.

### Why is this feature needed? What problem does it solve?

When discovering new tv shows or coming back to a show after a season break etc., I like to see the information screen to see the basic data of the show, access the trailer, cast, etc. Then use the "right arrow" button to see the seasons. It feels very smooth that way. This also provides some time for the fanart/clearlogo to load in (currently if I open a show and then change to another, it takes a noticeable couple of seconds to change the art, which is not as "pretty" as the rest of the addon). Using the context menu is always a hassle because I have one of those remotes with very few buttons so I my context menu key is "virtual"...I understand this might be a niche request but the current option is _so_ close to allowing this that I have to humbly imagine it is not too hard to implement. I would understand anyway if this gets denied, thanks for the amazing addon anyway.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
This is not something the addon is allowed to do. The only way to open info using a callback path is to change the path of the item so it instead runs an info command and is not longer a folder. Because tvshows are folders not playable items, then it makes the folder impossible to open because telling kodi to open the tvshow path now means it instead opens info and there is no way to open the season. Attempting to browse the season from info will now get you stuck in a loop because info closes to browse the folder, but attempting to browse the folder path tells the plugin to open info. 

Changes to how the select commands function need to be done inside Kodi as core changes, not inside plugin where it will have ripple consequences on every skin using the plugin.

The reason it's possible to have a details folder  is because it's just another folder. It isn't changing any behaviours of what paths do, it is just giving tvshows a slight detour to a separate folder which contains links to seasons as well as other folder. The path to seasons is not changed there's just an extra subfolder to navigate through first.

**Comment by jurialmunkey** [comment]
As an example of an issue this will cause - to use your example of pressing right that will no longer work. Instead it will cause info to be pressed (since that's what the seasons path does now and you tried to open it). Now info dialog closes instead (because that's what info does in the dialog). You can never get to seasons.

**Comment by xpeiro** [comment]
Thanks for the detailed response. I don't entirely understand, but that's ok if it is clear to you this cannot be done within the addon. Right now with the  "default select action in addon" set to "browse" option, this functionality does work as I described, with the only caveat that when clicking on an episode (or play on a movie) it shows the kodi context menu. Opening the tv show shows information and clicking right opens season view, no issue with that part (that's why I don't understand the "loop" you're describing). If it would be possible for the action in the addon to be "browse when opening tv show" and "play when opening episode or movie" I think it would work as per my request? But as I said, if it's clear to you this cannot be done or isn't worth it, no worries. Thanks again.
