### ISSUE TITLE
[Feature] Consistency with Arctic Fuse in the "search by people" option

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/plugin.video.themoviedb.helper#1179]
### Describe the feature that you'd like

Arctic Fuse when you go into "information" and "cast" it pops up a "credits" option where it shows the movies, tv, and production of said actor however when in tmdbhelper when searching it separates movies and tv instead of grouping them in one list. I would like if it works like Arctic Fuse where it is grouped.

### Why is this feature needed? What problem does it solve?

Shows movie, TV, and production in one list when searching a person instead of having to back out each time to see another list.

### Steps to reproduce.

1. search a person
2. click on them
3. choose movies
4. back out to see list again
5. choose tv

### Screenshots and Additional Info

How it looks in tmdbhelper with seperate options

<img width="1232" alt="Screen Shot 2024-03-17 at 5 09 05 PM" src="https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/43726430/9d792333-65fd-423b-9dfa-a95248c9f01a">

How I would like it to look 

<img width="1233" alt="Screen Shot 2024-03-17 at 5 09 59 PM" src="https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/43726430/d9a9712f-d7f9-4cde-b49b-74decae5ac57">

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
The big problem is that Kodi does not have a "mixed" content type, so there is no correct content type to set to the container (which then messes up skins because they don't know what viewtypes are appropriate).

It's fine in a widget because the skin can simply control the viewtype and knows that it is mixed content. For a standard Kodi view container, however, there is no way to indicate that the list contains both movies and tvshows
