### ISSUE TITLE
Constant TMDB Helper Error log

### ISSUE THREAD

**Issue by larsmichiko11** [jurialmunkey/plugin.video.themoviedb.helper#1200]
### Describe the bug

I just got back to using my Kodi again. When I opened my Kodi I get a 'TMDB Helper Error' at the beginning and saying I have to check logs for error information: https://paste.kodi.tv/odepaxuxev.kodi

Thank you in advance!

### Steps To Reproduce

Start Kodi (using AH2 skin)
Wait to finish AH2 load
Got the TMDB Helper error

### Debug log

https://paste.kodi.tv/odepaxuxev.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [x] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by C-O-D** [comment]
I am getting these constant errors for a few days now with Arctic Fuse since I upgraded to KODI 21.0. I have already deleted the complete user directory of TMDB Helper and also logged out of TRAKT and logged in again, but the error messages still appear every time I start KODI. Never had those before and would be too nice to get rid of them: https://paste.kodi.tv/exawaginic.kodi

**Comment by C-O-D** [comment]
I deactivated AutoWidget which produced a lot of errors so here's a much cleaner log: https://paste.kodi.tv/ivasejofay.kodi

**Comment by jurialmunkey** [comment]
> I deactivated AutoWidget which produced a lot of errors so here's a much cleaner log: https://paste.kodi.tv/ivasejofay.kodi

@C-O-D 

You're using Manjaro Linux with a different version of Python installed (3.12) than what ships with Kodi. Errors are to be expected due to difference in modules used. These are different errors to the original bug report in this thread.

It is too difficult for me to test multiple versions of Python other what ships with Kodi (which is 3.11.12 for LibreELEC/Android and 3.8.15 for Windows afaik).

Possibly might be related to a corrupted database file. You can try deleting your database files then start Kodi
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v6`

**Comment by jurialmunkey** [comment]
> 
> I just got back to using my Kodi again. When I opened my Kodi I get a 'TMDB Helper Error' at the beginning and saying I have to check logs for error information: https://paste.kodi.tv/odepaxuxev.kodi
> 

@larsmichiko11 - Looks like you only had a partial response from the TMDb API when asking for Genre IDs and that ended up being cached (which then continues to cause the issue because the cache isn't of the type expected). 

The commit above should avoid that occurring, will be in next update (5.2.24)
