### ISSUE TITLE
Create new player: Black screen before launching addon

### ISSUE THREAD

**Issue by Qirat77** [jurialmunkey/plugin.video.themoviedb.helper#1204]
### Describe the bug

Hi. Not sure if you’re able to help given the nature of my post. If not, no problem, and apologies.

I’ve created a new player for an addon and set it as the default player, which does its job. The script I found online sets ‘is_resolvable’ to false. With this setting, my screen goes black for a couple of seconds after selecting a movie/tv show from a Home Screen widget (similar to a refresh rate change) then loads links. Set to true, this doesn’t happen, but when video stops playing I get a playback error message. Not a big deal. 

However, I’ve noticed that if I open context menu on a movie/ tv show on the Home Screen widget and choose ‘select player’, and then select the same player, there is no black screen when ‘is_resolvable’ is set to false.

Wonder if this is a skin (Arctic Fuse), tmdb helper or addon issue? I can post a log, but would rather wait to see if you’re remotely interested in addressing this post first. Thanks. 

### Steps To Reproduce

Create new player, set to default player, then play a movie/tv show from a Home Screen widget. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
If you are using add-ons which do not resolve correctly, the plugin must resolve to a dummy video file first in order to maintain compatibility with add-ons which do resolve correctly via setresolvedurl.

If you use nothing that resolves correctly, set the setting `TMDbHelper > Expert > Dummy > Restrict to library strm` and it will perform the same as context menu.

As the setting suggests, this is not possible for library strm files, which *must* always resolve and so the behaviour cannot be overridden for library integration.

**Comment by Qirat77** [comment]
Thanks for taking the time. After setting restrict to library strm I still get a black screen for a couple seconds before launching addon, and some weird behaviour - if I exit the addon without playing a link, the addon repeatedly tries to relaunch. 

Actually installed the same kodi addon on my Mac to test, and get a nice tmdb helper logo display for a second before seamlessly launching the addon. I’m guessing this is what my Odroid N2+/ CoreELEC is having difficulty displaying and shows a black screen instead, but like I say, strange how select player doesn’t have this issue.  Not a problem though. Thanks.

**Comment by jurialmunkey** [comment]
The tmdb splash video file only plays if that setting is disabled and resolve is false. That's the dummy video used to resolves to instead because the addon provides no video directly via the correct means.

Are you sure you saved the setting (press OK after changing) - its very easy to forget to save it and just back out instead (which reverts changes you make). And then you need to reload kodi afterwards for it to apply.

With that setting enabled, there should be no dummy file used.

**Comment by Qirat77** [comment]
Hi. Tried this again and made sure I saved settings and reloaded Kodi. Still getting weird behaviour with restrict to library strm enabled. 

Provided a log. Please don’t waste any time trying to help further unless it’s of use to your work - if I disable restrict to library strm (and keep resolvable as false) all works well apart from the black screen for a couple seconds (which my Mac displays as a tmdb splash screen - limitation of my device I’m guessing), so can live with that. I still don’t see this when selecting player from context menu with same settings however - it’s a seamless transition. 

log with restrict library strm enabled/ resolvable false: 

1) Play movie, stop movie, playback error message. 

2) select a different movie, addon launches/generates links, back out without playing anything, addon auto relaunches multiple times before displaying playback error message. 

3) choose a different movie, select player via context menu, play, stop, no issues.

https://paste.coreelec.org/28C6ws

**Comment by jurialmunkey** [comment]
This is not the TMDb dummy splash video. It is not playing. 

If it were the splash, the log would have a message saying `lib.player.players - attempt to resolve dummy file`

Something else is causing your black screen.

Try using PlayMedia instead of xbmc.Player()
`TMDbHelper Settings > Expert > Reroute PlayMedia to xbmc.Player() [disable]`

Also check the following setting:
`Kodi Settings > Player > Videos > Adjust display refresh rate [off]`

If you have the Kodi to setting to adjust display refresh, this will cause a black screen when your TV switches modes to match the frame rate and resolution of the playing video. This is normal if this setting is enabled (if you've got this setting enabled, the strange part is why the context menu is *not* updating the refresh rate).

**Comment by Qirat77** [comment]
Using PlayMedia instead of xbmc.Player() made no difference.

However, you’re absolutely right - the black screen is a display refresh. Tested this by disabling restrict to library strm and changing adjust display refresh rate from ‘on start/stop’ to off - now I see the tmdb splash screen prior to launching addon. 

Given that I have this streaming addon set to source select and select links manually once generated, my understanding is that with adjust display refresh rate enabled, the dummy video tmdb helper creates prior to launching the addon triggers a display refresh.

If so, the black screen at that point makes sense, as does the further display refresh/ black screen after I select a generated link to play. 

Agreed, the fact that launching the addon via context menu/select player behaves differently is what threw me in the first place.
