### ISSUE TITLE
[BUG] In progress movies from trakt not starting from the last position

### ISSUE THREAD

**Issue by eesdil** [jurialmunkey/plugin.video.themoviedb.helper#1213]
### Describe the bug

I am only using Trakt to show the in progress movies. When I try to start the movie from the last position (Trakt) it starts from the beginning and not from the last position.

### Steps To Reproduce

1. Start a movie (leave enough time to be registered as in progress)
2. stop it
3. try to start it from the last position (from the Trakt's "In progress movies")
4. it starts the movie from the beginning

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
This depends on a combination of factors.

Whether the end plugin supports resume
Whether the end plugin supports setresolvedurl
Whether your tmdbhelper settings are set to use setresolvedurl and the player file is configured correctly.
whether you have enabled to retrieve resume points from Trakt in tmdbhelper settings so the items actually have resume points in kodi 

If all of the above are not true then resume will not work. Resume only works if all conditions are met - which is rare, and generally is the fault of the end plugin rather than tmdbhelper.

**Comment by eesdil** [comment]
thank you @jurialmunkey for the explanation.

The only thing is that  i have multiple devices with multiple users. Tried different methods (common database, jellyfin, ..) but they dont really work well for me, at least I was not able to set them up properly that they are quick and snappy.

The only option which seems to be working fine is using Trakt. It is working with lists and watched statuses great.
The only thing which is missing is to be able to start the movie from last position from the Trakt in progress list and then everything would be working great.

I only use Trakt for local library, so the only player which should work with it is the local kodi one.

I tried to search for settings and i found the different json files for plugins, but I couldnt find it for the local one.

Could you direct me where I can see how to set it up for the local player?

thanks a lot

**Comment by jurialmunkey** [comment]
Local files with resume should work out of the box. However, due to the way kodi stores resume, it will only work if you initially played the item from TMDbhelper - because resume is then stored on the tmdbhelper item (whereas played directly from library the resume point is saved to the library item).

The workaround is to use the Trakt addon to scrobble your progress to your Trakt account. The you enable the trakt option in tmdbhelper settings to retrieve resume points from Trakt and that will set resume points from Trakt to tmdbhelper items, meaning it doesn't matter where you play from as tmdbhelper is getting resume from Trakt rather than kodi - I hope that makes sense!

**Comment by eesdil** [comment]
Yes, I scrobble the progress to trakt (this I can see working as it appears in trakt itself) and I have the resume points enabled in tmdbhelper's trakt part.
I can see the list from tmdbhelper's trakt in progress movie list, and I  have the progress on them (the correct one). I can see it also on other devices with the correct resume points.
When I start to play them, it is even offering to resume, but at the end it starts from the beginning.

**Comment by jurialmunkey** [comment]
>  When I start to play them, it is even offering to resume, but at the end it starts from the beginning.

I suspect you have enabled some setting that is interfering. Best guess is the "Resend local files" expert setting, which is a hack that forces playback of local files to restart due to an old bug in the Trakt addon where it wouldn't recognise some items for scrobbling.

**Comment by eesdil** [comment]
hmm, I have just tried it and ... working great :)  feeling stupid, yesterday went through the settings and didnt spot it, altough it has a bit "TRAKT hack" sign on it :)

thanks a lot

**Comment by eesdil** [comment]
Seemingly, there was a reason this setting was on... :)

So if i switch it on, I can start at position,  but I can not scrobble anymore.

**Comment by jurialmunkey** [comment]
> So if i switch it on, I can start at position, but I can not scrobble anymore.

Yes, it is frustrating. I can't remember the exact cause (whether it is Kodi or the Trakt addon) but yeah, that's the point of the hack, it resends the file after starting playback to force it to be recognised by the Trakt addon (so solves scrobbling but loses resume). 

From memory, I think there is some piece of metadata that the Trakt addon relies on to recognise the item, but for some reason it Kodi loses that info (I think it might be DBID) first time on playback. I can't remember the specifics but it is something along those lines -- and for some reason resending the item to Kodi's player keeps the metadata the second time (but we lose the resume because we're sending it manually instead).
