### ISSUE TITLE
🐛 Doesn't load the specific landscape art for seasons until you click 'refresh details' in the context menu

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/plugin.video.themoviedb.helper#1220]
### Describe the bug

Hi Jurial!

Hope you're doing well!

This is just a minor aesthetic bug but I wasn't sure if this belonged in the Arctic Fuse or TMDb Helper repo, so please let me know if this is the appropriate place to post.

If your viewtype is set to 'Landscape' inside the TMDbH addon, and you click on a new TV Show (with more than one season), the season art is duplicated across all the thumbnails.

If I click on 'Manage Artwork' on any of the seasons, I can see the correct artwork in the preview, but if I back out and go to the addon it's still the duplicated artwork.

Once you click 'Refresh Details', it'll populate with the correct season landscape art.

I have posted some screenshots below as an example.

### Steps To Reproduce

1. While using Arctic Fuse, look up a new TV Show that has more than one season (Discover hub is what I used)
2. Click on the show and it should open inside the TMDbH addon
3. Make sure the viewtype is 'Landscape'

All the seasons have the same landscape art.

Bring out the context menu and select 'Refresh Details' and everything will update with season specific landscape art.

### When you first open the TV Show:
![TMDb Helper_Before refreshing details](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/167294806/d7350efc-90ed-44ce-a42d-2e453af831a4)

### After clicking 'Refresh Details':
![TMDb Helper_After refreshing details](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/assets/167294806/0b5926a0-ee59-45c0-9a89-9a3786d9f428)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
So what is the bug? If it's that the items don't update immediately, that's not a bug - that's simply how Kodi works.

Once a plugin creates the directory and Kodi displays it on screen, the plugin is no longer active and has no further control. ListItems cannot be modified after directory creation.

If you change the artwork database cache for the plugin items (e.g. via manage artwork) that will not change the ListItems onscreen because that is not possible. Changing the artwork cache only changes how the plugin will generate any future ListItems. 

If you want to see changes you made to the cache, you must first ask Kodi to refresh the directory. When Kodi refreshes the directory, it will ask the plugin to generate new ListItems (which will then reflect those changes made to the cache).

You can refresh the directory by going to a different one and then going back; or by reloading the skin; or, in a media window, by doing something which issues a container.refresh command (e.g. like the refresh details command does).

It would be a bad idea for the plugin to force the container to refresh after changing artwork. Simple example: a randomised list; but there's lots of other reasons too.

**Comment by jurialmunkey** [comment]
Also, I do not have this issue with not having season artwork.

Make sure that you have enabled FanartTV lookups for plugin and widget artwork in TMDbHelper settings. That will ensure that season artwork is added by default without needing to add it manually.

**Comment by OfficerKD637** [comment]
> Make sure that you have enabled FanartTV lookups for plugin and widget artwork in TMDbHelper settings. That will ensure that season artwork is added by default without needing to add it manually.

Thank you so much! This completely fixed the issue for me! I checked with a bunch of TV Shows and now I get the correct season artwork automatically.
