### ISSUE TITLE
[Feature] Add a listitem property to denote when a film is part of a collection for skins (Arctic Fuse) to use as an indicator

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/plugin.video.themoviedb.helper#1226]
### Describe the feature that you'd like

Hey J!

Hope you're doing well!

Currently, the 'Collection' indicator in the AF skin only works with local/library files. I was wondering if it would be possible to add a listitem property inside TMDb Helper which skins could use to show when a film belongs to a collection. 

This would let people visually know they could use the 'Browse lists' option in the context menu to open the collection. It could be helpful when trying to discover more obscure movies.

Currently, this is the collection icon:
![movieset](https://github.com/user-attachments/assets/1bd9e3bf-16c4-4ce2-befc-98029aaf6995)

Maybe we could use something like this to denote it as a TMDb Collection (not local):
![movieset_TMDb](https://github.com/user-attachments/assets/440ee60d-db6e-4a5c-9905-f96530e16398)

Not sure which would be an easier/better approach:
1. Having two separate toggles for Local and TMDb Collection indicators 
2. Or just having one 'Collection' toggle but 'Local' takes precedence over TMDb

Let me know what you think.

### Why is this feature needed? What problem does it solve?

Please see above.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Works fine for me. The icon denotes that the item **is** a collection, not that the item **belongs** to collection. It doesn't show for individual movies no matter what.

You can check if a movie *belongs* to a collection by checking `!String.IsEmpty(listitem.Set)`

Whether the skin should show an icon or not is different question (I don't think it should because the whole purpose of the icon is to differentiate a set of items as a folder from a single playable item within a folder of movies).

![screenshot00619](https://github.com/user-attachments/assets/ecb54270-a17c-4793-a067-1722e326d1a6)

**Comment by OfficerKD637** [comment]
Oh okay. My bad, I got confused between the two icons (collection vs library) and conflated those two issues in my post.

I totally see your point. It's just that sometimes you get recommended a really old movie that's part of a set/franchise/trilogy and it'd be nice to know if you skipped any previous ones belonging to that series.

Like I was recommended 'Before Sunset' but I didn't know there was 'Before Sunrise' that came before it (I should've done more research lol).
Now obviously if you are about to watch something like 'The Godfather 2', one would assume you know about 'The Godfather' (it's in the name, ha)

But thank you so much for letting me know about `listitem.set`. Does that only work for local items or also for TMDb as well?

**Comment by jurialmunkey** [comment]
It works for both. Listitem.Set contains the name of the collection the item belongs to. If it is a set in the library, it will additionally have a Listitem.SetID

And I get what you're saying but I don't think the place for it is the indicator - the indicator indicates something special about the item to draw attention to it and make it easier to spot amongst all the items eg we want in progress items to stand out (because we want to continue watching them), or movies from TMDbhelper that are also in the library (because we know those are playable), or a collection of movies (because it hides other movies behind it - eg we know that a star wars poster with a collection symbol is not just a new hope, but will also have empire strikes back etc.)

I don't think it's critical to see indicators for movies that belong to a collection - if we added indicators for every piece of interesting info they end up meaningless because they all override each other (or we have a million different indicators and badges covering the poster until you can't see it).

You can already get extended details about a movie in the info page. This includes whether the movie belongs to a collection, which will be listed in the same column as the director writer and studio. 

In a roundabout way that goes back to my point - if we add a "belongs to a collection" indicator, then why not also an indicator for all these other pieces of info like the director having directed other movies or the studio having produced others etc. - we could go on forever adding extra badges to the posters for all sorts of details. The indicator usage has to be judicious to avoid it looking ridiculous and becoming meaningless through excessive use (what even do all these icons mean! - even the collection and library icons are stretching it already)

**Comment by OfficerKD637** [comment]
Yeah now that I think about it, adding unnecessary icons will make the skin very convoluted and confusing.
And I'm also realizing that me missing the first movie was a user error (you can't solve users being dumb with skin updates 😂)

Thank you once again!
