### ISSUE TITLE
[Crashing] Service monitor container method crashes

### ISSUE THREAD

**Issue by MikeSiLVO** [jurialmunkey/plugin.video.themoviedb.helper#1233]
### Describe the bug

This plugin, when enabled on my system, causes Kodi on Windows to crash. Consistently. I can force it to crash with skin reloads and opening MyVideoNav.xml when navigating to the next/previous item. It also happens while using any skin like Estuary.

EDIT: Can't reproduce in Estuary. I mistakenly thought a skin reload while DialogVideoInfo was open, was connected.

### Steps To Reproduce

I can reproduce easily with multiple skin reloads and can/will provide additional logs or whatever else is needed :)

Multiple (maybe 2, 3, or 4) skin reloads
Navigate to a MyVideoNav section (movies, TV shows, etc...)
Scroll to next item
Crash

### Debug log

I have many debug logs, dmp files, and stacktrace.txt's that seem to say nothing helpful at all.  Now that I think of it, it seems to have started when I tried to remove Embuary Helper and switch primarily to TMDbH on my Aeon Nox skin but happens with any skin I use. I have been dealing with this issue for a bit now and I originally did have TMDbH debugging enabled but saw nothing that led me to think it was the cause. I assumed it was everything but this plugin until it was the only thing left...

Folder of previous crashes with related files.
https://drive.google.com/drive/folders/1CLLd9jgtsUOZdxFr6fTtcg5uNmVFOVCN?usp=drive_link

As soon as I turn on TMDbH... Crash.

https://paste.kodi.tv/ufobecajut.kodi

### Screenshots and Additional Info

I finally disabled TMDbH and that is how I figured out it was causing my crashing issues.

I clicked the box below stating I am on the latest release (I should've been on the one version before current for the folder link above) but the last log provided in the debug log section should be the latest release.

Thanks :)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
The plugin itself won't "cause" the crash directly -- Python by itself doesn't have the type of lower level access needed. It has to be via something not handled correctly in either Kodi's GUI API or a CPython module (and then something TMDbHelper is doing is exacerbating that issue).

Debug logs won't tell me much. Really need a stacktrace with debugging symbols enabled to have any idea whether it is something in Kodi or something in CPython. Not certain how to get that on Windows only LibreELEC.

Are you using the service monitor? Try disabling it and seeing if you can still cause the crash. That's my best guess as that uses Kodi's GUI API to fill the background container.

If it no longer crashes without the service monitor enabled (or by switching from container to property method), then my best guess is there's some issue in Kodi where it is not properly cleaning up the ListItem references in GUI API when it clears out the container on a reload -- If TMDbHelper was in the middle of updating the item, then when it tells Kodi to add those extra details to the ListItem, Kodi will crash because the Kodi GUI API tries to access a ListItem at a memory address that it just removed (null pointer dereference) -- if it were handled correctly, Kodi would simply raise an error instead of crashing.

That's very much a speculative guess, but my best one based upon the information.

**Comment by MikeSiLVO** [comment]
I can't force a crash with the Service Monitor off but I did notice something else...

When the Service Monitor is enabled and without any skin reloads, Kodi will also randomly crash if I navigate or open and close DialogVideoInfo for different items fast enough. Not sure if that info helps at all.

**Comment by jurialmunkey** [comment]
If you switch to the property method for service monitor, does it crash? 

i.e. normally you enable the container method with something like:
```
Skin.SetString(TMDbHelper.MonitorContainer,99950)
```

So can disable it by swapping that for this command and then restarting
```
Skin.Reset(TMDbHelper.MonitorContainer)
```

If it is what I think it is then it should be fine with property method, and only container method will crash.

**Comment by jurialmunkey** [comment]
Also other thing to test, with container method *enabled* can you try disabling the ratings and artwork lookups

```
Skin.SetBool(TMDbHelper.DisableArtwork)
Skin.SetBool(TMDbHelper.DisableRatings)
```

These are both threaded, so potentially can have a delay in setting those extra properties.

If my hunch is correct about ListItem memory address changing causing a crash because Kodi isn't tracking it properly in the API, then I expect that disabling these threaded lookups will have the same effect of avoiding the crash because it reduces the timing window for this type of scenario to occur where Kodi is trying to set data to something which no longer exists.

From there I can probably add a few extra "safety" type checks. It won't be possible to fix it as it indicates an issue in Kodi core, but we can at least rule out some other possibilities this way and hopefully get to a relatively stable state.

**Comment by jurialmunkey** [comment]
Oh and one more thing, in TMDbHelper expert settings enable "Rebuild service listitem offscreen" and restart (make sure to hit OK in the settings dialog to save the setting - I always forget to do this!). Possibly this might help with the container method.

So summary of tests to do:
1. Try with property method instead of container and see if it still crashes (indicates if it is just container method)
2. Try with artwork + ratings threads disabled with container method enabled (indicates what part of container method)
3. Try with expert setting to rebuild offscreen using container method with artwork+ratings enabled (this setting rebuilds a new listitem before adding ratings/artwork, so this will help see if it is an issue with the listitem memory address or the container).

**Comment by MikeSiLVO** [comment]
Using property method, Kodi does not crash.

``Skin.SetBool(TMDbHelper.DisableRatings)`` = No crashes so seems to be connected to this

``Skin.SetBool(TMDbHelper.DisableArtwork)`` = No effect plus does not crash when reset and Ratings are disabled

"Rebuild service listitem offscreen" was already enabled in my settings, should I test with disabled or not necessary?

**Comment by jurialmunkey** [comment]
Yeah maybe test with rebuild off-screen disabled just for good measure (but I'd be surprised if it has an effect).

**Comment by MikeSiLVO** [comment]
Yeah, no effect.

**Comment by jurialmunkey** [comment]
Can you test this PR and see if it helps at all? https://github.com/jurialmunkey/plugin.video.themoviedb.helper/pull/1235

I'm expecting best results with rebuild offscreen enabled, so test with that first, but might also help with it disabled.

It's less a fix and more a workaround to try to avoid creating the conditions which I think might be triggering the crash in Kodi. An actual fix would need changes in core but hopefully can at least detour around creating them as much as possible.

**Comment by MikeSiLVO** [comment]
I cannot cause a crash using #1235 with rebuild offscreen enabled or disabled with my previous testing methods but I can when reloading skin in the MyVideoNav window.

Just to confirm I disabled the plugin and tried to reproduce a crash and could not but can only with MyVideoNav open and doing a skin reload. If I reload skin outside of the videos window there is no crash, also seems to be exacerbated by Movie content since TV Show content doesn't crash until I navigate to Movies. 

Weird, it isn't crashing anymore. Maybe some caching is helping?

EDIT: Now it's crashing again... Seems more intermittent than previous.

EDIT 2: Aha! Its the rebuild listitems offscreen setting. Doesn't crash with that disabled.

EDIT 3: Found out why it seemed intermittent, the rebuild offscreen setting doesn't seem to take effect until a Kodi restart. I was testing just toggling it on/off.

EDIT 4: I think the size of my library is also attributing to this issue. I can reproduce in my recently added episodes section.

``videodb://recentlyaddedepisodes/`` is quite large since I added ``<recentlyaddeditems>99999</recentlyaddeditems>`` to my advancedsettings.xml file.

**Comment by jurialmunkey** [comment]
> Found out why it seemed intermittent, the rebuild offscreen setting doesn't seem to take effect until a Kodi restart. I was testing just toggling it on/off.

Yep, you pretty much always need to restart Kodi after changing service monitor settings to have them take effect. There are some that do apply immediately, but most need to be set on initialisation of the service.

(BTW I talking about user settings inside the TMDbHelper settings dialog here. The skin settings for toggling the service or blur/crop etc. don't require a restart, it's only user settings that do).

> I think the size of my library is also attributing to this issue. I can reproduce in my recently added episodes section.

It could be a separate issue but this shouldn't have anything to do with retrieving ratings causing a crash.

If you think it might be having an impact, you can disable Kodi DB lookups in TMDbHelper general settings (and restart afterwards) to see if it changes anything.

**Comment by MikeSiLVO** [comment]
My current methodology that causes a crash 100% of the time involves calling  skin variables view builder in a MyVideoNav window.

``Runscript(script.skinvariables,action=buildviews,contentid=$VAR[SkinVariablesContentVar],pluginname=$INFO[Container.PluginName])``

```
<variable name="SkinVariablesContentVar">
	<value condition="String.IsEqual(Container.Content,genres) + Window.IsVisible(MyMusicNav.xml)">genres-music</value>
	<value condition="!String.IsEmpty(Container.Content)">$INFO[Container.Content]</value>
	<value condition="Container.Content() + Window.IsVisible(MyVideoNav.xml)">none-videos</value>
</variable>
```
https://github.com/MikeSiLVO/skin.aeon.nox.silvo/blob/master/16x9/Includes.xml#L370

Disabling Kodi DB lookups, indeed, had no effect.

Removing the recently added entry from my advancedsettings.xml file did have an effect. No crash until I entered the movies section. Might be a coincidence but that seems to suggest that the amount of items are related somehow...

Default recently added episodes was only 25 items and no crash until navigating to the movies section, which contains 3,051 entries not including those in collections.  Calling skin.variables to build a view always causes a crash as soon as I navigate to the next entry with rebuild offscreen enabled.

How does the rebuild listitems offscreen work? Does it build listitems by page(s) of the container, is it building all items offscreen, or am I completely misunderstanding what that setting does and am totally off base here?

**Comment by MikeSiLVO** [comment]
Tried ``<recentlyaddeditems>1000</recentlyaddeditems>`` all the way to ``10000``

No crash until somewhere after 5000... I don't know what that means since my movies section is not that large.

``5000``= no crash ``6000``= crash

**Comment by MikeSiLVO** [comment]
The more I think about it, this seems similar to the old Kodi bug when reaching a property limit and things would start to go funky like missing fanart so had to add stuff like Container.ListItem.Art(fanart) to get around that. Instead of empty list items is Kodi crashing instead?

I'm just spitballing here 🤷‍♂️

**Comment by jurialmunkey** [comment]
> How does the rebuild listitems offscreen work? Does it build listitems by page(s) of the container, is it building all items offscreen, or am I completely misunderstanding what that setting does and am totally off base here?

No, complete misunderstanding. Nothing to do with what items you can see or readahead precaching or anything like that. 

It's about the ListItem added to the hidden background container -- onscreen in this sense means that ListItem has been added to the container in the GUI and is therefore available to the skin, not that it is literally visible onscreen (it could still be out of bounds in terms of coordinates or hidden by a fade animation etc.) 

The setting is about whether the ListItem in 99950 will only have its details modified offscreen (i.e. only *before* being added to the container) OR if it will also be modified "onscreen" (i.e. also *after* it is added).

To avoid having to wait for ratings/artwork, those are looked up separately afterwards. So the ListItem is first generated without that data, then it is updated later with that information once available (i.e. modified onscreen).

For legacy reasons, Kodi will temporarily lock the GUI as a precaution while updating an onscreen ListItem to avoid the GUI trying to access that memory whilst it is being written. To bypass the lock, ListItems can have an `offscreen=True` flag to tell Kodi that the ListItem will only ever be modified offscreen.

Since we don't want the GUI to lock and freeze whilst we are scrolling between items, we set offscreen=True (plus it is not meant to be necessary anymore anyway).

What the TMDbH expert setting does is ensure that we are actually true to our word and are only ever modifying offscreen items. It's basically an extra precaution where it avoids modifying the onscreen item by generating an entirely new ListItem once the ratings/artwork are retrieved, then adds that new item instead of updating the existing one with the ratings.


> The more I think about it, this seems similar to the old Kodi bug when reaching a property limit and things would start to go funky like missing fanart so had to add stuff like Container.ListItem.Art(fanart) to get around that. Instead of empty list items is Kodi crashing instead?

Yes this could be two issues in tandem. One related to a max property limit and Kodi running out of memory and crashing, and then a separate one with ListItem crashes.

**Comment by jurialmunkey** [comment]
Are you sure this crashes with the offscreen expert setting disabled? (not enabled).

I can get a scenario where I can reliably recreate the crash on windows with the offscreen setting *enabled*. But if I have the setting *disabled* it will work fine, which is what the default is (I can still cause a crash if I'm really trying to by spamming reload skin but I have to really make an effort, whereas with the setting enabled it's pretty reliable)

As far as I can tell, Kodi has some issue with the addItem() function after a reload. Offscreen makes it worse because it adds item twice in quick succession. It doesn't seem to be anything about the ListItem in particular, even a blank one will crash things. I don't think there's anyway to workaround it in the plugin - there's some bug with the function in Kodi but I'm not certain enough yet what the conditions are for it to be able to make a test case.

**Comment by MikeSiLVO** [comment]
``EDIT 2: Aha! Its the rebuild listitems offscreen setting. Doesn't crash with that disabled.``

I had that setting enabled cause I mistakenly thought it was doing a "readahead" of items offscreen and not what it actually does.

Currently using the version from PR  #1235 and the setting is disabled and haven't had a singe crash since.

**Comment by jurialmunkey** [comment]
Oh haha I'm dummy! I did see your edits but completely misread and thought you were saying the opposite - ie that you had thought you had it disabled but it was actually still enabled because you hadn't restarted.

In that case I'll merge the PR if it is improving things. Might actually remove the off-screen setting entirely as it appears to have the opposite of the intended effect (and I was fairly sure it wasn't necessary past Matrix anyway).

**Comment by MikeSiLVO** [comment]
I would suggest removing it altogether and thanks for helping me solve this!
It's been happening for awhile and I would have never noticed the connection to the offscreen setting.
