### ISSUE TITLE
[Feature] Fix for property inconsistencies

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#1246]
### Describe the feature that you'd like

There are some annoying inconsistencies when dealing with item detail properties.

ListItem.Director returns a [CR] separated string.
ListItem.Property(Creator) returns a ' / ' separated string.
ListItem.Writer returns a ' / ' separated string.
ListItem.Cast returns a [CR] separated string.
and so on.....

Could we get a global property that sets the separator:-

`Skin.SetString(TMDbHelper.DetailSeperator,[CR])` or `Skin.SetString(TMDbHelper.DetailSeperator, / )`

Then when you set the properties it should just be a simple string replace to change the separator.

Thanks.

### Why is this feature needed? What problem does it solve?

See above.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
I don't set the separator. These are done by Kodi. The directors/cast are just passed as a list of items to kodi and then Kodi formats the labels.

The only one I control is the creator property because that's a custom one, so I picked the slash separator as that's what Kodi uses for writer (also it uses it for director for me - not sure why you're getting cr instead).

Tmdbhelper also outputs each of the crew departments as numbered properties so you can join them together how you like.

**Comment by roidy** [comment]
>I don't set the separator. These are done by Kodi. The directors/cast are just passed as a list of items to kodi and then Kodi formats the labels.

Yes I know this is an inconsistency with Kodi itself and has been forever.  That's why I'm asking for this feature to be added, to give the user the ability to make all of the properties consistent.

>Tmdbhelper also outputs each of the crew departments as numbered properties so you can join them together how you like.

Again I know but these are only useful if you know how many items there are, eg one film may have 20 cast members and another has 50.

As you say you already split up and output numbered versions of the properties so It should be simple to re-join them with a custom separator and output it to another property, that way you can keep the original property the same as what Kodi provides.

**Comment by jurialmunkey** [comment]
I can make a different property, but I can't change how the kodi one is done.

**Comment by roidy** [comment]
That would be perfect, thanks.

**Comment by jurialmunkey** [comment]
Is `[CR]` needed here or is it more about getting consistency with `/` ??

Because the only one that's inconsistent in Kodi using`[CR]` is cast as far as I can tell. All the others already give `/` separator by default (director, writer, genre etc.) and looking at my code, I forgot that I already added `ListItem.Property(cast)` quite a while ago to get cast in the same `/` separated format as the others.

**Comment by roidy** [comment]
I need everything separated with [CR]. 

Would it not be more useful though if the user could choose the separator to use as I said in my first post. That would give people more options.

**Comment by jurialmunkey** [comment]
Mapping info is done at cache level so it would affect every skin. Also, as I said, I can't change the kodi infolabel behaviour so it requires a new property.

It's fine I can add new properties, was just trying to avoid resetting everyone's cache database for details and avoiding the need for double handling of the mapping.

**Comment by roidy** [comment]
>Mapping info is done at cache level so it would affect every skin. Also, as I said, I can't change the kodi infolabel behaviour so it requires a new property.

Ok, I didn't realise the data was all cached. No problem, it's not a big deal, thanks anyway.
