### ISSUE TITLE
[Question] Get seasons and episodes from Trakt integration

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#129]
Again, just a question. I know I already created an issue asking the same thing but I'm just curious about this. When I asked you about being able to give the option to use a different information provider instead of TMDB, you answered saying that it would mean the whole rewrite of the addon. 
While looking into my Trakt list I realised that, even though it uses the Trakt API to find the collections and watchlists from my profile, once inside a TV show it seems to be using the TMDB information as seasons in some animes are not the same as in Trakt. So here is the question. Would it be to difficult to, when using the Trakt part of the addon, to just use the Trakt API to fetch back information? And, given the information about TV shows is actually different from TMDB in some cases, how is the addon handling the Trakt history now? Shouldn't it fail when trying to mark an episode as watch in those cases?

**Comment by jurialmunkey** [comment]
Trakt only gives very limited information via the API.

For instance, here is the watched history result for a tvshow:
```json
 {
    "id": 1982347,
    "watched_at": "2014-02-27T09:28:53.000Z",
    "action": "checkin",
    "type": "episode",
    "episode": {
      "season": 2,
      "number": 1,
      "title": "Pawnee Zoo",
      "ids": {
        "trakt": 251,
        "tvdb": 797571,
        "imdb": null,
        "tmdb": 397629
      }
    },
    "show": {
      "title": "Parks and Recreation",
      "year": 2009,
      "ids": {
        "trakt": 4,
        "slug": "parks-and-recreation",
        "tvdb": 84912,
        "imdb": "tt1266020",
        "tmdb": 8592
      }
    }
  },
```

As you can see, it is very bare. There isn't even artwork. The only details are the IDs, title, season/episode, year, and watched timestamp. It needs to have info looked up via another service.

Since I have to lookup via TMDb, it makes sense to show all the info from TMDb so at least it is consistent.
