### ISSUE TITLE
[BUG] Issue with the "Mark as seen" flag

### ISSUE THREAD

**Issue by urs45** [jurialmunkey/plugin.video.themoviedb.helper#1298]
### Describe the bug

Not sure but I guess it's a bug. Some Players, (or maybe everyone?), don't set the marked as seen Flag when starting the player using the context menu while they work fine if set as Standard Player in Tmdbhelper addon.

### Steps To Reproduce

1. start a TV show using an other player than the one set as standard player
2. after watching no marked as seen flag is set
3. set the just used player as standard player
4. start the same or any other TV show episode again and this time the marked as seen Flag will be set

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Not possible. Kodi manages the storage of watched indicators. Kodi stores these based upon the path of the item. The context menu action does not have the same path (because it does a different action) and so the watched indicator cannot be added.

The only way to manage this effectively is via some third party (i.e. Trakt) where the end plugin will mark as watched in your Trakt account and then TMDbHelper is set to retrieve watched status from Trakt so that it can override Kodi.

**Comment by urs45** [comment]
Thanks for the info, i will try Trakt maybe or just flag items, started using a player via context menu manually, as it is anyway exceptionaly only and normaly the set standard player is used.
