### ISSUE TITLE
"Play Using" for episodes (.strm files)

### ISSUE THREAD

**Issue by akuiraz86** [jurialmunkey/plugin.video.themoviedb.helper#130]
Isn't tmdbhelper supposed to be showing the context menu item "Play Using" for episodes (.strm) when browsing in library mode? Like episodes created using another addon?

I'm using the Confluence skin and my TV shows were scraped using theTVDb scraper... not sure if either makes a difference

I'm not seeing the context menu item to "Play Using" when browsing with only my library.

I'd prefer to not have to browse into the TMDbHelper add-on... It is faster using library files.  Plus the 20 items restriction makes showing me my trakt collection painfully slow (i have 250+ shows)

Should I see that menu item or not?  If I am, I was wondering if it's because of my skin or how they were scraped...

I've already seen these previous issues but I still don't understand completely:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/116 and https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/98

**Comment by jurialmunkey** [comment]
.strm files are treated by Kodi as if they're just another video file - but instead of being a video they contain a shortcut link to a plugin url (in this case to TMDBHelper's player function). The library scraper determines what properties the library items have attached to them - so TMDBHelper has no control over the properties that are set for library items.

The TMDBHelper "Play Using" context menu requires the TMDB ID of the _TV Show_. However, library scrapers only set the Episode ID and that might not even be a TMDB ID (for instance TVDB scraper sets a TVDB ID). Since scrapers don't set the required ID, then the context menu item can't be used.
