### ISSUE TITLE
[Question] Navigating back in TmdbHelper

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/plugin.video.themoviedb.helper#131]
When I'm looking at information for a movie (World War Z), I can click an actor A (Mireiile Enos) to see more info about them. But if I then press Backspace, I don't go one step back but I also leave the movie.

What key do I press to get from the actor back to the movie ?

Also, weird stuff happens If you then pick the same movie, pick a different actor B (Sterling Jerins), pick another movie they played in, and then press backspace.   By going back I wound up with actor A but they weren't on the path I had taken. (I just repeated this, but this time no actor A).

**Comment by jurialmunkey** [comment]
>
> When I'm looking at information for a movie (World War Z), I can click an actor A (Mireiile Enos) to see more info about them. But if I then press Backspace, I don't go one step back but I also leave the movie.

It's because the very first info dialog is managed by Kodi and it gets closed before TMDBHelper opens so there is no dialog to go back to in the TMDBHelper history. I'm looking for a solution but haven't found a viable one so far. It's a trade off of using the native info dialog instead of a scripted window like Extended/Embuary Info.

>
>Also, weird stuff happens If you then pick the same movie, pick a different actor B (Sterling Jerins), pick another movie they played in, and then press backspace. By going back I wound up with actor A but they weren't on the path I had taken. (I just repeated this, but this time no actor A).

What skin? These sound like issues that exist with the old implementation of the info dialog (i.e. the approach in AZ2). A newer implementation exists that doesn't have these issues (new implementation will be in Arctic Horizon).

**Comment by drinfernoo** [comment]
Could the newer approach be ported to AZ2?

**Comment by jurialmunkey** [comment]
> 
> 
> Could the newer approach be ported to AZ2?

Yeah, I just haven't got around to it yet.

The process for how it is implemented is outlined in the wiki (I don't even bother outlining the old method anymore as the new one is far superior)
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Replacing-Extended-Info

**Comment by jurialmunkey** [comment]
Just pushed through an update for AZ2 to use the newer method.

**Comment by DaisyF8** [comment]
I was using AZ2. But it only happened that one time, wasn't able to replicate it.

Thx for the update and for explaining.
