### ISSUE TITLE
[Request] Speed up ‘Your Next Episodes’ list 

### ISSUE THREAD

**Issue by 7E1EVEN** [jurialmunkey/plugin.video.themoviedb.helper#133]
Hi jurialmunkey,

Do you think it’s possible for you to speed up the ‘Your Next Episodes‘ list. I’m aware it has to fetch a lot of data but I’ve seen other addons pull up the same list in considerably less time. 

Movie watchlist, latest released movies, random trending movies/tv shows all load within 5-10 seconds. While ‘Your Next Episodes’ takes up to 2 minutes sometimes. 

Not a dealbreaker but would be much appreciated

**Comment by jurialmunkey** [comment]
It's because they cache the upnext details on startup and only refresh the cache after a certain amount of time. If you want up to date details then it takes time.

I've added a cache for upnext so that the next time it is entered it will open much faster - the cache will be refreshed if Trakt records new activity (e.g. you watch an episode) or after a day (in case new episodes come out).

**Comment by 7E1EVEN** [comment]
Heyy thanks a lot. 

It does seem a little bit quicker. But to be honest I haven’t been using it this way in a while so my reference is kinda off. 

Appreciate you coming through though.

Stay healthy and stay safe.
