### ISSUE TITLE
Sort by air date option?

### ISSUE THREAD

**Issue by swisslis** [jurialmunkey/plugin.video.themoviedb.helper#138]
Is there a way currently, or can it be added, to have sorted by air date on 'your next epiosdes' ? Ideally the widget would update automatically and have a new aired today episode of something from my trakt collection at the start of the widget. Please let me know if this is already possible, or if it can be added. Many thanks

**Comment by jurialmunkey** [comment]
Yeah I think you're right - it makes more sense to sort by air date rather than watched date. My initial thinking was that you'd want shows you recently watched first - but then you miss out on shows that haven't aired for a while. That sorting (by recently watched) makes more sense for in-progress so that you can continue watching even if you're watching an older show.

Change in latest git

**Comment by drinfernoo** [comment]
Would it be possible to add a setting to flip between the two? I often find myself digging into old shows in the off-season and this sorting puts them way towards the end of the list (King of The Hill or Seinfeld, anyone?) 😅

**Comment by jurialmunkey** [comment]
@drinfernoo - There should be a setting now under  `Accounts > Trakts > Next episodes sort method`
