### ISSUE TITLE
[Request] Randomized - Trakt Watchlist

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/plugin.video.themoviedb.helper#146]
This one sounds weird, but hear me out haha!

So I’m normally the person who adds to my Watchlist faster than than I get to watch movies on said list. 

I have a widget on my homescreen pointing to my Trakt Watchlist, set to random ordering. 

However, it only pulls the first page, then randomizes that instead of randomizing the whole list. 

Setting the Trakt item count to 20 does help a lot in this scenario, but is it possible to bring in a true randomized list from Trakt’s Watchlist?

**Comment by joyraina** [comment]
I was looking for a similar solution for already existing trakt lists like IMDb top 250, etc. Widget puts first 20 items in a list in random order, so it is always same set of 20 movies. What I was looking for 20 set of random movies from set of movies in a list ( like IMDb top 250).

Possible work around of you:

> Create a new list in your trakt account with default sort set as random.
> Add item to that list
> Use that instead of my watchlist

Not tested it.
New user here using kodi on TV and trakt on mobile, so things are slow around here.

**Comment by jurialmunkey** [comment]
For personal custom lists, you can apply sorting on the website and have it applied in TMDbHelper. It won't work for a watchlist though -- you need to set the sorting for the watchlist in the addon settings. Custom lists aren't really a good substitute because they don't remove items you've watched.

The problem with random watchlist is that Trakt doesn't provide the option to do randomised sorting on server side. It can be done client side, but since that is a different approach to the current way the watchlist is sorted, that then requires having a special method specifically for randomised watchlist -- the need for a custom method just for a randomised watchlist is the main reason why you can't do it yet - I just haven't got to it!

**Comment by Demonseeed** [comment]
Thank you for the update jurialmunkey! Glad to you see you have it on your list, I was getting worried you’d eventually come back and say it’s not possible haha 😄

**Comment by jurialmunkey** [comment]
@Demonseeed - This will resolved (finally!!) in the upcoming v4 release (currently available as pre-release on the "refactor" branch).

You can now sort watchlist via the context menu with options to sort by rank, added, title, year and random. When adding as a widget, the plugin will display the sort options as an intermediary directory in skinshortcuts so that you can choose the sort method you prefer.
