### ISSUE TITLE
[Bug] Get Additional Details From The Local Kodi Library Database

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#155]
"Get additional details from the local Kodi library database"  stopped working.

**Comment by jurialmunkey** [comment]
How so?

**Comment by Blurayx** [comment]
I know very odd. when I installed the fix update the widgets changed instantly.
I have the same issue with my Mac & Nvidia Shield TV 

<a href="https://imgur.com/qIScQ0Y"><img src="https://i.imgur.com/qIScQ0Y.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/e0PFVU8"><img src="https://i.imgur.com/e0PFVU8.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/4WqPzLu"><img src="https://i.imgur.com/4WqPzLu.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Those are the season posters - they have never worked using library data. We already discussed this issue in the other issue which is still open because I haven't fixed it yet..
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/142#issuecomment-607026372

**Comment by Blurayx** [comment]
I think I'm getting myself confused.

To clear things up. at present TMDbHelper cannot grab none season posters in my library    
inside my  library folder
[img]https://i.imgur.com/KcUj5WH.png[/img]

**Comment by jurialmunkey** [comment]
Currently TMDbHelper only syncs local details for tvshows and movies. It does not sync local details of seasons or episodes.

Since Next Aired displays episodes, the info is not synced for the episode. Only the base tvshow info is synced. 

Episodes by default in Kodi show the season poster, not the tvshow poster. What I think you want is for Next Aired to show tvshow posters NOT season posters.

So the issue isn't actually about this option at all (and this option is actually working). The issue is that you want the default artwork type to be overridden for episodes in Next Aired.

**Comment by Blurayx** [comment]
Ok, I understand now. Thanks. Clearing things up 😀

**Comment by jurialmunkey** [comment]
@Blurayx - I think this should now be fixed. You will need latest version of TMDbHelper and latest version of Arctic Horizon. Next Aired posters should now match library posters. Can you test and confirm?

**Comment by Blurayx** [comment]
Wow, perfect!
Instantly changed and matched my library 😀
