### ISSUE TITLE
[Bug] Year variable not populated

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#169]
At some point in the latest commits I think you added something that broke the year variable in players. I'm getting a '+' instead of the year. I installed a version from some commits back and the year gets populated so it has nothing to do with TMDB.

**Comment by jurialmunkey** [comment]
Are you sure you were using the most recent version? I thought I already fixed this bug (It was because I accidentally pushed a version where I had commented the year out to test something).

It should have been fixed in 2.4.14 in this commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/e83c09ff34caafd047c934ec83f9fc9df0accbea#diff-1d5c3853ba377b8a720bd31008a9df95

**Comment by juanma-cvega** [comment]
I thought I was but probably I wasn't. I just tried again and it works fine.
