### ISSUE TITLE
[Feature Request] Option to add a delta to dates in players

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#173]
Would it be too complex to add the option to do something like `{premiered+X}` where X is a number to get the premiered date plus X days? It's a very specific request for the Emby player. For some reason I don't really get, it doesn't take premiered date but `MinPremieredDate` and `MaxPremieredDate`. I tried using premiered for both but it doesn't always work. By just adding a day to premiered for MaxPremieredDate it works in the cases I tried that didn't before. Sorry I just keep asking for what seems like hacks to get it working.

**Comment by jurialmunkey** [comment]
Does it take an ISO 8601 timestamp? Would something like this work ?
`plugin://embyconsearchurl/?MinPremieredDate={premiered}T00:00:00Z&MaxPremieredDate={premiered}T23:59:59Z`

You would be able to do that without any additions.

A `{premiered+X}` / `{premiered-X}` would be possible if X is a fixed predefined value. It wouldn't need to be hardcoded but it would have to be a specified fixed value in the player file 
e.g. 
```
"delta_X": -8
"delta_Y": 10
"play_movie": "plugin://searchpath/?min={premiered_X}&max={premiered_Y}"
```

But let me know if simply adding the timestamp works because whilst I'm not opposed to adding this timedelta feature, I don't want to add the extra code if it turns out it isn't needed.

**Comment by juanma-cvega** [comment]
Yes, you were right. Adding the time works fine so I'm going to close the issue. Thanks!
