### ISSUE TITLE
TV shows seasons view shows previous show seasons posters while loading

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#184]
As per the description, TV shows seasons view shows the previous loaded ones. For instance, after browsing a TV show with 6 seasons I went for another one with just 3. There were 6 seasons showing up with the poster art of the first season of the previous one. After some seconds, the right information pops up. For the first TV show being browsed, it's the list of TV show categories that shows up. 
On the other hand, the submenu is properly showing the number of seasons available for the show selected.

**Comment by jurialmunkey** [comment]
I'm not really understanding the issue. Season posters change correctly for me.
Can you provide some screenshots to demonstrate what you mean?

Are you talking about the integrated view in Arctic Horizon whilst focused on the Parent folder item ("..")? That's a skin issue. It is because the season container loads first and then the skin updates the containers for each season. Nothing to do with TMDbHelper.

I'll look at hiding the container in Arctic Horizon whilst it is updating but you're still going to be able to focus it and click on them with the last items - it will just make the posters have opacity of 0% until they load.

Really I find it better to just disable parent folder items altogether, as they are ugly and can allow access to parts of the system that you might not want other people to access.
`Settings > Media > General > Show Parent folder items (disable)`

**Comment by juanma-cvega** [comment]
Yes, your fix worked. I didn't even know the option you mentioned existed. It's a shame you cannot access the context menu for an episode while navigating through seasons. That would make it pretty neat to not have to first select a season to then navigate to the episode you want to get the context menu for.
