### ISSUE TITLE
Hide unaired episodes not working

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#190]
I just checked with the new episode of Young Sheldon, that's airing in about 10 hours, that the option doesn't work. It shows the episode even though it hasn't been aired yet. 
Image from episodedate.com.
<img width="808" alt="Screenshot 2020-04-30 at 15 38 15" src="https://user-images.githubusercontent.com/6765894/80717053-b156ce00-8af8-11ea-8790-6b8408eb2580.png">

**Comment by jurialmunkey** [comment]
TMDb doesn't provide a timestamp - it's just a date. So as soon as the date matches it is shown.

On TMDb it is listed as 30th April, so it is working correctly:
https://www.themoviedb.org/tv/71728-young-sheldon/season/3/episode/21?language=en-US

I err on the side of generous rather than strict date matching as I figure that the end user would rather have the episode display a few hours earlier than it is available rather than having to wait till the next day after it airs.

**Comment by juanma-cvega** [comment]
Fair enough. I still have to check but I guess there is going to be the same issue as with other addons that have library integration then. Because the episodes are scraped before they air, data won't still be available on TMDB (like thumbnail for example) and the episodes will need to be refreshed in order to refetch this information. I believe this is more of a Kodi thing as they are already in the library but is there anything that can be done from the addon to refresh this data?

**Comment by jurialmunkey** [comment]
Yeah, not much can be done from the addon side of things. Also, it can be a problem even if the episode has aired -- sometimes info on TMDb is updated before it airs and sometimes up to 24hrs  after. 

As far as I understand, the initial data on TMDb is pulled from other services in an automated scheduled job that happens every 24hrs - so it depends on where the episode air time falls in that cycle and whether the service the info is being pulled from has the data ready when the sync occurs.

> And I believe Horizon doesn't show the option to refresh episode metadata if I recall correctly.

`Info dialog > Manage > Refresh Info`

**Comment by juanma-cvega** [comment]
> Info dialog > Manage > Refresh Info

Silly me, I was searching in `Context Menu -> Manage`.
Thanks.
