### ISSUE TITLE
Schedule times for updates instead of at intervals

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#194]
When TV show synchronisation kicks in it takes some time to finish when there are many TV shows with many seasons as can be seen by the time the notification goes on. Would it be possible to skip those TV shows and seasons that are ended? It would depend on whether that information is available on the TMDB API. There could always be a function to force a whole synchronisation in case there is a need to recreate a folder that has been modified.

**Comment by jurialmunkey** [comment]
I don't think it would save that much time. Most of the time cost is doing the online lookup - the local database lookup to check if the items are in the library is very quick. That's why the progress pauses momentarily when it says adding season and then the movement through each individual episode is really fast - the online lookup of the season is what takes the time.

Plus then you have to contend with status info being incorrect - some shows are listed as ended when they are returning. Also what happens if you add an episode of a show that has already finished - it will never update.

The only real solution would be to maintain a database of which shows/seasons to skip and the skip them entirely - i.e. essentially maintain a "blacklist" of seasons to not even lookup because we know that they've already been added. 

I'm not quite sure how you would go about verifying that the season is complete though. You could guess that it is complete if there is a season after (e.g. if there is season 4 then season 3 must be finished). However, then you have the issue where there are placeholders for future seasons (e.g. like the crown season 4). And even without that concern, you would still need to at least lookup the last season every time -- the real benefit would only come when you can skip the lookup of the show entirely.

**Comment by juanma-cvega** [comment]
I guess there is no reliable way to skip seasons or complete TV shows based on TMDB information then. I haven't been able to verify performance with the synchronisation happening in the background but it seems, by just watching Kodi notifications showing up, that the loading of the EPG now is somewhat slower in the latest Shield Pro. But I guess that's the price to pay for having all those things at start up.

**Comment by juanma-cvega** [comment]
After the latest update I'm getting the following warning constantly. 
```
2020-05-03 20:44:24.162 T:123145360052224 WARNING: CSettingsManager: unable to read value of setting "library_autoupdate_interval"
2020-05-03 20:44:24.162 T:123145360052224 WARNING: CAddonSettings[plugin.video.themoviedb.helper]: failed to load value "2" for setting library_autoupdate_interval
```

**Comment by juanma-cvega** [comment]
Nevermind, I changed the library autoupdate configuration and it disappeared. I guess you changed the autoupdate values to predefined ones and I needed to update it to one of those.

**Comment by jurialmunkey** [comment]
Yeah I changed the range to start at 3hrs with a max of 48hrs in 3hrs increments - I'm surprised Kodi complains about an existing value not fitting that range though!

I think for large lists it is probably excessive to be doing an update more than every 3 hrs - main concern is that most users will just set these types of things to the lowest possible value without really thinking about the impact -- the api requests are cached for a day, but still it is quite a lot of hard disk reading to be constantly applying to a system particularly when it updates on startup and its also possible to do a manual update.

**Comment by juanma-cvega** [comment]
I agree it's overkill to do too many synchronisations, specially when you normally have one new episode per week per TV show. Actually, I have a question and a suggestion. 
First, the question. When you say API calls are cached, does that mean that, if you make a request in the morning and there is a new episode airing in the afternoon, you won't be able to see it until next day?
And the suggestion. Is it possible to make the synchronisation based on fixed hours? The suggestion comes for systems like Android where you may exit Kodi to start another app, like a game or the internet browser, to open Kodi again some 30 minutes later and get the synchronisation triggered again. Having fixed hours you can just wait for the related hour to start a synchronisation job. The problem would be if you never have Kodi open at those fixed hours so, would it be possible to store the last time the synchronisation was triggered and trigger it only if you missed at least one of the fixed hours at start up?

**Comment by jurialmunkey** [comment]
> First, the question. When you say API calls are cached, does that mean that, if you make a request in the morning and there is a new episode airing in the afternoon, you won't be able to see it until next day?

No, because usually episodes are listed on TMDb many days (if not weeks) in advance of their air date. See for example The Simpsons which currently has two future episodes listed for 10th and 17th of May https://www.themoviedb.org/tv/456-the-simpsons/season/31/episode/21

I only cache the raw data response from the API, not the processed end result. Whenever a function makes an api request, the code first checks if a cached local copy of the response exists and returns that if it hasn't expired. If the cache for that request had expired or didn't exist, then it will do a new lookup and store that data with a new expiry date. The plugin still does all the data processing every time a folder/widget loads.

So really a one day cache for TMDb season listings is playing it pretty safe - it would be very rare for an episode to be added to TMDb less than 24hrs before it aired. However, for Trakt user lists, since these can have an item added at any time, I only cache the metadata of the items -- the actual Trakt list is downloaded every time.


> And the request. Is it possible to make the synchronisation based on fixed hours?

Yeah I think this might be a preferable approach rather than an interval based one. It isn't really that great to have an update run everytime on startup, particularly since that's probably when you most want to watch things and not have the system be bogged down -- better to have it run in the background at specified times when you aren't watching something, plus there's always the option to run it manually.

So it would do the update at the specified time or, failing that, at the next available opportunity after that time has elapsed. Should be relatively easy to do.

**Comment by jurialmunkey** [comment]
Okay I think the latest update should now work as stated above.

Set a schedule time and it will update at that time or the next available time after that scheduled time. Need to test a bit more over a few days but I think it is working correctly.
