### ISSUE TITLE
Error while importing TV show

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#195]
I'm getting this error when importing the TV show The Crown but there isn't much information in the logs. I haven't enabled DEBUG, if you need logs in DEBUG I can make another run with them. 

```
2020-05-03 09:09:06.093 T:123145567944704  NOTICE: [plugin.video.themoviedb.helper]
                                            ADD LIBRARY -- Successfully added:
                                            special://profile/addon_data/plugin.video.themoviedb.helper/tvshows/The Crown/tvshow.nfo
                                            https://www.themoviedb.org/tv/65494&islocal=True
2020-05-03 09:09:11.794 T:123145567944704   ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=episodes&season=4&type=season&tmdb_id=65494&islocal=True
```

**Comment by jurialmunkey** [comment]
Is it causing any issues other than the log message?

There's no season 4 of The Crown yet. TMDb has a placeholder season with no episodes - so when the plugin tries to retrieve the episodes for season 4, it gets an error because there's nothing to retrieve: https://www.themoviedb.org/tv/65494-the-crown/season/4

**Comment by juanma-cvega** [comment]
> Is it causing any issues other than the log message?
No that I know of. It's just that you get a sound and text notification when this happens and it happens every time the synchronisation triggers.

**Comment by jurialmunkey** [comment]
Hmm, that's weird - you shouldn't get an onscreen notification about that type of error. You should only get a notification if there's an exception raised.

**Comment by jurialmunkey** [comment]
I tested with the crown and I don't get any notification of the error - only the progress notification (which is now hidden btw). 

I'll close this as fixed for now - let me know if you are still getting notifications about this error with the progress dialog hidden because that might be some other issue.
