### ISSUE TITLE
Displaying the genre

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/plugin.video.themoviedb.helper#197]
I'm running lastest TMDBHelper with latest Kodi and with Estuary Mod V2 skin. Don't know if my request is possible.
Let's say I'm going into movies/popular, when I'm scrolling the movies, the genre is not displayed in the left bottom corner (see left picture). But when I'm clicking on the movie itself (screen with cast, similar ...), then the genre is indeed displayed (see right picture).
I wonder if it is not possible to also display the genre in the first view (left picture). This makes scrolling more handier (skipping comedy for example). Tnx.

![New Image3](https://user-images.githubusercontent.com/60318531/80978430-538ef280-8e26-11ea-9e7b-764f13d45a9d.jpg)

**Comment by jurialmunkey** [comment]
For performance reasons, extra details are not retrieved with a list unless they have already been previously cached.

The plugin provides a service monitor that provides extra details about the current item - it is up to the skin to implement that. It's not possible for the addon to add details to the list retroactively after it has loaded and loading the details before will make the list take many times longer to load since an extra request has to be made for each item in the list.
