### ISSUE TITLE
Option to return elements from a Trakt list in a different order

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#204]
I was just checking the Trakt API and it seems they send a X-Sort-By header with the request that can be used to change the order the items are returned in. I'm not sure how that works with the limit of 20 elements per request that can be set in the addon though. 
https://trakt.docs.apiary.io/#reference/users/list-items
The reason for this request is that, when adding a list to a widget, you always get the same elements. You can add a random sorting to the widget but that would only randomise the current result which in the case of Trakt maxes out to 20. So it would be nice if there was a way to configure the request to change the order the results from the list of elements are returned.

**Comment by jurialmunkey** [comment]
You can already. The plugin respects the X-Sort-By header that is sent. You need to change the sort method on Trakt though - so you can only do it for lists that you own.

**Comment by jurialmunkey** [comment]
This is the sorting code:

```python
reverse = True if response.headers.get('X-Sort-How') == 'desc' else False
if response.headers.get('X-Sort-By') == 'rank':
    return sorted(items, key=lambda i: i.get('rank'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'added':
    return sorted(items, key=lambda i: i['listed_at'], reverse=reverse)
elif response.headers.get('X-Sort-By') == 'title':
    return sorted(items, key=lambda i: i.get(i.get('type'), {}).get('title'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'released':
    return sorted(items, key=lambda i: i.get(i.get('type'), {}).get('first_aired') if i.get('type') == 'show' else i.get(i.get('type'), {}).get('released'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'runtime':
    return sorted(items, key=lambda i: i.get(i.get('type'), {}).get('runtime'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'popularity':
    return sorted(items, key=lambda i: i.get(i.get('type'), {}).get('comment_count'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'percentage':
    return sorted(items, key=lambda i: i.get(i.get('type'), {}).get('rating'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'votes':
    return sorted(items, key=lambda i: i.get(i.get('type'), {}).get('votes'), reverse=reverse)
elif response.headers.get('X-Sort-By') == 'random':
    random.shuffle(items)
    return items
return sorted(items, key=lambda i: i['listed_at'], reverse=True)
```

**Comment by juanma-cvega** [comment]
So it's not on a response basis? I thought you could configure the sort header per call. I still don't get the point of doing it with a header in the response instead of in the request. Why do you need to use their header to sort the list after the fact? You could always sort yourself based on your preferences once you have the results. And you cannot paginate or limit the results at the client level that way as you would always get the same results from the call.

**Comment by jurialmunkey** [comment]
> So it's not on a response basis? I thought you could configure the sort header per call.

Nope. No server side sorting in Trakt API. Only client side. According to Trakt devs, it is too expensive to do server side sorting of user lists. The only list that supports server side sorting is watchlist - which I guess is because watchlists are relatively short (e.g. 10s of items rather than potentially 1000s of items).

> Why do you need to use their header to sort the list after the fact?

It tells the plugin how the list is sorted on the website so that the sort style is matched. 

As the list needs to be sorted before it is displayed, applying user defined sorting requires a way to indicate how the list is sorted *before* it is loaded -- basically, every list would need to have you first go through a discover type section where you selected the sorting before opening the list. It's way too clunky to do things that way.

It's not possible to apply a sorting method after the list loads because at that point the plugin instance no longer exists and obviously Kodi's own sort methods are useless because they only sort the current page.

> And you cannot paginate or limit the results at the client level that way as you would always get the same results from the call.

The response from the Trakt API for a user list isn't paginated because the list only contains very basic data needed to sort (e.g. title, listed_at, rank, votes, rating, first_aired) and the IDs to lookup details on TMDb/TVDb. Pagination for user lists are done client side (unlike TMDb lists) - the results are then stored in a short cache to avoid needing to redo the request and sorting (cache is refreshed on reopening the list after navigating elsewhere).
