### ISSUE TITLE
[Bug] Library calendar

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#205]
When I click on "into the dark" tv show to access the library it takes me to the Video library.
I have two more tv shows with the same issue but for now, I'm using this one as an example, I removed "into the dark" cleaned & rescanned but still having the same issue. can you please take a look at my log file https://paste.kodi.tv/elozereteq

<a href="https://imgur.com/rm8ndjO"><img src="https://i.imgur.com/rm8ndjO.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/GfS7Ink"><img src="https://i.imgur.com/GfS7Ink.png" title="source: imgur.com" /></a>

Next Aired(6.0.18) 
<a href="https://imgur.com/ay80QI5"><img src="https://i.imgur.com/ay80QI5.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/kfvAOau"><img src="https://i.imgur.com/kfvAOau.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
Hmm, this one has me a bit stumped.

Can you send me your library db so I can test a few things?
`kodi/userdata/Database/MyVideos116.db`

If you don't want to share it here, send me a private message on the forum with it.

**Comment by Blurayx** [comment]
Sent you a  private message 🙂

**Comment by Blurayx** [comment]
Update
I've also noticed that the Next Aired "into the dark" widget is blank.
I hope this may help you to find the bug.
<a href="https://imgur.com/EkAxofZ"><img src="https://i.imgur.com/EkAxofZ.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Just an update - I haven't found a fix yet but I do have some idea of what is happening.

So I've found this discussion on TMDb forums:
https://www.themoviedb.org/talk/5c2f76899251415a986de345

Basically, TMDb considers that series as standalone movies, whilst TVDb considers it an anthology tvshow. You aren't getting artwork/details because there isn't a matching show on TMDb in order to be able to get the correct IDs to match with the library.

It appears to be quite a touchy subject on TMDb for some reason. I don't think I agree with their decision here as it clearly looks like an anthology tv series to me, not a series of standalone movies.

The failing to open the library is a separate (but related) issue. I should be able to fix that and I think the fix should also at least allow for merging with the library details so you will at least get artwork.

I'm working on it now, so hopefully should have some sort of fix soon.

**Comment by Blurayx** [comment]
You’re right, it’s a very touchy subject 😮

**Comment by jurialmunkey** [comment]
@Blurayx - Can you test latest version of TMDbHelper. Looks like it is fixed now!

![screenshot778](https://user-images.githubusercontent.com/4618719/81463772-6bd48800-91ff-11ea-9b80-cef0012e22fc.png)
![screenshot779](https://user-images.githubusercontent.com/4618719/81463773-6d9e4b80-91ff-11ea-90aa-af0435b6f052.png)

Even the info from Next Aired calendar appears to be working correctly now.
![screenshot780](https://user-images.githubusercontent.com/4618719/81463774-6ecf7880-91ff-11ea-8fd3-8377c79c6b43.png)


Thanks for sending me the DB file. It helped a lot in being able to test and fix it!

**Comment by Blurayx** [comment]
YES!!!!! 😀
it's working thank you so much.

I have a question. I can't access the library from the home screen. When I was using Next Aired(6.0.18), It was possible. 
<a href="https://imgur.com/pnsDBHe"><img src="https://i.imgur.com/pnsDBHe.png" title="source: imgur.com" /></a>
