### ISSUE TITLE
Fanart.TV dialog loop

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#21]
Thanks for adding Fanart.tv support!

I have added my API key in settings, however when opening TMDBhelper via video-addons, I get stuck in a loop with "Missing/Invalid FanartTV API key" dialog. Pressing OK launches the dialog again (and again), force quitting Kodi seems to be the only way to get it to stop.

**Comment by jurialmunkey** [comment]
You shouldn't need to add an API key - the default key works fine. I've removed the setting because it isn't necessary and will cause confusion - it sounds like you entered your personal key, which should be put in the client key setting not the API key setting (which is a developer key).

**Comment by skyfsza** [comment]
Thanks for the feedback.  I put my personal key in both fields as I was not sure which to use. Removing the key from "API key" has fixed the looping dialog

Thanks again!

**Comment by drinfernoo** [comment]
With this chan, not being able to enter a user key, will that inflict any throttling on the request?

**Comment by jurialmunkey** [comment]
> 
> 
> With this chan, not being able to enter a user key, will that inflict any throttling on the request?

You can still enter a client key just not a developer key. Having a VIP client key is what gets you faster requests - a different developer key makes no difference and only serves for traffic statistics.
https://fanart.tv/2015/01/personal-api-keys/

There shouldn't be any reason for users to enter developer keys (however, you do need a personal OMDb key). I haven't differentiated between a user entered developer key and the default for quite a while now - the throttling is exactly the same:
* I limit TMDb requests to 4 per second (as per TMDb API specs) no matter what api key is entered.
* I limit OMDb requests to 1 per second to prevent overloading OMDb.
* I don't limit fanart.tv at all because it isn't critical if I hit their limit and don't get a response. The user just doesn't get any additional artwork for that item (i.e. clearlogo, clearart, banner, landscape).

**Comment by drinfernoo** [comment]
Gotcha 👍 I must've missed that you could still enter a personal key. Carry on 😁
