### ISSUE TITLE
TV shows with the same name merge when added to library

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#214]
I tried to add the two anime TV shows Berserk (1997 and 2016) to the library that were added to a Trakt list and I got the two of them merged (duplicated episodes). I went to check in the TV shows folder created by the addon and, for what I understand of its behaviour, the problem may come from shows not adding the year as a suffix the same way movies do.

**Comment by jurialmunkey** [comment]
Ah damn, yeah that's a problem.

Not quite sure how to address this issue and keep backwards compatibility. Might be okay since I skip items added to the library, but it's still going to be messy I think.

Ugh! Can't believe I didn't think about duplicate named tvshows...

**Comment by jurialmunkey** [comment]
@juanma-cvega - Can you test latest? Hopefully should fix the issue whilst also retaining backwards compatibility.

The solution:

- When adding tvshow, checks if the folder already exists.
- If it exists, reads the nfo file and checks that TMDb ID matches.
- If TMDb ID matches, use the existing folder to add missing episodes.
- If TMDb ID doesn't match, create a new folder `{showname} (TMDB {tmdb_id})`

I thought TMDb ID is a safer bet to append to the folder name since there can be inconsistencies with year depending on where the tvshow was added from.

**Comment by juanma-cvega** [comment]
I just did a quick test and the folder is created alright but the episodes are still being added to the other folder. Apart from that, how is the scraper doing to find the right information for the TV show with the TMDB id as a suffix? The folder was empty and it didn't have any art, while for the other shows you can see the poster art while browsing.

**Comment by jurialmunkey** [comment]
Hmm it seems to be working for me:

I added the earlier Berserk and then the later one and I get two folders:

![Annotation 2020-05-13 205240](https://user-images.githubusercontent.com/4618719/81804354-5099ad80-955c-11ea-9d87-a335416ca0d8.png)

**First folder contains one season**
![Annotation 2020-05-13 205323](https://user-images.githubusercontent.com/4618719/81804382-5a231580-955c-11ea-8173-83c0c70df442.png)


**Second folder contains two seasons**
![Annotation 2020-05-13 205532](https://user-images.githubusercontent.com/4618719/81804410-63ac7d80-955c-11ea-98c9-0d7a7d584d1b.png)
![Annotation 2020-05-13 205557](https://user-images.githubusercontent.com/4618719/81804414-65764100-955c-11ea-92d1-8b660945b009.png)


Is this incorrect? It looks right to me. Am I missing something here?


Scraper should use the nfo file to find the correct show. If the scraper you use doesn't do that properly, you might need to refresh the show manually -- there shouldn't be many like that as it is only if you have two shows with the same name, which should be pretty rare.

**Comment by juanma-cvega** [comment]
I haven't had much time, I just did a quick test so maybe I did something wrong. 

> I added the earlier Berserk and then the later one and I get two folders:

For what I understand you did a fresh import from shows you didn't have. In my case, I already had them imported so maybe that's the problem. Am I to test this after removing the already imported shows?

**Comment by juanma-cvega** [comment]
> It shouldn't matter as long as the episodes aren't already in the library (because if they are they will be skipped and not added).

Well, that was the problem. When you said backwards compatibility I thought you meant being able to properly import TV shows already imported (apart from compatibility with existing code). I removed the TV shows manually and did an update and it works fine from a clean slate.

**Comment by jurialmunkey** [comment]
It only matters if they've been scanned to the library - it will still add any missing episodes in the correct folder. Automating deletion of files is a dangerous path to go down - so if something needed to be deleted or removed, that would have to be done manually.

It's backwards compatible in that it retains the original naming scheme so that you shouldn't need to remove any of your existing folders other than the one that got messed up.
