### ISSUE TITLE
TMDB list API

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#215]
I remember I asked you about lists not long ago and you mentioned there is no API to access lists. So, isn't this the API to do exactly that?
https://developers.themoviedb.org/3/lists/v4-or-v3-lists
It seems there is a version 4 of the API but no idea when that was released, so maybe that's the API that was missing to implement that feature?
Also, that's the API to act on a list, the one to get the list of lists from a user is this:
https://developers.themoviedb.org/3/account/get-created-lists
Still, I don't see a way to get lists from others unfortunately.

**Comment by jurialmunkey** [comment]
The problem isn't that there's no API method. The problem is that TMDb user lists require authentication and, unlike Trakt, TMDb doesn't have a server side access code based method to do that.

TMDB requires a web browser on the same machine so that the app can pass the client secret to the TMDb authentication site and then once authenticated the browser can call the loopback to pass the access token back to the app client.

Since Kodi doesn't have a web browser by default, there's not really a standard approach that I can use that will definitely work for all machines -- Each platform would require specific approaches to call their webbrowsers - e.g. it's going to be different on Windows and LibreELEC and Android and OSX.

It can be done, but it's a lot of work basically.

**Comment by juanma-cvega** [comment]
Ok, I see what you mean. This may change with v4 of their API though. I just tested and I was able to get the contents of a list I created manually with the new version using Postman and the access token from the account settings.  https://developers.themoviedb.org/4/list/get-list
But the access token provided is read only, at least for now. So either the docs are wrong or they are ahead of development as the POST documentation says you need an access token but there is none available with write access for now. And the API to get the list of lists is still on version 3 so no really useful for now.

**Comment by jurialmunkey** [comment]
> And the API to get the list of lists is still on version 3 so no really useful for now.

Yep, without being able to browse the list of lists, it's not very useful.

Also, it would be very painful for users to input the access token manually on systems like LibreELEC using only a remote. Sure, they could ssh in, but that's asking for quite a bit of technical know-how.
