### ISSUE TITLE
[Feature Request] Play using (TMDB helper) within Local Library

### ISSUE THREAD

**Issue by basKT-case** [jurialmunkey/plugin.video.themoviedb.helper#219]
My particular use case might not be considered standard, but I'm hoping my feature request can still be considered. 

I have since moved on from OpenMeta to using TMDB helper. But one feature I miss was the ability to point to a title in my Local Library and choose from the context menu "Play using (OpenMeta)". This would then send that title to my assigned player (Seren) to scrape. 

I have a big Local Library with titles I have added over the years. The only downside is that much of the earlier added content is low quality from the days when I had a slow internet connection and HD rips were not a thing. But short of relying on a Trakt list for my Movies library, I would like to keep my exisiting Local Library listings with the ability to now scrape them with Seren and find a higher quality file where appropriate.

Is the a feature that is worth considering? I'm aware that there are work arounds that rely on migrating to Trakt collections, but I like being able to keep my legacy library.

**Comment by jurialmunkey** [comment]
It's been requested before:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/130#issuecomment-597364375
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/98#issuecomment-593048783

The main problem is that I need the TMDb ID of the item and that isn't necessarily available in the library.  Not so much an issue for Movies as they nearly always have either a TMDb or IMDb ID that can be used to do the lookup. 

The problem is more for Episodes since even if there is an ID in the library, most likely it will be a TVDb ID for the episode and I need the TMDb ID for the tvshow. 

I could do some guess work to search by title and find TMDb ID, but that's prone to false positives, especially when two different tvshows exist with the same name like "The Office" or "The Goldbergs" or "House of Cards".

**Comment by jurialmunkey** [comment]
@basKT-case - Can you test latest version? I think I've managed to find a workable solution. You should now be able to do Play Using (TMDbHelper) for any item in the library.

It should also work from other plugins too -- though maybe with varying success.

**Comment by juanma-cvega** [comment]
I just did a quick test and it seems it works. Or at least the name of the episode I was searching for appeared on the search string. What information is available to be used to call other players? The same as when used from within the addon or is there anything missing?

**Comment by basKT-case** [comment]
@jurialmunkey  - wonderful! I've tested the latest version and I can now Play Using (TMDbHelper) from my local library titles. That's exactly the function I was hoping for, and you were able to implement it. 

Thank you so much!

**Comment by jurialmunkey** [comment]
@juanma-cvega - The actual player function is the same. The context menu item is simply a translation layer which takes the library episode's IMDb / TVDb / TMDb ID (whichever is available) and uses that to find the corresponding tvshow TMDb ID on Trakt. The ID, season, and episode numbers are then passed to the player function which looks up all the normal details just like if you had clicked an item in the plugin itself.

@basKT-case - No problem. I've wanted to do this for a while but previously wasn't able to think of a good way to deal with it. Your post got me thinking about it again and I had one of those lightbulb moments where I realised that the solution was much simpler than what I had originally thought.

**Comment by willhowlett** [comment]
Sorry for bumping a very old issue. I was just wondering if this feature still existed? I don't see the option to Play Using (TMDbHelper) from context menu for my local library titles. Just wondering if there are extra configuration steps I need to take to enable it?
Many thanks!
