### ISSUE TITLE
[Feature Request] Language in discover

### ISSUE THREAD

**Issue by abbaskip** [jurialmunkey/plugin.video.themoviedb.helper#222]
I just discovered the discover tool - it's amazing. But would be even more amazing of language or country of origin could be set.

Country of origin especially if we could choose multiple. Currently I get loads of hits from foreign films and shows coming up.

**Comment by jurialmunkey** [comment]
Discover end-point doesn't provide a country of origin filter, so that's not possible. However, it does provide a filter for original language.

The `with_original_language=en` param has always been possible in the plugin URI, it just wasn't exposed in the GUI section of rules. I've now added it, so you should now be able to select it from the Add Rule... part.
