### ISSUE TITLE
Kodi crashed while refreshing library when tried to play a movie

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#229]
I'm not sure who's the culprit here, maybe a lack of resources, but I tried to play a movie through Embycon through the player while the addon was updating the library and Kodi just crashed after taking its time to try to play the movie. 
That happened on a Shield Pro 2019. Maybe the library update could be lowered its priority when Kodi tries to play something?

**Comment by drinfernoo** [comment]
A log file is the only way to see what's happening here. Luckily, this is likely not an issue with TMDbHelper, and probably just a faulty player file sending unexpected parameters to Embycon.

**Comment by juanma-cvega** [comment]
The same movie with the same player when there is no synchronisation happening doesn't crash. I'll see if I can reproduce the problem again and grab the logs this time. Kodi tends to crash when resources are low, I've seen that with Amazon Firesticks, so the issue is more about preventing if possible that Kodi gets `overloaded` to avoid these crashes than any problem with the addon.

**Comment by drinfernoo** [comment]
A log file is still going to be the way to actually figure out what's happening...

**Comment by jurialmunkey** [comment]
I'm not sure if there's a way to reduce the priority of a script.

I think this is always going to be an issue with running auto updates. It's just going to be layers upon layers of workarounds. Either it is a true bug causing a crash and needs to be fixed in Kodi core, or it is a system overload which requires better process management (e.g. Kodi needs to lower priority / delay other script operations until after playback starts).

The script itself would really only know after playback has started, which is probably too late -- the request for playback is typically the intensive part. Most of these low-power chipsets handle actual video playback relatively well, it's all the initial disk i/o and other processing where they struggle.

**Comment by juanma-cvega** [comment]
Yes, makes sense. I opened it just in case there was something that could be done from your side but I didn't have high hopes anyway. I'll close the issue now as there is nothing to do here.
