### ISSUE TITLE
{Enhancement} Import Trakt to Kodi Library?

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#242]
Is it possible to import your Trakt collections to Kodi library using TMDBH?

**Comment by drinfernoo** [comment]
Nope. This has been covered many times.

**Comment by JayDee696969** [comment]
Ok, did a search, but didnt see anything.

**Comment by JayDee696969** [comment]
Openmeta can do this, thought TMDBH might be able to also.

**Comment by jurialmunkey** [comment]
> 
> 
> Openmeta can do this, thought TMDBH might be able to also.

Just because you can doesn't mean you should. It's really bad that OpenMeta did this because now there is a whole subset of the Kodi community who have completely messed up their Trakt collections when the exact same purpose could have been achieved with custom lists.

Trakt collection is specifically for physical/digital media that you actually own - it is literally the media that you have "collected". It should only ever be synced *to*. It makes no sense to sync *from* it since those items should already exist in your library. Having items in your collection that you don't actually own a physical/digital copy of is like saying that you own the books that exist in your city library...

I don't understand what the obsession is with misusing the collection feature of Trakt when there already exists a functioning custom list system that works perfectly for the purpose without cluttering the collection with items you don't own. Just create a list on Trakt and add whatever items you want to sync to it, then add that list to TMDbHelper's auto update lists.

See my comment here discussing this matter (there was also another thread discussing but I can't find it at the moment) https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/153#issuecomment-612539754

> Trakt helps keep a complete collection of every TV show and movie you own digitally or physically (Blu-ray, DVD, HD DVD, VHS, LaserDisc, etc) and have available to watch
https://blog.trakt.tv/how-to-build-your-collection-146e6e80bcd7

**Comment by JayDee696969** [comment]
Well, not necessarily, theres plenty of streaming addons you can use Trakt with, even Netflix for Kodi addon, you dont need to have physical copies for streaming services, but i guess i see your point. You can get used to using the Trakt section in the addons rather than using Kodi Library.

**Comment by drinfernoo** [comment]
@JayDee696969 It sounds like you completely missed the point... you wouldn't consider every show on Netflix to be part of "your" media, either.

You don't necessarily have to "get used to" using other sections... if you want to use library, sync the appropriate lists as mentioned. Personally, I feel like the ideal setup actually uses a healthy mix of library and remote lists.

**Comment by jurialmunkey** [comment]
Trakt is pretty clear about what the collection is for. When you open your collection on Trakt website it specifically says in the banner:
> Your TV show and movie collection — All owned items including Blu-rays, DVDs, and digital downloads.
This point is repeated on the Trakt blog and in the support forums.
https://blog.trakt.tv/how-to-build-your-collection-146e6e80bcd7
https://support.trakt.tv/forums/188762-general/suggestions/19291261-what-is-collections-good-for

There's a reason why the collection is separate from watched history - because it is possible to watch things that you don't own and it is possible to own things that you haven't watched.

You can't "collect" things from Netflix because you don't own them - it is a subscription service. You might cancel your subscription in the future or Netflix might lose the rights to provide that show/movie in your region. 

Collection = items you own digitally/physically.
History = items you have watched.
Watchlist = items you want to watch.
Custom Lists = everything else.

Just create a custom list use that to sync with the library. That way you get all the same benefits whilst keeping your collection separate from your subscriptions.

**Comment by JayDee696969** [comment]
Hmm, interesting, so how do I import Trakt custom lists to library then?

**Comment by jurialmunkey** [comment]
TMDbHelper > Trakt > Your Lists

Then open the context menu on the list to add to the library
Context Menu > TMDbHelper Options > Add to Library

**Comment by JayDee696969** [comment]
Really? I never knew you can add a whole section to library like that! Ill have to try it out. So that wouldnt work for TV Collection section, just your custom lists?

**Comment by jurialmunkey** [comment]
You can do it for any custom list. You can do it for your lists, your liked lists, or trending popular lists. You can also setup to auto-sync custom lists.

**Comment by JayDee696969** [comment]
Oh, dam, thats all new to me. I guess this was the answer i was looking for when i opened this post. So I can Import my Trakt to Kodi library using this method. Should just told me that in the first place, lol. Thank you, Ill check this method out.

**Comment by JayDee696969** [comment]
So instead of adding shows to collection, i should be adding them to custom lists instead, gotcha..

**Comment by jurialmunkey** [comment]
Hahaha. Sorry I thought you already knew about the custom lists!

Yeah just create a custom list (or many lists) and add items to them, then you can set them up to auto sync and/or manually sync. Auto sync happens daily at the specified time (or 15 mins after Kodi start-up if you missed the last one), so sometimes you might want to update manually.

You can also do a bulk manual update of all your auto synced lists using the "Update Library Now" command in TMDbHelper Library settings. You can also add this command as a shortcut or as a keymap with:
`RunScript(plugin.video.themoviedb.helper,library_autoupdate,busy_dialog)`

**Comment by jurialmunkey** [comment]
The other benefit of using custom lists is that you can split the lists up into different categories. TMDbHelper will auto generate a smart playlist for each list containing only the items from the list -- that way you can also easily access the individual lists. -- e.g. you might want to have one list that is family movies, and another that is a specific genre or from favourite directors etc.

**Comment by JayDee696969** [comment]
Hmm yes.  I guess im starting to realize im probably better off just using the Trakt lists that are in the addon instead, since I guess the Kodi library isnt really needed unless you have physical copies stored. No need for Kodi library to scrape the metadata since its already there and ready in the Trakt sections of the addon.. Hmm starting to rethink everything now.. No need for Kodi library..

**Comment by patel-jeel92** [comment]
> TMDbHelper > Trakt > Your Lists
> 
> Then open the context menu on the list to add to the library
> Context Menu > TMDbHelper Options > Add to Library
> 
> You can also add any lists from other users that you've liked in the "Liked List" section. You can like a list by opening it on the Trakt website and pressing the thumbs up button
> e.g. You could add this IMDb Top 250 list by opening this link, clicking the thumbs up, and then navigating to Liked Lists in TMDbHelper and Adding to Library via context menu
> https://trakt.tv/users/nielsz/lists/active-imdb-top-250
> 
> You can also add any list from trending/popular lists.
> 
> You can also auto sync from lists in
> `TMDbHelper Settings > Library > Auto-update library from Trakt list(s)`

Hi, I cant find the TMDB Helper options in the context menu. I am wanting to add my liked trakt lists to my kodi library but cant add it since the context menu option does not exist. Is this in the new update?
