### ISSUE TITLE
[Enhancement] GUI for skins without TMDBH support built in?

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#243]
Would it be possible to add a built-in GUI for the information/Browse section?? Maybe just a toggle in settings to use a built in GUI. Any skin that isnt specially skinned to use TMDBH info/Browse section, just looks like a list. Maybe like Extended info mod looks, with the Play, add/remove from library, maybe some Trakt buttons?  Just an idea.

**Comment by jurialmunkey** [comment]
The plugin specifically doesn't use any scripted windows, so there is nothing to skin. 

It looks like a list because it is a list - it's just a list of folders presented like any other directory structure in any other plugin. 

To have scripted windows would require fundamentally altering how the plugin works -- I specifically didn't use scripted windows because they are very limiting. Scripted windows force the skinner to display what the script wants them to show and that is all -- a native approach allows for using the native info dialog and for the skinner to display things however they wish.

**Comment by JayDee696969** [comment]
Ok, so its the Includes_DialogVideoInfo.xml in the skin that needs to be modified? Is that correct?

**Comment by jurialmunkey** [comment]
Depends on the skin but yeah it's generally DialogVideoInfo

There's instructions for skinners in the wiki:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Replacing-Extended-Info

**Comment by JayDee696969** [comment]
Cool, gonna give it a go for Xonfluence skin.
