### ISSUE TITLE
Library episodes not marked as watch

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#249]
I've been wanting to ask this for some time but I haven't had much time lately to verify the behaviour. I have noticed after watching a TV show that none of the episodes are marked as watched when played from library. They are marked on Trakt though and if I run the Trakt program it updates the episodes in the library.
Apparently I'm not the only one with this problem. I just remembered I had to create this issue when I saw some people on reddit asking the same question.

**Comment by jurialmunkey** [comment]
There was a discussion about this matter just the other day in this thread: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/226
See my comment for why I don't use the hack that OpenMeta used to mark episodes as watched: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/226#issuecomment-640156272

So far I haven't found any reliable way to retrieve the DBID. Kodi doesn't pass any information about the library item back to plugin because a strm file in the library is technically a playlist (just with one item in it - the TMDbHelper plugin path) rather than a direct link to the plugin.

The best method so far is to have Trakt sync watched status back to the library.

Once I find a reliable way to get the DBID, I'll implement marking watched status - but I don't want to use a hack like OpenMeta because it could mark lots of things incorrectly.

**Comment by juanma-cvega** [comment]
Ok, thanks for the info. I missed that issue. You can as you want with the issue then, close it or leave it open as a reminder if you plan to take a look at it at some later point.

**Comment by SirRickie** [comment]
Hope you'll find the way to get the DBID. It would certainly make your great addon my default daily driver. 🙂

**Comment by drinfernoo** [comment]
@jurialmunkey, was that commit tested much? How were you able to grab the DBID?

**Comment by jurialmunkey** [comment]
@drinfernoo - Yeah it was working correctly when I tested it. Is it not working for you?

See my comments here about how it works: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/226#issuecomment-641710290

It uses the TMDb/IMDb/TVDb ID to lookup the DBID. Those IDs are all unique, so as long as the item was scraped correctly to the library, then it will find it (actually is a bit of a safeguard because if you scraped it as the wrong item, then it won't mark it since it doesn't actually match what you're playing).
