### ISSUE TITLE
[Request]Save Rules option in TMDb Helper > Discover section

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#257]
I love the TMDb Helper > Discover - Add Rules feature to pull out movies as per my defined rule.

But once you go back from that screen, it does not save the rules, so you need to create the rule all over again.
It will be nice to have an option to save the created rules such that I can trigger them again when I want, so much convenient.

**Comment by drinfernoo** [comment]
I like this idea, "Discover History" 😁

**Comment by jurialmunkey** [comment]
This is what I use Favourites for actually. I just context menu on the "Discover Movies w/ Below Settings" and Save to Favourites.

I have been meaning to implement a "Discover History" though, as it would definitely be very useful.

**Comment by jurialmunkey** [comment]
@onlytanmoy - Latest version should now allow you to save discover rules. There is an additional option above add rule called "Save Settings". You click that, enter a name, and then it is saved in the Discover parent folder (e.g. when you click "Discover" and it shows "Discover Movies" and "Discover TV Shows" it will also list your saved searches below those and an option to clear the history).

**Comment by drinfernoo** [comment]
Do you also plan on a history feature?

**Comment by jurialmunkey** [comment]
> 
> 
> Do you also plan on a history feature?

I found it to be excessive to save each discover search automatically. The standard search history works well because it's a single query field and is typically a "one-and-done" type of thing.

For discover, however, the usage pattern often involves going back and forth to tweak rules which quickly clutters the history with similar entries. The other big problem is naming - building a name from the rules creates a very long label, so the only real option is a keyboard prompt which is disruptive when tweaking rules.

**Comment by jurialmunkey** [comment]
This seems to be working well, so I'm going to close.

**Comment by onlytanmoy** [comment]
> This seems to be working well, so I'm going to close.

Thanks a lot 👍
