### ISSUE TITLE
[Feature Request] Trakt Watched Status

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#26]
I Iove those little check marks 😁

**Comment by jurialmunkey** [comment]
@drinfernoo - I've added an option in settings to get watched indicators from Trakt for movies and episodes.

Tvshows and Seasons are a pain because they require iterating over every episode and checking if it is watched, which is very slow -- Trakt only returns play count and last watched date. There isn't a field with how many episodes have/haven't been watched.

**Comment by drinfernoo** [comment]
@jurialmunkey Most other add-ons do have the ability to show the marks on seasons and shows :( Glad the functionality is in now, though.

**Comment by jurialmunkey** [comment]
If you've got any insight into what they are checking against, I'm happy to add it. Just currently I can't see any other method other than iterating over every episode.

**Comment by jurialmunkey** [comment]
Nevermind, I've actually found it. There's a separate progress call which for some reason is under the "/show" section of the API rather than "/users" or "/sync" - makes no sense as the "/show" section is meant to only contain non-user-specific details about shows. All the other user-specific calls come under users and sync.

**Comment by jurialmunkey** [comment]
Okay latest commit should add watched counts for tvshows and seasons. It does add significant additional wait time until the details are cached. Once cached it is pretty quick (but still slower than without).
