### ISSUE TITLE
Not an issue but dvd/bluray integration?

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#266]
This isn't an issue but I thought it might be a potentially cool integration for tmdbhelper, playback and information integration for discs/blurays?

It would probably not be something easy to add for TV show discs but movies I think should be relatively straight forward for a context menu item or bluray index.bdmv playback?
The disc label and or metadata should contain a parsable title and after that it's a relatively straight forward lookup?

It would be nice to play blurays through Kodi and have the posters and such and also trakt integration scrobbling?

It would be another legitimate function for tmdbhelper too.

**Comment by jurialmunkey** [comment]
You should already be able to do this with a media stub:
https://kodi.wiki/view/Media_stubs

You create a stub for the discs you have in your collection and then scan them to your library. Since stubs look like any other media item in the library, then they will be captured by the "Play with Kodi" part of TMDbHelper. Playing the stub will pop-up a yesno dialog prompting the user to insert the correct disc before playing.
