### ISSUE TITLE
[Feature Request] Step Action key/value add ListItem.Label

### ISSUE THREAD

**Issue by Xaque8787** [jurialmunkey/plugin.video.themoviedb.helper#268]
Would it at all be possible to add ListItem.Label to the Step Actions key/value dictionary pairing in the Player Function section?

**Comment by drinfernoo** [comment]
Why wouldn't you just use `{title}`? Unless you're trying to point a player at a *directory* (which would have its own URI which you could use as the base command), then shouldn't you be able to match title for a media item without any issue?

**Comment by Xaque8787** [comment]
I've been using the webdev tools to try and create a step through player
for a couple of add-ons. I need to use a regex search to match the movies
title, and the infolabel.title for the add-on is a unique name with no
information relevant to the title of the movie. The only infolabel that
seems I can use is the infolabel.label, which isn't in the key/value
library pairs for the step through actions.

I may be missing something, but with no metadata, only the filename, this
seems to be the only route I can think of.

**Comment by jurialmunkey** [comment]
You already can use `label` for the addon being called. 

``` 
"play_movie" : [
    "plugin://plugin.video.myplugin/path",
    {"label": "{title}"}
],
```

Just realised that is missing from the wiki. I'll add it now.

**Comment by drinfernoo** [comment]
@jurialmunkey I got the impression he wanted to be able to use `{label}`.

**Comment by jurialmunkey** [comment]
Movies/Shows/People etc. (i.e data you get from the API) don't have labels though... They have titles or names.

**Comment by drinfernoo** [comment]
Are they retrieved via JSON-RPC, then? That `Files.GetDirectory` method doesn't return a "label" key... but I know `ListItem.Label` is often different from `ListItem.Title` though 🤔

**Comment by jurialmunkey** [comment]
@drinfernoo - 
The `{keys}` on the right side in curly braces represent data from the online API about the movie. I get them doing using a request to the API.

The left side are the infolabels from the current folder being stepped through retrieved via `Files.GetDirectory`. Label is one of the base fields that are returned by default for that call without specifying any properties: `file`, `label`, `filetype`, `id` and `type`.

It took me ages to understand how to read the schema.

Basically if you look at [Files.GetDirectory](https://kodi.wiki/view/JSON-RPC_API/v8#Files.GetDirectory) you can see it returns [List.Item.File](https://kodi.wiki/view/JSON-RPC_API/v8#List.Item.File)

If you expand that schema, you can see the properties it returns. Any that are listed as "required" are always returned (the others you need to specify to retrieve in the properties param in the json-rpc call). So for `List.Item.File` it always returns `file` and `filetype`. 

If you follow the breadcrumbs, you can see that `List.Item.File` also extends `List.Item.Base` which extends `Video.Details.File` which extends `Video.Details.Item` which extends `Video.Details.Media` which extends `Video.Details.Base` which extends `Media.Details.Base` which extends `Items.Details.Base` which returns `label` as a required property (so *all* items return label since Item.Details.Base is at the base of the hierarchy for items)

**Comment by drinfernoo** [comment]
@jurialmunkey Ah, yep. I have been digging in the schema a bit myself lately 😉 I was just backwards on which you used where 😅
