### ISSUE TITLE
[Feature Request] Display unwatched count for all shows

### ISSUE THREAD

**Issue by sabre6** [jurialmunkey/plugin.video.themoviedb.helper#269]
Hello,

Right now it seems unwatched show count only presents itself on a poster (ie, in a widget) if at least 1 episode has been watched of that show.  Is it possible to have that feature for all shows in TMDBHelper?  So checkmark if all episodes are watched or # for unwatched episodes of that show, no matter if watched or not yet.  Thank you.

**Comment by drinfernoo** [comment]
Trakt doesn't report the number of unwatched episodes of shows that don't already have at least one watched episode in your history.

**Comment by jurialmunkey** [comment]
> 
> 
> Trakt doesn't report the number of unwatched episodes of shows that don't already have at least one watched episode in your history.

There are other ways to get the number of episodes though.

The total number of episodes is already filled in the ListItem.Episode field for tvshows/seasons, so really this is a skinning question since the data is already available to skins.

Personally, I think unwatchedepisodes should remain empty if you haven't begun watching a show. Otherwise there's no way to distinguish between shows that you've begun watching and shows that you've never watched.

In the library it makes sense since to show unwatched counts even if you haven't started because you would expect that you plan to watch all the shows in your library. In a plugin like TMDbHelper, however, it makes less sense because no one realistically plans to watch every show in existence...

**Comment by sabre6** [comment]
Thanks for the reply.  I totally understand.  I just like seeing a number for shows not even started, to get a sense of what type of time commitment might be needed to even start the show.  We have several folks in the house with their own profile, and their preferred shows.  As we are stuck inside still, we are always looking at other's shows to watch.
