### ISSUE TITLE
player file passing season premiered for year. Would like series premiered year if possible?

### ISSUE THREAD

**Issue by 123Venom** [jurialmunkey/plugin.video.themoviedb.helper#277]
any way to get episodes to pass in the player file the series premiered year vs. the seasons premiered year?

**Comment by jurialmunkey** [comment]
Yeah this is a constant problem with Episodes and Seasons because there is really only one premiered field for listitems.

I'll have a look and see what I can do. However, if you're planning on using this for matching the base tvshow, it might be better to look for some other data to match on as I've found there are sometimes variations in tvshow releasae year between different services -- e.g. sometimes tvdb and tmdb differ on release dates because of regional variations, different release types, or translations/remasters/rereleases etc.

**Comment by 123Venom** [comment]
What I've done for now is a small request to IMDb and I pulled the year from their meta in the header.  In the case of `The Office` it's (2005-2013) so I parse that first date as the series premiered year...for now anyway..lol.  I know what you speak of with meta data mismatch.  I just went through this with TMDb and Trakt differing from IMDb by a year on a decent amount of movie titles just yesterday.  Thanks for your time.  Fingers crossed you can pass that series premiered, even if as a new option and I could rid the extra request I'm making.  If it's a hassle I fully understand and know all to well what that's like.  Keep up the good work!

**Comment by jurialmunkey** [comment]
Okay I think this should do the trick. Player should now have `{showyear}` and `{showpremiered}` which will be the premiere year (YYYY) and date (YYYY-MM-DD) of the first episode of the series.

Can you test and confirm it is working correctly for you?

**Comment by 123Venom** [comment]
EXCELLENT!!  Can not thank you enough for this!!!  Now having series premiered I can rid the new little function I wrote, had a 48hr life span...lol

Returned `"year": "2005"` for `The Office`

**Comment by jurialmunkey** [comment]
Awesome. The solution felt a little too easy so I was worried that I was missing something! Glad it's working properly.

**Comment by drinfernoo** [comment]
My favorite kind of solutions, though! 😅
