### ISSUE TITLE
[Request] Revoke Trakt Authorization

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#278]
Just as the title 😁

**Comment by jurialmunkey** [comment]
What's the purpose of revoking? Is this to clear the token so that particular Kodi user account no longer has access to that Trakt account via TMDbHelper, or is this to revoke access to that account for TMDbHelper across all machines?

The token can be cleared by deleting the `trakt_token` setting from `userdata/addon_data/plugin.video.themoviedb.helper/settings.xml` -- That's essentially doing a "logout" of Trakt on that profile. Just not sure if that's what you're looking for or if a way to do this via the GUI is needed?

For revoking app access, it's better to do that via the website (Top Right User Menu > Settings > Connected Apps). It's possible to have multiple active tokens generated so that revoking via the API will only revoke access for the currently active token, whereas revoking via the website removes the permissions for all TMDbHelper tokens that have been generated.

**Comment by drinfernoo** [comment]
@jurialmunkey
> What's the purpose of revoking? Is this to clear the token so that particular Kodi user account no longer has access to that Trakt account via TMDbHelper, or is this to revoke access to that account for TMDbHelper across all machines?

The former. It is particularly useful when sharing setups, as the user can clear their authorization before sharing.

There is also a Trakt endpoint for it: https://trakt.docs.apiary.io/reference/authentication-oauth/revoke-token
