### ISSUE TITLE
Plexconnect & Emby Kodi

### ISSUE THREAD

**Issue by rijsab** [jurialmunkey/plugin.video.themoviedb.helper#282]
Hi jurialmunkey..

When I use Emby to have my movies in Kodi library tmdbhelper works really well and showing what is available in my local library with an indicator at right upper corner. 

When ai use plexconnect tp sync to local library tmdbhelper does not show for all movies indicator for local library. However for some movies there is the indicator available in the right upper corner however for most not. 

Can you explain what a likely solution can be?

I am using Arctic Horizon skin. 

Thanks.

**Comment by jurialmunkey** [comment]
TMDbH matches with the Kodi Db by checking for an IMDb / TMDb ID in the unique ID field. In a normal Kodi setup, the unique ID field is filled by the movie scraper.

However, as far as I undestand, PKC doesn't use a Kodi library scraper to update the Kodi Db. Instead PKC adds info from the Plex Server by directly editing the Kodi Db.

So the issue is either (1) PKC simply doesn't fill the uniqueid field in the Kodi db; or (2) your Plex Server doesn't have this info. Since you say some items from PKC do still match, it is most likely the second.

A test to do:

On your Kodi machine, go to "Settings > Service Settings > Control"
Enable "Allow remote control via HTTP"

In a web browser put this in the address bar (Kodi needs to be running).
```
http://127.0.0.1:8080/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies","params":{"properties":["uniqueid"]}}
```

NOTE: Change `8080` to whatever your port was (that's the default). If you need to use a web browser on a different machine from Kodi then change `127.0.0.1` to whatever the IP address is of your Kodi machine (Settings > System Info > Network > IP Address).

Hit enter and you should get some output in your browser which will show you whether there are uniqueids in the Db. If there aren't IDs for TMDb or IMDb under uniqueid then TMDBHelper wont be able to match anything.

![image](https://user-images.githubusercontent.com/4618719/89093133-20470a00-d3fb-11ea-8ab1-77d45ec784ef.png)

**Comment by rijsab** [comment]
Hi Jurialmunkey,

Please see attached and seems I have uniqueid for each movie? How is it possible that the same movie is showing in different widgets of tmdbhelper and in some of these widgets the indicator is available and in other widgets the indicator is missing? 
![Screenshot_20200802-000549_Samsung Internet](https://user-images.githubusercontent.com/49214680/89111291-51075d80-d454-11ea-8fc9-91266e08431f.jpg)

**Comment by jurialmunkey** [comment]
Oh, you didn't say it was only I. some widgets. I thought you meant that the movies weren't matching at all. 

These should definitely match. Which lists are not showing library indicators?

**Comment by rijsab** [comment]
Hi Jurialmunkey,

Apologies if I was not clear. All widgets are coming from tmdbhelper.

New Shows
Similar to.. ( some showing indicator and some not)
TV Shows recommended to you
Random popular list
Random trending list
TV Shows trending this week.. some are having indicator and some not
Currently airing
TV studios
Trending movies.. some are showing indicator and some not
Movies recommended for you..

It is very strange that a poster of a TV show is not showing the local library indicator.. however when I enter the seasons I see the indicators available for each episode.

Movies are playing correclty but again no indicator to indicate available in local library

Thanks.

**Comment by jurialmunkey** [comment]
Are you sure that all the missing movies have a TMDb ID listed in your library database (can confirm with the JSON RPC call)?

A lot of the TMDb lists don't supply external IDs (i.e. IMDb / TVDb), so you need to have the TMDb ID in your library for it to match.

**Comment by rijsab** [comment]
Hi JM,

Yes definitely showing an ID for all movies and TV shows.

![20200811_231856](https://user-images.githubusercontent.com/49214680/89950703-70f40980-dc2a-11ea-9a60-be02c615c9b7.jpg)

Above picture is showing for Trakt Movie watchlist I have.. as you can see the library indicator is showing on poster

![20200811_232034](https://user-images.githubusercontent.com/49214680/89950752-89642400-dc2a-11ea-8842-42a52a2f7a88.jpg)

Above is from Trakt Trending movies.. again the indicator is available

![20200811_232605](https://user-images.githubusercontent.com/49214680/89950817-a567c580-dc2a-11ea-8196-74c8d4705786.jpg)

Above is from Trakt similar movies.. as you can see no indicator available and I have this issue with Shows and Movies.. in 1 widget the indicator is a available and in another one not but all from Trakt

**Comment by jurialmunkey** [comment]
@rijsab - Can you show me the JSON RPC output for that movie "The Outpost"?

**Comment by rijsab** [comment]
Here you go mate..

![SmartSelect_20200811-231708_Chrome](https://user-images.githubusercontent.com/49214680/89997068-ecd26e00-dc8b-11ea-8190-125677ab79aa.jpg)

**Comment by jurialmunkey** [comment]
Yep, as I suspected. The problem is that your library is missing a "tmdb" uniqueid for that movie (it only has "imdb")

That means that any list that comes from tmdb (e.g. Similar/Recommended) won't be able to match that item because tmdb lists only have tmdb ids (whereas Trakt lists also have imdb ids).

**Comment by rijsab** [comment]
I am using the widget lists through addon-->TMDbhelper-->Trakt-->Based on last Watched.

Should this work in this case regardless of having only imdb ID for my library?

**Comment by jurialmunkey** [comment]
"Based on Recently Watched" is actually the same as the TMDb Recommendations list in the info dialog, so no it wouldn't work with just IMDb.

The only difference for the "Based on Recently Watched" is that the recommendations are based off a movie that TMDbHelper picks at random from your 5 most recently watched movies in your Trakt history (rather than being based off the movie in the info dialog).

**Comment by jurialmunkey** [comment]
@risjab - Can you test latest? I've re-added some additional fallback checks based upon using title+year if no matching id can be found.

**Comment by rijsab** [comment]
Hi, is this for both TV shows & Movies applicable? Do I need to do a full library scan?

**Comment by rijsab** [comment]
I have tested and works much better. 

However I have House of Cards onmy library but indicator is not available in similar to.. HOWEVER when I open Info and browse the TV Show I can see all indicators are available for the seasons.. so what is causing the indicator not showing up in the widget but working in Info screen?

**Comment by jurialmunkey** [comment]
>  I have House of Cards onmy library but indicator is not available in similar to

TV Shows are harder to match using title+year because there is more variation in title and year values (e.g. different services might use different release dates or year field will relate to season/episode release rather than tvshow pilot premiere).

You're only going to get reliable matches for tvshows if the item has a TMDb ID in the library.

> HOWEVER when I open Info and browse the TV Show I can see all indicators are available for the seasons.. 

What do you mean by "Browse"? If you mean click the "Browse" button, then you are just opening the normal season folder for that item just like if you had browsed to it through the addon/library videos section.

When opening seasons/episodes view, TMDbHelper also pulls down extra tvshow details. These extra details have IDs for other services (e.g. TVDb/IMDb/Trakt), so there's a better range for matching. TMDbHelper does this for seasons/episodes view because it only needs to make one extra request to pull the additional details, whereas for a list of multiple shows it would take too long because an additional request is needed **per** show.

Also note that watched indicators (the checkmark) are not the same as library indicators (the box). Watched indicators can also come from Trakt data, whereas library indicators are only shown if a match is found with the library.

**Comment by rijsab** [comment]
Hi @jurialmunkey 

I have now for movie The Putpost both IMDB & TMDb ID as you can see. 

Still no local library indicator available on poster for widget Trakt Watch list and Recomendations. Based on previously mentioned by you this should now work as both ID's are available in JSON file?

Is this perhaps a bug?

![SmartSelect_20200814-021551_Samsung Internet](https://user-images.githubusercontent.com/49214680/90199248-71300880-ddd4-11ea-8404-7a7f77250056.jpg)

**Comment by rijsab** [comment]
Hi @jurialmunkey 

I have now for movie The Putpost both IMDB & TMDb ID as you can see. 

Still no local library indicator available on poster for widget Trakt Watch list and Recomendations. Based on previously mentioned by you this should now work as both ID's are available in JSON file?

Is this perhaps a bug?


![SmartSelect_20200814-021551_Samsung Internet](https://user-images.githubusercontent.com/49214680/90199309-a9cfe200-ddd4-11ea-8fba-6eaccf415bc0.jpg)

![20200811_232605](https://user-images.githubusercontent.com/49214680/90199373-d84dbd00-ddd4-11ea-8428-058f6df27ab0.jpg)
