### ISSUE TITLE
[Feature request] Hide children's content

### ISSUE THREAD

**Issue by dairefagan** [jurialmunkey/plugin.video.themoviedb.helper#284]
I am not sure if it is possible to do but could you please consider implementing an option to hide children's content from all lists and the widgets generated from them. I mean specifically content that is aimed entirely at children, so I am not sure if it is possible to hide that content but not hide content that is not adult rated but watched by adults.

**Comment by jurialmunkey** [comment]
Unfortunately I don't think it is possible. TMDb provides a field to filter out explicit "adult" content (i.e. erotica) but there's no field which specifically designates "kids" content.

Can't use classification (i.e. MPAA rating) because not all G rated content is specifically aimed at children - e.g. "The Straight Story" by David Lynch is rated G.

On TMDb there's a "kids" genre but it's only for tvshows. The closest for movies is "family" which also covers movies like Back to the Future and Harry Potter, so very much less than ideal.

**Comment by jurialmunkey** [comment]
Haven't been able to find a reliable way to do this unfortunately. So going to close this one for now.
