### ISSUE TITLE
[Request] Like/Unlike List from Context Menu in "Popular/Trending/Liked/Your Lists"

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#289]
Just as the title 😁

**Comment by jurialmunkey** [comment]
Ah I've been meaning to add this! Good reminder because I always think about it when browsing and then forget to add it.

**Comment by jurialmunkey** [comment]
@drinfernoo - As of v4.0.5 in refactor branch you can now like/unlike lists via context menu. I don't bother checking if list is already (un)liked because not worth the overhead of pulling in an extra list of lists to determine which context option to show - I just assume if we're in trending/popular lists that we want to like lists and in the liked lists section we want to unlike lists.

**Comment by jurialmunkey** [comment]
Also, there appears to be some issue on Trakt where if you unlike a list that isn't the first list then the Trakt server doesn't update it's cache properly so it keeps showing in liked lists for a while. It only appears to trigger refreshing their cache when you unlike the first list (then all the others you've unliked also stop showing up).
