### ISSUE TITLE
Trending Lists no longer in date added order

### ISSUE THREAD

**Issue by umonkey13** [jurialmunkey/plugin.video.themoviedb.helper#291]
Since the last update i believe from the repo (last couple of days) trakt trending lists such as Latest releases are no longer in data added order. Can this please be fixed? 

Also are we able to access tmdb my lists i can not see this anywhere in the addon??  

And another thing, show next page on widgets has stopped working again if you could please look at this also. 

Thanks for this great addon and your awesome skins greatly appreciated

**Comment by drinfernoo** [comment]
I believe this is an issue with Trakt having done recent server maintenance, as it's having similar effects on other add-ons as well.

**Comment by jurialmunkey** [comment]
> Since the last update i believe from the repo (last couple of days) trakt trending lists such as Latest releases are no longer in data added order. Can this please be fixed?

It's an issue on the Trakt end. TMDbHelper is working correctly (and nothing has changed in this area of code anyway).

I just checked "Latest Releases" by Gilad & Alex and the Trakt API is returning `X-Sort-By: rank` in the header. TMDbHelper is correctly sorting that list by rank just like Trakt tells it to do. The problem is that Trakt should be returning `X-Sort-By: added` for that list but it's not.

> Also are we able to access tmdb my lists i can not see this anywhere in the addon??

The methods TMDb API provides for authenticating a user aren't really suitable for Kodi because they all require having a web browser on the same machine as the application to be authenticated (which is a problem for setups using LibreELEC etc.).

> And another thing, show next page on widgets has stopped working again if you could please look at this also.

Working fine for me. Are you sure that your widget item limit is high enough to display it?

![Honeyview_screenshot207](https://user-images.githubusercontent.com/4618719/91731770-a0bf7d00-ebea-11ea-9557-adc34a001d4f.jpg)

**Comment by umonkey13** [comment]
Thanks for the detailed response hopefully trakt will notice and fix this, shame about the tmdb lists guess i will have to rebuild them on trakt. 
That has fixed the next page issue don't know what changed they were working before a skin update and then disappeared didn't think to change the limit. Thanks again for all your support

**Comment by jurialmunkey** [comment]
> Thanks for the detailed response hopefully trakt will notice and fix this.

I reported it on the Trakt API feature forum yesterday so hopefully they'll see it.

**Comment by umonkey13** [comment]
Looks like they have, been changed now thanks again
