### ISSUE TITLE
Wrong TV Show Scraped for Latest Episode

### ISSUE THREAD

**Issue by decknine** [jurialmunkey/plugin.video.themoviedb.helper#292]
![Capture](https://user-images.githubusercontent.com/42182450/91649669-d5c3b680-eaa8-11ea-8f47-c8e4cdb1f8d9.JPG)
![Capture2](https://user-images.githubusercontent.com/42182450/91649682-f4c24880-eaa8-11ea-931a-0b6523c3c0d5.JPG)

**Comment by drinfernoo** [comment]
TheMovieDB Helper doesn't do any scraping 🤔

Is this something that you physically have in your library, or an "integrated" item from TMDbHelper? Also, what is the item supposed to be, and what is the XML snippet down below supposed to represent?

**Comment by decknine** [comment]
not sure what you mean by integrated? this is a physical library item as you say. the code is from the view/xml file used by the skin in kodi to dictate what is displayed on screen, as can be seen by the highlighted section, which is incorrect. 

The issue is tmdb helper is identifying "Perry Mason 2020" as "Perry Mason 1966"? and thus displaying the information for the wrong show.

**Comment by jurialmunkey** [comment]
Service monitor can only match by Title. Not much I can do if there are two shows with the same name. Can't use year to confirm because I need the year the show first aired but if a season or episode is focused the infolabel for year will be the release date of that specific season/episode. Also, Kodi doesn't have any infolabels that supply the parent tvshow first aired year for an episode/season listitem.

With movies I'm able to use IMDb ID to confirm the item but for tvshows its impossible to tell if the default ID field is tvdb or tmdb since both are just numbers with no prefix.

**Comment by decknine** [comment]
If tmdb isn't able to distinguish the difference between two shows with the same name, and there is no way to reference "year" then this plugin isn't the best solution for tvshows. this plugin "https://kodi.wiki/view/Add-on:TV_Show_-_Next_Aired" does not work currently with kodi 19 due to python 3 requirements. Are you able to use or preference tvdb as an information source for tvshows specifically? This way you would be able to search by "Year" and have more accurate results, as tvdb includes the year in the title.

**Comment by decknine** [comment]
also is there possibly a way to search both information providers using the imdb id and return a positive based on title match?

**Comment by jurialmunkey** [comment]
> If tmdb isn't able to distinguish the difference between two shows with the same name, and there is no way to reference "year" then this plugin isn't the best solution for tvshows. 

Nothing to do with the information provider used. The issue relates to the information Kodi provides about the focus item to do the lookup in the first place. 

For example,  Breaking Bad first aired in 2008. To find it on ANY online service we would search for "Breaking Bad" and take the result where `year = 2008`. However, say we have S05E16 focused in Kodi -- when we ask Kodi for `ListItem.Year` it will return "2013" because that's the year S05E16 aired. If we then search for "Breaking Bad (2013)" on TMDb/TVDb we get no results because there's no such show called "Breaking Bad" which started in 2013.

Kodi provides no way to retrieve the parent show year date directly from the listitem, hence why I can't use year.

> also is there possibly a way to search both information providers using the imdb id and return a positive based on title match?

Doesn't matter because there's no way to know what the ID is actually for.

Kodi has one ID field exposed as an infolabel - that is `$INFO[ListItem.IMDBNumber]`. HOWEVER, despite the name, this field is not necessarily the imdb id. It could be the TMDb ID, it could be the TVDB ID, it could be the ID for the episode season or show. There's no way to differentiate, so we need to lookup all the possible variations and then compare them back to the data we can get from Kodi to validate.

The important factor for the service monitor is speed - it needs to return results about the current item fast otherwise it isn't very useful. To do multiple look-ups and then compare to validate results is going to slow things down all for what is only a very small number of shows that have exactly the same name (There are five shows I know of where this is an issue - Perry Mason, The Twilight Zone, House of Cards, The Goldbergs, and The Office).

Next Aired has an advantage here in that it is *only* concerned with shows in the library. That means it can generate a database of shows on Kodi startup and read from that. If there are two shows with the same name it can apply further validation. TMDbHelper, on the other hand, has to work on-the-fly for add-ons and so cannot possibly precompile a database of results in the same way.

**Comment by jurialmunkey** [comment]
^^^ That update should improve the validation considerably. It's not perfect but it worked for all my test cases.

Basic logic is:
Sorts search results by year descending (so newest first). 
Checks if year of search result is less than or equal to year of focused episode/season.
If it is returns the result, if not check the next one.

**Comment by decknine** [comment]
Wow, I knew there must be a way around it! Well done sir. 😁
