### ISSUE TITLE
[Feature Request]IMDb section like Trakt

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#295]
Can you please add an IMDb section (similar to existing Trakt section) to access my IMDb WatchList, personal list?

**Comment by jurialmunkey** [comment]
IMDb doesn't have a publicly available API unfortunately.

**Comment by onlytanmoy** [comment]
Please can you check how the Fen add-on implemented it then?

**Comment by jurialmunkey** [comment]
It gets it by reading the html directly off the website and guessing which sections of the html contain the info that it wants. The IMDb terms of service forbid that type of scraping of data for that purpose - no legitimate addon on the official Kodi repo is going to get away with that sort of thing because it opens things up for all sorts of legal action.

Not only that, but that approach of scraping html will break as soon as the html layout changes which means it will require constant updates to maintain whenever there is such a change.

**Comment by jurialmunkey** [comment]
> You may not use data mining, robots, screen scraping, or similar online data gathering and extraction tools on our website

https://help.imdb.com/article/imdb/general-information/can-i-use-imdb-data-in-my-software/G5JTRESSHJBBHTGX#

**Comment by onlytanmoy** [comment]
@jurialmunkey got you, thanks for checking this out for me.

**Comment by jurialmunkey** [comment]
no problem!
