### ISSUE TITLE
[Request] Add Release Date Sorting in Lists

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#296]
Pretty much the title: https://www.reddit.com/r/Addons4Kodi/comments/ipg7e7/_/g4kbrzx?context=1000

**Comment by jurialmunkey** [comment]
How would this be managed though? How would the user select the sort method? Obviously we don't want Kodi's inbuilt sorting because that's only going to sort the page. 

Sorting the whole list needs sorting to be chosen *before* the list is opened because I need to sort *before* I paginate and cache. And some type of setting is going to be too global when really we might only want the one list sorted and maybe not even everytime. 

The sorting is the easy part, it's setting the URI param that's the difficult part.

**Comment by drinfernoo** [comment]
Ah, I see the dilemma. I had originally thought this would be as simple as using Kodi's sort... but of course it's not that simple, I should've known 😅

Close if you feel it's not feasible, but just a request I felt was worth "passing along".

**Comment by jurialmunkey** [comment]
^^^ Can you test that? Adds context menu items to userlists that allow you to open them with a specific sort method.

Doesn't appear to be anyway to group context menu items when added to listitem via python ListItem class -- Bit annoying because there's quite a few options. Still appears to work well and maybe not much of a problem for lists since they only have two context menu entries normally (Add to Favs and TMDbHelper options submenu).

**Comment by drinfernoo** [comment]
I'll give them a try and test tonight. With regards to widgets... I'm not really sure how we'd handle that, but let's see how the sorting works 👍

**Comment by audiosistem** [comment]
Hi! Chapeau bass for the work done! Not all addons work with the player. Exodus redux, La Plaza and Crew do not work. Tempest, Venom are ok. Can you do something? Thanks!

**Comment by drinfernoo** [comment]
You'll need to take it up with those add-on's/player's developers.

**Comment by jurialmunkey** [comment]
> I'll give them a try and test tonight. With regards to widgets... I'm not really sure how we'd handle that, but let's see how the sorting works 👍

One thing to test that I didn't really and only thought of now is the pagination. It should work fine and sorting persists over multiple pages, but I didn't really test that out - in particular, sorting one way then going through a few pages and then going back and sorting another way.

**Comment by drinfernoo** [comment]
That does work for me, actually! It seems these are working just fine, though I didn't get a chance to think much on accessing them through a widget 🤔

**Comment by jurialmunkey** [comment]
@drinfernoo - Got a solution in the refactor branch for selecting sort methods in skinshortcuts. Now when you click the lists in the skinshortcuts dialog it shows an intermediary directory where you can select sort method.
