### ISSUE TITLE
Trailer button does not appear until after the movie has been loaded once.

### ISSUE THREAD

**Issue by Kawsiphek** [jurialmunkey/plugin.video.themoviedb.helper#299]
I would love to have an option to enable showing the trailer button by default. Currently, when using TMDb Helper with any skin, the trailer button does not appear until the show has been loaded once, or "refresh cached details" has been selected in the "TMDb options" context menu. I am not sure if it is possible, but I imagine the trailer data could be retrieved when the artwork data is retrieved?

I have tested this in Arctic Horizon, as well as Arctic Zephyr 2.  When I load movie information from another add-on, like Seren for example, the trailer button always shows by default. I love using TMDb Helper to discover new and trending movies, but would prefer to view the trailer before watching, and not have to navigate the context menu as a workaround. (Other members in my house do not understand the context menu.)

I am using Leia 18.8, and have my YouTube API properly setup. I also have trailers enabled in "The Movie Database metadata add-on." Please let me know if you need anymore information or would like me to troubleshoot.

I appreciate the hard work you've put into this add-on. It really has some great features and categories, and I would prefer to use TMDb Helper widgets over anything else.

**Comment by drinfernoo** [comment]
For what it's worth, the setting for trailers in "The Movie Database metadata add-on" that you mention, is for addingg trailer information into your library when scraping library items.

**Comment by jurialmunkey** [comment]
Not possible. Trailer info is only available when pulling detailed info - tmdb doesn't provide it in the basic list info. If I pull details for every item in the list then the list will take way longer to load because Ill need to make an additional 20 requests on top of the single request needed to grab the list itself.

**Comment by jurialmunkey** [comment]
Install imdb trailers addon and use the included imdb trailer player. Or just use the play with youtube player as that will nearly always play a trailer.

**Comment by drinfernoo** [comment]
Unfortunately, neither of those options are incredibly convenient for users with a default player set... You can access them from the context menu, but not at all from the information window 😨

Would it be in the realm of possibility to have an (disabled by default) option to retrieve the extra information anyways? That way people who aren't worried about loading times can get more complete metadata?

**Comment by jurialmunkey** [comment]
> Would it be in the realm of possibility to have an (disabled by default) option to retrieve the extra information anyways? That way people who aren't worried about loading times can get more complete metadata?

There's better options than pulling down all the details for every single item just to fill a single field that might only be used occasionally. 

For instance, in Arctic Horizon if you have online ratings turned on the skin will use the service monitor to fill the trailer field and display the trailer button in the info dialog (assuming you have trailer button enabled of course!). If you don't see the trailer button there then pulling the extra data in the list is going to make no difference...

Other skins can use the service monitor for the same purpose. That's the whole point of the service monitor - to pull these small pieces of extra data so that it doesn't need to be off-loaded onto the plugin side and the addon isn't making 100s of extra requests for something only used on occasion.

**Comment by jurialmunkey** [comment]
`PlayMedia($INFO[Window(Home).Property(TMDbHelper.ListItem.Trailer)])`

**Comment by Kawsiphek** [comment]
Thanks for the information. I was able to get the trailers to appear in AH by enabling 'online ratings' so that should work well enough for what I need. I did not find that setting in AZ2, so I assume it does not function the same way?

You mention using service monitor in other skins, but that is something for skin developers to use correct? I do not think I am able to enable it myself in the settings from what I can find. 

What would that 'PlayMedia' path be used for? Is that for skin devs as well?

**Comment by jurialmunkey** [comment]
> Thanks for the information. I was able to get the trailers to appear in AH by enabling 'online ratings' so that should work well enough for what I need. I did not find that setting in AZ2, so I assume it does not function the same way?

Yeah not in AZ2. I haven't worked on that skin in quite a while and this was a more recent addition that only made it in to AH.

> You mention using service monitor in other skins, but that is something for skin developers to use correct? I do not think I am able to enable it myself in the settings from what I can find.

Yeah it's a skin dev thing. 

You can toggle it on/off with by setting a keymapped button or a skin shortcut action to `Skin.ToggleSetting(TMDbHelper.Service)` -- although it won't do all that much if the skin doesn't support it.

Also, if you just want to turn it on (rather than toggle it) you can use `Skin.SetBool(TMDbHelper.Service)` instead.

> What would that 'PlayMedia' path be used for? Is that for skin devs as well?

Yeah. Though if you turn the Service Monitor on yourself you could bind it to a keymap button and it should work when in the info dialog.
