### ISSUE TITLE
No Pagination available for certain Trakt lists

### ISSUE THREAD

**Issue by mattardo** [jurialmunkey/plugin.video.themoviedb.helper#310]
Some Trakt lists, such as _Your In-Progress TV Shows_ and _Your Next Episodes_, do not have a _"Next Page"_ option. I have confirmed that my Trakt lists contain enough items to warrant additional pagination, considering the 20 item limit per page.

**Comment by jurialmunkey** [comment]
This is fixed in the upcoming v4 refactor of TMDbHelper - You can test it out from the "refactor" branch but keep in mind it's not quite release ready yet
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/refactor

Previously pagination was just simply too time consuming for these lists. Trakt doesn't actually supply these lists directly and they instead need to be calculated in the plugin by requesting the progress data for each individual show in the watched history. Because Kodi doesn't support rolling dynamic loading of items one-by-one, paginating a list means we need to know all the items it contains - which would take a _long_ time if you've watched a lot of different shows!

In the refactor I've improved the calculating process somewhat so that it's faster but the key reason pagination is now possible is due to smarter caching that limits the amount of re-lookups that need to be done when recalling later. So the very first time loading the list is still going to take a long time but once that's done, the follow-ups are much much improved.
