### ISSUE TITLE
Fanart api issue with new version

### ISSUE THREAD

**Issue by naudski** [jurialmunkey/plugin.video.themoviedb.helper#320]
Hi!

I noticed a lot of errors in the kodi log having to do with 404 errors with the fanart webservice.
I have my own personal fanart api configured in the tmdb addon, but these errors contain another api. Seems hardcoded in the addon. I attached a screenshot. 

Regards 
Naudski
![20201026_185221](https://user-images.githubusercontent.com/66551514/97209908-2dd31c80-17bd-11eb-8d8d-c327f5b9dcd2.jpg)

**Comment by jurialmunkey** [comment]
Fanart TV uses two separate API keys - the developer API key and the personal client API key.

The key you are seeing is TMDbHelper's developer key. This key is needed for TMDBHelper to access Fanart TV. Then you have the personal client key which is the individual user key for VIP access to subscribers and faster look-ups for registered users. That is the key that you input in the settings.
https://fanart.tv/2015/01/personal-api-keys/

You can ignore the 404 errors. Those are normal with Fanart TV - it just means that particular show or movie is not found on Fanart TV. For instance, in that error you have TMDb ID 741074 which is "Once Upon A SnowMan (2020)". If you look this movie up on the Fanart TV website you will see that it has no images:

![image](https://user-images.githubusercontent.com/4618719/97233995-16834600-1834-11eb-985f-d47735ae325f.png)

404 will only be logged once. After that the plugin caches an empty object so it avoids rechecking for one day. You are probably seeing a lot of these because the v4 of TMDbHelper uses a new cache prefix so everything needs to be recached.

I might make these errors less verbose as they really are unimportant.

**Comment by naudski** [comment]
Thanks for your anwser!
