### ISSUE TITLE
Auto Repeat Video Again

### ISSUE THREAD

**Issue by Wafflestyx** [jurialmunkey/plugin.video.themoviedb.helper#327]
[Issue 309](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/309) 

Been using the refactor version, updated to 4.0.21, somewhere along the way this issue returned.

Edit: Shows are not getting marked as watch.

**Comment by jurialmunkey** [comment]
Can you try out the version in the testing branch and see if that works better for you:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/testing.zip

Testing branch is based off Leia - if you need a Matrix version of the testing branch let me know and I can make one.

**Comment by Wafflestyx** [comment]
Was able to test it out and it seems to take care of both, wanting to play again and not getting marked as watched.


I do get a dialogue box saying "this play is missing is_resolvable... dialogue can be skipped buy adding is_resolvable to the player file" 

Is the player file in question the corresponding .json file in the players folder?

Is this something you could over right as a global setting in TMDBh settings?

**Comment by jurialmunkey** [comment]
Yes the player files are the json files in the addon data folder of TMDbhelper.

No it can't be a global setting as individual plugins will interact differently so it needs to be set on a per plugin basis - eg some plugins will work fine being called using setresolvedurl whereas others won't work. It basically depends on whether the end player plugin itself sets a resolved url or if it instead needs to pass directly to the kodi player. 

If it turns out this approach works well for users and I merge into master (which I think I will as I'm pretty sure this is going to be the most stable approach), then I'll setup a player configure dialog where you can set resolved method via gui. I wanted to do this anyway as I want to make a way to set fallbacks via gui.

**Comment by drinfernoo** [comment]
@jurialmunkey Player configuration through a GUI sounds like the bee's knees 😁

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Player configuration through a GUI sounds like the bee's knees 😁

Yeah I think it's about time that I get around to adding gui config. I think the main things will be disable/enable, priority, fallback, and resolve method.

**Comment by jurialmunkey** [comment]
@drinfernoo - Configuration options now merged to master (found in TMDbHelper settings under Players category).

See comments here for how it works: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/325#issuecomment-719883272

Ability to edit fallbacks still needs to be added but will be coming soon! 😁

**Comment by jurialmunkey** [comment]
Now with fallbacks too! 😉
