### ISSUE TITLE
Error Message Selecting Movie

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/plugin.video.themoviedb.helper#330]
I get an error message (see attached image) when I select a particular film from a Tmdb Helper Movies Watchlist widget using the Aura official skin. 

I am given two options: “play media” and “setresolvedurl”. I select either one and it still works and calls the proper play method. This is the first time seeing this error message.  Is this something that you’re able to fix or may know what’s going on?

![0C59117C-3F4D-44A9-A119-52CCC4DB6E79](https://user-images.githubusercontent.com/67085646/97794882-f063fa00-1bd5-11eb-8e84-668157d1e510.jpeg)

**Comment by drinfernoo** [comment]
Seems that player needs to be updated... @jurialmunkey, is there a default value specified if a player doesn't?

**Comment by jurialmunkey** [comment]
> 
> 
> Seems that player needs to be updated... @jurialmunkey, is there a default value specified if a player doesn't?

@drinfernoo 
If the value isn't set it, the fallback is `"is_resolvable"     : "select"` which is what prompts the dialog.

Other values are:
`"is_resolvable"     : "true"` = setResolvedURL method
`"is_resolvable"     : "false"` = PlayMedia method

Should set to true where possible for best experience and only use false if it doesn't work. A lot of addons will work with setResolvedURL from inside TMDbHelper and from widgets - it largely appears to be .strm files in the library that have issues so make sure you test those before setting the flag either way (although not the end of the world if it is set incorrectly because the user can still override via the configuration dialog anyway).

The flag will only need to be false for addons that shell out to a script to scrape various sources before playback -- and even many of these will still work, it just depends on whether the addon itself passes the url back to kodi via setResolvedURL.

Nearly all addons that play directly (e.g. Netflix, Youtube) when clicking an item will work properly via setResolvedURL (I say "nearly all" because obviously there might be some weird plugin out there that appears to play directly but actually does some weird script thing where it doesn't pass a playable url back to Kodi via setResolvedURL). 

I'd expect addons that only prompt to select quality/bit-rate would also work fine with the setResolvedURL method - (e.g. I know BiNGE by Matt Huisman and SlyGuy works with this method, so I'd expect their other addons like Disney+, Kayo, Foxtel etc. to also work that way since they all share the same basic inputstream framework underneath).

**Comment by ray2301** [comment]
this is actually a good feature. individual addons can be setup in settings to always resolve or always play. i don't see this as a bug.

**Comment by LN13uLL** [comment]
> this is actually a good feature. individual addons can be setup in settings to always resolve or always play. i don't see this as a bug.

It’s not a feature as it didn’t happen before lol. But it doesn’t happen anymore.

**Comment by jurialmunkey** [comment]
> 
> 
> > this is actually a good feature. individual addons can be setup in settings to always resolve or always play. i don't see this as a bug.
> 
> It’s not a feature as it didn’t happen before lol. But it doesn’t happen anymore.

It is a feature and it is done deliberately for the reason ray2301 states - it gives users the ability to test whether the player works with setResolvedURL or if that particular plugin requires the inferior PlayMedia method to work. Once the user is confident that the player works with setResolvedURL (or doesn't work and needs PlayMedia), that select dialog can then be overridden by setting the flag appropriately in the player configuration dialog.

Also, people who ship third party players can set the flags themselves from within the player file itself, which will then override the dialog prompt and instead automatically choose the required option. For instance, the Netflix , BiNGE and Youtube players that I ship by default with the plugin have setResolvedURL flag enabled and so will never prompt this choice.

It's a little bit of short term pain for a better long term experience overall.
