### ISSUE TITLE
The movie/tv lists are not refreshing at the same time in all Kodi instances

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/plugin.video.themoviedb.helper#333]
Hi jurialmunkey,

I have 3 Kodi setups and I noticed that the movie/tv lists are not refreshing at the same time in all of them. Some are having updated info and some are having old info. e.g. In one setup I'm seeing contents for "Trending Movies Today" list from yesterday and for another setup I'm seeing updated contents for today.

Please advise. Thanks!

**Comment by jurialmunkey** [comment]
Most lists are cached on disk for 24hrs and don't update until the cached version expires. Caching is necessary because otherwise we'd needlessly be hitting the apis and constantly pulling down the same data every time Kodi refreshes after watching something. There are a few exceptions where lists are updated more frequently out of necessity such as watchlists, custom lists and other trakt sync lists -- Trakt has a special last_activities timestamp for these that I'm able to check to see if the cached version is out of date. 

Generally, though, most lists are cached 24 hrs. However, if they're more than 24hrs out of date, then that's an issue where something is going wrong.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Okay, I'll check once 24 hrs. complete and let you know if the lists are updating or not.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,

It's been 24 hrs. since my last list update. I checked now and found that my lists refreshed.
Thank you!

However, is there no way to shorten this 24 hrs. duration to something like 12 hrs.?
That way we can get updated information in even less time.
Nevertheless, if you think that way the apis will get over-clogged then I can understand the problem.
Please advise. Thanks!

**Comment by jurialmunkey** [comment]
I'd rather leave it at 24hrs. The TVDb API recently became a paid API, so the fact that Trakt and TMDb APIs remain free to use means I would like to try to respect them and minimise the amount of traffic hitting them as much as possible whilst still providing a full featured plugin.

My TMDb API stats show that there are approx 50,000 daily unique users of TMDbHelper - so anything that increases the number of requests being made per user can add up very quickly. Halving the cache time effectively means a doubling of requests being made which will be a very significant traffic increase - well, probably a little less than double since some users probably only use Kodi at a specific time of night but you get my point.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
OK fine. I can understand the situation. 24 hrs. wait time is fine for now. Thanks for your help!
