### ISSUE TITLE
[Bug] Next Aired-watched/unwatched

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#351]
Next Aired is displaying watched/unwatched icons. Also when unwatched is selected tv show thumbnails are displayed.
I notice this issue before the current update.

watched
![watched](https://user-images.githubusercontent.com/2873112/98469827-cca64280-21d9-11eb-9244-a5733a9d84c5.jpg)

unwatched
![unwatched](https://user-images.githubusercontent.com/2873112/98469838-d760d780-21d9-11eb-88df-94c5971327aa.jpg)

**Comment by Blurayx** [comment]
Sorry about the duplicated post. I had an error when I posted the first bug report and didn’t realise it generated the post.

**Comment by jurialmunkey** [comment]
What's wrong with showing watched indicators? TMDbHelper merges library details, so if you have that episode in your library and you watched it then it is going be marked as watched.

Also, are you sure you don't have Kodi's setting to show thumbs for unwatched episodes disabled? 
`Settings > Media > Videos > Show information for unwatched items > Episode thumbs`
If you have that disabled then AH won't show episode thumbs for unwatched items and will instead show fanart/landscape to prevent spoilers.

**Comment by Blurayx** [comment]
Before the major update, I never had this issue. "spitting image" and the other tv shows don't have the icons and don't change to thumbnail when watched.
As you can see from the image below my settings are correct.

![test](https://user-images.githubusercontent.com/2873112/98485184-671f7980-220c-11eb-8373-1dc1832f25c5.jpg)

**Comment by jurialmunkey** [comment]
If those are your settings, then it is working correctly.

Unwatched episode = AH shows fanart/landscape to hide any spoilers that the thumbnail might contain.
Watched episode = AH shows thumbnail if available because you've already watched the episode so no spoilers.

> Before the major update, I never had this issue.

I would say the inverse is true - previously TMDbHelper had an issue where it did not merge watched status correctly from the library. Now it works as intended and so you are seeing thumbs correctly being hidden/shown depending on watched status.

> "spitting image" and the other tv shows don't have the icons and don't change to thumbnail when watched. this is where I'm confused.

The star icon means "recently added" - it doesn't mean unwatched. It just means that the episode title matches an episode title in your ten most recently added episodes. You can disable recently added indicators in the skin settings.

In terms of thumbnails:
Before Matrix the library used to also store posters in the thumbnail field (basically was a generic field that might contain a banner, poster, or thumb depending on various conditions). As a result, the library is a complete mess when it comes to being able to retrieve thumbnails reliably so I just don't bother since we definitely don't want to see a poster there. 

What that means is that in order to show a thumb, a thumb needs to be available on TMDb. That episode of Spitting Image doesn't even exist on TMDb and the episode of Killer Siblings doesn't currently have a thumbnail on TMDb. That's why those would be falling back to fanart/landscape - because there simply isn't a thumb available and Kodi library is too unreliable to take a thumb from (at least until Matrix).

![image](https://user-images.githubusercontent.com/4618719/98486704-2444bc80-2273-11eb-9bfb-7d7229b91da3.png)

**Comment by Blurayx** [comment]
Ok,Thanks
