### ISSUE TITLE
[Bug] Trakt Next Episodes list showing hidden items also

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/plugin.video.themoviedb.helper#356]
Hi jurialmunkey,
I noticed that in the TMDB Helper Trakt section under Next Episodes list I'm able to see those episodes also whose progress I've hidden in Trakt. However, this is not the case with the Trakt website or Seren addon, where if I hide the progress for a TV series, then it doesn't show up under Next Episodes list. This issue is happening both under Trakt Next Episodes section as well as TV Shows Next Episodes section. Could you please check why this is happening and if it can be resolved?

**Comment by jurialmunkey** [comment]
> I noticed that in the TMDB Helper Trakt section under Next Episodes list I'm able to see those episodes also whose progress I've hidden in Trakt. 

It really should already hide hidden shows.
Can you go to [this link](https://trakt.tv/settings/hidden) and confirm that the shows are listed hidden on that page and what section they show up under?

Also, I'm wondering if this might be a cache issue rather than a logic issue - Are these recently hidden shows? Or do even shows that you've hidden a long time ago show in the list?

Also you say "episodes" that you've hidden, but afaik it isn't possible to hide single episodes on Trakt. You can only hide full shows. Pretty sure you mean shows here but just want to double check that you are actually hiding shows and not referring to something entirely different.


> This issue is happening both under Trakt Next Episodes section as well as TV Shows Next Episodes section

FYI - These are exactly the same list. It shows in both folders because it relates to TV Shows and uses data from Trakt.


> However, this is not the case with the Trakt website or Seren addon, where if I hide the progress for a TV series, then it doesn't show up under Next Episodes list. 

FYI - There's not a specific "Next Episodes" call on Trakt API. Next episodes are calculated in the client and so each application will use a different method. 

In TMDbHelper I (1) sync entire watched progress from Trakt account, (2) look through tvshow watched history in last watched order skipping hidden shows, (3) check if each show has unwatched episodes, (4) find next episode to watch for show and (5) then add to list (additional step 6 if sorting by air date and I call data from api about each episode in the list to be able to then sort). 

It would be preferable if this list was provided server side as it would ensure much better consistency and speed but Trakt have rejected developer requests for that. Point is that it isn't just simply a missing flag somewhere telling the server not to give me hidden shows but rather some caching issue in my code (this list involves some complex caching code to try to avoid it needing to recalculate everything each time - the raw list with nothing cached takes many minutes to pull all the data and calculate)

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Yes, the shows are showing up as hidden in this link:
https://trakt.tv/settings/hidden
They are listed under the heading "Watched progress and up next".

These are not recently hidden shows. I've hidden them since a long time back.

My mistake, by "episodes" I meant the entire TV Shows that I've hidden and not any particular episode.

As I said it's happening in both the lists, and you mentioned that both of these lists are the same.

I checked on multiple Kodi instances on different devices, and found the same issue happening everywhere. So I'm not sure if this is some kind of cache issue or not.

Could you please try and replicate the issue from your end and kindly advise? Thanks!

**Comment by jurialmunkey** [comment]
Strange. That sounds like it should work then. I've done multiple tests and if I remove/add shows from hidden items the "Your Next Episodes" section reacts appropriately after I re-open it (i.e. hides/shows).

Can you tell me the shows specifically that aren't hiding so I try with them and see if I can replicate?

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,

Few of the shows which aren't hiding are as follows:
1) Marvel's The Punisher (2019)
2) Suits (2011)
3) Schitt's Creek (2015)
4) Robocop: Prime Directives (2001)
5) Hanna (2020)
6) Marvel's Iron Fist (2018)
and many more...

Basically, all my hidden shows are showing up under "Next Episodes" list in TMDB Helper.
I can confirm that this is not an issue with my Trakt account, as the hidden episodes are not showing up under "Next Up" section in Seren addon. Please advise.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
I also removed the hidden items from my "Hidden TV Shows" list in Trakt and hid them again from my "In Progress" list in Trakt.
They worked perfectly in Seren, but not in TMDB Helper. Please advise.

**Comment by jurialmunkey** [comment]
I just simply don't understand why. It works flawlessly for me. I added all these shows by marking the first episode of each as watched and then show up correctly, then I hide them all and they hide correctly:

Next Episodes After Adding Shows:

![Honeyview_screenshot283](https://user-images.githubusercontent.com/4618719/99067725-49cd1f80-25ff-11eb-8445-2e47755bec0f.jpg)

My Hidden Shows:

![image](https://user-images.githubusercontent.com/4618719/99067696-3de15d80-25ff-11eb-911c-06c569e23923.png)

Next Episodes After Hiding Shows:

![Honeyview_screenshot284](https://user-images.githubusercontent.com/4618719/99067727-4b96e300-25ff-11eb-99ae-0c0d21de6c6f.jpg)

**Comment by jurialmunkey** [comment]
Okay I'm going to ask a really stupid question and it is a real long-shot but since it occurred to me I have to ask just in case -- Are you absolutely certain that the Trakt account you are logged into with TMDbHelper is the same Trakt account as you are using elsewhere?

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Yes, I have only one Trakt account that I use everywhere, and as I said it's working perfectly fine in Seren. The issue is only with TMDB Helper. Don't know why this issue is happening, but since you said it's working totally fine for you so I guess I have to live with it. Thanks anyways for looking into it and spending your valuable time behind it!

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
I found this old issue thread here:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/100

This was a similar issue like mine. I think you solved it somehow. Could you please check once? Thanks!

**Comment by jurialmunkey** [comment]
That issue was before there was code to hide the items. The code in the addon now is a result of that issue.

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Then I guess there's no hope for my issue to get resolved. Don't know why this is happening on all my Kodi setups, both on Android and Windows devices. Maybe I've to live with it. Thanks anyways!

**Comment by jurialmunkey** [comment]
I'd still like to get this fixed though! I'm just not quite sure what the issue is.

Can you grab latest version, I've added a logger function which might help me understand what is going on.

Go to:
`TMDbHelper Settings > Expert > Log output of Trakt request`

It will prompt you to enter a URL. In the onscreen keyboard enter:
`users/hidden/progress_watched?type=shows`

It will then save the output of that request to a file in the `addon_data/plugin.video.themoviedb.helper/log_request` folder. A pop-up will tell you exactly where it is saved. Can you grab me that output file and attach it here?

**Comment by ShibajiCh** [comment]
`[trakt_usershiddenprogress_watchedtypeshows.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5540373/trakt_usershiddenprogress_watchedtypeshows.zip)
`
Hi jurialmunkey,
Please find the requested file attached. However, I noticed that all my hidden shows are not listed in this file. Only few of them are listed. Kindly advise. Thanks!

**Comment by jurialmunkey** [comment]
If they aren't listed there then they aren't hidden from watched progress. You need to rehide them from the progress section on Trakt.

**Comment by jurialmunkey** [comment]
If you're interested in finding what hidden section they are actually under, here are all the possible URLs you can use

`users/hidden/calendar`
`users/hidden/progress_watched`
`users/hidden/progress_watched_reset`
`users/hidden/progress_collected`
`users/hidden/recommendations`

You can filter all of them by type by adding the `?type=shows` parameter to the end (or don't include it to get all types).
Possible options are: `shows` `movies` `seasons`

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
There's definitely some issue going on. I've 46 TV Shows in my Trakt Hidden list. Please see below:

![image](https://user-images.githubusercontent.com/65297828/99147342-3f199580-26a6-11eb-8b9c-022df5d23584.png)

However, only those 10 are showing up in the log_request file. Why?

I tried filtering as per your instructions, but I only received the "No response" pop-up message, except from the below two:
users/hidden/progress_watched?type=shows
users/hidden/recommendations?type=shows

I tried with the following as well, but I'm only getting the same 10 shows in the list:
users/hidden/progress_watched?type=seasons
users/hidden/progress_watched?type=movies

I also tried removing them and re-hiding them, but the same issue occurs.
Could you please advise on why this is happening and kindly look into the issue?

**Comment by jurialmunkey** [comment]
> However, only those 10 are showing up in the log_request file. Why?

Ah this is the hint I needed! Trakt started forcing pagination of some lists that used to be optional, so if you don't specify a limit then they set it to 10 (rather than unlimited).

Can you test latest version (you might need to trigger a cache refresh by hiding something in Trakt).

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
The latest TMDB Helper v4.0.48 worked perfectly fine.
The above issue is resolved now.
Thanks a lot for your help!
Keep up the good work!

**Comment by jurialmunkey** [comment]
We got there in the end! 

Thanks for testing!

**Comment by ShibajiCh** [comment]
Hi jurialmunkey,
Yes, you finally fixed the issue.
Glad to help you!
I'm an avid user of the TMDB Helper addon and Kodi.
You're a life saver.
Thanks a lot!
