### ISSUE TITLE
[Bug] Fallback players not working? 

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#357]
I will post a log later but I don’t want to post anything I shouldn’t be in it. Using the configure players setting makes it freeze and then crash after the first addon can’t find it, then using one of the preconfigured .jsons with fallbacks in it such as Disney.netflix from DrInf’s GitHub that used to work on a previous version of TMDBH gives an error now when trying to configure players or play anything with tmdb helper, or set default movie or episode players.

**Comment by drinfernoo** [comment]
I haven't updated those players in awhile, and I think there's been changes to the player structure.

**Comment by jurialmunkey** [comment]
Please post log. Configure players and fallbacks work correctly for me, so I cannot know what the issue is without a log.

**Comment by jurialmunkey** [comment]
Also please try latest github master - might be an issue with non-ascii characters being used in filenames.

**Comment by mathu204** [comment]
https://paste.ubuntu.com/p/N2jXCMVcWy/

Error with latest master installed, I used preconfigured players I’ll try to make one using the configure players setting itself. Last time I did it like this; it searched with first addon, 0 links then crash

**Comment by jurialmunkey** [comment]
```
NOTICE: ADDON: plugin.video.themoviedb.helper v2.4.36 installed
```
I'm sorry but that is nowhere near the latest version of TMDbHelper.

Latest version is v4.0.44

**Comment by jurialmunkey** [comment]
Can you try v4.0.45? I forgot about players that specify multiple plugin dependencies. That should fix things hopefully.

**Comment by mathu204** [comment]
> Can you try v4.0.45? I forgot about players that specify multiple plugin dependencies. That should fix things hopefully.

Tested, did not work it froze my Kodi again like last time leading to a crash or me force quitting here is the log. Im going to test with a different addon than the one that was crashing and get back to you
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5540272/kodi.log)

**Comment by jurialmunkey** [comment]
I cant recreate this issue. What are the exact steps to recreate it?

**Comment by mathu204** [comment]
> I cant recreate this issue. What are the exact steps to recreate it?

Install/Update tmdb helper.

Configure players. Select Fen, movie fallback = Seren.json play movie

Episode fallback = Seren (smartplay) play episode.

Play movie Kung Fu Mulan, or Four Poster (movies that won’t have any links) scrapes up to halfway, about one source left it freezes then crashes or I have to force quit.

Doing it vice versa for Seren.json with Fen for both fallbacks, Seren finished a scrape successfully but with 0 links and then takes me back to the menu I scraped from without going to next player.

**Comment by jurialmunkey** [comment]
> Doing it vice versa for Seren.json with Fen for both fallbacks, Seren finished a scrape successfully but with 0 links and then takes me back to the menu I scraped from without going to next player.

Both these players have no steps and instead provide a direct url, so they won't work with fallbacks. All the fallback does is tell TMDbHelper what to do if the player steps don't return a url. Any player that provides a url directly is *always* going to provide a url (the url defined in the player) and thus will never fallback.

Whether the addon being called via the URL plays successfully is a different matter but by that stage things are out of TMDbHelper's hands. 

The fact that you say these players return to the menu makes me think you have the wrong "is_resolvable" flag set. You should be using "PlayMedia" (i.e. is_resolvable = false) for these players because they shell out to a scraper script.

**Comment by mathu204** [comment]
> > Doing it vice versa for Seren.json with Fen for both fallbacks, Seren finished a scrape successfully but with 0 links and then takes me back to the menu I scraped from without going to next player.
> 
> Both these players have no steps and instead provide a direct url, so they won't work with fallbacks. All the fallback does is tell TMDbHelper what to do if the player steps don't return a url. Any player that provides a url directly is _always_ going to provide a url (the url defined in the player) and thus will never fallback.
> 
> Whether the addon being called via the URL plays successfully is a different matter but by that stage things are out of TMDbHelper's hands.
> 
> The fact that you say these players return to the menu makes me think you have the wrong "is_resolvable" flag set. You should be using "PlayMedia" (i.e. is_resolvable = false) for these players because they shell out to a scraper script.

Oh I was under the impression it should be setresolvedURL cause everyone was saying that. 

So is there any hope whatsoever that fallbacks can be set up for these types of addons? Whether something on your end, or players being rewritten, or something on the addon developers end?

**Comment by jurialmunkey** [comment]
> So is there any hope whatsoever that fallbacks can be set up for these types of addons? Whether something on your end, or players being rewritten, or something on the addon developers end?

Not really because there isn't any way to know what the end plugin will do with the URL, so it isn't possible to tell if it was successful or not. Plus TMDbHelper exits after it calls the URL. 

Even if I waited to see if something started playing, there's so many variables to take into account. For instance, as a very simple example, how long do we wait until we say that it has timed out? We wait too short a time and the fallback is called before the user has a chance to select anything (or perhaps even before the plugin completes its scraping), wait too long and the user starts doing something else when all of a sudden the fallback player gets randomly called in the middle of what they are doing. 

We would need some standardised way of plugins telling Kodi that they were successful or not. The current way to do that is via setResolvedURL but clearly these plugins don't even use this method so it is an uphill battle to get authors to support some type of specific call back function for TMDbHelper if they don't even use the standard one for Kodi.

**Comment by mathu204** [comment]
> > Doing it vice versa for Seren.json with Fen for both fallbacks, Seren finished a scrape successfully but with 0 links and then takes me back to the menu I scraped from without going to next player.
> 
> Both these players have no steps and instead provide a direct url, so they won't work with fallbacks. All the fallback does is tell TMDbHelper what to do if the player steps don't return a url. Any player that provides a url directly is _always_ going to provide a url (the url defined in the player) and thus will never fallback.
> 
> Whether the addon being called via the URL plays successfully is a different matter but by that stage things are out of TMDbHelper's hands.
> 
> The fact that you say these players return to the menu makes me think you have the wrong "is_resolvable" flag set. You should be using "PlayMedia" (i.e. is_resolvable = false) for these players because they shell out to a scraper script.

Hey jurial, I have a question for you I am using Premiumizer addon and im wondering since I dont belive this one does a scraper dialog, i mean it does scrape my cloud for files its not like Seren/F*n/other addons, can a fallback player be set for it? I think it is a .search json so like u said i dont think it is a direct url or the other.

**Comment by jurialmunkey** [comment]
> Hey jurial, I have a question for you I am using Premiumizer addon and im wondering since I dont belive this one does a scraper dialog, i mean it does scrape my cloud for files its not like Seren/F*n/other addons, can a fallback player be set for it? I think it is a .search json so like u said i dont think it is a direct url or the other.

The key is whether you can find the movie/show using the search function of the addon you use as a player. The fallback is only used if you can't browse to the item inside the plugin, it has nothing to do with whether or not that item can actually play or not.

For example, if I search "Mandolorian" on Netflix plugin I'm simply not going to find it because Netflix doesn't have the Mandolorian - so in this case the fallback will be used. However, if you used Quasar without providers that's not going to fallback because you will be able to find the item inside Quasar but it just isn't playable because there's no provider. 

All TMDbHelper is doing with a player is automating what you would normally click on inside Kodi. It isn't checking if the actual file could play successfully or not

**Comment by mathu204** [comment]
> > Hey jurial, I have a question for you I am using Premiumizer addon and im wondering since I dont belive this one does a scraper dialog, i mean it does scrape my cloud for files its not like Seren/F*n/other addons, can a fallback player be set for it? I think it is a .search json so like u said i dont think it is a direct url or the other.
> 
> The key is whether you can find the movie/show using the search function of the addon you use as a player. The fallback is only used if you can't browse to the item inside the plugin, it has nothing to do with whether or not that item can actually play or not.
> 
> For example, if I search "Mandolorian" on Netflix plugin I'm simply not going to find it because Netflix doesn't have the Mandolorian - so in this case the fallback will be used. However, if you used Quasar without providers that's not going to fallback because you will be able to find the item inside Quasar but it just isn't playable because there's no provider.
> 
> All TMDbHelper is doing with a player is automating what you would normally click on inside Kodi. It isn't checking if the actual file could play successfully or not

I see, then I have a follow up question based on the process u showed me. So the show in question I am testing this with is Bleach and I have the whole show in my PM Library. The show episodes are named like this in the Kodi Library 1x123 and so on. So when I play 1x123 in Premiumizer player using tmdb helper it will autoplay it unless the episode doesn’t have the 1x at the beginning in which it will show up a dialog with all my bleach episodes and ask me to play. 

I changed my settings in the PM addon and did a search exactly “Bleach 1x123” which I think could be put as “{showname} {1}x{e} or {sxe}” and when it is named exactly as Bleach 1x123 it will autoplay. For example if I had 124 named just as Bleach - 124, and did a search for Bleach 1x124 in the addon nothing would pop up which is what I would want for the fallback to occur right? The thing is when I play 1x124 in my library through PM player when it can’t find 1x124 it brings up the dialog and asks me to pick the episode which I need to eliminate to get the fallback to occur. 

So I know that the settings I have enabled in PM will make it so if I search Blesch 1x124 no results will occur so my question is do u think I can change the PM player parameters to search it exactly as that so that when it doesn’t find sources it will just not find anything enabling the fallback to work? Sorry I am wording this very poorly I hope u can understand it lol. But basically I think I need to edit the PM players search parameters to search exactly for Bleach 1x124 so that when it finds no sources rather than showing me the dialog it will just find no sources so the fallback can be triggered
