### ISSUE TITLE
Trakt watchlist library integration

### ISSUE THREAD

**Issue by Giel88** [jurialmunkey/plugin.video.themoviedb.helper#358]
Right now you can add custom or liked lists to your library. Which is great but it would be great if adding your trakt watchlist to your library would be possible aswell. 

I know you've talked about it on #153 but are you still planning on adding trakt watchlist library integration? As an avid watchlist user this would make a lot of sense.

**Comment by Carguy1CC** [comment]
Agreed! Trakt "Watchlist" integration into Kodi Library would take this addon over the TOP! I love TMDb Helper a LOT but, I'm never able to get my Kodi library to match up correctly... In the past I've been using OpenMeta/OpenInfo & syncing Trakt "Collection" is much easier! Although there's NO option to sync your "Watchlist" with it either?! Each show/movie has to be added individually!? Can we get TMDb Helper to integrate & sync our whole Trakt "Watchlist" all at once?? I definitely prefer TMDb Helper over OpenMeta! But, I've just recently started using TMDb Helper & wondering if I'm just missing something?! I can get it to integrate "users" or "liked" lists, but will NOT sync "Watchlist" with context menu addon or through library settings?! Also, I noticed even the "users" & "liked" Trakt Lists seem to be having a problem as well because they aren't syncing the WHOLE entire list at once... (Lists of 60-100 shows/movies) will only add +/- 20 movie/shows... ANY help or instructions on how to properly accomplish this would be GREATLY APPRECIATED! 😉

***Using Kodi 18.9 on 2019 Shield TV Pro with Xenon Plus 4.0 Build.  Thanks!

**Comment by dm2912** [comment]
but as soon as you watch something, even a single episode, then trakt removes it from the watchlist. so it would not sync and keep up to date bar the initial sync

So for instance, if you put a show that was 3 episodes in on your watchlist.

helper would add those 3 episodes to your library, but as soon as you watched 1 then the show would vanish from your watchlist and further episodes would not be added

**Comment by Giel88** [comment]
Have to admit I solely use my watchlist for movies and custom lists for TV shows so removing after watching is fine for me. :)

**Comment by dm2912** [comment]
yeh, for movies trakt watchlists are great

for tv shows, certainly when it comes to library integration, they are useless.

**Comment by jurialmunkey** [comment]
> for tv shows, certainly when it comes to library integration, they are useless.

It _could_ work because TMDbHelper scans for .nfo files in the save folder on subsequent updates to determine which shows it should update with new episodes. The main issue is if the user watches an episode _before_ the update occurs and then the show is never added.

> Have to admit I solely use my watchlist for movies and custom lists for TV shows so removing after watching is fine for me. :)

You'd still have the same with movies though. If you watch the movie on a streaming service before the library update occurs then the movie would never be added to the library.

I think watchlist would work well being manually added from the context menu. I'm keen to add that as an option as I think it makes a simple and quick way to add all the things you want to watch to the library. However, it is probably a poor choice for a monitored list. Really custom lists are the only suitable option for auto-updates.

Also, it seems that a _lot_ of users really struggle to understand the function and purpose of Trakt's watchlist and collection sections, so what would happen is that I'd end up receiving lots of reports of "bugs" where the real issue ends up being what is between the keyboard and the chair.

**Comment by Giel88** [comment]
> You'd still have the same issue with movies though, albeit on a smaller scale. If you watch the movie on a streaming service before the library update occurs then the movie would never be added to the library.

Which is exactly what you'd want right? If I watch the movie before the library update (regardless of the streaming service) there's no reason to still add that movie to my library. For me that's the strength of auto syncing a watchlist to the library: it adds the movies I want to watch and once I've watched it, it's gone. No need to keep it there.

**Comment by jurialmunkey** [comment]
Yeah but movies added to the library won't be removed from the library after being watched because the file is still on disk. You'd need to go manually delete the file yourself and then clean the library. Tmdbhelper never deletes anything (I think automated deletion is a dangerously bad idea). 

What that means is you end up with an inconsistent experience where some movies in your watchlist get added and stay in your library forever despite having watched them, and other movies never get added all

**Comment by Giel88** [comment]
Ah yeah, now that I think about it... I believe metalliq had a 'clean library' function that you could run every once in a while.

**Comment by mrXoo** [comment]
Instead of adding to the kodi library you could just use the trakt watchlist and add it to your skin somewhere. Ive added my watchlist as a widget. When I watch a movie then it disappears.

**Comment by JayDee696969** [comment]
I just dont understand why anybody needs the Kodi Library if your using Trakt? I guess the only reason would be if you actually have downloaded copies of the media stored and arent using addons to play from, otherwise why not just use the Trakt sections instead?

**Comment by jurialmunkey** [comment]
> 
> 
> I just dont understand why anybody needs the Kodi Library if your using Trakt? I guess the only reason would be if you actually have downloaded copies of the media stored and arent using addons to play from, otherwise why not just use the Trakt sections and the players instead?

That's what I personally do (just use the online Trakt sections rather than updating to library) but I think people like having the library integration because the library itself is very fast since it is local database. It also gives the ability to mix local and non-local content together in the one place, letting you use smart playlists and library nodes etc.

**Comment by Giel88** [comment]
> > I just dont understand why anybody needs the Kodi Library if your using Trakt? I guess the only reason would be if you actually have downloaded copies of the media stored and arent using addons to play from, otherwise why not just use the Trakt sections and the players instead?
> 
> That's what I personally do (just use the online Trakt sections rather than updating to library - I only add local content to my library and then play it via the "Play with Kodi" player) but I think people like having the library integration because the library itself is very fast since it is local database. It also gives the ability to mix local and non-local content together in the one place, letting you use smart playlists and library nodes etc.

Mainly nodes and speed. Widgets and the library load way faster. I also like to fire up content from my phone using the Yatse app.

**Comment by jurialmunkey** [comment]
@Giel88 - Most recent version on master branch should now allow adding watchlist to library either as a monitored list or manually via the context menu. It appears to be working well for me - could you test and let me know how it goes?

It's still going to have the disadvantage discussed earlier about items not being added if they were watched before the scheduled update had a chance to run. However, I think there is a real legitimate use case for monitoring watchlists.

When I thought about it more, I think you're probably right that in most cases the "disadvantage" will actually be viewed as expected behaviour. For instance, usually things sit on my watchlist for a while because I add things that look interesting but I'm not necessarily in the mood to watch today. If I add something and watch it immediately, generally I only added it to the watchlist because I wanted an easy way to get it to show up in Kodi without searching for it. 

The only time I can think it might be an issue is when adding a tvshow and watching the pilot immediately after to decide whether to continue with it. However, in that case there is always the option to manually add the show which is done easy enough via the context menu (or later via TMDbHelper's recently watched list).

**Comment by Giel88** [comment]
Thanks a lot. So far it's working great!
