### ISSUE TITLE
TMDB lists bugs

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#363]
I found a few bugs. When I choose any tmdb list with tv shows, clearart does not appear until I refresh the details. It only happens with tmdb tv shows. Also in tmdb lists, movies and tv shows,  MPAA and run time missing. When I refresh the details everything appears. With trakt lists, everything works properly.

**Comment by jurialmunkey** [comment]
These aren't bugs. Tmdb doesn't provide this information in basic lists so the extra details need to be  called individually - the plugin has always operated this way.

Fanarttv needs a tvdb id for retrieving TV show art and a tvdb id can only be retrieved from doing a detailed lookup.

The detailed lookup takes time because it needs to be done individually for each item. So for the sake of speed I leave it to be manually retrieved. Tmdbhelper also provides a service monitor which allows skins to pull these details dynamically on the fly. Once the details are cached, next time the list opens the details will be there.

Trakt doesn't provide any details with items so I'm forced to do a lookup for trakt lists. This is why trakt lists take so much longer to load the first time.
