### ISSUE TITLE
Support players that set `xbmcplugin.setResolvedUrl`

### ISSUE THREAD

**Issue by ruinernin** [jurialmunkey/plugin.video.themoviedb.helper#37]
As this plugin has already resolved and found metadata relating to an item when an external player is called this addons should play the _ListItem_ it already has while using the playable URI returned by the external addon by way of `xbmcplugin.setResolvedUrl()`.

At the moment it "shells" out to an external script leaving all playing and metadata up to the external script.

**Comment by drinfernoo** [comment]
Essentially, you would have this plugin interface with Kodi's `Player`, rather than expecting the called add-on to do so?

**Comment by jurialmunkey** [comment]
This is an interesting idea. I wonder if there is information that is pulled from the source plugin that users would want? For instance, in the Netflix plugin the Genre info is quite different from TMDb and there is returning show information embedded in the Plot. I guess the trade-off is consistency of info vs. specialisation of info.

Also, not sure how it would affect calling the `info=play` function outside of the plugin. At the moment you can call something like `RunPlugin(plugin://plugin.video.themoviedb.helper/?info=play&query=$INFO[ListItem.Label])` which makes it possible to call the player function from an external script or plugin (e.g. you could use it to embed a button in extendedinfo or Sualfred's script.embuary.info).

The other problem is that detailed information is not necessarily filled in at the time of list creation (unless it was previously cached) - I only force the detailed info to be pulled when I call the player function and there isn't any way to pass that back to the listitem.

I'll have a play around with resolving the url instead and see how it works out.

**Comment by ruinernin** [comment]
> This is an interesting idea. I wonder if there is information that is pulled from the source plugin that users would want? For instance, in the Netflix plugin the Genre info is quite different from TMDb and there is returning show information embedded in the Plot. I guess the trade-off is consistency of info vs. specialisation of info.

It should still be possible for the external plugin to add data as I understand it from other addons.

> The other problem is that detailed information is not necessarily filled in at the time of list creation (unless it was previously cached) - I only force the detailed info to be pulled when I call the player function and there isn't any way to pass that back to the listitem.

Sure but assuming the external plugin has no data, this is still better than nothing.

I believe the metadata may be passed automatically in these cases if the flag `isPlayable` is set on the _ListItem_. I could be wrong about this though.

**Comment by jurialmunkey** [comment]
Okay, I did a few tests with setResolvedUrl.

- External plugins (e.g. Netflix) do overwrite metadata even when resolving url, so no problem there.
- HOWEVER, because isPlayable needs to be set before calling the player function, there isn't any way to know whether a resolvedurl or a folderpath will be returned. Failing to resolve a url when isPlayable is set causes a "One or more items failed to play" error dialog. This error dialog is a deal breaker because the user is presented with an error despite the plugin behaving in the correct way.

So I guess the question is - do you know any way to prevent getting the error dialog if what is returned is not a resolved url

**Comment by jurialmunkey** [comment]
@ruinernin - Can you test latest version (2.1.0) and see if it is suitable for your needs?

I'm not resolving the url but I've found a way to pass the listitem metadata to the player nonetheless, so I think this should work with you. 

I tested with a local dummy file with no metadata and it worked as expected (whilst still allowing plugins that do provide metadata to override) but I haven't tested properly with a plugin that lacks metadata.

**Comment by ruinernin** [comment]
@jurialmunkey Can confirm this works, nice! Thanks.

**Comment by L2501** [comment]
setResolvedUrl is the correct way for kodi plugin addons to play content, not this folder+xbmc.player hack

**Comment by jurialmunkey** [comment]
> 
> 
> setResolvedUrl is the correct way for kodi plugin addons to play content, not this folder+xbmc.player hack

@L2501 - That's simply not true. setResolvedUrl is *one* way for kodi plugins to play content. There are other legitimate approaches using isFolder = false, including using xbmc player:
https://forum.kodi.tv/showthread.php?tid=294840&pid=2443809#pid2443809
https://forum.kodi.tv/showthread.php?pid=2227469#pid2227469

This is a special case where xbmc player is needed because the addon being called has not yet resolved the url, so there is nothing to pass to setResolvedUrl at that point. Instead the addon being called by TMDbHelper needs to be passed to the player so that the player can then call the addon to resolve the url.

**Comment by L2501** [comment]
You are piling hacks upon hacks to to make it "work" and the result is that plugins that are written properly using setResolvedUrl are unusable. These folder plugins should fixed instead.

**Comment by jurialmunkey** [comment]
> 
> 
> You are piling hacks upon hacks to to make it "work" and the result is that plugins that are written properly using setResolvedUrl are unusable. These folder plugins should be fixed instead.

Can you point me to a plugin using setResolvedUrl that doesn't work?
