### ISSUE TITLE
Unable to update library tv shows from Trakt list

### ISSUE THREAD

**Issue by spursgalea** [jurialmunkey/plugin.video.themoviedb.helper#370]
#First of thank you for the fix for my last issue.i have discovered nother one.i can update my trakt movies list but not my tv shows .I don't understand why this happing. It's also frustrating because it's a great add-on on use here's my log https://pastebin.com/hWzjFXdw
.ps I have logged out logged of Trakt

**Comment by drinfernoo** [comment]
Update. You're running an older version from before this bug was already fixed.

**Comment by spursgalea** [comment]
I downloaded a kodi fork so I don't lose any of my stuff.i made sure I was on the latest version. Yes my log if needed
https://pastebin.com/XJBzmCJ
![Screenshot_20201119-053841_WBMC 189](https://user-images.githubusercontent.com/17916354/99626756-cd857280-2a2a-11eb-8efd-acf87744dc21.jpg)

**Comment by jurialmunkey** [comment]
Please get me the library updater logs from
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/*.json`

They will be listed as the date and time the update occurred.

**Comment by spursgalea** [comment]
https://pastebin.com/SjGTsYN9 I hope it helps

**Comment by jurialmunkey** [comment]
Log shows that you already added the shows previously, so they have been skipped from being updated. TMDbHelper will skip any shows that you previously added and aren't currently airing because there is no point updating them.

If you deleted the strm files after adding the shows, you can force a show to be readded by adding it to the library individually from the context menu. 

With the latest version I just pushed, selecting "-Update library now" from TMDbHelper settings will force all items from your monitored lists to be re-added.

**Comment by spursgalea** [comment]
Ok thanks
