### ISSUE TITLE
[Feature Request] Consolidated Search Shortcut Section In Addon

### ISSUE THREAD

**Issue by LN13uLL** [jurialmunkey/plugin.video.themoviedb.helper#377]
Hi, there's a search shortcut in the addon within Movies, TV Shows, and People.  Would it be possible to have a new section called search?

Then under Search section, have a shortcut for Movies search, TV Shows search, and People Search?  Hope that is doable.

Example:

Current structure:

Movies
     - Search
     - Popular
     - Top Rated
     - ....(and so on)
TV Shows
     - Search
     - Popular
     - Top Rated
     - ....(and so on) 
People
     - Search
     - Popular
     - Trending Today
     - ....(and so on)
....(and so on)

Proposed structure request:

Same as above, but have a new section called Search.  This would allow me and people create one shortcut as a category/submenu item for search instead of three items.

Search
     - Movies
     - TV Shows
     - People
     - [search history results shows here]
     - Clear Movies Search History
     - Clear TV Shows Search History
     - Clear People Search History
     - Clear All Search History

**Comment by drinfernoo** [comment]
Use a hub, maybe?

**Comment by LN13uLL** [comment]
I’m currently using the aura skin so it doesn’t have a search built in that I could find. I could use hub/submenu but I would have to create one for each type of search since it’s in movies, tv shows, and people. If there’s a search section I can make it just one button

**Comment by drinfernoo** [comment]
Ah, my mistake... I thought this was an issue on one of the skins 😅 Carry on!

**Comment by jurialmunkey** [comment]
Yeah I actually think that this is a good idea. Particularly since I'm planning on bringing in TMDb's other search endpoints (companies, collections, keywords, multi), so this subfolder will give a good place to house those too.

Basic functionality was enough to implement - should be working on latest master.

**Comment by LN13uLL** [comment]
You are way too awesome, @jurialmunkey ! :)

Just tested it out! Works perfectly!!!! 👍🏼👍🏼

Thank you!! Looking forward to other searching points.

**Comment by jurialmunkey** [comment]
Also FYI - Currently the search history for each content type is kept in a separate list and the combined search history just interleaves the list (e.g. 1st movie search, 1st tv search, 1st person search, 2nd movie search etc.). I didn't have the foresight to include timestamps so the only possibilities are either that or just grouping each type one after the other (e.g. all movie searches, then all tv searches, then all person searches).

I'll eventually fix it up to include timestamps (which will reset history for everyone due to the format change) so that we get true ordering of the history but for the time being I figure interleaved is moderately better than grouped (though neither is really ideal for the purpose here).

**Comment by LN13uLL** [comment]
Thanks for the update. I noticed that. It works for me for now :-).
