### ISSUE TITLE
Search engine for trakt

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#384]
Is it possible to get a search engine only for trakt as we have a search engine only for tmdb?

**Comment by jurialmunkey** [comment]
What purpose would that serve? All the data about the items ultimately comes from TMDb because Trakt API only provides minimal metadata - lists from Trakat are basically just a list of IDs that then need to be looked up on other services.

**Comment by matke-84** [comment]
Some of us use trakt lists and have accounts on the same. If there is a trakt already separate it is logical that it has the ability to search as it has tmdb lists. If I have already created my own trakt lists, it is not always easy to search for a movie manually.

**Comment by drinfernoo** [comment]
@matke-84 You can see Trakt Lists from inside TMDbHelper already 🤔

**Comment by matke-84** [comment]
@drinfernoo I know. I'm talking about the search. Isn’t it easier to type name of a movie or tv show than to go looking manually through the lists? I say again, if there is search for tmdb lists logically it should be search for trakt lists as well.

**Comment by drinfernoo** [comment]
Are you searching for things that aren't on TMDb, but *are* on Trakt? Because simply searching by name should certainly be simpler than having to remember which search engine to use as well?

**Comment by matke-84** [comment]
Yes, I want to search some things, my lists, which are on the trakt, on my account. I still don't understand why the trakt is singled out if I don't have this basic search function? When I enter the tmdb helper, in trakt list, the first thing that should stand is the search. But if the creator of this still fantastic addon doesn't think it's necessary, then I'm writing all this for nothing. My opinion is that it should exist.

**Comment by drinfernoo** [comment]
@matke-84 Just because they're on Trakt doesn't mean you can't search them with this addon, though... This already does "compile" metadata from both services already, by taking certain data from one that isn't available from the other, and vice versa.

To top it all off, this is completely transparent to the user... meaning that no matter which service you try to search directly, the add-on will end up reporting the same items with likely very minimal differences in metadata or results.

**Comment by jurialmunkey** [comment]
Why can you just search for the item you are looking for using the standard search function already in the addon?

If you want to watch say Star Wars, you're not going to get different results by searching Trakt. In fact the end result will be the same because ultimately all the metadata you see comes from TMDb anyway.

I'm still not understanding exactly what you want to search for on Trakt that you can't already search for using the standard search function in the addon. Give me an example of what you're trying to achieve.

**Comment by matke-84** [comment]
OK. If I watch a movie or TV show that is on the tmdb list, will it appear on my tract account as watched?

**Comment by jurialmunkey** [comment]
> 
> 
> OK. If I watch a movie or TV show that is on the tmdb list, will it appear on my tract account as watched?

It makes no difference whether the item is from a Trakt list or a TMDb list. TMDbHelper doesn't play anything itself. TMDbHelper player files are just a set of rules that tells it how to search for an item on an external plugin and then the plugin in question is told to play the item if a match is found. Syncing of playback progress to Trakt is entirely dependent on that end plugin because ultimately it is the end plugin which is giving the playable file to Kodi.

For instance, say you click on an episode of Stranger Things in TMDbHelper and choose Play with Netflix. What TMDbHelper does is opens the Netflix plugin's search function and passes the TV Show Title to the keyboard. It then looks for the best matching item in the results and clicks on it, then it clicks on the matching season, and then clicks on the matching episode. Playing something via TMDbHelper is basically just a way to automate the search process so you don't have to physically go into each plugin and click on things to play with different plugins -- instead TMDbHelper does all that in the background.

**Comment by matke-84** [comment]
Hey, I see you put a list search in trakt. However, I don't understand exactly which lists searches, so if you can explain to me. 
And now that we’ve got a search in the trakt I hope we’ll be able to search movies and tv shows individually. If we get that, we go for a beer. And not only one... ;-)

**Comment by drinfernoo** [comment]
I'm so confused here... hasn't this add-on *always* had the ability to search individual movies and TV shows? 🤔

**Comment by matke-84** [comment]
Themoviedb helper has tmdb lists and trakt lists. The reason why the search for the trakt list is important to me is because I only use the trakt lists in the tmdb helper, not the tmdb lists. There are several reasons for this. The most important thing is that I have been using the trakt account for a while. I also use skins that work better with trakt lists... But I've said all this before. But since I saw that some search was done, I hoped that we would get a full search for movies and tv shows but in trakt part of tmdb helper. :-)

**Comment by jurialmunkey** [comment]
I keep telling you it makes absolutely no difference which part of the addon you search items from because ultimately all the metadata about the item comes from TMDb.

**Comment by drinfernoo** [comment]
@matke-84 Your request was fulfilled before you opened the issue.

**Comment by drinfernoo** [comment]
@jurialmunkey I think he just wants a "search" shortcut *in* the Trakt menu?

**Comment by matke-84** [comment]
@jurialmunkey When we talk about tmdb lists, I miss clearlogo, movies runtime and MPAA. I know this is up to skins that don't have a tmdb helper monitor implemented in the skin. But trakt doesn't provide any details with items  so you forced to do a lookup for trakt lists and because of that I get everything right. It loads everything slowly, but for me it's not a big problem. One of the reasons why I use trakt lists. But let's get this over with. I still think this is a fantastic addon and I will use it anyway. I wish you all the best and keep doing such a good job.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey When we talk about tmdb lists, I miss clearlogo, movies runtime and MPAA. I know this is up to skins that don't have a tmdb helper monitor implemented in the skin. But trakt doesn't provide any details with items so you forced to do a lookup for trakt lists and because of that I get everything right. It loads everything slowly, but for me it's not a big problem. One of the reasons why I use trakt lists. But let's get this over with. I still think this is a fantastic addon and I will use it anyway. I wish you all the best and keep doing such a good job.

So really you are asking for an entirely separate feature which is force all details to load.

**Comment by matke-84** [comment]
@jurialmunkey  Unfortunately, there are skins that are abandoned, and some skinners do not want or do not know how to implement a tmdb helper monitor. Without a monitor, it is difficult to get all the data automatically, and you only enabled that in the trakt. Skins without all that stuff look completely pointless. But like I said I will continue to use this great addon no matter what. I respect you as much as your work, so I wouldn't want to bother you anymore.
