### ISSUE TITLE
potential bug + feature request

### ISSUE THREAD

**Issue by ricinga666** [jurialmunkey/plugin.video.themoviedb.helper#391]
Now I've got over my issue with getting my list added to the library. So far I've been pretty impressed by the addon. However, I have a strange issue.

I've set unaired episodes to not show but random shows pop up with the first episode.  as an example, Loki episode 1 shows up in my library as does manifest season 3 episode 1. Also, have a few more on top of these. examples. 

Other Shows like the Mandalorian for example show the latest episode and next weeks is not yet listed which is as expected..

Feature request.  I often add old shows that I want to rewatch to my list and would love it if the dated added to the library was the airdate and not the date it was physically added.   

I use the recently added function of the library a lot to keep track of new episodes.

regards Richard

**Comment by jurialmunkey** [comment]
> I've set unaired episodes to not show but random shows pop up with the first episode. as an example, Loki episode 1 shows up in my library as does manifest season 3 episode 1. Also, have a few more on top of these. examples.

If there is an episode listed on TMDb but it has no air date then it isn't ignored because it is impossible to tell if it is actually a future episode or it is simply because someone hasn't added the air data (otherwise we end up with the reverse issue where episodes are hidden that shouldn't be just because they don't have airdate data).

For instance, with Manifest S03E01 you can see on TMDb there is a dummy item added with no information:
https://www.themoviedb.org/tv/79696-manifest/season/3/episode/1

There's not really any good way to deal with these unfortunately (other than updating TMDb itself with better air date data about the shows). I find it is generally better to be cautious and show the episodes without airdates rather than hide them.

> Feature request. I often add old shows that I want to rewatch to my list and would love it if the dated added to the library was the airdate and not the date it was physically added.

Not really something that can be done from the plugin side. All TMDbHelper does is create `.strm` file which is essentially a shortcut that acts like a video file but runs the player function instead. What metadata is added in the library is all handled by the library scraper and Kodi itself.

What you want to do is create a Smart Playlist (Videos > Playlists > New Smart Playlist) with the following settings:
Type = Episodes; Order by = Year; Sort Direction = Descending.

That will give you a list of episodes with newest airing episodes at the front.

![Honeyview_screenshot299](https://user-images.githubusercontent.com/4618719/101319674-77338300-38b6-11eb-8e8a-e9f090434b6c.jpg)

**Comment by ricinga666** [comment]
Thanks, I thought it might be possible as prior to removing the library integration fen had this feature and also didn't add these episodes to the library.

**Comment by mathu204** [comment]
> > I've set unaired episodes to not show but random shows pop up with the first episode. as an example, Loki episode 1 shows up in my library as does manifest season 3 episode 1. Also, have a few more on top of these. examples.
> 
> If there is an episode listed on TMDb but it has no air date then it isn't ignored because it is impossible to tell if it is actually a future episode or it is simply because someone hasn't added the air data (otherwise we end up with the reverse issue where episodes are hidden that shouldn't be just because they don't have airdate data).
> 
> For instance, with Manifest S03E01 you can see on TMDb there is a dummy item added with no information:
> https://www.themoviedb.org/tv/79696-manifest/season/3/episode/1
> 
> There's not really any good way to deal with these unfortunately (other than updating TMDb itself with better air date data about the shows). I find it is generally better to be cautious and show the episodes without airdates rather than hide them.
> 
> > Feature request. I often add old shows that I want to rewatch to my list and would love it if the dated added to the library was the airdate and not the date it was physically added.
> 
> Not really something that can be done from the plugin side. All TMDbHelper does is create `.strm` file which is essentially a shortcut that acts like a video file but runs the player function instead. What metadata is added in the library is all handled by the library scraper and Kodi itself.
> 
> What you want to do is create a Smart Playlist (Videos > Playlists > New Smart Playlist) with the following settings:
> Type = Episodes; Order by = Year; Sort Direction = Descending.
> 
> That will give you a list of episodes with newest airing episodes at the front.
> 
> ![Honeyview_screenshot299](https://user-images.githubusercontent.com/4618719/101319674-77338300-38b6-11eb-8e8a-e9f090434b6c.jpg)

I was gonna make a post about this, is there a command or something somewhat easy I can do on my end to make TMDBHelper not add episodes without release dates? 

Would you consider adding a setting like "No new episodes beyond last release date" where episodes without a release date past the most recent episode with release date data dont get added? I kinda worded this shitty so heres an example of what I mean. Say

The Mandalorian S2
E1 - 2020/01
E2 - 2020/02
E3 - 
E4 -
E5 - 2020/05
E6 - 2020/08
E7 -
E8 - 2020/09

S3
E1 - 

All the episodes up to S2 E8 would get added as that is the last episode that has a release date.

Also I just manually added a release date to episode 1 of Loki on TMDB, would TMDBHelper remove this file after an update when the date is updated to the TMDB database or whatnot, or would this episode only not get added when there is no existing folder already with that episode in there. I assume its the latter but kinda hope it can be the former.

**Comment by jurialmunkey** [comment]
> Would you consider adding a setting like "No new episodes beyond last release date" where episodes without a release date past the most recent episode with release date data dont get added?

I've never come across a scenario where that would be useful. The issue isn't that random episodes are missing air dates, the issue is that entire seasons or even entire shows sometimes don't have _any_ release date data at all - so those would be missed regardless.

> Also I just manually added a release date to episode 1 of Loki on TMDB, would TMDBHelper remove this file after an update when the date is updated to the TMDB database or whatnot, or would this episode only not get added when there is no existing folder already with that episode in there. I assume its the latter but kinda hope it can be the former.

TMDbH never deletes any files from library folders ever. It's too dangerous with all the different types of setups that people might have. It is also generally a bad to delete files automatically on the basis of information downloaded off the internet from a website that anyone can edit...

> Is there like a TBA flag I can add on TMDB in replace of a date when its unknown so that its both shown that the airdate is not known yet rather than nothing, and 2 will not be added to library through TMDBHelper when it detects this? If not maybe I can/should make a request for this on TMDB's site.

I don't think there is. I'm pretty sure that their guidelines state that placeholders shouldn't be added, so there shouldn't ever be "TBA" episodes on the website really -- I'm pretty sure episodes are only _supposed_ to be added once there is release date.

**Comment by mathu204** [comment]
> > Would you consider adding a setting like "No new episodes beyond last release date" where episodes without a release date past the most recent episode with release date data dont get added?
> 
> I've never come across a scenario where that would be useful. The issue isn't that random episodes are missing air dates, the issue is that entire seasons or even entire shows sometimes don't have _any_ release date data at all - so those would be missed regardless.
> 
> > Also I just manually added a release date to episode 1 of Loki on TMDB, would TMDBHelper remove this file after an update when the date is updated to the TMDB database or whatnot, or would this episode only not get added when there is no existing folder already with that episode in there. I assume its the latter but kinda hope it can be the former.
> 
> TMDbH never deletes any files from library folders ever. It's too dangerous with all the different types of setups that people might have. It is also generally a bad to delete files automatically on the basis of information downloaded off the internet from a website that anyone can edit...
> 
> > Is there like a TBA flag I can add on TMDB in replace of a date when its unknown so that its both shown that the airdate is not known yet rather than nothing, and 2 will not be added to library through TMDBHelper when it detects this? If not maybe I can/should make a request for this on TMDB's site.
> 
> I don't think there is. I'm pretty sure that their guidelines state that placeholders shouldn't be added, so there shouldn't ever be "TBA" episodes on the website really -- I'm pretty sure episodes are only _supposed_ to be added once there is release date.
> 
> EDIT: See the guidelines here:
> https://www.themoviedb.org/bible/tv/59f743289251416e71000037#59f7445c9251416e71000038
> 
> They specifically say "Blank episodes (with a missing title and/or air date) should be avoided. Please wait until the info is officially released". The only exception is for the first episode of the next season because it might not be known until very close to the air date.

Hey jurial so you said if the episodes DO have release dates, and they are beyond the date I added them of, (ex today is 01-07 anything 08 and beyond shouldnt be added), right? I added Re Zero to the library and all the episodes past S2E14, have release dates so it shouldnt be added but they were still added. Is it because I added the show to library through the context menu and it only works for lists? If so do u think it can be extended to the "Add to Library" context menu method? Or am i facing a bug?
