### ISSUE TITLE
In Progress widget shows watched items

### ISSUE THREAD

**Issue by naudski** [jurialmunkey/plugin.video.themoviedb.helper#394]
Hi Jurialmunkey!

I noticed that in movies the tmdbhelper In Progress widget in Auramod shows watched items. I have the option "hide watched items on widgets" selected in tmdbhelper.
In tvshows by the way it is working. I see indicators of episodes left to see and watched items are hidden.
I'm using tmdbhelper 4.0.77 and Leia 18.9

**Comment by naudski** [comment]
I think I figured it out. If I mark a movie as watched in the context menu it does not work. But when I open the context menu and select Trakt Options and then mark it as watched it works.
Is there a difference between these mark as watched options?

**Comment by jurialmunkey** [comment]
"Mark as watched" is an inbuilt kodi function that marks locally (ie inside kodi only) for that specific item in that specific list - ie it doesn't mark the movie itself as watched, instead it is marking the listitem "shortcut". There is no way for a plugin to remove this context item or control what it does. 

Tmdbhelper only uses watched status from Trakt to determine if something is watched. Using the watched status of the local item makes no sense since we aren't even playing that item directly but are instead calling another plugin to play a different item based on the info - ie we ask to play same movie but to kodi they look like separate items because they're from separate plugins and the end url used to play will be different depending on the plugin and source etc. 

So the only approach that makes sense is to use Trakt because at least that way we can retrieve the watched status regardless of which plugin was used to play (as long as the plugin in question works with trakt).

Itd be less of an issue if plugins all worked with setresolvedurl because that actually passes watched/resume etc between the two. Unfortunately however many plugins rely on calling the kodi video player directly so local watched status is practically useless. The frustrating thing from my perspective is that Kodi gives no way to override what the function does or trigger something else along with it.

**Comment by jurialmunkey** [comment]
Oh also more specific to the issue here - kodi only applies the local watched status *after* the plugin creates the items, so there's no way to hide the item based on local watched status since the directory of items was already made and the plugin code finished. So the only option for hiding watched is if the info is available via Trakt.
