### ISSUE TITLE
[Bug] XBMCVFS Error when adding shows but shows are still added correctly

### ISSUE THREAD

**Issue by mathu204** [jurialmunkey/plugin.video.themoviedb.helper#396]
This error shows up when adding shows, i havent tried individually but i synced a watchlist to my shows and this error comes for each show so I cant just let it sit back and add. Its not a super big deal but thought I would bring it to your attention, since its not a real error (the shows still add and work/play correctly)

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5700447/kodi.log)

**Comment by jurialmunkey** [comment]
Turn off folder creation checks in tmdbhelper settings.

**Comment by mathu204** [comment]
Alright, does turning this off still keep it so TMDBHelper doesn’t make duplicates ?

**Comment by jurialmunkey** [comment]
Nothing to do with duplicate checking. 

The error refers to a check where after the folder is created we need to make sure it actually exists (ie it was created successfully) before attempting to write to it. 

For some reason on some systems xbmcvfs reports that the folder doesn't exist after creation even though clearly it does (we can see it on disk and clearly we are capable of writing to it). So the error is reporting that the xbmcvfs file system is saying the folder we are trying to write to doesn't exist. Since we know that the folders are being created and we can write to it, we have a setting to skip that checks and just write blindly to the folder under the assumption it was created successfully. 

It is just a weird quirk of xbmcvfs on some Android systems. On Windows and Linux the checks work properly. I could use a more direct method of writing but xbmcvfs is a safer approach so I use that.

**Comment by mathu204** [comment]
> Nothing to do with duplicate checking.
> 
> The error refers to a check where after the folder is created we need to make sure it actually exists (ie it was created successfully) before attempting to write to it.
> 
> For some reason on some systems xbmcvfs reports that the folder doesn't exist after creation even though clearly it does (we can see it on disk and clearly we are capable of writing to it). So the error is reporting that the xbmcvfs file system is saying the folder we are trying to write to doesn't exist. Since we know that the folders are being created and we can write to it, we have a setting to skip that checks and just write blindly to the folder under the assumption it was created successfully.
> 
> It is just a weird quirk of xbmcvfs on some Android systems. On Windows and Linux the checks work properly. I could use a more direct method of writing but xbmcvfs is a safer approach so I use that.

Oh that is strange bc I’m getting this error on Windows but regardless I’ll just disable it since it works, it does not make a difference to me. In the case the folder is not there and I have this checked, would tmdb helper just make the folder and re add everything?

**Comment by jurialmunkey** [comment]
> Oh that is strange bc I’m getting this error on Windows but regardless I’ll just disable it since it works, it does not make a difference to me.

Sorry, I was mis-remembering the original issue as only being reported on Android, but I went back to look at the original issue (way back at start of year) and there were reports for Windows too.

> In the case the folder is not there and I have this checked, would tmdb helper just make the folder and re add everything?

You're misunderstanding the issue.

This error is because the builtin Kodi function used to *make* the folder on disk - `xbmcvfs.mkdirs(path)` - incorrectly reports on some systems that it wasn't able to make a new folder. So all the setting does is tell TMDbHelper to ignore whatever xbmcvfs.mkdirs says and instead assume that it made the folder even if it says that it wasn't able to.

It's basically the difference between only going shopping if your bank balance says you have money versus going shopping even if your balance is $0 because it is payday so you know there is money in there but your bank app is just a bit delayed in showing new deposits.

The override is relatively safe. Even if mkdirs *did* actually fail to make the folder, you can't write to a non-existent folder. Instead, trying to do that would raise and exception and the script would stop with an error notification (similar to going to the shop and having your card be declined). Since it is something related to the filesystem, I err on the side of caution and leave it up to the user to take responsibility for overriding the check.

**Comment by mathu204** [comment]
> > Oh that is strange bc I’m getting this error on Windows but regardless I’ll just disable it since it works, it does not make a difference to me.
> 
> Sorry, I was mis-remembering the original issue as only being reported on Android, but I went back to look at the original issue (way back at start of year) and there were reports for Windows too.
> 
> > In the case the folder is not there and I have this checked, would tmdb helper just make the folder and re add everything?
> 
> You're misunderstanding the issue.
> 
> This error is because the builtin Kodi function used to _make_ the folder on disk - `xbmcvfs.mkdirs(path)` - incorrectly reports on some systems that it wasn't able to make a new folder. So all the setting does is tell TMDbHelper to ignore whatever xbmcvfs.mkdirs says and instead assume that it made the folder even if it says that it wasn't able to.
> 
> It's basically the difference between only going shopping if your bank balance says you have money versus going shopping even if your balance is $0 because it is payday so you know there is money in there but your bank app is just a bit delayed in showing new deposits.
> 
> The override is relatively safe. Even if mkdirs _did_ actually fail to make the folder, you can't write to a non-existent folder. Instead, trying to do that would raise an exception and the script would stop with an error notification (similar to going to the shop and having your card be declined). However, since it is something related to the filesystem, I err on the side of caution and leave it up to the user to take responsibility for overriding the check.

Ah I see, thanks for the explanation then.
