### ISSUE TITLE
[Request] Season Artwork

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#4]
As the title says 😉

**Comment by jurialmunkey** [comment]
I'm not sure exactly what you're requesting ???

**Comment by drinfernoo** [comment]
You can see each artwork item for movies, shows, and even episodes, but it doesn't seem like you can see the artwork returned for individual seasons... Does that make sense? My bad 😬

**Comment by jurialmunkey** [comment]
Do you mean in the browser how you have these options for the detailed item?
![Honeyview_screenshot395](https://user-images.githubusercontent.com/4618719/63218657-a0507180-c1a2-11e9-920d-f8f6581f07d6.jpg)

I would have to have an additional seasons details landing page between show and episodes.
e.g. Tvshows List > Tvshow Details > Seasons List > **Season Details** > Episodes List > Episode Details

I guess that makes sense as a point of consistency. I just thought perhaps users would want to go straight to the episodes when clicking a season rather than having an additional details page in-between.

**Comment by drinfernoo** [comment]
I was thinking about that as a drawback as well... maybe under the show itself have a section for "season artwork"? And then inside that it would show each season as a subsection, with the artwork inside?

I guess the add-on is meant less for browsing directly, and more for the endpoints to be used in the info dialog?

**Comment by jurialmunkey** [comment]
I think both aspects are important. The browsing experience has to work well so that the plugin paths can be used as widgets. 

This approach is also a possibility. The main drawback is that it will require it's own unique function rather than using an existing approach. Not the end of the world, just not as neat code wise as the details landing page.

I'll have more of a think about what approach would work best and get back to you.

**Comment by drinfernoo** [comment]
My other idea (I could open another issue 🤣) was to maybe have the ability to just open info directly when you choose a movie/show/episode item, instead of taking you into the add-on itself. That would especially make widgets a bit easier to use, in my opinion.

**Comment by jurialmunkey** [comment]
> 
> 
> My other idea (I could open another issue 🤣) was to maybe have the ability to just open info directly when you choose a movie/show/episode item, instead of taking you into the add-on itself. That would especially make widgets a bit easier to use, in my opinion.

You should already be able to open the info dialog by pressing info on a widget item. If you don't have an info button, you can do long-press ok to open context menu and then choose "Information".

If I change the onclick behaviour then it will break the browser functionality. Plus, I'd rather skinners decide how to handle widget onclick actions instead of the addon/user forcing it upon them.

If I make it optional in the addon (either as a setting or an extra path param), then it makes the onclick behaviour unpredictable - skinners won't know if the default onclick action will open the browser or the info dialog without using additional checks. Having standardised onclick behaviours gives skinners much more control.

Plus, if onclick opened the info dialog directly, the detailed info would not be loaded (unless it was previously cached). Requesting detailed info for each item in the list is not feasible because it will result in hundreds of additional api calls. And the extra detailed info can't be added after an onclick action because an onclick essentially creates a new plugin instance and so can't access objects from the previous instance.

**Comment by drinfernoo** [comment]
That's all totally fair! Makes sense to me 😉

**Comment by jurialmunkey** [comment]
On that note, I just pushed an update to AZ2 that will open the info page for themoviedb helper widgets.

**Comment by drinfernoo** [comment]
Is that a setting or default? Either way, I should be able to push it to the repo tomorrow morning.

**Comment by jurialmunkey** [comment]
Default. Makes TMDb Helper homescreen widgets have same behaviour as they do in the info dialog.

Also, no rush! Whenever you have the time.
