### ISSUE TITLE
Incorrect API queries for certain shows?

### ISSUE THREAD

**Issue by stuoningur** [jurialmunkey/plugin.video.themoviedb.helper#40]
Hi,
I saw that for certain shows like The Witcher or as in the included log Lost in Space the API Query is getting a 404, other shows seem fine so far.

[https://pastebin.com/sqFt9Sz9](https://pastebin.com/sqFt9Sz9)

Thanks!

**Comment by drinfernoo** [comment]
Seems like your API key was mistyped in settings to me, as I'm able to view The Witcher *and* Lost in Space with both the default key and my own.

**Comment by stuoningur** [comment]
Maybe it's an issue how seren reports the info to tmdb helper. Opening the show directly via the addon works fine as well.

**Comment by jurialmunkey** [comment]
Please don't use a personal API key for TMDb. It is completely unnecessary and the option only exists for the sake of future-proofing.

**Comment by jurialmunkey** [comment]
The 404 is because your query title has the year in the title e.g. `Lost in Space (2018)` and there is no such tvshow called `Lost in Space (2018)`. The tvshow is called `Lost in Space`.

You need to pass `&query=Lost in Space&year=2018` to find this show correctly.

Either the skin you are using is passing `ListItem.Label` instead of `ListItem.TvShowTitle` to the query param, or the addon you are using is unnecessarily appending the year to the tvshowtitle. 

I really wish all these addons wouldn't do this type of thing where they force their design choices on skins by appending unnecessary info and/or colours that pollute the infolabels and make them unusable for other purposes. There is already a `ListItem.Year` - why can't addon authors just fucking use that instead of forcing it into `ListItem.Title` for fucks sake.

**Comment by jurialmunkey** [comment]
Looking at the TVDb api, it seems that they add the year to the title if there was a previous series with the same title. Really annoying that they do that - further confirms my decision not to use TVDb.

**Comment by drinfernoo** [comment]
@jurialmunkey Yes, this helps with shows that have since been remade, like [Cosmos](https://thetvdb.com/series/cosmos) and [Cosmos (2014)](https://thetvdb.com/series/cosmos-a-spacetime-odyssey), for example.

**Comment by jurialmunkey** [comment]
@drinfernoo - It's not necessary to add the year to the title though. There is a specific field for year which should be used. Further, the whole reason why we have `Label` *and* `Title` is to allow a modified label whilst keeping `Title` clean.

For instance, in Episode 1 ("Impact") of new Lost in Space, the infolabels should be:
`Label` = `1x01 - Impact` or `Impact` (addon's choice)
`Title` = `Impact`
`TvShowTitle` = `Lost in Space`
`Year` = `2018`
`Episode` = `1`
`Season` = `1`

And at tvshow level the info labels should be:
`Label` = `Lost in Space (2018)` or `Lost in Space` (addon's choice)
`Title` = `Lost in Space`
`TvShowTitle` = `Lost in Space`
`Year` = `2018`

Also, TVDb changes which show gets year appended depending on popularity. For instance:
`The Witcher (2002)` [Original]
`The Witcher` [New]
`Lost in Space` [Original]
`Lost in Space (2018)` [New]

**Comment by jurialmunkey** [comment]
Whilst both TVDb and TMDb show the the year with the title on the website to distinguish between reboots and originals, the important difference is that TMDb correctly splits these into separate fields when returning a request from the API and TVDb does not.

It would be fine if TVDb added the year to *all* titles because then we could split the string with confidence. The issue is that it is only added to some titles and so we are forced to guess whether or not something added in parentheses at the end is indeed the year and not some other important info.

**Comment by jurialmunkey** [comment]
Either way, I'm now scrubbing all details in parentheses from query strings because of this shit approach of adding the Year to the Title field. We just have to hope that there aren't any legitimate titles with parentheses in their name now...

**Comment by jurialmunkey** [comment]
@stuoningur - Can you test latest and confirm that the query string scrubbing is working correctly for you and you are now getting results for these.

**Comment by stuoningur** [comment]
Tested and confirmed it working.

Also if it helps as additional info, I am using auramod as a skin.
