### ISSUE TITLE
[Request] Enable all details in TMDB lists

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#403]
@jurialmunkey Now that we have gained speed, I think that there is no reason for some information to be excluded from TMDB lists, such as movie time duration, mpaa, raitings... but also integrate fanarts for tmdb movies and tv shows lists such as clearlogo, clearart, cdarts... of course with the possibility that they can be excluded as for the trakt list. You mentioned that the metadata itself doesn't affect on performance so much, and as fanarts are concerned, whoever wants can turn them on, they are certainly turned off by default.
P.S. I asked a question in the previous topic that you closed, so I don't know if you have a habit to read old posts, and I think it's maybe is better to go as a new topic or request.

**Comment by jurialmunkey** [comment]
I do read comments in closed issues but yes I prefer a new thread per feature/bug as it makes things easier to reference and keep track of.

You can already enable fanart TV for TMDb lists. The option is global and applies to every list.

I will add an option for detailed metadata in TMDb but there will be a performance cost as details need to be retrieved on a per item basis (whereas the basic details TMDB provides in the same request as the list itself, which is why it isuch faster).

**Comment by matke-84** [comment]
@jurialmunkey I don't know if you know, but for tmdb lists, not everything works properly as fanarts are concerned. Tv shows doesn't get clearlogs at all, I know that for sure, that's why I asked, I'll check for other fanarts, so I'll let you know. For movies, I think it works almost everything, but I'll check that out too.

Well, I think from everything you wrote to me in the previous post, that the difference will be very small. Considering that we can gain acceleration, I think it will be almost invisible in that case.

I’m here for testing and every other kind of help. ;-)

**Comment by matke-84** [comment]
@jurialmunkey I tested tmdb helper with a few skins (and with your skin Artic Horizon). Clearlogos, cleararts... don't work with tv shows. To be more precise, it doesn't pull them automatically. I have to refresh the details to get fanarts. This only happens with tv shows and only in tmdb lists. With movies all fanarts that I noticed works as it should.

**Comment by mathu204** [comment]
> @jurialmunkey I tested tmdb helper with a few skins (and with your skin Artic Horizon, my default is titan bingie mod). Clearlogos, cleararts... don't work with tv shows. To be more precise, it doesn't pull them automatically. I have to refresh the details to get fanarts. This only happens with tv shows and only in tmdb lists. With movies all fanarts that I noticed works as it should.

This one is due to Titan Bingie Mod not supporting TMDBHelper completely, but it is being worked on

**Comment by matke-84** [comment]
@mathu204 Fanarts (clearlogos, clearts, cdarts...) for Tv shows doesn’t work on any skins I’ve tried.

**Comment by jurialmunkey** [comment]
>Fanarts (clearlogos, clearts, cdarts...) for Tv shows doesn’t work on any skins I’ve tried.

It is because Fanart.TV _only_ accepts a TVDb ID for TvShows (not a TMDb ID) so it isn't possible to retrieve additional artwork without first retrieving the details.

You can see this in action by choosing `Context Menu > Refresh Details` and the list will reload and you will now see the artwork it downloads.

This is why TMDbHelper ships a Service Monitor similar to Skin Helper so that these types of details can be retrieved on the fly. Support for the Service Monitor is what mathu204 would be referring to.

**Comment by matke-84** [comment]
@jurialmunkey So fanarts for tv shows in tmdb lists can only be obtained if a service monitor is implemented in skin itself, unlike tv shows that are obtained via trakt lists that are obtained automatically? I thought the principle was the same because it's a bit tricky then there are skins that no longer have support, but also those whose creators do not want to insert a service monitor or do not even know how to do it. But in this way the hope remains that the guys working on the titanium bingi mode skin will be able to implement the service monitor. That would be a great combination. I hope maybe some of your cooperation. That would be a great combination. One of the best skins and addons for kodi on one place. It would be awesome. :-)

**Comment by jurialmunkey** [comment]
> So fanarts for tv shows in tmdb lists can only be obtained if a service monitor is implemented in skin itself, unlike tv shows that are obtained via trakt lists that are obtained automatically?

No. You can also refresh the details for the item via the context menu. The TVdb ID is in the details request and thus the fanart tv lookup can be done once we have TVdb.

The reason why it works with Trakt is because I already need to do a full metadata lookup for each item since Trakt doesn't give any metadata itself, so we already have the ID from the details request.

Once I implement the option to do the full details request for TMDb lists, you will see that the fanarttv request will also work because you will then have a TVdb ID for each item.

**Comment by matke-84** [comment]
@jurialmunkey Thanks for the detailed answer. I'm waiting for a new update with full details request option.
I wish you a Happy New Year. All the best in life and keep doing such a good things as tmdb helper. All the best. ;-)

**Comment by jurialmunkey** [comment]
@matke-84 - FanartTV should work for TMDb lists now on latest version (v4.2.1). Basically if you have Fanart TV enabled it will automatically also download the detailed metadata. 

I'll add some more granular options later -- Since some requests depend on other requests, I'll need to have a bit of a think about how best to reorganise the settings to accommodate. However, for now if Fanart TV is turned on it should work for all lists and pull in all data, which is what I expect the general majority would be wanting with that enabled anyway.

**Comment by matke-84** [comment]
@jurialmunkey It works fantastically. Thanks a lot. That is why this addon is one of the best, because the suggestions and criticisms of end users are listened to. It is in the interest of all of us to make it as good as possible. Thank you again for everything you do. I look forward to the next updates and improvements.

**Comment by matke-84** [comment]
@jurialmunkey I noticed a small bug with a clearlogos. When I enter in the tv shows season, clearlogo appears only on specials and episode group and only very rarely in some ordinary season. It happens in all skins, in tmdb and trakt list, even in your artic horizons. Can you check what this is about. For example, there is no such problem in the elementum. Thank you in advance.
Specials season-appears clearlogo
![Screenshot_20210103-104803](https://user-images.githubusercontent.com/74268331/103475897-8cb2a480-4db1-11eb-9357-772f47d4136e.png)
Normal season-no clearlogo
![Screenshot_20210103-104750](https://user-images.githubusercontent.com/74268331/103475907-a227ce80-4db1-11eb-9c98-828252339a9c.png)
Season 1-appears clearlogo
![Screenshot_20210103-104843](https://user-images.githubusercontent.com/74268331/103475911-ac49cd00-4db1-11eb-8fe9-c211f8037eea.png)
Season 2-no clearlogo
![Screenshot_20210103-104850](https://user-images.githubusercontent.com/74268331/103475915-b53a9e80-4db1-11eb-9b2f-50243e1733f9.png)
