### ISSUE TITLE
Addon hanging and also hogging up RAM

### ISSUE THREAD

**Issue by azakaria** [jurialmunkey/plugin.video.themoviedb.helper#407]
There appears to be some kind of memory leak issue with this addon when used with Arctic Horizon skin. 
When clicked on the addon, it doesn't load and gets stuck in a busy loading notice: 
![image](https://user-images.githubusercontent.com/10538779/103391016-4fb28d80-4ae5-11eb-9e1f-93321eccfd5b.png)

When this happens every other addons seem to get stuck on the busy loading empty screen. But when I disable the TMDB helper addon and restart Kodi, everything is find within the Arctic Horizon skin. Now if I enable TMDB helper addon again, and try to open it, again all addons loading gets stuck. 

And it's eating up the RAM in my computer! :(
![image](https://user-images.githubusercontent.com/10538779/103392153-7e7f3280-4aea-11eb-9746-4ee39fc06a86.png)

Tried to debug it and I am noticing that something is causing some kind of looping call to blur_image route: 
![image](https://user-images.githubusercontent.com/10538779/103391413-6954d480-4ae7-11eb-851e-cb205a8d433e.png)

Thought disabling the blur_image line in routing_table would help but no change. Still, this looping call keeps happening. But, if I disable the addon, arctic horizon skin works fine, and everything goes back to normal. Also, note that the addon itself works in Esturary skin though. So, some relation between the Arctic Horizon skin and TMDB helper is problematic. 

I have attached the full Kodi log. 
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5756321/kodi.log)

**Comment by jurialmunkey** [comment]
Please try latest version from github master (v4.1.5)

**Comment by azakaria** [comment]
I upgraded both TMDB helper and Arctic Horizon to the latest versions of 4.1.5 and 0.5.55 respectively. Cleared all cache and tried again and unfortunately, still seeing the same problem. Here is a video screencast showing the problem: https://www.youtube.com/watch?v=2ypyI8D7-XI

Also attached the latest Kodi debug log. 
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5758486/kodi.log)

Still not sure if this is Arctic Horizon issue or TMDB helper issue because TMDB Helper works fine on other skins. On the other hand, Artctic Horizon seems to work fine with all other addons with TMDB Helper disabled. Also wondering if there is a race condition issue because sometimes the busy loader stays for minutes and sometimes it loads within 30 seconds.

**Comment by jurialmunkey** [comment]
Basically what happens is that Kodi only loads a certain number of plugins at a time and so if there is something blocking the current threads from completing then it will hold up everything until those complete. It might not necessarily be TMDbHelper itself, but rather some other addon is holding up some module/resource etc. that it needs and if all the other threads are TMDbHelper then obviously those can't complete and so Kodi sits waiting on them all. 

Unfortunately the log doesn't tell me much. The fact that I never have this issue anymore (not since v4 rewrite) leads to me to believe it is some weird interaction with another addon on your system holding things up.

To rule out the blur script causing something weird interaction, can you install latest Arctic Horizon from github? I realised it still runs the blur script even with blur disabled, so that shouldn't happen anymore (I doubt it is the problem anyway but worth ruling out just in case).

One thing I would suggest is loading the skin, exit Kodi properly (not force quit or Alt+f4), and then re-open Kodi so that Arctic Horizon loads from startup. Give it a couple of minutes to load-up and then see if the issue still persists. It could be something as simple as some cache needing to clean-up properly and by constantly exiting early it never happens. 

If it is still persisting, another thing you can try is deleting simplecache.db from Kodi/userdata/addon_data/script.module.simplecache/ (you need to exit Kodi first otherwise it will just rewrite it).

**Comment by azakaria** [comment]
@jurialmunkey - I will follow all of the above but will also do a completely fresh install with only Arctic Horizon and TMDBH and then try it out again. Doing more testing and debugging. Will keep you posted on my findings. Thanks for all the great suggestions to get to the bottom of this issue.

**Comment by azakaria** [comment]
@jurialmunkey - Very happy to report that the blur script was the culprit. :)
As soon as I got the newest version from Github and replaced the skin.arctic.horizon folder, everything appears to be fixed! No hanging, no RAM hogging. Didn't have to clear simplecache.db and force closing of Kodi also seems to be having no negative impact. Thanks so much for the fix! You and your Kodi addons are the best 🥇

**Comment by azakaria** [comment]
@jurialmunkey - Although I closed this ticket since the Blur feature is not something I am going to use, but wanted to let you know that as soon as I enabled the Blur feature, I am able to reproduce the same problem again. All the addons are hanging. I did a completely new fresh install with nothing else but just Arctic Horizon and TMDBH and still the same problem. There are no other addons in the Kodi setup. 

Also, note that I have an Nvidia Shield. There is no problem like this on that device. So, this might be an issue with just the Windows 10 64bit systems. I even installed it on another Window 10 64 bit laptop and had the same issue with Blur. Anyway, not a big deal for me anymore since everything is working for me without the Blur feature but thought I just let you know. :)

**Comment by jurialmunkey** [comment]
Thanks for testing. ^^^ This is really useful info about it being the blur runscript causing the issue even on a fresh install. 

I'm using Win 10 64 bit on my main dev laptop, so definitely not Windows related -- if anything, normally it is the other way around with Linux/Android platforms having issues with the PIL image library used for blurring. 

Since I can't recreate the issue myself, can I just ask you to test one more thing for me?

I have a suspicion that it isn't actually the blur function itself but instead the issue is calling it manually via Runscript. To test that out, can you delete the following lines in the skin and then restart kodi but with blur enabled:

In `kodi/addons/skin.arctic.horizon/1080i/Includes_Home.xml` delete these lines:
https://github.com/jurialmunkey/skin.arctic.horizon/blob/master/1080i/Includes_Home.xml#L437
https://github.com/jurialmunkey/skin.arctic.horizon/blob/master/1080i/Includes_Home.xml#L1410

If it works without those lines then that will confirm that the manual call via RunScript is the issue.

**Comment by azakaria** [comment]
@jurialmunkey - Sorry for the delayed response. 

I tested by deleting lines 437 and 1410 in Includes_Home.xml file. Reloaded Kodi with Blur turned on and faced the same issue of TMDBH taking a long time to load the start screen. But when I disabled Blur and reloaded, it's working fine again. Seeing the same thing in the logs. Lots of calls to the blur_image function and then it just holds there for a minute or so and then things get released and the first screen loads. The setup is still just Kodi + Arctic Horizon + TMDBH (that came with the theme).
