### ISSUE TITLE
[Request] Show and season IDs for players

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#409]
An add-on I'm currently looking at making a player for uses fields for `trakt_show_id` and `trakt_season_id` in its arguments for playing an episode. I had intended on trying to find where in the API you would find these, in order to request then more specifically, but it would be sweet if you were able to pass those through to players 😉

**Comment by jurialmunkey** [comment]
You can already get the Trakt id for the show with `{trakt}` or if you need the slug it is `{slug}` -- or at least you _should_ be able to; let met know if they aren't working for some reason.

I guess I could get season ID but it is a pain -- another separate call to get it. I don't know why anyone would use it though because it is just the season number but incremented by 1 if there is a specials season (i.e. because specials is season 0, it becomes ID 1 and bumps them all up).
