### ISSUE TITLE
[Bug] Playing local library files doesn't work anymore

### ISSUE THREAD

**Issue by Navios92** [jurialmunkey/plugin.video.themoviedb.helper#410]
I'm using Kodi 18.9 on the latest Fire Cube and v4.2.5 of TMDb Helper. My local library consists of .strm files exported from Google Drive addon. Playing local files from my In-Progress Movies trakt list used to work fine, but then it stopped all of a sudden.

I checked TMDb Helper settings and found this new option "Reroute PlayMedia to call xbmc.Player() directly", that was enabled by default. If I disable it, then I can play my local files again. However, the movie restarts from the beginning instead of resuming.

I have captured 2 log files. The first one is when the Reroute option is enabled and the local file doesn't play at all. The second one is when the Reroute option is disabled and the movie plays fine but restarts instead of resuming.

[kodi_tmdbh_01.log](https://paste.ubuntu.com/p/Xkp5SZQkTr/)
[kodi_tmdbh_02.log](https://paste.ubuntu.com/p/JHFKjHGwbq/)

**Comment by talondnb** [comment]
Also having this issue.

**Comment by jurialmunkey** [comment]
@talondnb @Navios92 - Could you both try latest github master version and see if you are still having the issue.

TMDbH should now correctly retrieve the url from the .strm and pass directly to setResolvedURL, thereby skipping the PlayMedia/xbmcPlayer route entirely. Hopefully will also fix the resume point issue since it now gets resolved.

**Comment by Navios92** [comment]
> @talondnb @Navios92 - Could you both try latest github master version and see if you are still having the issue.
> 
> TMDbH should now correctly retrieve the url from the .strm and pass directly to setResolvedURL, thereby skipping the PlayMedia/xbmcPlayer route entirely. Hopefully will also fix the resume point issue since it now gets resolved.

So playing local strm files works now, and so does resuming. But it seems like TMDbH stores a different resume point than the local one.
When I play a movie, TMDbH will ask me to resume or restart. After I choose resume, I get another dialogue also asking to resume or restart, but this time it has the correct resume point. Eventually, the movie will resume from the correct local resume point.

https://paste.ubuntu.com/p/7CrzhgbYtk/

**Comment by Navios92** [comment]
I noticed something but it may not be related. In-Progress Movies list doesn't update after playback ends. In fact, it seems like it updates only once or twice a day.

**Comment by jurialmunkey** [comment]
> So playing local strm files works now, and so does resuming. But it seems like TMDbH stores a different resume point than the local one.

TMDbH doesn't store resume points. Kodi stores the resume points.

From a quick look at the code of the CloudDrive module that the GDrive plugin uses, it looks like it is also handling resume points independently. What I believe is happening is that Kodi sees a resume point attached to the TMDbH item path, so it asks to resume. Then the CloudDrive module sees a resume point and also asks to resume.

The reason why the two points would diverge is because Kodi only stores resumes points attached to the item path. So Kodi will only store a resume point for the TMDbH item if the item was played via TMDbH -- whereas if you play that item separately via the library the resume point is attached to the .strm file.

The issue is that Kodi generally expects plugins to allow Kodi to manage resume points but many plugins override this behaviour via various hacks such as we see here.

> I noticed something but it may not be related. In-Progress Movies list doesn't update after playback ends. In fact, it seems like it updates only once or twice a day.

What do you mean by "In-Progress Movies". Are you talking about a library playlist or the TMDbH section.
In-Progress via TMDbH is based off the Trakt account. It only updates if your Trakt account is updated.

**Comment by Navios92** [comment]
> From a quick look at the code of the CloudDrive module that the GDrive plugin uses, it looks like it is also handling resume points independently. What I believe is happening is that Kodi sees a resume point attached to the TMDbH item path, so it asks to resume. Then the CloudDrive module sees a resume point and also asks to resume.

I see. It's not a big deal anyway as long as movies eventually resume correctly. It would be great though if TMDbH could somehow automatically skip the prompt about its resume point.
I noticed however that If I try to play with Kodi using "Select player" from the context menu, the movie won't resume. It seems like the changes in the last build don't apply here.

> What do you mean by "In-Progress Movies". Are you talking about a library playlist or the TMDbH section.
> In-Progress via TMDbH is based off the Trakt account. It only updates if your Trakt account is updated.

I'm talking about the trakt list in TMDbH. I understand that it updates when my trakt account is updated, but how often is that supposed to happen? Mine seems to update only once or twice a day, or even less frequently.

**Comment by patel-jeel92** [comment]
Should Reroute PlayMedia to call xbmc.Player() directly be disabled in the settings for strm files to play with resume points?

**Comment by patel-jeel92** [comment]
Any help on what the settings should be set? Should Reroute PlayMedia be enabled? Should dummy setResolvedUrl method to library strm be enabled?
