### ISSUE TITLE
Add TV Show Specials to library

### ISSUE THREAD

**Issue by Desperados85** [jurialmunkey/plugin.video.themoviedb.helper#418]
Normally I don't really care about specials but the tv show Euphoria released two episodes as specials which I would like to add to my library.
The problem is I can't seem to figure out how to do that..

I have added two Trakt lists to TMDb Helper to synchronize to my library, one for movies and one for tv shows, Euphoria is added to the tv show list.

I tried to add the two specials to the tv show list using the context menu, first individually and then the whole special folder. When asked to add to library, I click yes, it starts scraping but nothing was added.
So I did the same thing on the Trakt website hoping the specials would get added during the daily update. That was yesterday so I just checked and again nothing..

Is there a certain method with specials, am I doing something wrong?

Help would be appreciated :)

**Comment by jurialmunkey** [comment]
No you're not doing anything wrong, the addon just doesn't support adding specials (or individual episodes for that matter). 

The problem is that there is rarely an "official" numbering for specials and the numbering on TMDb is just whatever order people bothered to add them on the website. What that means is that you basically never end up with them playing correctly in another addon because the numbering pretty much never syncs up - so I just don't see much point to adding them. 

If you wanted, you could add specials manually by creating a new strm file in the folder of the show - just copy one of the strm for another episode and open it in a text editor to change the numbering (you'll need to look it up on tmdb to see the numbering). As long as the numbering inside matches tmdb and the filename numbering matches your library scraper then you will be able to add it that way.

**Comment by Desperados85** [comment]
Thank you! I will definitely try that when I get home :)

**Comment by Desperados85** [comment]
So I just did as you said, created the strm files myself, updated the library and it worked :)
I then ran into the problem you mentioned with the naming.. 

The first special should be S00E01 but Seren and Fen both search for S01E00.. So that doesn't work.. Venom does search for the right name but doesn't scrape my cloud files so that doesn't work either.. I then tried Realizer, it scraped my cloud, I selected the torrent but then got a playback error so I guess the Realizer player is broken..

I know you don't maintain the players but thought maybe you could take a look at what could be wrong with the Realizer player? I don't understand the players at all, if I could I would edit the player myself but not at all familiar with coding, the player wiki only made me more confused lol.

**Comment by Desperados85** [comment]
So I found a workaround to play the specials without having to manually browse through any addon. I used the 'search seren' player, that brought me to Euphoria in Seren and I could play the specials from there! So thanks for helping me with the strm files :)
