### ISSUE TITLE
[Request] Re-add deleted episodes to library upon airdate being added to TMDB database.

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#421]
Not sure on the viability of this so feel free to educate me. But to my knowledge when you delete episodes, TMDBH wont re-add them on a background update bc it keeps track of what episodes it added in a file? 

My request is that say I have Show A Season 4 episodes 1 through 10. Episode 1-4 have release dates, 5 comes out next week but 5-10 have no release dates and thus get added into the library anyway. If I delete 5-10 they wont get re-added I believe until I trigger a manual refresh, or the cache time runs out. Is it possible to make it so that when episode 5 gets release date added, TMDBH will detect and add that episode? 

Maybe an option for it to be enabled for background scans, and I dont think it would break anything, maybe inaccurate sometimes but you always have the option to go and trigger a manual refresh and re-add everything/whats missing.

I think maybe how the option could work is when enabled, TMDBH similar to how it keeps track of episodes added as to not re-add them, it could keep track seperately of episodes that were deleted and wont re-add these ones but will check TMDBH for these episodes on every background scan and if out of that deleted list, any airdates are now available they would get added to the library. Triggering a manual update in TMDBH settings would either delete this cached list, or prompt you and ask if you want to clear it similar to how it asks if you want to clear players before adding new ones.

(Now that I wrote this, kinda extra, but if its all viable, an extra option to do this for plot too would be nice so that instead of triggering refresh details in the library for episodes when a plot gets added to TMDB database, new episodes (only deleted ones) would only get added when plot (and/or airdate if u enabled it i guess) is available. This would make it so when the new episodes are added to the library theyd be ready with the plot already. It might add a day or two late bc plot doesnt always update right away but I would be fine with that sacrifice if it means I dont get empty episodes with no plot added and need to manually trigger refresh details for all my currently airing shows.

[would/should only happen on episodes that were deleted and are in the deleted list bc similar to airdates if this were to happen on regular episodes and adding it would skip many episodes bc some episodes are already aired just with no plot or airdate or both].

As always feel free to educate me if im having very bad misconceptions on how this would work I dont mean to just hound you with unrealistic requests. Take care.

**Comment by unkn0wn234** [comment]
So I realized I rambled and made a lot of assumptions here so im trying to condense this into a simpler request:

Request: Re-add deleted episodes to library upon airdate being added to TMDB database, by keeping track of deleted episodes in a file, and scanning deleted episodes for airdates during background scans, when airdates are updated add these episodes to library. Triggering manual update in TMDBH settings would wipe the file that keeps track of deleted episodes or ask you if you want to clear or not.

**Comment by jurialmunkey** [comment]
To put it simply, it would defeat the entire purpose of the update history. 

The _only_ reason TMDbH keeps an update history is so that it can speed up subsequent updates by skipping unnecessary season and tvshow look-ups (e.g. why waste time looking up a show again today when we only added yesterday and it won't air again until next week). To then check each skipped item for airdates would be the same as not keeping an update history at all and just running a manual forced update every single time.

I'm planning on adding an option to flip whether episodes/movies without airdates are treated as aired or unaired. There's not going to be a perfect solution but I think having that option is a simple approach which will solve 99% of the issue. Basically users who emphasise making sure they get all aired episodes and dont mind a few false positives for unaired episodes can leave it as is, whereas users like yourself who want to make sure that unaired episodes aren't added early can toggle the option over and then manually add the random odd episode which was skipped because it is missing data.

**Comment by unkn0wn234** [comment]
> To put it simply, it would defeat the entire purpose of the update history.
> 
> The _only_ reason TMDbH keeps an update history is so that it can speed up subsequent updates by skipping unnecessary season and tvshow look-ups (e.g. why waste time looking up a show again today when we only added yesterday and it won't air again until next week). To then check each skipped item for airdates would be the same as not keeping an update history at all and just running a manual forced update every single time.
 In response to this one, Im making an assumption here dont mean to tell you youre wrong or anything. If it kept a file of only episodes you deleted and added those to the check history it wouldnt have to recheck every single show like a manual refresh would it? I kinda envision it like this

I have 100 shows in the library, 90 are in the update history and wont be rechecked. 5 are going to be rechecked due to leaving the update history cache or whatever reason, but the other 5 say if they were in the update history originally but i deleted episodes it would only recheck these shows alongside the other 5 so it would only check 10 shows (and 5 only new airdates added) rather than 90. I may have rambled again.

>I'm planning on adding an option to flip whether episodes/movies without airdates are treated as aired or unaired. There's not going to be a perfect solution but I think having that option is a simple approach which will solve 99% of the issue. Basically users who emphasise making sure they get all aired episodes and dont mind a few false positives for unaired episodes can leave it as is, whereas users like yourself who want to make sure that unaired episodes aren't added early can toggle the option over and then manually add the random odd episode which was skipped because it is missing data.

This would be great then, yea i wouldn't mind adding the random odd episodes personally. Id still like to hear your response to the above but it will likely be this option u go with anyway so I have 2 questions.
1- Would it be possible to add a secondary option under this one so that on top of checking for airdate it checks for plot too? (I assume it would be even more difficult with this one due to the fact just like many episodes have no airdate there are probably numerous shows with episodes already out that have no plot which would make TMDBH miss even more episodes). Which leads me to my second question
2- Similar to how you were talking about the GUI for choosing players for shows do you think maybe we could enable this airdates option on a per show basis? That way we could just use it for currently airing shows, and on top of that would reduce the amount of shows wed have to scan and check for missing episodes and add the missing ones, this way wed know the handful of shows we turned it off for and just have to check them. (I hope this one is possible I think it would be the best solution out of all, + if this one is possible let me know what you think of the plot question from the question above working with this option)

Thanks for responding and letting me know :D

**Comment by jurialmunkey** [comment]
> but the other 5 say if they were in the update history originally but i deleted episodes it would only recheck these shows alongside the other 5 so it would only check 10 shows (and 5 only new airdates added) rather than 90. I may have rambled again.

The problem is that TMDbH can only know if an item was removed from the library by checking if it is still in the library - each update it would need to check each previously added episode to confirm that it was still in the library. Its not as bad as doing the online lookup but it is still adding a fair amount of extra overhead.

**Comment by unkn0wn234** [comment]
> > but the other 5 say if they were in the update history originally but i deleted episodes it would only recheck these shows alongside the other 5 so it would only check 10 shows (and 5 only new airdates added) rather than 90. I may have rambled again.
> 
> The problem is that TMDbH can only know if an item was removed from the library by checking if it is still in the library - each update it would need to check each previously added episode to confirm that it was still in the library. Its not as bad as doing the online lookup but it is still adding a fair amount of extra overhead.

Ah okay thanks for explaining that.

**Comment by jurialmunkey** [comment]
In response to the other questions:

>Would it be possible to add a secondary option under this one so that on top of checking for airdate it checks for plot too?

Yeah this would be fairly trivial to add - the data is already there when pulling the season, so it is just a matter of checking the plot field as well as the airdate field. It would add a tiny bit of extra overhead but fairly inconsequential.

I guess the main issue would be episodes that have been forgotten about and no one added a plot for. I imagine this would be more a problem with documentary / reality / panel type shows.

> Similar to how you were talking about the GUI for choosing players for shows do you think maybe we could enable this airdates option on a per show basis? 

I don't see much point to this because you can always just do a manual scan of a single show with the option turned off to fill in any gaps where past episodes are missing airdate data - TMDbH never deletes anything, so once the episodes are added for a show it isn't like they will be removed once you re-enable the option.

**Comment by unkn0wn234** [comment]
> In response to the other questions:
> 
> > Would it be possible to add a secondary option under this one so that on top of checking for airdate it checks for plot too?
> 
> Yeah this would be fairly trivial to add - the data is already there when pulling the season, so it is just a matter of checking the plot field as well as the airdate field. It would add a tiny bit of extra overhead but fairly inconsequential.
> 
> I guess the main issue would be episodes that have been forgotten about and no one added a plot for. I imagine this would be more a problem with documentary / reality / panel type shows.
> 
> > Similar to how you were talking about the GUI for choosing players for shows do you think maybe we could enable this airdates option on a per show basis?
> 
> I don't see much point to this because you can always just do a manual scan of a single show with the option turned off to fill in any gaps where past episodes are missing airdate data - TMDbH never deletes anything, so once the episodes are added for a show it isn't like they will be removed once you re-enable the option.

Thats true but I envisioned it more like this cause I have like hundreds of shows now to populate my library and make it look like theres a selection. Since like u said in the beginning this is what kept you from adding the option till now, there are many episodes for shows and especially obscure shows that are already aired and just not added which would prevent them from being added. So in general knowing that Id like to keep it like this where it adds everything airdate or not, the only shows where I would want to make it so it adds unaired episodes would be shows in my next up which is a fairly small selection. Being able to set it up on a per show basis makes it so you wouldnt have to go back and enable/reenable for shows. And while I think its not tedious it just helps in making it more automated imo. Though I guess u could always mass add lists with the option off, then delete all the unaired episodes manually, then turn it back on. But without a program like TinyMediaManager (which I do have but is paid) ud have to go find the episodes manually for each show to delete. If we did it the other way around it'd be even more tedious to go through hundreds of shows and find the ones with missing episodes, just my thoughts. 

The GUI/per show option would also make it much better to work with the plot option I was talking about since like we both said there would probably be even more episodes than missing airdates with missing plots that have already been aired just with no information added that would be skipped. This way you could control which shows are being used for the airdate options+plot options while making it so when you mass-add its unaffected. And it would also make it so you wouldnt have to change settings when adding and refreshing, it would just know which shows have the option of checking unaired or not while leaving the mass majority untouched. 

I hope you reconsider this one bc if everything else I said may be pointless working with the plot option I think is the major benefit. 

Alternatively, if its possible maybe instead of an option to enable or disable "treat episodes without airdates as unaired", it could be more something like treat episodes without airdates as unaired for next up shows (currently watching). So it would only affect shows you're currently watching. I say this bc the airdates things is really only imo used for the currently watching shos that fill up Next Up widget in my library. I dont want the next episode that is unaired to show up in the next up widget, anywhere else I wouldnt mind.

**Comment by jurialmunkey** [comment]
I think the big problem with this type of approach is the complexity - both in terms of user accessibility and code maintenance. More complexity is more debugging, more legacy and niche test cases to consider when making changes, and simply more chance for users to make bad assumptions about how things work and break things. 

Basically it needs to stick to the K.I.S.S. principle - Keep It Simple Stupid.

I'm not opposed to looking for a solution but writing a GUI media manager is not that solution. There's a reason why Tiny Media Manager is paid - writing software to manage exceptions and provide automation using imperfect data sources is time consuming and complex.

At the end of the day, I've probably overstated the problem with missing airdates. I honestly believe that the new option will solve 99% of the problem. Yeah, there might be some niche older shows missing airdates, but ultimately the _best_ solution is simply to go on TMDb and actually add in the missing data!

Also, it is important to note that TMDbH only skips checking episodes it has already _added_. On the next scheduled check for that show, TMDbH will check _all_ episodes that haven't been added (e.g. due to being unaired) in the current season. Also, the manual check from context menu is a forced check of all episodes - so as long as you updated the date data on TMDb the missing episode will get added.

And finally, FYI I've added the new "Hide items without airdates" option to latest git master. So please test that out and then once we confirm that is working we can look at better handling some exceptions if needed (though I honestly think you'll find it solves 99% of the problem and managing the more niche cases isn't going to be as complicated as you're anticipating).

**Comment by unkn0wn234** [comment]
> I think the big problem with this type of approach is the complexity - both in terms of user accessibility and code maintenance. More complexity is more debugging, more legacy and niche test cases to consider when making changes, and simply more chance for users to make bad assumptions about how things work and break things.
> 
> Basically it needs to stick to the K.I.S.S. principle - Keep It Simple Stupid.
> 
> I'm not opposed to looking for a solution but writing a GUI media manager is not that solution. There's a reason why Tiny Media Manager is paid - writing software to manage exceptions and provide automation using imperfect data sources is time consuming and complex.
> 
> At the end of the day, I've probably overstated the problem with missing airdates. I honestly believe that the new option will solve 99% of the problem. Yeah, there might be some niche older shows missing airdates, but ultimately the _best_ solution is simply to go on TMDb and actually add in the missing data!
> 
> Also, it is important to note that TMDbH only skips checking episodes it has already _added_. On the next scheduled check for that show, TMDbH will check all episodes that _haven't_ been added previously (e.g. due to being unaired) in the current season. Also, the manual check from context menu is a forced check of all episodes - so as long as you updated the date data on TMDb the missing episode will get added.
> 
> And finally, FYI I've added the new "Hide items without airdates" option to latest git master. So please test that out and then once we confirm that is working we can look at better handling some exceptions if needed - though I think manually handling those niche caches isn't going to be as complicated as you're anticipating.

Hi jurial I appreciate you explaining it like this for me. I understand, and I’ll test out this new commit tonight or tomorrow morning! Thank you for implementing this!

**Comment by dm2912** [comment]
just to add to this, its been an ongoing annoyance for me that season 3 of race across the world for instance keeps getting added to the library

https://www.themoviedb.org/tv/87340-race-across-the-world/season/3

season 3 has not even been recorded but someone chose to add it to tmdb without airdates, as a result it keeps getting added.. 

i think an option to be able to exclude episodes without airdates would be a good move. (but i appreciate there may be issues with historical shows that may not have their original airdate on tmdb)

(I have reported that season for removal on tmdb but the mods all appear to have been asleep for a while now)

**Comment by jurialmunkey** [comment]
@dm2912 - The option to exclude episodes without airdates has already been added in the most recent git version (4.2.15)

**Comment by unkn0wn234** [comment]
So far seems to work! Thanks jurial!
