### ISSUE TITLE
Can't authorize Trakt in TMDBHelper

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#422]
I tried authorizing Trakt numerous times in TMDBHelper after uninstalling reinstalling too. Im not sure if tmdbhepler shows the trakt username after connecting or not, but after authorizing it doesnt show up, if i try to access any personal user trakt lists like next up, or watchlists nothing happened. After updating to repo 2.0 and installing the latest through github I got an error on the trakt connection here is the log

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5893959/kodi.log)

**Comment by jurialmunkey** [comment]
Trakt connection error

```
2021-01-29 07:50:04.462 T:4496  NOTICE: [plugin.video.themoviedb.helper]
                                            ConnectionError: {"https://api.trakt.tv/oauth/device/code": 1611924664.462}
                                            Suppressing retries for 1 minute
```

They were probably having server issues. I know that they're experimenting with some different options for managing server requests currently after there were some issues earlier this month with one particular addon absolutely thrashing their API due to a recursive request bug (not blaming anyone - bugs happen and ultimately it is good that as a result Trakt are implementing better safeguards on their servers, but also teething problems are expected along the way).

General advice is to give it some time and then try again. I was able to authenticate just now when I checked, so maybe try again now - if you still can't authenticate let me know.

Also, the only thing settings will show to indicate that you're authenticated is the log out option (which basically shows if there's a trakt access token saved).

**Comment by unkn0wn234** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5897339/kodi.log)

happened again on a test now, I basically deleted my  Kodi stup with the library intact so I will have to go redo all that again just been a bit lazy

**Comment by jurialmunkey** [comment]
Logs say trakt authenticated successfully.

You can try the nuclear option and delete the addon_data folder for TMDbH (close Kodi first before deleting).
`kodi/userdata/addon_data/plugin.video.themoviedb.helper`

That will reset all the cached data and settings back to defaults.

**Comment by unkn0wn234** [comment]
> Logs say trakt authenticated successfully.
> 
> You can try the nuclear option and delete the addon_data folder for TMDbH (close Kodi first before deleting).
> `kodi/userdata/addon_data/plugin.video.themoviedb.helper`
> 
> That will reset all the cached data and settings back to defaults.

deleting addon data folder worked, thank you.
