### ISSUE TITLE
Request: add In-Progress Episodes to Trakt 

### ISSUE THREAD

**Issue by SnakeATWAR** [jurialmunkey/plugin.video.themoviedb.helper#424]
We have In-Progress TV Shows already which is great for keeping track of what shows you've been watching, but something I would find particularly helpful is a list of In-Progress Episodes. This would be especially helpful if you want to finish the last episode you were watching but had to stop early and help it stand out from shows you (or your spouse) have been watching since then. I believe it should be possible as Seren does this already. This is the one thing that would make tmdb helper be able to take over (and consolidate) my local media tabs and my Seren powered tabs. 

Anyways, I do want to say thanks a lot for this add-on and l the other work you do for the Kodi community.

**Comment by unkn0wn234** [comment]
> We have In-Progress TV Shows already which is great for keeping track of what shows you've been watching, but something I would find particularly helpful is a list of In-Progress Episodes. This would be especially helpful if you want to finish the last episode you were watching but had to stop early and help it stand out from shows you (or your spouse) have been watching since then. I believe it should be possible as Seren does this already. This is the one thing that would make tmdb helper be able to take over (and consolidate) my local media tabs and my Seren powered tabs.
> 
> Anyways, I do want to say thanks a lot for this add-on and l the other work you do for the Kodi community.

Might not be the answer youre looking for since I think you want in progress episodes in its own tab/widget. But the episode you are in progress in, should be the one that shows up in Next Up rather than the episode after that so it would still resume.

**Comment by SnakeATWAR** [comment]
> 
> Might not be the answer youre looking for since I think you want in progress episodes in its own tab/widget. But the episode you are in progress in, should be the one that shows up in Next Up rather than the episode after that so it would still resume.

That's good to know. I'll have to test this today. Thanks! 

It would still be nice to have a separate folder for "in-progress episodes" but until then, this should be good enough. Thanks!

**Comment by jurialmunkey** [comment]
> It would still be nice to have a separate folder for "in-progress episodes" but until then, this should be good enough. Thanks!

What would be the difference between this "in-progress episodes" and the current "your next episodes" section?

**Comment by unkn0wn234** [comment]
> > It would still be nice to have a separate folder for "in-progress episodes" but until then, this should be good enough. Thanks!
> 
> What would be the difference between this "in-progress episodes" and the current "your next episodes" section?

Basically just the episodes u have progress in in trakt so u can easily see which episodes you need to finish up.

**Comment by SnakeATWAR** [comment]
Exactly. They stand out as being incomplete as opposed to getting lost in a list of next episodes. I usually set up my TV widgets with In-Progress Episodes, Recently Watched Shows, and then I have a few discovery widgets for when I want to find something else. It would be nice to be able to consolidate my local and streaming TV tabs into one with TMDB Helper and still keep this widget layout.

**Comment by jurialmunkey** [comment]
But "your next episodes" only displays the next unwatched/partially watched episode for each show that is incomplete so I dont see how it is much different.

I'm not opposed to having an list that displays all episodes that you only watched part of - I'm just not really understanding the use case compared to "your next" - if anything I would think in progress episodes would be really annoying because if an episode has long credits and you stop before the end of the credits then those episodes would also be mixed in because technically you hadn't watched the entire episode even though it was just credits.

**Comment by unkn0wn234** [comment]
> But "your next episodes" only displays the next unwatched/partially watched episode for each show that is incomplete so I dont see how it is much different.
> 
> I'm not opposed to having an list that displays all episodes that you only watched part of - I'm just not really understanding the use case compared to "your next" - if anything I would think in progress episodes would be really annoying because if an episode has long credits and you stop before the end of the credits then those episodes would also be mixed in because technically you hadn't watched the entire episode even though it was just credits.

regarding the last part most addons have a mark watched at x% so it rarely leaves episodes as in progress when you get to in progress

**Comment by DaisyF8** [comment]
The difference in use case, if I understand correctly, is like that half eaten bag of chips/crisps of flavour x that gets pushed to the back of the cupboard while you keep buying new bags and storing them in front. 

You eat the new bags of flavours a, b and c always till empty and replenish with new bags.   You don't get reminded of flavour x in the way you want because it's too far back AND you don't notice it's half-eaten.

A list of started but not finished bags would keep x in front.

Especially pickles.

Forget this post as soon as you read it. That means now.
