### ISSUE TITLE
[Request] Unpaginate certain Trakt Lists

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#430]
Correct me if im wrong, but from what I saw you say on this in other threads the reason you didn't do this was to not overload Trakt with unneccesary API calls which I understand. 

Would you consider unpaginating Trakt related stuff that are directly related to the user? In order of importance imo, Next Up, Watchlist, ~~Collection~~. (and maybe personal user-lists but not really that necessary since long user lists probably fall into the a lot of API calls situation you were talking about, but i think maybe itd be fine since its only for personal lists and not every list.)

**Comment by jurialmunkey** [comment]
Next up is paginated because more results make it slower (it needs to be calculated client side using multiple requests - trakt doesn't just provide a list of items that can be retrieved). Plus generally the item you want is in the first page so it makes no sense to increase the load time considerably when the majority of the time you don't need those extra results.

Watchlist is an unlimited list and so could have potentially hundreds of items.The same goes with personal lists.

Also the overload is not on Trakt. It is on TMDb and fanart TV as those services provide the details for each item (and each item in the list needs a separate call)
