### ISSUE TITLE
Netflix Player not working

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/plugin.video.themoviedb.helper#435]
Since a few weeks the Netflix Player stopped working.

Now I just get this

![20210206_220724](https://user-images.githubusercontent.com/10348988/107129958-94da9400-68c9-11eb-8a3b-3e45696a7dd8.jpg)

https://paste.kodi.tv/magumirihi

In Netflix-addon I allready checked "Enable IPC over HTTP" to avoid time-out.  I read this in a previous Issue, but with it unchecked is the same.

**Comment by jurialmunkey** [comment]
Built in Netflix player is working fine for me (I just watched S3 of Cobra Kai last week)

**Comment by jurialmunkey** [comment]
I was also able to play this episode of snow piercer just fine.

Make sure you're using the builtin Netflix player and not one from a 3rd party source.

**Comment by DaisyF8** [comment]
I'm a bit confused by your answer so I guess I'm missing something.  I'll sum some stuff up and hopefully you'll be able to point out the spirelli in my spaghetti.

I'm using Netflix 1.12.2 by castagnait libdev jojo asciidisco caphm.

Through TmdbPlayer, I use this Netflix-player (top one).
![20210209_101258](https://user-images.githubusercontent.com/10348988/107343226-6cb58580-6ac1-11eb-8fcd-e82e6f76ac86.jpg)

All these players get provided (as far as I know) by the bit.ly-url on the bottom of the picture below. There is one setting I haven't figured out what it does exactly (but I keep it checked). "Use bundled players"; is this what you mean by "builtin Netflix player" and are the players from the bit.ly-url the 3rd party source ?
![20210209_101345](https://user-images.githubusercontent.com/10348988/107343232-6de6b280-6ac1-11eb-9049-257c6c9df530.jpg)

This url links to the a4kopenproject.
![Capture](https://user-images.githubusercontent.com/10348988/107344308-97540e00-6ac2-11eb-9ba6-e07dece2bf8d.PNG)

In TmdbHelper-settings the top one is the only Netflix-player I know of.
![20210209_101413](https://user-images.githubusercontent.com/10348988/107343234-6e7f4900-6ac1-11eb-9b38-92b3884e5bd2.jpg)

These are the settings.
![20210209_101424](https://user-images.githubusercontent.com/10348988/107343237-6f17df80-6ac1-11eb-981a-249e5bcc97c2.jpg)

**Comment by DaisyF8** [comment]
And to be complete : In Netflix there are five profiles. I selected mine with context menu as "Profile set to auto-selection" and "Profile set for playback from the library".

**Comment by drinfernoo** [comment]
@DaisyF8 The best option is to "Use bundled players", and remove `netflix.json` and `youtube.json` from your players folder. They'll be being removed from the `json.openplaywrs` package shortly.

**Comment by jurialmunkey** [comment]
To add to what drinfernoo said above:

TMDbH ships by default with built-in players for Netflix and Youtube (and a few others). Those players are used by enabling the "use bundled players" option (enabled = use bundled + downloaded; disabled = only use downloaded).

If two players have the same filename then the one that TMDbH builds _last_ will be used (because it will override the slot in the players select dialog). Bundled players _should_ override downloaded players because the order TMDbH builds players is (1) downloaded -> (2) bundled (if enabled) -> (3) reconfigured.

I suspect what has happened is that you've reconfigured the Netflix player whilst "use bundled players" was disabled. Reconfiguring a player creates a copy of the file (to avoid editing the original), so that copy would have been based on the downloaded version not the bundled. Since reconfigured players are built last, that copy would now be the version always used regardless of the "use bundled" option.

If I'm correct then you should be able to open the Netflix player in the configuration dialog and choose "Reset to Defaults". That will delete the reconfigured version and now you should be using the default version instead.

To be 100% certain, you can do what drinfernoo said and delete the actual downloaded and reconfigured player files for netflix. The files to delete should be:

`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/players/netflix.json`
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players/netflix.json`

**Comment by DaisyF8** [comment]
Where is that file netflix.json I should delete located ? Not the one in .kod/addons/plugin.video.themoviedb.helper/resources/players ? I deleted that netflix.json. No difference, still same error message.

I even deleted that entire folder. Makes no difference to the players I can select, they are still all there. So that folder, those are the "bundled players" right ?

So then where do the json.openplayer files (from the bit.ly url) get extracted to?

I'm doing stuff logically but still I'm lost :)

**Comment by jurialmunkey** [comment]
@DaisyF8 - See my comment above (I think we commented at the same time).

I suspect you have a reconfigured version of the player which will be:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players/netflix.json`

Try deleting that and see if it helps.

**Comment by jurialmunkey** [comment]
@DaisyF8  - Also btw the one you deleted IS the bundled one!!!

**Comment by jurialmunkey** [comment]
In summary:

You want to KEEP:
`.kodi/addons/plugin.video.themoviedb.helper/resources/players/netflix.json`
FYI - you can redownload this file from [here ](https://raw.githubusercontent.com/jurialmunkey/plugin.video.themoviedb.helper/master/resources/players/netflix.json)if you deleted it

You want to DELETE:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/players/netflix.json`
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players/netflix.json`

**Comment by DaisyF8** [comment]
I'm so glad I never really delete a file when tinkering but just add an underscore somewhere :) So I didn't need ro reinstall or mess with backups.

Thanks for the help directing me to the stuff in userdata. Deleting there fixed it.

And yes, it was caused originally by modifying a player while "use bundled" was unchecked.

Thanks so much. BIG spirelli :)

[Solved]
