### ISSUE TITLE
Library update every time Kodi starts

### ISSUE THREAD

**Issue by jaimsitecom** [jurialmunkey/plugin.video.themoviedb.helper#436]
Hi. Am just wondering if the option to have the ‘Library update everytime Kodi starts’ can be integrated into an option in the settings. I know there is an option to update the library on a certain time but it would be more awesome to have the option /choice to start the update everytime i boot/restart up kodi. 

Thanks in advance and more power to TMDB HELPER!

**Comment by jurialmunkey** [comment]
What purpose would this serve?

TMDBh is already programmed to automatically run an update 15m after startup if you happened to miss the last update time because Kodi was turned off.

It doesn't make sense to update more than once a day because there won't be anything new to add - you'd just be wasting CPU cycles to do nothing.

**Comment by jaimsitecom** [comment]
Thanks for the quick reply. I understand your point. But some tv shows have different airtimes especially non-usa shows. So some shows get added at different times (timezone factor) thus updating library twice a day might be needed. 

Thanks anyways.

**Comment by jurialmunkey** [comment]
Time of day isn't factored into the air date calculations, only the date. Episodes are added if the air date is today (or in the past). Rerunning the update on the same won't add any more episodes.

**Comment by jaimsitecom** [comment]
Got it. Thanks again anyways.
