### ISSUE TITLE
Is there an option to remove the splash screen

### ISSUE THREAD

**Issue by Badi4** [jurialmunkey/plugin.video.themoviedb.helper#437]
Can we remove the TMDB splash screen that shows up once you start playing something.

**Comment by jurialmunkey** [comment]
No. it's necessary to resolve to a video for addons that don't use setresolvedurl otherwise kodi will complain about failed playback. Addons like Netflix which properly use setresolvedurl won't havr the splash whereas some of the other addons people use don't do things correctly so force the need for the splash.

**Comment by jurialmunkey** [comment]
Also note that you can change the duration in expert settings but beware that lower value might cause issues on many systems.
