### ISSUE TITLE
[BUG-MATRIX] Get issues when creating certain widgets.

### ISSUE THREAD

**Issue by Nadarob-Skillane** [jurialmunkey/plugin.video.themoviedb.helper#438]
Using Matrix RC1 Android 64-bit on Nvidia Shield.
Arctic Horizon skin (modified addon.xml file to be compatible with Matrix).
TMDBH version 4.2.15

How to replicate issue:
Create a widget using Addons>Video Addons>TMDBH>TV Shows >Your In-Progress > Sort By: Added
Throws up a TMDBH error, but you can still go on to create the widget. However, when loading the skin, you get the same TMDBH error, and the widget does not get created.
Not limited to this particular widget, but any that are created using the Sort By: Added upon creation.
On a side note, can I ask why there is an option for Sort BY: in the widget creation creation, as the skin also has that option when creating the widgets, and it also is a pain as it names the widget 'Sort By: * ' when creation is complete.

**Comment by jurialmunkey** [comment]
Debug log please.

The sort by option is included in  tmdbhelper so that it is possible to sort the _entire_ list. It is necessary because Kodi's sort options only sort the items that are visible - ie the first page, which is often not very useful.

**Comment by Nadarob-Skillane** [comment]
Thanks for the explanation regarding sorting. Much appreciated.
Full debug log attached.
Creating the widget in skin settings starts at 22.06. Then, I back out and the skin saves/reloads. Once All widgets have reloaded (and the TMDBH error pops up), then Kodi is shut down - the error for loading the widget is at 22:07:38.993
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5976651/kodi.log)

**Comment by jurialmunkey** [comment]
Latest version from Matrix branch should fix the issue.

BTW the reason you are getting the error in the first place is because you are using a sorting method that doesn't make sense for the content you are trying to sort -- the "Added" sort method uses the Trakt field "listed_at" which is only available in lists where items are manually added to the list (i.e. the time they are "listed at"). In-Progress isn't a list where items are added, so it isn't possible to sort by added.
