### ISSUE TITLE
[Question] watchdog alternative

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#439]
You did a great job incorporating TV Shows-Next Aired into The movie DB helper and "update library after adding items".
Would it be possible to make The movie DB helper work like watchdog but without putting stress on the CPU? I think it would be a great alternative. 
Name: The movie/Music DB helper plus or a separate add-on for music.

![screenshot000](https://user-images.githubusercontent.com/2873112/107872173-2f297180-6ea0-11eb-86eb-f1ee52e15969.png)

I think we need an alternative because watchdog has not been updated since 2013. Obviously, I’m thinking months down the line when you have time. What Do you think?
No worries if it's too complicated. it was only a thought 🙂

**Comment by jurialmunkey** [comment]
I've never used watchdogbut it sounds like something that should be an entirely separate addon - I can really see the connection to TMDb.

Also I'm pretty sure it is still being worked on because according to the watchdog forum thread a Matrix version is in the works:
https://forum.kodi.tv/showthread.php?tid=128896&page=54

**Comment by Blurayx** [comment]
Ah, I didn't know there's a matrix version in the works.

Thanks😀
