### ISSUE TITLE
Question about Library Integration (Updating) through TMDBH on more than one device.

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#451]
I recently got an Android box that I've installed Kodi on that also has network file transfer. Ive since copied my complete library from my PC to the android box, and plan to keep that as the main place.

Anyways my question is I am going to set up the Movie and TV paths in my PC TMDBH Library settings to the new location on my Android box. As well as set those same paths on my box. Will updating library on my PC conflict with library updating on my Android Box as well? Say I run Kodi on my PC and it adds a few episodes of Show A, and then when I boot it up on my Box and it runs a background update, will it detect those new episodes added or will it duplicate it?

**Comment by jurialmunkey** [comment]
So both devices will share the same folder location? I haven't tested that type of setup but I believe it should work.

There might be some double up of lookups since each box doesn't know what the other has done in terms of the next lookup log. However, in that case, the actual files won't be duplicated - the other box will just overwrite the same strm file.

You could minimise this writing double up by doing a kodi library update before TMDBh runs its update.  Since TMDBh has a 15min delay before doing a missed scheduled update, you'd probably get pretty far by setting kodi to update library on startup. Even better would be a shared mysql library between both machines but that is more complex to setup. 

The main thing you want to avoid is having both machines scheduled to update at the same time because the combined disk usage will probably slow things down. And make sure language settings are the same on both machines because foldernames are written using the language set in TMDbH and kodi.

**Comment by unkn0wn234** [comment]
> So both devices will share the same folder location? I haven't tested that type of setup but I believe it should work.

Yes they would be sharing the same folder location.

> There might be some double up of lookups since each box doesn't know what the other has done in terms of the next lookup log. However, in that case, the actual files won't be duplicated - the other box will just overwrite the same strm file.

If this is the case it's fine, as long as I wouldn't have to do extra deleting/managing. The reason I am doing this is because I dont want to keep copying the files from one setup to the other and jsut have everything be done automatically.

> You could minimise this writing double up by doing a kodi library update before TMDBh runs its update. Since TMDBh has a 15min delay before doing a missed scheduled update, you'd probably get pretty far by setting kodi to update library on startup. Even better would be a shared mysql library between both machines but that is more complex to setup.

Could you elaborate on the first point? I will probably avoid mysql, if I update the library before a TMDBH update, does that mean TMDBH will detect that it's already in my library and skip overwriting it?

> The main thing you want to avoid is having both machines scheduled to update at the same time because the combined disk usage will probably slow things down. And make sure language settings are the same on both machines because foldernames are written using the language set in TMDbH and kodi.

For this, yea I wont have them scheduled to update at the same time, and it wouldn't happen anyway as I would never (or very rarely) have Kodi open on both devices at the same time. It would just be a more constant switching between devices.

Thank you for the info I will update you on how it goes!

**Comment by jurialmunkey** [comment]
> If I update the library before a TMDBH update, does that mean TMDBH will detect that it's already in my library and skip overwriting it?

Yep, exactly. There would still be the duplication of the lookup of the show to check for new episodes but the writing of the strm file to disk would be skipped because it is already in the library.

**Comment by unkn0wn234** [comment]
> > If I update the library before a TMDBH update, does that mean TMDBH will detect that it's already in my library and skip overwriting it?
> 
> Yep, exactly. There would still be the duplication of the lookup of the show to check for new episodes but the writing of the strm file to disk would be skipped because it is already in the library.

Alright thank you I will close this for the time being. Much appreciated as always
