### ISSUE TITLE
Support for IMDB Top 250 rating?

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#452]
I was looking at the detailed items in the wiki and it does pull some things from IMDB, can you consider adding support for the IMDB Top 250 rating?

Context: https://forum.kodi.tv/showthread.php?tid=337862&pid=3020552#pid3020552

Basically in the extended info dialog he has added support to use TMDBHelper for some information, getting the Top 250 IMDB rank from TMDBHelper would be great to fill it in!

**Comment by jurialmunkey** [comment]
Already supported for quite some time, I just forgot to document it in the wiki. Added now.

FYI -- TMDbHelper doesn't pull any data from IMDb. IMDb doesn't have a publicly accessible free API and scraping data from their website is forbidden by their terms of service.

IMDb rating comes from the OMDb database and Top250 is done by comparing against the Trakt Top250 list:
https://trakt.tv/users/justin/lists/imdb-top-rated-movies?sort=rank,asc

**Comment by unkn0wn234** [comment]
> Already supported for quite some time, I just forgot to document it in the wiki. Added now.
> 
> FYI -- TMDbHelper doesn't pull any data from IMDb. IMDb doesn't have a publicly accessible free API and scraping data from their website is forbidden by their terms of service.
> 
> IMDb rating comes from the OMDb database and Top250 is done by comparing against the Trakt Top250 list:
> https://trakt.tv/users/justin/lists/imdb-top-rated-movies?sort=rank,asc

Thank you, which one is it in detailed items tho I still dont see it? Will it fall under IMDb rating or votes?

**Comment by drinfernoo** [comment]
I don't think it actually got added... The last revision was in July.

**Comment by jurialmunkey** [comment]
> Thank you, which one is it in detailed items tho I still dont see it? Will it fall under IMDb rating or votes?

It isn't in the detailed items wiki because it is never added as a listitem property. It is only ever added as a window property via the service monitor. It's done this way because it requires a completely separate call which isn't worth the extra overhead to do for every item in every list - being service monitor only means that it is only ever looked up for the current item.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#ratings-specific
