### ISSUE TITLE
Tmdbhelper player not working through fen on kodi19

### ISSUE THREAD

**Issue by deyooluv** [jurialmunkey/plugin.video.themoviedb.helper#455]
Fen scrapes through tmdb helper player fine. However there is no playback after selecting any of links from the displayed result window. Fen works fine without going through tmdb helper. 

{
    "name" : "Fen",
    "plugin" : "plugin.video.fen",
    "priority" : 500,
    "play_movie" : "plugin://plugin.video.fen/?mode=play_media&vid_type=movie&library=True&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}",
    "play_episode" : "plugin://plugin.video.fen/?mode=play_media&vid_type=episode&library=True&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}"
}

**Comment by deyooluv** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6126879/kodi.log)

**Comment by drinfernoo** [comment]
Then that is an issue with the player, not with TMDbHelper.

**Comment by cgcgcgcgcg** [comment]
@deyooluv Maybe you should open an issue -include the log- in Fen's GitHub:
https://github.com/Tikipeter/repository.tikipeter/issues

**Comment by jurialmunkey** [comment]
You probably need to percent encode your keys because the addon likely expects a different encoding

e.g.
`{title}` needs to become either `{title_url}` `{title_url+}` `{title_escaped}` or `{title_escaped+}` depending on what the end plugin expects. You can see all the encoding options for TMDbH player keys here:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes

You would need to do this for all the `{keys}` that pass through text values.
