### ISSUE TITLE
[Question] Fanart TV

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#457]
When I select landscape or fanart art nothing happens.

https://user-images.githubusercontent.com/2873112/111015066-ebdaf980-839e-11eb-9c6f-18257ca3f1b4.mp4

![2](https://user-images.githubusercontent.com/2873112/111015089-fbf2d900-839e-11eb-922a-f151f037d712.jpg)

Thanks

**Comment by drinfernoo** [comment]
Is this in Matrix?

**Comment by Blurayx** [comment]
Yes

**Comment by jurialmunkey** [comment]
That context option only changes the artwork provided by the service monitor which looks up details for the currently focused item. Kodi doesn't allow scripts to change the properties of the item itself, which means skins can only use service monitor info _outside_ of the list (e.g. the clearart or other details in the info half such as ratings).

Also, Arctic Horizon always prefers info provided by the item itself and only uses the service monitor info as a fallback when the item doesn't have any info (e.g. if your item didn't have clearart, AH will use the clearart that the service monitor finds for the item).

EDIT: I should also add an extra clarification here that if the list itself comes from TMDbHelper _then_ that option will also change the art in the list because cached info about items is shared between the plugin and the service monitor.

**Comment by Blurayx** [comment]
Ok. Thanks!!😀

**Comment by Blurayx** [comment]
I'm beginning to think matrix is a step back than moving forward. so many changes. What's the alternative to downloading clearart?

Thanks

**Comment by jurialmunkey** [comment]
If this is in the library then why don't you just change the artwork in the info dialog like normal:

https://user-images.githubusercontent.com/4618719/111055590-86d0f200-84cb-11eb-89c1-ced22174d5e2.mp4

**Comment by Blurayx** [comment]
For some reason, my clearart is always blank. is there a setting I need to enable?

<img width="1589" alt="Screenshot 2021-03-14 at 02 55 21" src="https://user-images.githubusercontent.com/2873112/111055775-2c0aac80-8471-11eb-91d4-5fa0c340376e.png">

**Comment by jurialmunkey** [comment]
Extra artwork works well for me using Universal Movie Scraper and TMDb TV Shows Scraper. The only thing I had to do was refresh info for my movies/shows once I changed the settings to enable extra art. These are the settings I use:

![Honeyview_screenshot00011](https://user-images.githubusercontent.com/4618719/111057205-bdae0480-84d9-11eb-9556-afe80dfb9140.jpg)


![Honeyview_screenshot00012](https://user-images.githubusercontent.com/4618719/111057183-7b84c300-84d9-11eb-8c80-8ad0a2a1c654.jpg)


If you are using TVDb as your scraper, it should also be pointed out that it is no longer maintained. TVDb are switching to a paid subscription only model and Kodi team members have no interest in actively developing a scraper that requires payment to use. So if you are using TVDb as your scraper then you should switch to something else. Otherwise you will have to deal with issues like this until eventually it stops working completely when TVDb switch off the free API.

**Comment by Blurayx** [comment]
I'll stick with TVDb until the free API is switched off because it scraps 100% of my tv shows. TMDb only scapes about 80%.

Thanks
