### ISSUE TITLE
TMDB Helper Error Getting Reconfigured Players

### ISSUE THREAD

**Issue by dazazbab** [jurialmunkey/plugin.video.themoviedb.helper#460]
Hi,

Been having problems playing media from TMDBH. I tried playing from the context menu and from inside the addon. Keep on getting the same error:

_ERROR <general>: GetDirectory - Error getting /storage/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players/_

I checked and couldn't find that folder anywhere. 

On one of the earlier Matrix version of TMDBH I downloaded TMDB Players from _bit.ly/tmdbplayers_ and set up FEN to play Movies and Shows. Can't remember which version that started giving me this issue. Now I can't play or even configure players inside TMDBH.

Here's my log: http://ix.io/2T18

Thanks in advance. 🙏

**Comment by jurialmunkey** [comment]
That error is inconsequential and can be ignored.

The issue is this `RuntimeError: Unknown addon id 'plugin.video.thecrew'` which is causing an exception to be raised. Likely you have a player installed for this plugin but the actual plugin itself is disabled. Your options are either uninstall that plugin, enable the plugin, or delete the player file for it.

**Comment by dazazbab** [comment]
Aah.. that make sense.. I just migrated to Matrix and restore a backup from Leia.. I do see a lot of incompatible addons.. I’ll try those options and get back to you..

Thanks

**Comment by dazazbab** [comment]
Deleted the player file for the crew and exodus and everything works fine now. Thanks a lot!!
