### ISSUE TITLE
Maybe TMDb Helper is to blame for Fen and Shadow player issues?

### ISSUE THREAD

**Issue by cgcgcgcgcg** [jurialmunkey/plugin.video.themoviedb.helper#465]
Using Fen, after scanning it says "busy" without showing sources, I have to press Backspace to stop it.
Using Shadow it immediately  shows a TMDbH error.
Log with both players:
[Fen.kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/6193370/Fen.kodi.log)

**Comment by jurialmunkey** [comment]
Log indicates TMDbH is working as intended.

Probably misconfigured player file. My guess is that the addon you are calling expects a certain type of url encoding but the player file doesn't use any.

It probably works some of the time as long as the title is a single word. But once you have spaces or special characters then it will likely break because those aren't encoded in the format expected by the player addon.

Different methods for changing the encoding of values passed to the player can be found here:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes
