### ISSUE TITLE
Option to Flatten if only one season

### ISSUE THREAD

**Issue by unkn0wn234** [jurialmunkey/plugin.video.themoviedb.helper#467]
so when theres only one season it goes directly into episode view rather than seasons and only being one season to click into.

**Comment by drinfernoo** [comment]
There's a setting inside Kodi for this.

**Comment by unkn0wn234** [comment]
> There's a setting inside Kodi for this.

I have it enabled but it doesnt seem to affect TMDBH

**Comment by jurialmunkey** [comment]
Yeah, pretty sure that kodi setting only affects the library.

I'll have to think about best approach to do this as just rerouting the season path if there's only one will be problematic for skinners who rely on that path to display seasons for shows in the info dialog. And I can't just change the path for the show to point to season 1 because tmdb lists don't provide number of seasons as part of the basic info (ie would require a separate lookup on every tvshow item which is going to be much slower).

**Comment by jurialmunkey** [comment]
I decided against adding this as it will be too convoluted with other season paths.
