### ISSUE TITLE
[BUG] TMDB Helper sends the wrong episode to the player

### ISSUE THREAD

**Issue by movianlost** [jurialmunkey/plugin.video.themoviedb.helper#471]
themoviedb Helper sends the wrong episode to the player if I try to play an episode of an anime, this only happens to anime, other shows work fine and tmdbHelper sends the correct episode.

Even for anime it's a hit and miss, for example for 'Attack on Titan' it sends the correct episode, but for other anime like One piece, Naruto, Naruto Shippunden it send the wrong episode, if you want to test this, make sure to try a season that is not season 1 (season 1 works fine for any anime).

Here is an example and the log from the moment I started doing this test:

- clicked on One Piece, then season 5, then episode 1
- I read the log and find that tmdbHelper is sending payload that contain {seasson:5,episode:131} to player Elementum like this plugin://plugin.video.elementum/library/play/show/37854/season/5/episode/131
- I get an error because episode number is wrong, there is no episode 131 in season 5

Here is the log:
https://pastebin.com/raw/ZecPRkKX

**Comment by jurialmunkey** [comment]
That's the info that is on TMDb
https://www.themoviedb.org/tv/37854/season/5/episode/131

Tmdbhelper is working correctly. Tmdb reports the episode as S5E131 so tmdbhelper is sending the correct episode according to the info on the website.

The issue with anime is that tmdb uses the original Japanese TV rolling numbering where as tvdb uses the US release split numbering. The addon you are calling probably relies on tvdb.

And before you ask for an option to have tmdbhelper grab info from tvdb, the answer is no. There are a myriad of reasons why but most important is that tvdb will soon have a paid subscription model and will switch off their free API, so I'm not interested in writing code for a service that requires payment to use.

**Comment by movianlost** [comment]
From this issue: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/170
I have read this issue and other linked issues and now I have a better understanding.
I know that there is nothing that can be done with this because it's my player's fault for relying on tmdb api data and expecting that data to be compatible with other apis. With that said, and I know that this won't solve the issue, but I read about episode groups and you said in previous issues that you can access them, but I can't find it in the addon.

You said:

> At long last I've implemented this option - you can access episode groups from
> Tv Show > Context Menu > Browse lists > Episode groups

But I can't find Browse lists in the Context Menu of a any show.

Another question. I contacted the developer of Elementum,, the player that I use with Themoviedb Helper about getting rid of TVDB and only using data from TMDB, but he said he can't get anime's episode absolute number without using TVDB. 
From your experience, what would be the best solution to this? I suggested to calculate the absolute number based on the number of episodes on each season, for example, if show has {S1->20 episodes, S2->10 episodes, S3->50 episodes} and I want to know absolute number for S3E30 all I have to do is 20+10+30=60 which is absolute number.  But he said that this is not a guarantee to result in correct absolute number, what do you think?

**Comment by jurialmunkey** [comment]
> From your experience, what would be the best solution to this? I suggested to calculate the absolute number based on the number of episodes on each season, for example, if show has {S1->20 episodes, S2->10 episodes, S3->50 episodes} and I want to know absolute number for S3E30 all I have to do is 20+10+30=60 which is absolute number. But he said that this is not a guarantee to result in correct absolute number, what do you think?

~The problem is the opposite of what you think it is. On TMDb the episodes are already in Absolute order. That's why the [first episode of season five](https://www.themoviedb.org/tv/37854/season/5/episode/131) of One Piece is listed as Episode 131.~

~The issue is that on TVdb (which Elementum uses) the default is not absolute. For the [same episode on TVdb](https://www.thetvdb.com/series/one-piece/episodes/362049) the default ordering is "Aired Order" which lists the episode as Season 8 Episode 1~

EDIT: Sorry, I misread. I thought you were suggesting that TMDbH would add the episode numbers but I realised you were suggesting that the other addon do this to get the same absolute number.

In which case -- TVdb _already_ does have absolute ordering available, and which does list the Episode as 131 (e.g. look at [top of this page](https://www.thetvdb.com/series/one-piece/episodes/362049) and you will see the ordering available on TVdb). _However_, that ordering lists the Season as 1 (not 5 like on TMDb). So you still have a problem any way you slice it.

A few options I see - but all have downsides:

1. Since TMDb is already in absolute order for anime but the seasons differ from TVdb, you could create a separate player file specifically for anime that hardcodes the season as 1. This would require the addon that you're calling to have an option to set anime to absolute ordering. However, if this is a global setting in the addon (rather than a flag that can be passed in URI via the player) then you will run into the opposite problem with non-anime shows because those don't use absolute ordering on TMDb (but will now be in absolute order on your addon due to global setting).
2. If you look in the [available player keys](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#available-keys) you will see that TMDbH provides `{epid}` which is the TVdb episode ID. So if the addon you're using has a way to pass that through instead of season/episode numbers then that could be a possibility. Though the info for external IDs can sometimes be patchy on TMDb.
3. If the addon you're using provides an option to search for episodes (not just tvshows) OR if it has an option to flatten seasons, then you could potentially create a player that attempts to match episode on title rather than ID or season/episode numbers. With flatten seasons on, you could have a player that first searches for the tvshow, then because the season is flat the next step can then attempt to match on the basis of episode title.

Those are options are all going to vary in terms of reliability. Ultimately when two services have different approaches to ordering and numbering, it becomes really difficult to be able to get them to match up consistently.

> But I can't find Browse lists in the Context Menu of a any show.

Works fine for me both in Seasons view and from Context Menu > Browse Lists. Make sure that you don't have special episodes disabled in `TMDbHelper Settings > Navigation > Hide Specials / Up Next Folders`

![Honeyview_screenshot00031](https://user-images.githubusercontent.com/4618719/113362099-4b726680-9399-11eb-9821-7358cbdc9adf.jpg)

With that setting disabled you will get a "Special" season called "Episode Groups" in the seasons of a show:
![Honeyview_screenshot00030](https://user-images.githubusercontent.com/4618719/113362133-5e853680-9399-11eb-843c-ed65aeff2428.jpg)

You also get an "Episode Groups" option in the context menu under "Browse Lists" when opening the context menu on the show itself
![Honeyview_screenshot00033](https://user-images.githubusercontent.com/4618719/113362156-7066d980-9399-11eb-9061-8f9c1585bd0a.jpg)

**Comment by jurialmunkey** [comment]
I was reading your comment here https://github.com/elgatito/script.elementum.burst/issues/265#issuecomment-811422252 and I think maybe there is confusion all around.

TMDb _does_ use absolute ordering but _only_ for anime that aired in Japan under a rolling release (which is going to be pretty much all anime). For other tvshows it uses normal season aired order.

TVdb provides options for a few different ordering types, one of which is absolute ordering. However, TVdb's absolute ordering always sets season to 1 (unlike TMDb which sometimes includes season numbers as a way to split up rolling release shows with 100s of episodes).

Elementum already uses TVdb's absolute ordering for anime (unlike most other addons using TVdb which instead use the default ordering).  The problem that you're running into is that TMDb also includes season number in some cases.

In which case, your best option is to create a separate player for Elementum that is specifically for Anime and hardcodes the season to 1 -- i.e. duplicate your original player and give it a new name so that you then have two players: one for anime with the hardcoded season and one for other shows that passes through the season.

**Comment by movianlost** [comment]
Thank for you taking time to explain this in details, I will reply about your TMDB/TVDB suggestions after fixing Browse group issue.

I went to TMDB Helper settings and `Hide Special/ Up next` is are already disabled.

Here is what I did along with the screenshots. I brought context menu for show One Piece, then choose TMDBHelper Options, and you can see the options that are available there. Then I went back and entered One piece, there is no Episode Groups there, then I click again on One Piece, I have both `Up next` and `Specials` but no `Episode Groups`.

Here are the screenshots: https://imgur.com/a/6AcUvGF

**Comment by movianlost** [comment]
@jurialmunkey  should I open a separate issue for this?

**Comment by jurialmunkey** [comment]
What version of TMDbHelper do you have installed? From your screenshots it looks like a very outdated version because that details directory (3rd screenshot in your link) hasn't existed for a very long time. Since v4 that browse view has been a pop-up context menu.

**Comment by movianlost** [comment]
I got tmdbHelper addon from the official Kodi repository, now I see that they have the older version 2, after I updated using your repository, I can see the episode groups.

In this newer version, why are some seasons and episodes displayed in red?

![screenshot006](https://user-images.githubusercontent.com/81398427/113632158-295b3b80-965a-11eb-9836-cf6b05d76f4d.png)

**Comment by jurialmunkey** [comment]
Unaired episodes are marked in red. Anything missing air dates or with an air date in the future is treated as unaired. There's a TMDbH setting to toggle whether items missing airdates are treated as aired or unaired.
