### ISSUE TITLE
[BUG] After changing the language from English to Polish, the icons of the film genres will not appear

### ISSUE THREAD

**Issue by notoco** [jurialmunkey/plugin.video.themoviedb.helper#477]
After changing the language from English to Polish, the icons of the film genres will not appear
Screenshot with EN:
![screenshot00003](https://user-images.githubusercontent.com/36659110/113700456-281c2400-96d7-11eb-833c-3c25649b84c4.png)
Screenshot with PL
![screenshot00004](https://user-images.githubusercontent.com/36659110/113700549-42ee9880-96d7-11eb-9a2b-fd75edb4f730.png)
Screenshot with DE:
![screenshot00005](https://user-images.githubusercontent.com/36659110/113700639-60236700-96d7-11eb-8a31-d6b041a534c7.png)

(skin - my mod of your skin - some changes with fonts and vietypes) - but the same is on AH original

**Comment by jurialmunkey** [comment]
The issue is with the genre icon pack addon not having textures for polish filenames. Nothing to do with skin or tmdbhelper.

If you look in the textures for genre icon pack you will see that they have English filenames. All the skin does is point to the png in the genre addon that matches the label of the genre. So eg if the genre label is "Action" it points at "action.png". The issue is that when you switch to polish the label becomes "Ackja" and there's no "ackja.png". 

If you want to use the genre icon addon with Polish then you need to change the filenames in the textures xbt of genre pack to match the polish equivalents.

**Comment by notoco** [comment]
Thanks a lot for the info - it's logical, unfortunately.
So I correct and make my own version of genres texture :)
