### ISSUE TITLE
[Request] Only update library for new episode

### ISSUE THREAD

**Issue by Logs22** [jurialmunkey/plugin.video.themoviedb.helper#487]
I doubt this is possible, which is why I'm starting off the request like this. It would be cool if there was a feature alongside the "Update Library Now" button there was something like "update new episodes now" that only scrapes for either new episodes, or starts at the last season of a show so that its not going through a bunch of seasons that haven't changed.  I know for some with massive libraries the update check can take a long time, and I thought that that could solve the problem. 

Thanks for reading!

**Comment by jurialmunkey** [comment]
The auto update already keeps a log of what has been updated and only checks most recent seasons of shows currently airing (I'm simplifying a bit here - the actual rules a bit more complex than that but the general idea is that the auto update skips unnecessary checks for already added items or shows not currently airing).

The update button in the settings dialog is a "forced" update which resets the log and runs through the update as if it had never been done before.

The scheduled auto-update is sufficient on its own. There is no reason to be using the forced update button in settings regularly. The only real reason to use the force update button in the settings is if you want to rebuild your library (e.g. you deleted the folder, cleaned the library and want TMDbHelper to recreate the strm files).

**Comment by delluser** [comment]
The auto update waits to long to happen.  When I start kodi it takes 25 minutes for the update to occur.  Is it possible to have it update the TMDB Helper on start up of kodi or after a given period of time after start up.  I have the kodi library set to update library on start up but if the TMDB Helper does not update right away then there is nothing to update.  Setting a time to update does no good. Mine is set for 12am and it has not updated in 2 days. I have to use the update now function and we know what that does but it does update then. Why not have the option to check for updates every time kodi is started instead of a certain time.  Other than this issue the addon works very well and is a wonderful asset to kodi.  I hope that you can help in this matter.    Thank you

**Comment by jurialmunkey** [comment]
There's a setting already to update kodi library after the update is done, so there's no need to also set kodi to update on startup.

The update happens 10 minutes after the service starts (600 seconds to be precise). If it takes 25 minutes on your system, then that indicates a long delay in kodi startup and no change to my code is going to change that.

There's a reason why it is delayed 10 minutes and that's to give systems time to start without bogging things down with a hdd heavy process that will slow startup down even more. If your system is already struggling to startup then that will just make things worse.

**Comment by delluser** [comment]
Ok then. Thank you for the information. Now I know what to expect. Again, Thank you for your response.

**Comment by delluser** [comment]
I updated my build and now the TMDBhelper will no longer update even after the ten minute wait. any ideas. i'm using the lastest version from the kodi repo.
