### ISSUE TITLE
[BUG] Inconsistencies in TMDBHelper (and service monitor) Properties - Studio.1.

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#499]
When returning the list of Studios using `Window(Home).Property(TMDbHelper.ListItem.Studio)` and we want to select the first studio using `Window(Home).Property(TMDbHelper.ListItem.Studio.1.Name)`, the returned studio doesn't match the first item in the list. The same issue happens with `ListItem.Property(Studio.1.Name)`.

Here are some examples from DevHelper to make it easier to see:

The Falcon and the Winter Soldier (TMDBHelper - TV shows - Popular - addon widget): https://i.imgur.com/V8e1aAz.png
- Position 1 should be Disney+, not Marvel Studios
- Position 2 should be Marvel Studios, but it is empty

The Flash (TMDBHelper - TV shows - Popular - addon widget): https://i.imgur.com/U3wshH4.png
- Same symptoms as above, position 1 is missing, the other positions have moved up in its place

Game of Thrones (other addons' widget) : https://i.imgur.com/gOHYXP2.png
- Same symptoms as above, HBO is missing when it should be position 1.

This bug makes it difficult to select the first studio, which almost always has a remote logo we can utilize.

**Comment by jurialmunkey** [comment]
The problem is that the TMDb API has two different keys for tv show studios - "networks" (i.e. the distributor - e.g. Disney+) and "production companies" (i.e. the creator - e.g. Marvel Studios) - whereas for films there's only the one key (production). Since both are mapped to studios, when the properties are written for production they overwrite the one from networks.

In latest matrix I've added a separate property called "network". So you can now use `ListItem.Property(network)` to get only the network and you can get positional with ListItem.Property(network.1.name) [or equivalent window property for service monitor - also can get tmdb_id or icon instead of name just like with studio].

Network will still be included in ListItem.Studio since many skins rely on ListItem.Studio - but really I should remove it from there entirely because technically a network is a distributor not a studio.

**Comment by inb4after** [comment]
Thanks for the quick fix and explanation once again! I will test it out soon.

**Comment by SerpentDrago** [comment]
I always would have preferred to have network. Amazing *fix*. Love it!

**Comment by inb4after** [comment]
Working well so far during testing, thanks again for this 🥇

**Comment by inb4after** [comment]
@jurialmunkey 

Apologies for this off-topic, but I've run into a small/big issue which I think might be a Kodi bug.

I've set the TV network image to a control with an ID, 90645:

https://github.com/SerpentDrago/skin.auramod/blob/d704e905bd0344bfafe1fcb07bb93995d8899a5e/1080i/Includes_Object.xml#L4176

This works fine in **Home.xml**, `Control.GetLabel(90645) == image path`.

But when the window is **MyVideoNav.xml**, the **label** of control 90645 (the **image path**) is empty.

**Even though** the network image is displayed correctly and `Control.IsVisible(90645) == true`.

Is there anything that could prevent the image control from not having a label in a certain window? It seems very strange that it works fine for Home.xml, but not MyVideoNav.xml

I also tested a label control `<control type="label" id="90647">` and the `<label>` within **is** correctly applied to the ID and can be GetLabel'd, so this bug only specifically affects image controls `<control type="image" id="x">` in MyVideoNav.xml?

**Comment by jurialmunkey** [comment]
Do you include that control in multiple views? Probably have a duplicate somewhere so you have two controls with same id.

**Comment by inb4after** [comment]
> 
> 
> Do you include that control in multiple views? Probably have a duplicate somewhere so you have two controls with same id.

That was exactly the problem, fixed this and it worked!

I assigned `1$PARAM[studioid]` and `2$PARAM[studioid]` (one for each image - tvshows and movies) and changed the ID each time the include is used.

Thanks so much, it was bugging me for a while 🤣

**Comment by SerpentDrago** [comment]
@jurialmunkey think i noticed you didn't have have a white / monochrome for certified fresh. Friend made one for me your free to use.

https://github.com/nativeit/rt_trans/tree/main/iconpack
