### ISSUE TITLE
[Feature completion] Sort order for Trakt Lists

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/plugin.video.themoviedb.helper#502]
I made a Trakt list 'Anime' to which I add Anime-shows I watch. To keep Anime seperate from regular tv-shows I use Trakts 'hide' to not have Anime show up in my NextUp widget.

I want to get Trakts sort order RecentlyWatched working for widgets.

My Anime-MyList-widget would then start with the most recently watched series, that would be good.  Trakt is allready showing my list like this.

1. If I create a widget from this list (Trakt/YourLists/Anime) the wizard lets me decide 'sort by' before creating the widget. 
 The wizard shows Rank/Added/Title/Year/Random.  Trakt provides on top of these Popularity/Percentage/Votes/MyRating/RecentlyCollected and the one I'm interested in RecentlyWatched.  Is it possible to add this/these sort methods ?

2.  For widgets TmdbHelper (in some cases probably) has two concurrent/conflicting sort-methods (I think). The one while creating the widget described above and then 'Sort Method' for created widgets.  Under SortMethod I find among others LastPlayed, LastUpdated and LastUsed but these 3 don't give me the result Trakts RecentlyWatched gives (because  also SortBy).

3. Small remark : The widgets label gets named "Sort by: Added" instead of the Lists name.  Shouldn't the label refer to a name instead of a sort-method?

I remember we talked a few years ago also about sort-order for Trakt. I hope 1 and 2 above refer to new trakt features not implemented yet into TmdbHelper.

**Comment by jurialmunkey** [comment]
(1) Not really possible with the data that the API returns. Trakt sorting is done client side (not server side) and the API for lists doesn't return data about watched info. The example below shows what the API data returns for a list. As you can see it really only has data for sorting by Rank, Added (listed), Title, Year, and Random.
``` python
{'rank': 1, 'id': 483442186, 'listed_at': '2020-03-03T02:50:15.000Z', 'notes': None, 'type': 'show', 'show': {
    'title': 'Justified', 'year': 2010, 'ids': {
         'trakt': 1427, 'slug': 'justified', 'tvdb': 134241, 'imdb': 'tt1489428', 'tmdb': 1436, 'tvrage': 23472}}}
```

(2) You're confusing TMDbH sorting methods which happen at the plugin code level before the list is displayed and Kodi sorting methods which are applied on the displayed items returned from the list. That's why you don't get the same results - because those Kodi sort methods in the skinshortcuts dialog are just sorting the first page of items. TMDbH doing that type of sorting on the whole list at the plugin level would require individual detailed info lookups for every item in the list, so it would be incredibly slow (potentially 1000s of lookups if the list was large). Trakt website can sort like that because they can make a special API call with the required data but 3rd party apps are limited to the data shown above.

(3) The naming is a Skinshortcuts thing. Skinshortcuts pulls the label from the name of the folder (which I need to label as the sort method otherwise you wouldn't know what you're clicking!). I've pushed a little update to put the sort method on a newline in the label under the list title, which should help a fair bit here.

**Comment by DaisyF8** [comment]
1 and 2 are very clear now, and thx for 3.

**Comment by jurialmunkey** [comment]
@DaisyF8 - Actually just thought of a decent way to do this that isn't too performance intensive. Can you test latest matrix github version - should now be able to sort by watched (I've also added a few additional sort methods that are possible now). It is going to be slower than the other sort methods (and I wouldn't recommend it on really large lists) but otherwise it looks to be working fairly well.

**Comment by DaisyF8** [comment]
@jurialmunkey Yeah looks to be working okay.  I'll test some more and let you know.

Awesome :)

**Comment by DaisyF8** [comment]
And 3 yesss, Widget name now refers to the List name instead of SortedBy.

**Comment by DaisyF8** [comment]
@jurialmunkey If you add a Watchlist widget now (both TV and Movies) the widget title is 'None'

Edit : Is applicable to any list that isn't a Trakt list I think.

**Comment by DaisyF8** [comment]
Some skins are probably going to have confused formatting because of that carriage return if they don't provide for multiline in their (settings) layout.

**Comment by DaisyF8** [comment]
I have a fun new request caused by what you just added :)

4. Arctic Horizon shows in the folder of every Show I'm currently watching another folder 'UpNext'. This contains the first unwatched episod of that show and following, **even if I choose 'Hide' on the Trakt-website** (which is good, in my case I Hide certain shows to not have anime show up in Trakts Next Up).

So the question is : Can TmdbHelper generate a NextUp specific to a (personal) Trakt-List ?

That way you could have an UpNext for a list.  What I have now (thanks to your newly added SortByWatched) is an ordered list of Shows from a List in a widget.  Can I have the Next episodes for every show in that list (Sorted By Watched) ?

**Comment by jurialmunkey** [comment]
> If you add a Watchlist widget now (both TV and Movies) the widget title is 'None'. Is applicable to any list that isn't a Trakt list I think.

Ah yep you're correct. I forgot that I also use the same list of sort methods for collection/watchlist etc. Should be fixed now (and I've also removed the extra sort methods for those as they won't work there - new sort methods will only work for user lists at the moment).

**Comment by jurialmunkey** [comment]
> That way you could have an UpNext for a list. What I have now (thanks to your newly added SortByWatched) is an ordered list of Shows from a List in a widget. Can I have the Next episodes for every show in that list (Sorted By Watched) ?

That's an interesting idea. So it'd essentially be "Your Next Episodes" list but instead of being based on watched history, it'd be based off a custom list. Could work if it was limited to one episode per show in the list and sorting is done beforehand (i.e. instead of each tvshow item, it displays the next episode to watch for each tvshow - and once you watch something the episodes in the list then update). 

I'll have a think about how to achieve this - definitely could be a really useful feature.

**Comment by DaisyF8** [comment]
Naming is solved with latest commit. Extended sorting is stil there with In Progress for example, maybe intentional.

**Comment by jurialmunkey** [comment]
Not sure if you meant to close this issue but I do intend to implement the "Your Next Episodes" from a Trakt list feature eventually, so I've created a new issue specifically for that.

**Comment by DaisyF8** [comment]
Oops sorry. I thaught it was on a separate todi-list of yours.
