### ISSUE TITLE
.strm files

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#51]
Hi and thank you for this amazing addon.

Is it possible to bring back the function that allow us to play .strm files from the kodi library? A large part of my movies collections are links provided by an online premium account that I own.. I decided to download all my movies there when I realize that Themoviedb helper give me the chance to use my External hard drive for something else. 

So, this was a very important function for me ;)

Thanks for your help!

**Comment by drinfernoo** [comment]
What do you mean by "bring back"? The latest versions on GitHub have it just introduced the feature...

**Comment by jurialmunkey** [comment]
@drinfernoo I think @alKODIque means the TMDbHelper playing local `.strm` files that are *not* from TMDbHelper. I had to disable playing local .strm files with the player because otherwise I would end up in a recursive loop where TMDbHelper .strm files in the library would try to play themselves.

@alKODIque - Can you test latest version? I've added a check to determine whether or not the .strm is from TMDbHelper and only play if it is from some other source (otherwise reverts to an external player as it currently does).

**Comment by alKODIque** [comment]
> @drinfernoo I think @alKODIque means the TMDbHelper playing local `.strm` files that are _not_ from TMDbHelper. I had to disable playing local .strm files with the player because otherwise I would end up in a recursive loop where TMDbHelper .strm files in the library would try to play themselves.
> 
> @alKODIque - Can you test latest version? I've added a check to determine whether or not the .strm is from TMDbHelper and only play if it is from some other source (otherwise reverts to an external player as it currently does).

@jurialmunkey 
Yes, that’s exactly what I meant... Sorry for my poor English by the way.
I will test the latest version tonight and come back to you.
I was thinking about the possibility to add a kind of « kodi library player » if there is no other possibility. Do you think that,s something possible?

**Comment by alKODIque** [comment]
With the latest update you made, everything is working like before! I can play movies from my kodi library who provides from .strm files :)
Thank’s a LOT!

**Comment by jurialmunkey** [comment]
Excellent thanks for testing!
