### ISSUE TITLE
[Question] Translate $INFO[Window(Home).Property(TMDbHelper.ListItem.Status)]

### ISSUE THREAD

**Issue by wsx79** [jurialmunkey/plugin.video.themoviedb.helper#510]
I translate the skin I Use in Italian language.
Now it's very good but I have the status of tv series in English.
The skin take this from tmbdhelper and It comin in english.
There is the possiblity to translate in Italian?

![Immagine](https://user-images.githubusercontent.com/68690475/122684785-e431b900-d207-11eb-959c-92f59c67010f.jpg)

**Comment by jurialmunkey** [comment]
It comes that way from the API. I don't set the naming of that field. Library scrapers also leave it untranslated. 

It needs to stay untranslated because it's the only way a skin can check the status of the show - if it gets translated then skins can't check against the field to see if a show is cancelled or returning etc (eg that text being set to green in your screenshot likely relies on check against the status to see if it is set as returning).

The translation should be done at skin level via a variable.

**Comment by wsx79** [comment]
Thanks.
I made it by skin using

`
	<variable name="Label_Info_NextAired_Status">
		<value condition="String.Contains(Window(Home).Property(TMDbHelper.ListItem.Status),Returning Series)">$LOCALIZE[31861]</value>	
		<value condition="String.Contains(Window(Home).Property(TMDbHelper.ListItem.Status),Planned)">$LOCALIZE[31862]</value> 
		<value condition="String.Contains(Window(Home).Property(TMDbHelper.ListItem.Status),In Production)">$LOCALIZE[31863]</value> 
		<value condition="String.Contains(Window(Home).Property(TMDbHelper.ListItem.Status),Ended)">$LOCALIZE[31864]</value> 
		<value condition="String.Contains(Window(Home).Property(TMDbHelper.ListItem.Status),Canceled)">$LOCALIZE[31865]</value> 
		<value condition="String.Contains(Window(Home).Property(TMDbHelper.ListItem.Status),Pilot)">$LOCALIZE[31866]</value> 
	</variable>
`

**Comment by inb4after** [comment]
@jurialmunkey Do you know of any solutions/workarounds for localizing OMDB data? I've looked at the API briefly, but I don't think they even support translated details? 

For example, `Window(Home).Property(TMDBHelper.ListItem.Awards)` will always be in English: `X wins & Y nominations.`

**Comment by jurialmunkey** [comment]
@wsx79 - Excellent. FYI you might want to use `String.isEqual` instead as it is much faster than `String.Contains`.

@inb4after - Yeah, all OMDb data is English only. However, I do give the number of wins and nominations as individual values (I grab them from the main awards string via a regex), so you can use translate at the skin level for eg `$info[window(home).property(tmdbhelper.listitem.oscar_nominations),nominated for, oscars] `

Obviously you need to localise the "nominated for" text but you should be able to create a string in a skin that is localised using that. Check the wiki for the others (I do it for wins and nominations for oscars and awards). https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor

For the rotten tomatoes review consensus obviously not possible since it is a large block of text but at least awards can be.

**Comment by inb4after** [comment]
> @wsx79 - Excellent. FYI you might want to use `String.isEqual` instead as it is much faster than `String.Contains`.
> 
> @inb4after - Yeah, all OMDb data is English only. However, I do give the number of wins and nominations as individual values (I grab them from the main awards string via a regex), so you can use translate at the skin level for eg `$info[window(home).property(tmdbhelper.listitem.oscar_nominations),nominated for, oscars] `
> 
> Obviously you need to localise the "nominated for" text but you should be able to create a string in a skin that is localised using that. Check the wiki for the others (I do it for wins and nominations for oscars and awards). https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor
> 
> For the rotten tomatoes review consensus obviously not possible since it is a large block of text but at least awards can be. 
> 
> 
> 
> 
> 

Thanks for the hints and explanations, it will definitely help us out. 

I've also already merged with changes OP's PR to `String.IsEqual` for this reason as well!
