### ISSUE TITLE
[Bug] Clear Logo in Episodes is only visible in Specials

### ISSUE THREAD

**Issue by Edd75** [jurialmunkey/plugin.video.themoviedb.helper#516]
Hi dev,
Using Kodi on nvidia Shield. When I select a tv show from home, I can see the clear logo, but in the seasons view, the logo display disappears (in some cases I have seen it appear, but in very few cases), although in Specials it can be seen. By pressing on the episodes, it is displayed again.
Can the clear logo be made to display in the seasons view?
Thanks for your help!

**Comment by jurialmunkey** [comment]
Clear Art displays fine for me at season level in Arctic Horizon with fanart.tv enabled for service monitor in TMDbH settings.

**Comment by Edd75** [comment]
Correct me if I'm wrong, but Arctic Horizon doesn't have this Seasons view.  
I have enabled fanart.tv as well in TMDB Helper settings.
Could it be that TMDB Helper is only for this skin?
Thank you very much for your work!

**Comment by matke-84** [comment]
@jurialmunkey This little bug has been around for a long time. I left the post a couple of months ago. As far as I can see, he hasn't solved it yet.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/403#issuecomment-753592965

**Comment by jurialmunkey** [comment]
@matke-84 - That's a bug with Arctic Horizon not referencing the service monitor for clearlogo (whereas it does properly for clearart). I just pushed a fix to Arctic Horizon for that bug.

EDIT: Also just pushed a fix for TMDbH which will fix up some inconsistencies between "normal" and "special" seasons so that they will both grab full details.
