### ISSUE TITLE
[BUG] TMDBHelper and episode tmdb_id/imdb_id

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#519]
I have run into an issue where TMDBHelper will not return service monitor properties, if it is given `episode` tmdb_id/imdb_id. This results in missing meta compared to when `tvshow` tmdb_id/imdb_id is given.

Here are some screenshots to better explain this (Lucifer S02E08):

Episode ID given: https://i.imgur.com/MoquCTR.png
Effect on skin: https://i.imgur.com/i2ub0Zg.png

TVShow ID given: https://i.imgur.com/hjuatgL.png
Effect on skin: https://i.imgur.com/xAPhaET.png

Notice that service monitor properties when episode ID is given are empty. This tells me that TMDBHelper doesn't currently support episode ID lookups or there's a different issue preventing the properties from being set.

This only affects episodes, and TV shows and movies are working fine. Is it possible for TMDBHelper to support episode ID + tvshow ID simultaneously?

**Comment by jurialmunkey** [comment]
How would it be able to tell apart an episode id from a tvshow id if they are stored in the same field? Without something to distinguish the ids it is impossible to tell what they are for and so it has to be assumed that they're tvshow ids

**Comment by jurialmunkey** [comment]
BTW it doesn't use `ListItem.UniqueID(tmdb)` at all - the service monitor only uses `ListItem.IMDbNumber` for v18 backwards compatibility. ~~This is the first time I've come across an episode storing the IMDb number for the episode~~ 
EDIT: Wow, I just realised my own library has IMDb episode IDs stored - must be a new addition for the v19 scraper. Shows how often I play things directly via the library rather than using TMDbHelper to choose where to play from.

EDIT: Since there's no way to distinguish if it is a tvshow or episode ID, I think the best approach might be to ignore the ID altogether for episodes. Patch incoming.

**Comment by inb4after** [comment]
I did look through some of the code which uses season and episode numbers as well as the show ID so I can understand why episode ID is not really needed.

Would a potential (by no means required) solution be: Send a request to TMDB and return if the ID is for an episode or a TV show/movie, but that is probably a request you would rather not make in the first place?

Because most items from library or widgets have `ListItem.IMDbNumber` as a hybrid field (either tmdb_id or imdb_id) especially on v18 this now makes a lot more sense to me why TMDBHelper was coded to use both and should expect only `tvshow` ID or bad things will happen!

Not to mention your point about `ListItem.UniqueID(tmdb.tvshow)` and `ListItem.UniqueID(tmdb.episode)` etc. not existing and even if switched to, would break backwards compatibility.

Thanks for your input on this.

**Comment by inb4after** [comment]
Tested the patch, I am now getting ratings for episodes across skin!

https://i.imgur.com/VbuQy4c.png

Is TMDBHelper preferring to use query instead?

Thanks again.
