### ISSUE TITLE
[BUG] Visual inconsistency in ListItem.Cast vs. Window(Home).Property(TMDbHelper.ListItem.Cast)

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#528]
For cast list summary, we use `Window(Home).Property(TMDbHelper.ListItem.Cast)` which condenses the cast list nicely into a `/` separated list for easy display on spotlight widget.

How the window property normally looks: https://i.imgur.com/aIrGAf3.png

How the info property looks now: https://i.imgur.com/2GLDHGZ.png

Inconsistencies shown here, for both the container(id) and focused info property: https://i.imgur.com/nQ6Yp1X.png

However, in order to fix the issue of focusing normal widgets changing the spotlight content, we must use `Container(1505).ListItem.Cast`, but from the above screenshots, it doesn't display as intended and we lose a lot of cast members as a result.

It would be beneficial if ListItem.Cast used the same `/` separated list as the service monitor.

**Comment by jurialmunkey** [comment]
The cast property of a listitem is a list (not a string) containing cast member listitems (eg icon, role etc not just name). Kodi controls how those cast names from the cast list are then concatenated into the listitem.cast string. 

On the flip side, a window property *must* be a string - hence why TMDbH is concatenating names into one string for the window property

Btw this has been an issue for years:
https://forum.kodi.tv/showthread.php?tid=209540

**Comment by jurialmunkey** [comment]
Should be able to use `Container(ID).ListItem.Property(Cast)` now to get a ` / ` separated concatenated list of cast members (note it isn't ListItem.Cast because I can't control how Kodi writes that - so I output to custom Property(Cast) instead).

I've also fixed the positional properties for cast, as I just realised they weren't working (crew/writer/production etc ones were just not cast) - e.g.
ListItem.Property(Cast.1.Name) 
ListItem.Property(Cast.1.Role) 
ListItem.Property(Cast.1.Thumb)

**Comment by inb4after** [comment]
Thanks for the quick fix!
