### ISSUE TITLE
[BUG] IMDB_Votes and Trakt_Rating/Trakt_Votes visual inconsistencies

### ISSUE THREAD

**Issue by inb4after** [jurialmunkey/plugin.video.themoviedb.helper#529]
IMDB_Votes bugs:

https://i.imgur.com/1DLD0Ss.png

1\. `ListItem.Property(IMDB_Votes)` needs comma formatting to match `Window(Home).Property(TMDBHelper.ListItem.IMDB_Votes)`

Trakt_Rating/Trakt_Votes bugs:

https://i.imgur.com/f4rgUWo.png

1\. `ListItem.Property(Trakt_Votes)` and `Window(Home).Property(TMDBHelper.ListItem.Trakt_Votes)` needs comma formatting

2\. `ListItem.Property(Trakt_Rating)` needs to be rounded to 1 decimal place instead of 2; `Window(Home).Property(TMDBHelper.ListItem.Trakt_Rating)` is already correct here

3\. `Window(Home).Property(TMDBHelper.ListItem.Trakt_Votes)` decimal place needs to be removed as votes are always whole numbers; `ListItem.Property(Trakt_Votes)` is already correct here

**Comment by jurialmunkey** [comment]
Where are you getting these ListItem.Properties from? TMDbHelper doesn't fill these. There's absolute no point trying to sync formatting with random plugins or library scrapers because they can all vary.

**Comment by jurialmunkey** [comment]
I've fixed the `Window(Home).Property(TMDBHelper.ListItem.Trakt_Votes)` comma formatting because that's was a bug where I accidentally was applying rating formatting rather than vote formatting.

All rating formats in TMDbHelper Service Monitor window properties are either: a single decimal place score out of ten; OR a whole integer percentage out of 100. That's done so generally scores stay three characters wide (e.g. 8.1 or 81%).
 
The rest have nothing to do with TMDbHelper. TMDbHelper doesn't fill ListItem.Property() with votes or ratings. Like I said, there's no point attempting to sync with other plugins or scrapers as these can all vary. And impossible to change the properties of listitems for _other_ plugins or the library...
