### ISSUE TITLE
TMDB Adding items to library from multiple trakt lists duplicates stuff and adds entries ending with (TMDB id) 

### ISSUE THREAD

**Issue by patel-jeel92** [jurialmunkey/plugin.video.themoviedb.helper#538]
I have library integration enabled and have added items to my local library. However, I see that some of the tv shows are duplicated. The duplicated items differ in folder name with them ending in TMDB id. For example, I have 2 entries for the following tv show

3% (2016) 
3% (2016) (TMDB 68467)

I use TMM to manage my media. The one without the TMDB ID gets recognized by TMM and has tvshow.nfo populated fully. The one with the TMDB ID  has a tvshow.nfo as well but it only has https://www.themoviedb.org/tv/68467 inside it

**Comment by jurialmunkey** [comment]
You cannot edit the tvshow.nfo file. It is what TMDbH uses to determine whether it is "its" folder and is safe to write to. 

If you edit that file then TMDbH will create a new folder to avoid accidentally overwriting files that it shouldn't. It has nothing to do with multiple lists.

**Comment by patel-jeel92** [comment]
Isnt there a better way to check if it is "its" folder? For example, the directory set in setting for movies and tv shows? 

So does this mean in kodi will scan two items which the are the same in my library? One without the (TMDB 68467) in the title and one with?

**Comment by jurialmunkey** [comment]
> Isnt there a better way to check if it is "its" folder? For example, the directory set in setting for movies and tv shows?

No. Firstly, the directory could be a shared source which already contains other content that the user doesn't want overwritten.

Secondly (and more importantly), it is possible to have two different shows with the same name.  TMDbH retrieves the TMDb ID from the `tvshow.nfo` file to determine that it is writing to the correct version of the show. 

For instance, there are two shows called "The Office" - the original UK series and the US remake. See also: The Twighlight Zone, Perry Mason, The Goldbergs, The Wonder Years, Full House (the list goes on). Without a reliable way to check the TMDb ID, you'd end up overwriting The Office UK episodes with the US version (or vice versa) and they'd be mixed up in your library.

The reason I don't use a different method is due to backwards compatibility. Originally I simply wrote out to the folder name without checking the TMDb ID and the issue of similar named but different shows only came up once users already had established libraries. Using the existing `tvshow.nfo` written by TMDbH was a simple way to determine which show was already in each folder.

> So does this mean in kodi will scan two items which the are the same in my library? One without the (TMDB 68467) in the title and one with?

If you have the same show split over two folders and the folders don't have the same name, then Kodi will create two library entries for the show when you scrape them (assuming you use an online scraper and not just local .nfo scraper). The name won't be different - you'll just have two shows called "3%" in your library each linked to one of the folders.

You won't have duplicate episodes because TMDbH doesn't add episodes that are already in the library, but the episodes will be split over the two folders (basically whatever was in the folder before you edited the .nfo will be in the plain name folder, and whatever was added after will be in the new folder with the ID affix).

**Comment by jurialmunkey** [comment]
Okay so I've added on option on latest github matrix version which will force TMDbH to use `tvshow-tmdbhelper.nfo` instead
`TMDbH Settings > Library > Use alternative .nfo filename to avoid externally managed .nfo conflicts` 
(you might need to scroll down to see the option)


Once you've enabled this option, probably the easiest thing to do would be to delete the TMDbHelper library folder and rebuild it from scratch:

- Delete the entire folder
- Clean Kodi library to remove existing entries `Kodi Media Settings > Library > Clean library... (Expert level)`
- Force TMDbH update via the "Update library now" option in TMDbH settings.


If you wanted to try to salvage what you've already got instead, you could do the following (it's a bit more work but it'll avoid wiping the entire library and your existing TMM .nfo files).

- Delete any of the folders that have the `(TMDb 12345)` style affix
- Clean your Kodi library to remove those entries from the library
- In each of your tvshow folders create a `tvshow-tmdbhelper.nfo` text file containing the TMDb URL with the correct ID number `https://www.themoviedb.org/tv/12345`
- Force the library update via the TMDbH setting "Update library now"

**Comment by patel-jeel92** [comment]
Thanks for the detailed explanation. I understand why the duplicate items are occuring now. The reason I chose TMM to manage my media was because it creates a tvshow.nfo file for the whole show and scrapes artwork, subtitles, actors, rating, and everything and creates loads it into the tvshow.nfo file which is kodi compatible. That way when this item is scanned by kodi, it doesn't have to scrape as that info should already be available. 

I know Kodi wants tvshow.nfo file to be in a certain format and TMM provides that which i find very useful.

I have another idea and let me know if this doesn't work. So instead of creating a new folder, can TMDBh check if tvshow.nfo exists? If it does, check for the TMDB id inside the xml (Check this link for what the xml is supposed to look like: https://kodi.wiki/view/NFO_files/TV_shows). If it does, use that. If it doesn't, check if tvshow.nfo file has a url of type `https://www.themoviedb.org/tv/12345`, if it does, use that, if it doesn't then create a new folder with tvshow.nfo with the url or with what kodi expects with just the minimal information such as the tmdbid.

Also, If I was to go with the second option where I manually added the `tvshow-tmdbhelper.nfo` file in each folder, would the name of the file actually be just `tvshow.-tmdbhelper.nfo` or would i replace tvshow with the name of the show. So `3%-tmdbhelper.nfo`?

**Comment by jurialmunkey** [comment]
> I have another idea and let me know if this doesn't work. So instead of creating a new folder, can TMDBh check if tvshow.nfo exists? If it does, check for the TMDB id inside the xml 

I did consider that but it doesn't deal with the issue of marking the folder as acceptable for TMDbH to write to. 

More importantly though, TMDbH will overwrite your .nfo file. This is particularly an issue for settings dialog update which is intended to be a _forced_ update that writes out new .strm and .nfo files for each show (unlike the auto-update which only adds missing shows and episodes).

That's why I added the alternative .nfo filename option. That way your `tvshow.nfo` made with TMM will be left alone and TMDbH will write the url out to `tvshow-tmdbhelper.nfo` instead.

> Also, If I was to go with the second option where I manually added the tvshow-tmdbhelper.nfo file in each folder, would the name of the file actually be just tvshow.-tmdbhelper.nfo or would i replace tvshow with the name of the show. So 3%-tmdbhelper.nfo?

Filename literally should be `tvshow-tmdbhelper.nfo`

It doesn't really matter that much though. TMDbH checks all the .nfo files in the folder until it finds one it can extract the URL from. The only difference will be that TMDbH will write the missing `tvshow-tmdbhelper.nfo` file once it finishes updating the show so now you'll have three - `tvshow.nfo` `tvshow-tmdbhelper.nfo` and `3%-tmdbhelper.nfo`

**Comment by patel-jeel92** [comment]
Sounds good. Thanks for your help

**Comment by patel-jeel92** [comment]
If I manually install the zip from the master branch right now, will the addon auto update later when there are new updates?

**Comment by drinfernoo** [comment]
@patel-jeel92 The latest version (4.3.27) should be available on repo, without needing to manually install.

**Comment by patel-jeel92** [comment]
Its not showing up yet. From the alpha repo v2.2 right?

**Comment by drinfernoo** [comment]
@patel-jeel92 That's correct. Open the context menu on the repository and choose "Check for updates". I updated it around nine hours ago.
