### ISSUE TITLE
[BUG] Error when trying to click on any videos in context menu “Browse Lists”

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/plugin.video.themoviedb.helper#548]
Every time you go manually into any title's **Browse Lists < Videos** under context menu and then click on any of the trailers, teasers, etc. nothing plays and throws a tmdb helper error; I'll provide a debug log and clip below showing the issue.

**Debug Log:** https://paste.kodi.tv/mevovohefa

**Video Clip showing steps to get to the issue:** https://streamable.com/738pb6

**Comment by jurialmunkey** [comment]
Ah yes I see what you mean. It's not adding the youtube URL to the path properly anymore and instead is adding the generic player path.

I should be able to fix this issue - I'll get back to you sometime over the weekend.

**Comment by Nuklear92** [comment]
Thank you, sir! 🙏

**Comment by jurialmunkey** [comment]
Okay, latest git version (4.3.33) should fix this issue.

I've also made a few improvements

- Videos related to the specific episode or season will be combined with videos for the base tvshow. The episode specific videos will be at the front, then the season specific ones, and the finally the general videos for the base show.
- Details from the movie/show will be added to give artwork and extra info rather than default icons
- EDIT: pushed an update that will also add the thumb of the video (v4.3.34)

Could you please test latest git version and confirm it is working for you?

**Comment by Nuklear92** [comment]
> Okay, latest git version (4.3.33) should fix this issue.
> 
> 
> 
> I've also made a few improvements
> 
> 
> 
> - Videos related to the specific episode or season will be combined with videos for the base tvshow. The episode specific videos will be at the front, then the season specific ones, and the finally the general videos for the base show.
> 
> - Details from the movie/show will be added to give artwork and extra info rather than default icons
> 
> - EDIT: pushed an update that will also add the thumb of the video (v4.3.34)
> 
> 
> 
> Could you please test latest git version and confirm it is working for you?

I'm not being prompted or can't manually update to the latest one you pushed, still says my latest version from repo is 4.3.31 🤷‍♂️

**Comment by jurialmunkey** [comment]
I didn't add it to the repo. 

You will need to download the zip from github and install via zip. Otherwise you'll need to wait for @drinfernoo to add it to the repo as he kindly manages that side of things for me.

**Comment by drinfernoo** [comment]
@jurialmunkey I already did 😉

**Comment by Nuklear92** [comment]
So, just tested the fixes and now it's working correctly, thumbnails are being displayed and videos are playing no issues. Thanks for the fix 😃👍
