### ISSUE TITLE
[BUG] WARNING <general>: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): ...

### ISSUE THREAD

**Issue by jmh2002** [jurialmunkey/plugin.video.themoviedb.helper#549]
I seem to have developed a memory leak that leads to running out of memory and Kodi freezing.

I've gone through the process of disabling the various installed addons and I _think_ it may be TMDBH that is causing the issue (but I'm not 100% sure).

I have the following message in the log - does it indicate this type of problem?

I would appreciate some help please.

`WARNING <general>: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): the python script "/storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE`

**Comment by jurialmunkey** [comment]
Generally no. It just means that the python garbage collector tried to clean a memory reference but couldn't because the class object was still in use by another process. 

Its been speculated that there's some cpython issue where the garbage collector miscounts references to internal c++ objects that get inherited (basically sees empty plates around the table and thinks everyone is done eating dinner so goes to clear the plates but then realises someone is still eating).

Either way, even if that is a leak, there's nothing that can be done at the plugin code level as it's an internal cpython issue that needs to be fixed in core code
https://forum.kodi.tv/showthread.php?tid=307508&pid=2530372#pid2530372
