### ISSUE TITLE
Translation - setting English as a language doesn't work

### ISSUE THREAD

**Issue by ntzb** [jurialmunkey/plugin.video.themoviedb.helper#550]
Hi, 
The language specified in TMDbHelper settings is NOT English, and my player doesn't support it.
I'm trying to set it up so it sends the English translation (or is it the non-translated name? and not "English translation"?), but it doesn't work.
I set up my player to be:
```
{
    "name"              : "mpg",
    "language"          : "en",
    "plugin"            : "plugin.video.mpg",
    "priority"          : 100,
    "is_resolvable"     : "true",
    "play_movie"        : "plugin://plugin.video.mpg/?vod=yes&title={en_title}",
    "play_episode"      : "plugin://plugin.video.mpg/?vod=yes&title={en_showname}"
}
```
but I still get the non English title.
I tested the translation feature with other languages and it works as expected (obviously), so the issue is getting the English information if the language set in TMDbHelper settings is NOT English.

**Comment by jurialmunkey** [comment]
It's because TMDb API treats English as the default site language, so there's no "Get Translations" call for "en" even if the default language in the API request is not english.

Have your tried using `{originaltitle}` instead of `{en_title}`? That'll give you the title of the movie/show in its original language. (I think I forgot to document that in the wiki - added it in there now)

**Comment by ntzb** [comment]
hmm, that's too bad.
I can use original title, but for foreign movies I'll still have the same issue.
I'll need to add another call to tmdb in my player, with the tmdb_id, to get the English title then.

**Comment by jurialmunkey** [comment]
@shmizan - Ah, I didn't think about foreign titled movies that are known by their English name (e.g. Spirited Away). 

Ok latest git version adds a player option to specify `"api_language": "en-US"` which will override the base api call language setting. That is, it will change all the base keys instead of creating translation keys - e.g. it changes `{title}` itself rather than creating `{en_title}` like the normal translation language does.

To use it, add to your player json (you can use any language-country combo but I imagine you'd want en-US)
`"api_language": "en-US",`

**Comment by jurialmunkey** [comment]
Wiki - https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#force-api-language-and-country-override-slower
