### ISSUE TITLE
Your Next Episodes - widget disappears after watching show, have to restart skin.

### ISSUE THREAD

**Issue by hindsight2021** [jurialmunkey/plugin.video.themoviedb.helper#551]
As descibed, every time I finish a show, when my widgets refresh in Auramod (latest) the tmdbhelper widget for "your next episodes" has started to vanish with error:

2021-08-20 10:42:49.661 T:19633   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_nextepisodes&tmdb_type=tv&widget=true

When this happens, I have to restart my skin to get this widget to refresh/show again.

It happens after finishing any show episode in any player, as the widget refresh is called.

Log: https://pastebin.com/UNiYJMaX

Kodi 19.1 Nodi Fork, Nvidia Shield, latest players/addon releases.

**Comment by jurialmunkey** [comment]
I don't use next episodes list personally but I've noticed similar issues in the last week or so with the recently watched and in-progress shows lists which also use the same sync data from Trakt. Looks like the Trakt server is a bit slower for some reason now and it's hitting the timeout limit.

In latest git version I've changed it so that the sync will fallback to the previously cached data if Trakt timeouts (or otherwise fails). I figure that a slightly out of date list is better than getting no list at all and needing to force a skin reload. I've also bumped up the timeout from 10 to 20 seconds, which seems to be the sweet spot (I was still getting timeouts at 15 but not 20).

Could you try latest git version and see if that fixes things for you?

**Comment by hindsight2021** [comment]
Thanks, I’ve updated to the git version, and will report back after stability testing. Sounds like this will do the trick, appreciated!

**Comment by hindsight2021** [comment]
4 hours of use with no replication, it’s already 100% better. Thanks.

**Comment by jurialmunkey** [comment]
> 4 hours of use with no replication, it’s already 100% better. Thanks.

I haven't noticed any issues either since, so the fix appears to be working well. Thanks for reporting and testing!
