### ISSUE TITLE
Allow for syncing movies only

### ISSUE THREAD

**Issue by bidyboop** [jurialmunkey/plugin.video.themoviedb.helper#553]
When I add a new movie on trakt.tv and do a sync with 'Update library now' both TV shows and movies are synced.

It would be great to be able to pick and choose what to sync (movies or TV shows).

(Might be less of an issue if syncing would be faster and/or in parallel).

**Comment by jurialmunkey** [comment]
The reason it is slow is because the update library now command in the settings forces a complete update of the entire library. Basically it forces the update to ignore the cache containing details of the last update so it checks everything rather than skipping what it has already added / recently updated. You should only use it if something breaks.

If you want to add a single movie, you're better off using the TMDbHelper search function and then adding to the library directly using the context menu options.

You can also do a "soft" update that mimics the non-forced auto-update that happens at the specified time by using the following command:
```
RunScript(plugin.video.themoviedb.helper,library_autoupdate,busy_dialog)
```

You can also do an update from a single list using this command (this is what the add to library context menu does on a trakt list)
```
RunScript(plugin.video.themoviedb.helper,library_autoupdate,busy_dialog,user_slug=OWNER_OF_LIST,list_slug=LIST_URL_SLUG)
```

For instance if you want to update from this list: https://trakt.tv/users/canconfirm/lists/shut-up-and-watch you can use this command:
```
RunScript(plugin.video.themoviedb.helper,library_autoupdate,busy_dialog,user_slug=canconfirm,list_slug=shut-up-and-watch)
```

If you use a skin that uses skinshortcuts, you should be able to add these as actions to a custom menu item (alternatively you can keybind them to a remote button or key combo).

**Comment by jurialmunkey** [comment]
^^^ Latest github version will now give you a choice between Forced and Quick updates when selecting the option from the settings. That way you don't need to mess about with custom commands (the commands still work if you want to bind a key/menu though!)
