### ISSUE TITLE
TMDB Helper adds duplicate items in folder

### ISSUE THREAD

**Issue by patel-jeel92** [jurialmunkey/plugin.video.themoviedb.helper#555]
I had made a copy of the movies and tv shows folder with strm files along with nfo files and posters. The nfo files I had in each directory had both, the ones created by TMDBh and the ones created by TMM. The TMDBh is using the alternative nfo file name. For other various reasons, I had to set up kodi from scratch and after installing the tmdb helper add on, I restored the location for movies and tv shows for tmdb helper library integration and set the appropriate paths. After the first library update, even though tv shows already existed in my folder with the alternative nfo file, TMDB helper added duplicate items with (TMDB-id) in the folder name

**Comment by drinfernoo** [comment]
Sounds an awful lot like #538?

**Comment by patel-jeel92** [comment]
Yeah and that's what I wanted to discuss. Based on that issue you came up with the alternative nfo file. So with that setting, it seems like it is not scanning the nfo file correctly and it's creating new items. I have checked that the folders have the alternative nfo file present along with tvshow.nfo that TMM creates.

**Comment by jurialmunkey** [comment]
Sounds like you didn't scan the folder to your library _before_ running the TMDbH update. When determining if it needs to write a new file, TMDbH _only_ checks the _library_ first to see if it exists. It would be too slow to check every individual `.strm` file in the folder for every episode, which is why it uses `.nfo` to determine that it "owns" the folder before writing to it.

However, that doesn't explain why it is ignoring the alternative `.nfo` and creating a new folder. I made a test case which I think replicates your scenario and I was able to recreate the issue, so I'm fairly certain I know what the issue is.

The latest github version (v4.3.37) _should_ fix the problem (it worked properly with my test case). Can you test following your same restoration process as before. I know it is a pain to rebuild from fresh restore but I'm pretty confident v4.3.37 will solve the issue and confirming that it works properly will save a lot of headache down the line.

**Comment by patel-jeel92** [comment]
After i reset Kodi and restored the folders with movies and tv shows, the first thing I did was scan my entire library before adding any add-ons. 

Testing the fix may take a while since I have to rescan the whole library.

**Comment by jurialmunkey** [comment]
> After i reset Kodi and restored the folders with movies and tv shows, the first thing I did was scan my entire library before adding any add-ons.

Ah okay. Well that puts you in a much better position because those extra folders created _should_ be mostly blank except for any new episodes that you didn't have before. Makes the task of deleting the extra folders and cleaning the library much less painful because there won't be duplicated items in the new folders.

> Testing the fix may take a while since I have to rescan the whole library.

Yeah no worries! When you can. Like I said, fairly confident that I fixed it but always good to get confirmation.

**Comment by patel-jeel92** [comment]
Will this update be available in the repo or do I have to manually download from here

**Comment by drinfernoo** [comment]
@patel-jeel92 I'll update the repo as soon as I can. Every update goes to the repo eventually, but I don't always get a chance to do it *immediately* when GitHub is updated.

**Comment by patel-jeel92** [comment]
Okay thanks. I will wait for the update in the repo

**Comment by patel-jeel92** [comment]
Hey @jurialmunkey I tested the latest version and I still saw new folders with TMDB prefix get created. Here are the steps I followed. 

1) I removed any TMDB prefix folder from my path.
2) Updated to the latest version on TMDBHelper
3) Ran the update library using the quick option

**Comment by jurialmunkey** [comment]
Hmm, if you're definitely using v4.3.38 (or higher) then I'm not quite sure why this would be still happening.

Can you give me the `.nfo` files for an example show that is getting a new folder made (I want all the `.nfo` files from both the original folder and the newly created one).

Also can you get the library update log matching the time of the update. It'll be here:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_library/YYYY-MM-DD-hhmmss.json`

Finally, can you double check to make sure that you are definitely using v4.3.38 (or higher).

**Comment by patel-jeel92** [comment]
Actually I think i spoke too soon. I retried the same steps as I mentioned above, but this time, after deleting all folders with (TMDB*) in the name, I did a clean on the kodi library. After that was successful, I updated the library again and it didn't create new duplicate items! 
So the steps I took: 
1) Remove all duplicate folders with TMDB in title 
2) Go to Settings -> Media -> Clean Video Library 
3) Go to TMDBHelper settings and update library

**Comment by jurialmunkey** [comment]
@patel-jeel92 - Hmm, interesting. Did you do a Quick update in TMDbH or a Forced one?

Note that a Quick update in TMDbH will skip shows not currently airing that you added in the last TMDbH update. If you did a Forced update, then it is definitely working because that checks everything - but if it was only a Quick one then it possibly just skipped those shows since you did an update recently.

Basically each TMDbH update stores what it did in an update cache and sets a "next check" date value for each show based upon airing status. The Quick update checks the update cache first before deciding to check a show, whereas Forced ignores the update cache and checks every show. 

The rules for Quick update are as follows (the rules are evaluated in order so that a higher up rule always take precedence).

| Rule | Next Check for Show | Description |
| --- | --- | --- |
| Next airdate is today | Today | Show airs today. Check for new episodes |
| Next airdate in less than 7 days | Next air date | Show airs this week. Check for new episodes on the day it airs |
| Next airdate in 7 to 30 days | 7 days | Show airs this month. Check next airdate again next week in case the network's schedule changes |
| Next airdate in more than 30 days | 30 days | Show airs in more than a month so is currently on a break. Check next airdate again next month in case the return date changes. |
| Last aired less than 30 days ago | Tomorrow | Show doesn't have a next airdate listed but aired within the last month. Check next airdate again tomorrow just in case it is a currently airing show but no one had added the details of the next episode yet. |
| Last aired 30 to 90 days ago | 7 days | Show doesn't have a next airdate and didn't air last month. Show is currently on break. Check next airdate again next week in case return date is added |
| Status is Cancelled or Ended | 30 days | Show was cancelled or has finished. Check next airdate again in a month just in case it gets picked up by another network or there are special episodes airing. |
| Status is None or Continuing | 7 days | Show hasn't been cancelled and hasn't aired in more than 90 days. Check next airdate again in a week in case more details about status or return date are added. |

**Comment by patel-jeel92** [comment]
I let the library update on it own with the time I have set. I didnt get to choose but I am assuming it was a quick update. But I have not seen the duplicate items so I am content. I can try doing the full update and report back
