### ISSUE TITLE
[Request] Setting to control how many items are shown in each list

### ISSUE THREAD

**Issue by tjamieg** [jurialmunkey/plugin.video.themoviedb.helper#56]
At the moment, every list has a different number of items per page.

For example, a few I have noticed are:
- Movies > Based on Recently Watched = **20** items
- Movies > Trending Today = **20** items
- Movies > Liked Lists > Latest Releases = **9** items
- Movies > Watchlist = **10** items
- Movies > Your Recently Watched = **10** items
- Movies > Recommended For You = **10** items

Could this be changed so that every list returns the same number of items per page?

And could that number be an adjustable value in the settings page, so that people could change it according to their personal preference?

It may not seem like much of an issue when clicking on the pages individually, but I use the above exapmles as home screen widgets and it can get quite annoying.

**Comment by jurialmunkey** [comment]
TMDb API limits all lists to be paginated at 20 items and the limit cannot be changed.
Trakt pagination defaults to 10 items. It is possible to change the limit for some Trakt lists but not all.

However, Trakt API doesn't supply artwork, so an additional individual request has to be made to TMDb for every item in the list. TMDb API has a 4 requests per second limit, so that's already 2.5 seconds per 10 item list. Add to that fanarttv requests, trakt watched requests, kodi library requests, script processing time - and each additional item in the list starts to add a lot of extra loading time. That's why I limit to 10 items.

Also, some trakt lists require a lot of additional processing (e.g. in-progress) and it really is not feasible to return more than 10 items without excessive loading times.

I'm not sure why you are getting 9 items in a liked list though. Probably something is not being found on TMDb or there is a duplicate item.

**Comment by jurialmunkey** [comment]
@tjamieg - Please test latest version. I've added an option in settings to extend trakt lists to 20 items to make them consistent with TMDb lists. Please note that this option will extend the loading times of some trakt lists quite considerably.

`TMDbHelper Settings > Accounts / API Keys > Trakt > Expand Trakt list limit to 20 items` 
(you might need to scroll down to see the option)

Let me know if there are any Trakt lists not respecting this setting.

**Comment by tjamieg** [comment]
@jurialmunkey amazing work!

After enabling the "Expand Trakt list limit to 20 items" option, every trakt list now shows (or tries to show) 20 items, which makes them consistent with the TMDb lists.

The "Latest Releases" Trakt list by Gilad & Alex now shows 19/20 items instead of 9/10, which I put down to a duplicate movie on TMDb (titled Heritage) not showing in the list. So more of an issue with TMDb other than the add-on.

All I would say now though, is that people who don't enable the "Expand Trakt list limit to 20 items" option, will still get some lists with 20 items and others with 10 as opposed to 10 items globally, if that makes sense.

**Comment by jurialmunkey** [comment]
> The "Latest Releases" Trakt list by Gilad & Alex now shows 19/20 items instead of 9/10, which I put down to a duplicate movie on TMDb (titled Heritage) not showing in the list. So more of an issue with TMDb other than the add-on.

If there is a duplicate item the plugin won't add it, so that would be why.

> 
> All I would say now though, is that people who don't enable the "Expand Trakt list limit to 20 items" option, will still get some lists with 20 items and others with 10 as opposed to 10 items globally, if that makes sense.

It's always possible to reduce the number of items shown from the skin side of things. Having 20 items in TMDb lists gives skinners much more flexibility - particularly as many of the TMDb lists are only used in skin scenarios (e.g. Recommended, Similar, Cast, Movies from a Genre / Studio / Director etc.).
