### ISSUE TITLE
$INFO[Window(Home).Property(TMDbHelper.ListItem.Cast.X.Name)] not working

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#560]
$INFO[Window(Home).Property(TMDbHelper.ListItem.Genre)] - works fine giving all genres separated with a /

$INFO[Window(Home).Property(TMDbHelper.ListItem.Genre.x.Name)] - works fine giving a single genre at position x

$INFO[Window(Home).Property(TMDbHelper.ListItem.Cast)] - works fine giving all cast members separated with a /

$INFO[Window(Home).Property(TMDbHelper.ListItem.Cast.x.Name)]  - FAILS, returning nothing :(

Is this a bug?

**Comment by jurialmunkey** [comment]
Ah yes you're right - it's a bug. Looks like it's been there since v4.0 so I'm surprised no-one noticed until now.

Can you test latest github version (v4.3.40). It should fix it for both the Service Monitor and ListItem Properties in TMDbH lists.

Service monitor should now return:
```
$INFO[Window(Home).Property(TMDbHelper.ListItem.Cast.x.Name)]
$INFO[Window(Home).Property(TMDbHelper.ListItem.Cast.x.Role)]
$INFO[Window(Home).Property(TMDbHelper.ListItem.Cast.x.Thumb)]
```

TMDbH list items should also now have the following properties:
```
$INFO[ListItem.Property(Cast.x.Name)]
$INFO[ListItem.Property(Cast.x.Role)]
$INFO[ListItem.Property(Cast.x.Thumb)]
```

**Comment by roidy** [comment]
Can confirm that v4.3.40 fixes the issue.

Big thanks 👍
