### ISSUE TITLE
Movies added to kodi’s favorite won’t play via FEN player

### ISSUE THREAD

**Issue by jaimsitecom** [jurialmunkey/plugin.video.themoviedb.helper#562]
Since version 4.4.0, all movies added to kodi’s favorites folder won’t play thru when using FEN player. Is there a new setting i need to do in the player configuration for this to work again?

Thanks!

Log:
https://mega.nz/file/pYYSHZJZ#p0r4kFFSu4vQH5c0lpP970NUgllxOHMyu8a8bTp0t1g

**Comment by jurialmunkey** [comment]
TMDbH is working correctly.

This is likely a problem with your player file not using encoding for spaces as seen here:
```
plugin://plugin.video.fen/?mode=play_media&vid_type=movie&library=True&query=Black Island (2021)&year=2021&poster=https://image.tmdb.org/t/p/w500/53jsv5TASLwOqsJNsUNp4RPPq2l.jpg&title=Black Island&tmdb_id=847981
```

Plugin paths can't have spaces. You need to use one of the special suffix encodings
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes

**Comment by jaimsitecom** [comment]
Ok. Thanks for the setailed explanation.

**Comment by jurialmunkey** [comment]
@jaimsitecom - You don't need to be a programmer - it's just a simple textfile edit. 

If you go to where the players are installed `.kodi/userdata/addon_data/plugin.video.themoviedb.helper/players` you will find some .json files. If you edit these in a text editor you will probably see some lines like the following:

```
"play_movie" : "plugin://plugin.video.fen/?mode=play_media&vid_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}",
"play_episode" : "plugin://plugin.video.fen/?mode=play_media&vid_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}"
```

We're interested in the parts like this:
```
&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}
```

TMDbHelper is going to replace `{name}` and `{title}` with the actual name and title of the movie and then send the url it makes to Kodi. However, urls can't have spaces or special characters, so if the title has a space it will break the url (if you've ever seen a website url with `%20` in it then you've seen a url percent encoded space). So we need to tell TMDbHelper to "translate" those characters before it adds them to the plugin://url

We can tell TMDbHelper to use URL percent encoding by adding `_url` to the keys like so:
```
&query={name_url}&year={year}&poster={poster_url}&title={title_url}&tmdb_id={id}",
```
Whether you use `_url` or `_url+` or `_escaped` or `_+` etc. depends on what the plugin expects but generally `_url` is going to be the encoding that most plugins use. Also, FYI, we don't need to encode `{year}` or `{id}` because those will just be numbers (so no special characters or spaces). 

@drinfernoo - I imagine this will be relevant to you as I noticed some of the "direct" players in the bit.ly link aren't using encodings for plugin:// paths. At the very least they'd need to be replacing spaces - but I imagine most probably need `_url`

**Comment by jaimsitecom** [comment]
> @jaimsitecom - You don't need to be a programmer - it's just a simple textfile edit.
> 
> If you go to where the players are installed `.kodi/userdata/addon_data/plugin.video.themoviedb.helper/players` you will find some .json files. If you edit these in a text editor you will probably see some lines like the following:
> 
> ```
> "play_movie" : "plugin://plugin.video.fen/?mode=play_media&vid_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}",
> "play_episode" : "plugin://plugin.video.fen/?mode=play_media&vid_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}"
> ```
> 
> We're interested in the parts like this:
> 
> ```
> &query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}
> ```
> 
> TMDbHelper is going to replace `{name}` and `{title}` with the actual name and title of the movie and then send the url it makes to Kodi. However, urls can't have spaces or special characters, so if the title has a space it will break the url (if you've ever seen a website url with `%20` in it then you've seen a url percent encoded space). So we need to tell TMDbHelper to "translate" those characters before it adds them to the plugin://url
> 
> We can tell TMDbHelper to use URL percent encoding by adding `_url` to the keys like so:
> 
> ```
> &query={name_url}&year={year}&poster={poster_url}&title={title_url}&tmdb_id={id}",
> ```
> 
> Whether you use `_url` or `_url+` or `_escaped` or `_+` etc. depends on what the plugin expects but generally `_url` is going to be the encoding that most plugins use. Also, FYI, we don't need to encode `{year}` or `{id}` because those will just be numbers (so no special characters or spaces).
> 
> @drinfernoo - ~I imagine this will be relevant to you as I noticed some of the "direct" players in the bit.ly link aren't using encodings for plugin:// paths. At the very least they'd need to be replacing spaces - but I imagine most probably need `_url`~ EDIT: Actually, it's only the Fen player without any space encoding I think. The rest look like they're using either `_+` space replacement or `_url` encoding.

Thanks! I will try this. I already informed Tikipeter about this, but he says FEN dont do support between TMDB HELPER and FEN.  No problem, if I can’t figure this out with your instructions, i’ll just use Venom’s player. 

Thanks so much for the help!

**Comment by jaimsitecom** [comment]
i tried to do your instructions, but still won't play, must be caused by something i wrote:
"play_movie" : "plugin://plugin.video.fen/?mode=play_media&amp;vid_type=movie&amp;query={name_url}&amp;year={year}&amp;poster={poster_url}&amp;title={title_url}&amp;tmdb_id={tmdb}",

anyways, i just pointed the player to use venom's instead... works well.

thanks again!
