### ISSUE TITLE
[Feature] [Request] Ability to add Trakt Collection to Kodi Library

### ISSUE THREAD

**Issue by hmoghani** [jurialmunkey/plugin.video.themoviedb.helper#568]
Currently only Trakt Lists can be added to the Kodi Library using TMDB helper. To get to feature parity with OpenMeta, a feature needs to be added to TMDB Helper to let users to use Trakt Collection instead of lists as their source for the Kodi Library.

**Comment by jurialmunkey** [comment]
Covered so many times before. Answer is no. Use a trakt custom list. Collection is specifically for items you physical own so should already be in your library. Just because OpenMeta abused the collection doesn't mean that other addons should continue to misuse it. This is specifically what custom lists are for. 

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/405#issuecomment-752872402

**Comment by drinfernoo** [comment]
TMDbHelper surpassed "feature parity" with OpenMeta almost the day it was released 😅
