### ISSUE TITLE
all command with $INFO[ListItem.Label] don't works if [ListItem.Label] contain & or ,

### ISSUE THREAD

**Issue by Nanomani** [jurialmunkey/plugin.video.themoviedb.helper#570]
all command with $INFO[ListItem.Label] don't works if [ListItem.Label] containt `&` or ` ,`

eg : 
Fast & Furious: Hobbs & Shaw
Extremely Wicked, Shockingly Evil and Vile

Because you can see in log all characters are truncated from `&` or ` ,`

eg : with label "Ave, César !"

log :  https://paste.kodi.tv/efaxesalox

This can be tested with the skin "Artic Horizon".
Reproduce :  
1 - open "Information" for a video
2 - select "Item" in list "Same director", "Same year", ... with `&` or ` ,` in his label 
3 - "plugin.video.themoviedb.helper" stuck

The code in "Artic Horizon" is here : 

https://github.com/jurialmunkey/skin.arctic.horizon/blob/555ce9dff281527d0396c47c7d931cb3580e44bd/1080i/Includes_Defs.xml#L339-L341

**Comment by jurialmunkey** [comment]
Kodi/Skin issue. Comma is a special character which separates arguments passed to runscript command - so if there's a comma in the label it will split the command. Nothing tmdbhelper can do about it because the problem happens before kodi even runs tmdbhelper script command. Nothing the skin can do about it because there's no skinning engine commands to replace commas.

**Comment by Nanomani** [comment]
Ok, it is clear for me now.
Thanks a lot for your quick answer.

**Comment by jurialmunkey** [comment]
@Nanomani - Please try latest version of Arctic Horizon that I just pushed to Arctic Horizon github (0.5.70) -- I think I found a way around it in the skinning engine.

**Comment by Nanomani** [comment]
Yes I confirm you your lastest version fix this behaviour when there is ` ,` in label.
Thanks a lot :)
