### ISSUE TITLE
Actor image stop showing up

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#572]
I use AuraMod Skin which has a actor's icon on the OSD screen that when you click on it ,,it shows you the actors from the TV Show or Movie that your currently watching ,I noticed any update after 4.4.5 broke this feature in the skin only the actors name show up but no images ,would really appreciate if this could be fixed or look at 🙏you guys have done a AMAZING job with TMDB H ✊🏼

**Comment by drinfernoo** [comment]
Sounds like a skin issue 🤔

**Comment by jurialmunkey** [comment]
Probably related to the fix to `ListItem.Art(thumb)` that I did to separate it from `ListItem.Art(poster)` but I forgot to relink Poster to Icon (it used to go Poster > Thumb > Icon -- but now that Thumb is out of the chain I need to set a direct fallback from Poster > Icon).

It's kinda a skin issue because the skin should use ListItem.Art(poster) -- but a lot of skins probably rely on Icon so it's best to relink it.

Can you try 4.4.13? (commit I just pushed) Should hopefully fix it.

**Comment by xyzfre** [comment]
Thank you for the quick response and as soon as I get home I'm definitely going to try the commit you just push and very grateful hopefully it's fixed going to keep you posted as soon as I get a chance👍🏼￼￼

**Comment by xyzfre** [comment]
My apologies for the late response the commit from today definitely fix the issue really appreciate all the hard work that goes into TMDB Helper ✊🏼￼￼
