### ISSUE TITLE
blur_img function causing Kodi to crash

### ISSUE THREAD

**Issue by heppix** [jurialmunkey/plugin.video.themoviedb.helper#581]
Hi!

I found that `blur_img` function makes Kodi to crash without a lot of errors in log file.
Everything what is generated by this bug is that:

```
2021-11-05 14:53:49.499 T:67094   DEBUG <general>: Activating window ID: 11141
2021-11-05 14:53:49.499 T:67094   DEBUG <general>: ------ Window Init (Custom_1141_FlixSpotlight_Level2.xml) ------
2021-11-05 14:53:49.499 T:67094    INFO <general>: Loading skin file: Custom_1141_FlixSpotlight_Level2.xml, load type: KEEP_IN_MEMORY
2021-11-05 14:53:49.508 T:67204   DEBUG <general>: Thread Timer start, auto delete: false
2021-11-05 14:53:49.779 T:67206   ERROR <general>: Exception in thread 
2021-11-05 14:53:49.779 T:67206   ERROR <general>: blur_img
2021-11-05 14:53:49.779 T:67206   ERROR <general>: :

2021-11-05 14:53:49.779 T:67206   ERROR <general>: Traceback (most recent call last):

2021-11-05 14:53:49.779 T:67206   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
```

Here you can see full log file: https://paste.kodi.tv/jolupuconu.kodi

When I'm onloading `Skin.SetBool(TMDbHelper.EnableBlur)` everything is OK.
The root of the problem is when I'm onloading this
`SetProperty(TMDbHelper.Blur.Fallback,$VAR[MediaFanartVar],Home)`
This SetProperty makes kodi to crash and generate this not full error.

If you need some more info, I will provide it. Thanks :)

**Comment by jurialmunkey** [comment]
The reason for your crash is because your $VAR isn't an image at the time you run SetProperty(). 

SetProperty() is a function, so the $VAR[] is evaluated *when you run it*. That is, you're only adding the **end value** of the variable **at the time** the function was run. You can't add a _reference_ to the variable itself.

Please read the wiki. You are using the fallback wrong. 
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#blur-monitor

You need to use *SourceImage* to set the order of artwork used. The *Fallback* should be a static image to use *as a fallback* when the current item doesn't have any of the source image types specified.

For example:
```
SetProperty(TMDbHelper.Blur.SourceImage,fanart,Home)
SetProperty(TMDbHelper.Blur.Fallback,special://skin/extras/background.jpg,Home)
```
^ This tells the monitor to try to use `ListItem.Art(fanart)` first, then `ListItem.Art(thumb)` if fanart isn't available. If neither is available it will use the fallback which is the background.jpg in the skin's extras folder

The `fanart` keyword is an alias for `Art(fanart)|Art(thumb)` but you can specify your own custom order of source images instead by separating with a pipe `|` like so
```
SetProperty(TMDbHelper.Blur.SourceImage,Art(tvshow.clearlogo)|Art(landscape)|Art(discart),Home)
```
^ This will try to use the tvshow clearlogo first, then landscape then discart. You get the idea.

**Comment by heppix** [comment]
Oh well. Thanks for your explanation. Now I understand what is wrong. However... I'm curious, because my current implementation works on my devices except on Ubuntu with Wayland. 
You can look on my mess here: https://github.com/nfm886/skin.cosmic ^^

There is the line: https://github.com/nfm886/skin.cosmic/blob/master/xml/Custom_1141_FlixSpotlight_Level2.xml#L5 I mentioned earlier. Basically I wanted to make blur in another dialog window by passing https://github.com/nfm886/skin.cosmic/blob/master/xml/Includes.xml#L2841 a property with fanart to variable.
As I said it working but not on my PC. That's why I'm here :)

I don't know why it stopped working. If it's not fixable or hard to fix I will just opt-out from my idea and implement it the way you explained. Probably I won't be able to use it in custom dialog window since ListItem.Art(fanart) is empty then.

#edit
Hmm... There is something deeper. I don't know if it's related to my system (which is basically Ubuntu 21.10 with Wayland) or Kodi itself but I changed skin to Arctic Horizon to check if my implementation sucks or this function does not working at all and... crash :P

#edit2
Kodi running on Wayland/X.Org/Standalone - crashes all the time. I will dig further^^

#edit3
Just compiled Matrix version from GH to make sure .deb package from PPA is not only affected but it still crashing.

**Comment by heppix** [comment]
Ok, it works now :)
Upgraded python to 3.9.8 from 3.9.7 which was shipped with Ubuntu 21.10. After it just installed pillow package to avoid this error came from embuary helper and everything is working now :) Sorry for bothering but though it may affect more people.

https://streamable.com/2pbn5l (sorry for low quality...)

Just wanted to say thanks @jurialmunkey for your work. You are doing good job with your skins and tmdbH, thanks! :)

**Comment by jurialmunkey** [comment]
Ah, that makes sense! Glad you found a solution.

I didn't realise the version of Kodi compiled for Ubuntu overrides Kodi's own included python modules. In that case, it's similar to the Arch and Manjaro issues with PIL in Leia  https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/376 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/244

Thought the crash was a bit odd because if the fallback is blank or not a real file location, it should just get ignored. Even if you point it to a file that's not an image, at worst the try block should catch the exception in the image loader and TMDbH will grumble about it but carry on.

**Comment by jurialmunkey** [comment]
@nfm886 - FYI, if you only need to blur a single image as a one time thing, you can run the command as a script function instead of using the blur monitor:
```
<onclick>RunScript(plugin.video.themoviedb.helper,blur_image=$VAR[MediaFanartVar])</onclick>
<onclick>ActivateWindow(1141)</onclick>
```

There's no point having the blur monitor enabled and running constantly in the background if the only reason you need it is to blur a single image when opening a dialog. Plus, with the runscript you can launch it _before_ you open the window so that you're blurring the image that's active at the time.

(BTW - if you run into issues with filenames containing commas, you might need to wrap the $VAR in single+double quotes `'"` like so `blur_image='"$VAR[MediaFanartVar]"'` )

**Comment by heppix** [comment]
> @nfm886 - FYI, if you only need to blur a single image as a one time thing, you can run the command as a script function instead of using the blur monitor:
> 
> ```
> <onclick>RunScript(plugin.video.themoviedb.helper,blur_image=$VAR[MediaFanartVar])</onclick>
> <onclick>ActivateWindow(1141)</onclick>
> ```
> 
> There's no point having the blur monitor enabled and running constantly in the background if the only reason you need it is to blur a single image when opening a dialog. Plus, with the runscript you can launch it _before_ you open the window so that you're blurring the image that's active at the time.
> 
> (BTW - if you run into issues with filenames containing commas, you might need to wrap the $VAR in single+double quotes `'"` like so `blur_image='"$VAR[MediaFanartVar]"'` )

Oh man, that's totally awesome. I must try this because until now I made a hassle to make it working and my implementation is far from good ^^
