### ISSUE TITLE
TMDB helper Addon repeating Playback of Videos upon completion

### ISSUE THREAD

**Issue by shaktoo1** [jurialmunkey/plugin.video.themoviedb.helper#589]
Kodi 19.3 On Windows 10 & Android ( Nvidia Shield ) Latest TMDB Helper (4.4.29)  via jurial repo + Latest Fen & Seren players . I use mySQL database to have a central Library database which is shared with all the PC's & Shields throughout the household as well as Trakt keeping tabs.

I have used TMDB helper to create a local Library which then uses (currrently FEN) addon players to play files.

Last 1 week using library integration and when I select a show to watch it does the normal thing of finding sources. After the video ends it looks for sources again for the same thing. If I manually stop it then it states playback failed & the file does not get marked in local library. I have tested this on both Seren & Fen & its the same issue.

If I play files individually from within any addon this does not happen. ONLY happening when using TMDB Helper / Library.

I have deleted & re set up from scratch all three of these addons but still there is no change .

Please could anyone help. I could find a similar thread from 1 year ago but that was for libreleec & Pi3 + supposedly resolved via update from jurial's repo. As I have the latest from repo then this should not happen right ?

I was unable to upload debug l;og anywhere as its deemed too big ( why I cannot understand )
So please find a Link to the log@ my google drive
[https://drive.google.com/file/d/1E9Y7rLiyVjCC18r0dKH3I_6B9CJ0iUEL/view?usp=sharing](url)

**Comment by jurialmunkey** [comment]
Your player settings are incorrect. These types of addons which shell out to a script to scrape sources do not resolve directly to a file. However, you've set the players up as resolvable as seen by this line in your log:

`lib.player - finished resolving path to url`

Any player that isn't resolvable should instead load the dummy file first to prevent this looping issue. When the Kodi library doesn't receive a resolved video directly then it will attempt to replay. If your settings for these players were correct, you'd see this line instead:

`lib.player.players - attempt to resolve dummy file`

The library MUST resolve to a file directly otherwise it will retry to play again. Playing the TMDB logo dummy file is a hack to deal with these types of hacky addons which don't properly resolve to a url like Kodi expects.

You can solve this issue by going to `TMDBHelper Settings > Players > Configure Players` and reverting your players so that the `is_resolvable` flag is set to false (it should be false by default, so you must've editing this setting yourself).

**Comment by shaktoo1** [comment]
Thank you very Much Jurialmunky ! You are amazing and you have nailed it. 
As I do remeber roughly at the time this started to set up the player with the resolve setting.
I am going to clear that / change it and then will give you the end result whether it has worked (most likely)

**Comment by shaktoo1** [comment]
Some Further feedback.
It is defintely the player sepcifically the Fen player  as it does not automaticallly set the resolve url and has to ask for input. When one tries to set that function to be selected by default as what I did in the player , although makes it jst one click automatic But then unfortunately causes the loops issue.
It does not happen with Seren
Does not happen with Netflix, Disney  & Amazon addons either
Could something be done to retain the automatic set url function yet avoiding the loop error ? If its to do with the addon players then I understand.

**Comment by jurialmunkey** [comment]
I'm sorry I have no idea. I don't use Fen and didn't make the player for it. This is definitely a player configuration issue though and not a TMDbHelper issue.

Anything that doesn't resolve directly should have it's player file is_resolvable flag set to false. This can be done either directly in the player file itself, or by using the configuration dialog in TMDbHelper to edit the player file settings.

**Comment by drinfernoo** [comment]
@jurialmunkey If an add-on does use `setResolvedUrl(...)`, but has to scrape for the file, is that still an instance where `is_resolvable` should false?

**Comment by jurialmunkey** [comment]
> @jurialmunkey If an add-on does use `setResolvedUrl(...)`, but has to scrape for the file, is that still an instance where `is_resolvable` should be `false`?

As long as it passes the correct handle and Kodi gets a playable stream url, then it should be fine. It's not scraping per se that's the issue (most plugins do some form of scraping - e.g. Netflix and Youtube do some form of scraping, and both those use setResolvedUrl correctly). It's just that generally these types of addons which scrape multiple sources tend to pass directly to xbmc.Player() or they don't set the handle correctly or they end the plugin instance early by using RunScript()

I suspect that there's also probably some plugins which use setResolvedUrl in some places and xbmc.Player() in others. I suspect some of the one-liner commands might be like this even if the listitems inside the plugin use setResolvedUrl correctly.
