### ISSUE TITLE
In progress TV shows for Trakt user lists

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#590]
There is a 'new' feature for Trakt VIP users that lets you see in progress tv shows from a specific user list instead of from the whole catalog of shows in all lists. Would it be possible to integrate this functionality? 
In my case, I use the library integration functionality to import lists to the Kodi library and then I use the auto generated playlists to create other playlists based on them that show in progress tv shows for each one. With this functionality I wouldn't need all this because I could use Trakt lists directly for my 'In progress' witgets per playlist.

**Comment by jurialmunkey** [comment]
This sounds fairly similar to a feature I've been planning to implement for a while: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/561

My idea was slightly different in that it would grab the next "up next" episode for each show in the list and display as a list of episodes. Whereas I'm assuming you're suggesting a list that displays tvshows (not episodes) and then you click the tvshow to open up the "up next" folder for the show.

I can't see any API call in the documentation for this in-progress list feature. It would definitely by nice to have but it'd be pretty slow without a proper call. To do it manually would mean iterating over every item in the list and querying the watched status until enough items were found to display a page -- could be a problem on a large list if you had fewer than a full page worth of shows in progress (essentially would query every single item in the list!).

Do you have any links to announcements about this feature or anything like that? I'm wondering if it's just not listed in the API docs.

**Comment by juanma-cvega** [comment]
I asked a question in their git account, they a have an issue opened since July about new endpoints for VIP users but so far there is only endpoint added. 
I checked their website and I can see the URL is in the following form:
https://trakt.tv/users/username/progress?list=listId

**Comment by jurialmunkey** [comment]
Okay so I tried this:
https://trakt.tv/users/audioworm/progress?listid=tv-shows-of-the-decade

It looks like it displays the list's _owner's_ progress (i.e. audioworm's progress) rather than my own progress. It'd still be useful on your own lists, but I feel like where a feature like this really comes into it's own is being able to use it on liked lists that are maintained by other users.

Either way, the `users/{user_id}/progress` endpoint has never been available via the API, so I doubt this call would be available in the API either. It gets brought up frequently on the github and the discussion boards, and it's always been met with the same response that it should be calculated client side instead - e.g. https://github.com/trakt/api-help/discussions/300

Calculating client side is fine if you have a single app with complete control and aren't constantly switching apps because then you don't need to sync that often - e.g. You watch something with App_A, then App_B syncs when it opens and doesn't need to sync again until you close it and watch something with App_A again. The problem with Kodi is that scenario happens often because we're essentially running multiple apps side-by-side.

The only way it'd be possible is to generate the normal in-progress list and then filter it using a Trakt user list. Which is definitely possible, just potentially slow if you want to have multiple widgets since each instance is going to be as slow to generate as the full in-progress list. It might not be as bad due to how I cache the sync but it'll really depend on the timing of Kodi launching each plugin instance.

**Comment by juanma-cvega** [comment]
Ok, I didn't know even the in progress endpoint for all TV shows wasn't available in the API. It's kind of disappointing, given this is a VIP feature. If it's not exploitable from outside their website, I don't see the point on paying for it to be honest.
When doing it the way you propose, wouldn't pagination cause problems with the logic? As far I know, you don't get the whole list in way go, it's always paginated, so you would need to go to the end  of every list used as widget to get the full picture.

**Comment by jurialmunkey** [comment]
Pagination isn't applied serverside to custom lists because they're essentially a raw list of IDs with a few additional details for sorting purposes (plus need to get it one go to sort it properly). Pagination on those is done client side instead and it's only to avoid excessive tmdb details lookups because none of the items come with any details. 

And the in progress is also generated all in one go because it's based off syncing watched history (and same deal with the pagination to avoid too many tmdb lookups). So it's actually one of those rare cases where pagination is artificially applied to both lists client side and we have the opportunity to compare the full lists before pagination is applied.

**Comment by jurialmunkey** [comment]
Okay this was actually ridiculously easy to implement and performance doesn't seem _too_ bad.

Can you test? It's working for me ~but I also don't have enough shows in-progress to force pagination so I'm not sure if there will be issues there~ EDIT: Just tested with a different list where I had more in-progress and pagination seems to be working correctly.

On a Trakt Custom list (can be liked, popular, trending or your own) go to context menu
Choose `Browse Sorted List` and then `Sort by: In Progress`. 

It will give you a list of all in-progress shows in the list sorted by most recently watched. ~For now, the tvshows just open into the standard seasons view but I guess we'd probably want it to open directly into the "Up Next" season folder instead. I'll add that soon - just want to make sure it is working correctly first~ EDIT: Should now reroute to up next folder.

**Comment by juanma-cvega** [comment]
Cool! I just tested it and it works!

**Comment by jurialmunkey** [comment]
Let me know if there's any issues but it seems to be working well, so I'll close this for now.
