### ISSUE TITLE
Keep track of the selected episode group in Trakt

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#592]
Is there any way an episode group for a TV Show could be stored somewhere? The current behaviour forces you to enter the TV show, go to the episode group and select the one you want every time. 
Here I'm talking about the option from the addon, not from the library after importing a TV show.

**Comment by jurialmunkey** [comment]
It's a little tricky because Kodi makes each folder/page it's own independent instance but definitely possible. It'd mean rerouting the season folder path to point to the episode group which then creates two issues:

1. How do you indicate that you want the path rerouted to the episode group? 
2. Once it has been rerouted, how do you disable the rerouting to get back to the normal season view?

**Comment by juanma-cvega** [comment]
For the first point, I guess that's the main issue here as that'd mean keeping track of the configuration for each TV show that has configured the episode group option and then searching for a match against this list every time a seasons list is visited. I'm not sure what would be the impact of an option like this performance wise when using low powered devices.
The second point, I would imagine it like going to the episode groups option again and selecting the default group which would effectively remove the marker for that list from whatever storage is used to maintain the option selected.
