### ISSUE TITLE
Player not available in the list when playing an episode

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#594]
I found a TV show where the Embycon play episode player doesn't show up and I'm trying to understand why. As far as I understand, because this player requires the TVDB episode ID to work, if TMDB doesn't have this ID configured as part of the external IDs list for the episode, the player is disabled automatically so it doesn't appear in the list of selectable ones. I went to the TMDB page for Young Sheldon season 5 (the one that doesn't work) and I added the external IDs myself a couple of days ago for all the episodes. Then I tried again to watch it through the addon but I was still having the problem. I tested again today to see if the problem was related to the episode being cached but it still doesn't work. I also tested some episodes I haven't tested before in case the cache is kept longer than I though with the same result. 
Is there any reason why a player could be disabled that I'm missing?

**Comment by jurialmunkey** [comment]
The only reason a player won't show up is if one of the asserted values is empty (eg like what you're seeing with the ID).

Have you tried refreshing the cached details for the item from the context menu? Details are cached for 14 days, so you've probably still got the old details cached locally

The show ID will come from the base show item - so it won't matter if you try to play a different episode because it'll be the base tvshow details that need to be refreshed.

**Comment by jurialmunkey** [comment]
Oh wait it's _tvdb_ epid. That'll come from Trakt. Check on Trakt that they've got the episode id listed.

**Comment by juanma-cvega** [comment]
Well, they must have added the IDs recently because I checked this morning on Trakt and the IDs were there and now I just tested it on another machine where I did a fresh install and it worked straightaway. I still need to test it again on the Shield after refreshing the details though but I'm closing the issue given it all looks good.

**Comment by jurialmunkey** [comment]
Probably Trakt pulled the ID that you added on TMDb ;)
