### ISSUE TITLE
SetResolveUrl fails randomly

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#595]
It may have nothing to do with your addon given this option is not supposed to work for every use case but I would like to know if there is something you can do from your side. 
I've been using the Embycon player for months with the setResolveUrl option and sometimes I get a Kodi error stating it cannot play the video just before the video starts playing. When I press ok on the error popup, the video just stops and I need to start all over again. I thought the problem came from the Embycon addon as it all started almost at the same time I updated to Kodi 19. Then I remembered I had set the setResolveUrl to on on the player so I tested it without the option and now I don't get any more error messages (only a screen flashing 3 times when the player changes the framerate before starting the video). 
The thing is, it seems there is some kind of timeout somewhere because when it works, normally it's when the video starts playing fast. When there is a delay starting the video it's when I tend to get the error message. This happens on a Shield, I just tested it on a PC where it plays almost instantly and I'm not getting any error.

**Comment by jurialmunkey** [comment]
That's because embycon doesn't use `setResolvedUrl()` and uses `xbmc.Player().play()` instead to play a playlist. You can see that on the following lines in its source and `setResolvedUrl` is never mentioned anywhere in the code -
https://github.com/faush01/plugin.video.embycon/blob/develop/resources/lib/play_utils.py#L112
https://github.com/faush01/plugin.video.embycon/blob/develop/resources/lib/play_utils.py#L532
(fyi - `player = xbmc.Player()` so `player.play() = xbmc.Player().play()`) 

Anything that uses xbmc.Player().play() will still play via setResolvedUrl because the code is still being called. The problem is that plugin instance used to play (e.g. embycon) finishes once it runs xbmc.Player().play(). Because Kodi didn't get a url via setResolvedUrl() before the plugin ended then it counts it as a failed play (and so retries).

I'm not 100% certain how the underlying C code works in Kodi. However, I get the sense that if xbmc player starts the file quick enough then Kodi wont reattempt because it sees a new file in the videoplayer. Though it still technically counts as a resolve failure, so you'll still get the popup after playing 5 items if there's no "successful" setresolvedurl plays inbetween.

If you set is_resolvable=false, you can still bypass the dummy file when playing from *inside* TMDbHelper by enabling `Restrict dummy setResolvedUrl method to library strm` under TMDbHelper Expert settings. However, for .strm in the Kodi library, you _must_ resolve to the dummy because Kodi considers all items in the library to be playable and thus resolvable (whereas with plugin directories outside the library I can override the IsPlayable flag and send the item to a script instead of a video).

**Comment by juanma-cvega** [comment]
Ok, I just tested the option you mentioned and it works fine as well so I'm closing the issue given there is nothing else to do. Thanks for the advise.
