### ISSUE TITLE
Addon not found for update in Kodi 19

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#596]
Someone must have already asked this as I don't think I'm the only one with the problem but I haven't found the issue in the list. In Kodi 19 I'm forced to verify manually by going to the repository whether there is an update for the addon. I have enabled the setting to allow updates for official addons from other repositories but it doesn't work. Is there any other thing that needs to be done for this to work?

**Comment by mrgsi** [comment]
This one has bugged me as well, and actually why I just came here. When I check the jurialmunkey repo, the addon is never Enabled. I update it, it gets enabled, then when I check it later, it's not enabled any more. If it's not enabled, it doesn't get updated. I allow updates from "any repo". This is the only add-on that has this issue and I have a lot of add-ons. I am thinking it is some kind of conflict due to the add-on also being available from the official Kodi repo.

**Comment by juanma-cvega** [comment]
I also use the catch up addon that is available in the official repo and in the author's one. The author has a beta repository but it doesn't get updated from it either so it seems a problem with Kodi itself

**Comment by jurialmunkey** [comment]
Yeah its a Kodi v19 issue. Hopefully it will be fixed in v20.

I will update the version in official repo soon.
