### ISSUE TITLE
Trakt List Container.Content and ListItem.DBType bug

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#6]
Hi Jurial,

Thanks for the great work with this addon and all your skins!

I have been doing some testing with the new Trakt integration and picked up a small bug with TV Shows in the "Trending Lists, Popular Lists, Liked Lists and Your lists" directories being set with Container.Content & ListItem.DBType movie instead of tvshow.

Thanks!

**Comment by jurialmunkey** [comment]
It was intentional because Trakt user lists can mix content types so I just set them all to movies in Kodi. However, I just pushed an update which will compare number of movies with number of tvshows and set Container.Content appropriately. ListItem.DBType should also set correctly now.

Can you test latest and confirm that it is now working correctly?

**Comment by skyfsza** [comment]
Just did a quick check and looks like DBType and Container.Content are being set as tvshow now.

Thanks for the update!
