### ISSUE TITLE
Missing thumbs for some TV Shows

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#602]
Not sure if this is an addon issue or what. Maybe someone can steer me in the right direction.
However I have some TV Shows that dont have any thumbnails for the show and the season. The episode is fine. I looked them up on the links below and there is a cover thumbnail. Not sure why they arent showing though.

 https://www.themoviedb.org/tv/63726
https://www.themoviedb.org/tv/32538
https://www.themoviedb.org/tv/99248
https://www.themoviedb.org/tv/14658

**Comment by jurialmunkey** [comment]
What exactly do you mean by "thumbnails"? A show/season doesn't have thumbnails because it isn't a video, so there isn't a still image screenshot like there would be with an episode. Shows/seasons have Art(poster) and Art(fanart) typically. Art(thumb) only makes sense for an episode.

Also all these shows are displaying with posters correctly for me inside TMDbHelper... Are you talking about posters missing in the library? Because TMDbHelper has nothing to do with your library metadata scraper.

**Comment by mrXoo** [comment]
ah yes I was referring to my library. I'm using the moviedb scraper for movies and tv shows. It shows the cover art on the website but doesn't scrape the images to my library.

**Comment by jurialmunkey** [comment]
Yeah themoviedb library scraper is maintained by someone else. Nothing to do with TMDbHelper other than both add-ons get their data from themoviedb API.
