### ISSUE TITLE
[Feature] Add to library without creating strm files

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#607]
Would it be possible to have the option to add a TV Show to the library without creating the strm files for each episode.

I know that this is currently possible using the "Navigation->Hide unaired episodes" option, however the problem with that is it hides the episodes when browsing the plugin. What would be nice is a separate option to turn off the creation of the strm files, so only the base show directory and the nfo file is created.

My reasoning for this is that it is nice to add the empty TV Show to my library so I can use the "Next Aired Library" path to see when the episodes air but I don't want fake strm files scanned into the library cluttering up the "Recently Added Episodes" widgets. 

Thanks

**Comment by jurialmunkey** [comment]
Do you use Trakt? This is what I use Trakt for. Add the show to your Trakt watchlist and it will show up in the Trakt calendar `TMDbHelper > Trakt > Your TV Shows Calendar >`

It works exactly the same as Library Next Aired but it's based upon your Trakt watched history + Trakt collection + Trakt watchlist.

It is exactly the same plugin:// path params as the library based one but with `info=trakt_calendar` instead.

**Comment by roidy** [comment]
Unfortunately that doesn't work for me..

I add the new show 'Naomi' which premieres on the 12th of January to my trakt watch list, it show up fine on the the Trakt website in my calendar but when navigating to `TMDbHelper > Trakt > Your TV Shows Calendar > This Fortnight`  it fails to appear even though my other shows that are in my library for the 12th of January appear.

Also tried with 'The Cleaning Lady' which premieres on the 4th of January, it appears on the website in my calendar but fails to show up under `TMDbHelper > Trakt > Your TV Shows Calendar > This Fortnight`

If I go to  `TMDbHelper > Trakt > TV shows Watchlist` they show up, they just don't list the premier episodes in the `Your TV Shows Calendar > This Fortnight`

**Comment by roidy** [comment]
Ok, so after some more testing I found that new shows appear in `TMDbHelper > Trakt > Your TV Shows Calendar > This Week` but not `TMDbHelper > Trakt > Your TV Shows Calendar > This Fortnight`

Could this be a bug?

---------------------------------------------------------------------

Ok, so after leaving it for some time they now appear in both This Week and This Fortnight..... Weird, I'm guessing there is some kind of caching happening and that's why there is a delay in the shows appearing.

**Comment by jurialmunkey** [comment]
> Ok, so after leaving it for some time they now appear in both This Week and This Fortnight..... Weird, I'm guessing there is some kind of caching happening and that's why there is a delay in the shows appearing.

Calendar lists are cached for 6 hours:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/matrix/resources/lib/trakt/progress.py#L269

Typically the calendar will only change every 24 hours, so I figure refreshing it every 6 hours is plenty for most cases. The only reason it'd change in less than 24 hours is by watchlisting something new.

If you do find the cache refreshing timing a problem, let me know I can look at tweaking it. Currently it's time based for the sake of simplicity but I can change it to check the activity log instead if necessary -- activity based refresh involves slightly more overhead because it needs an API call to retrieve the log and some extra computation to compare against the cached data but it ensures the list is always up-to-date.

Personally though, I've never found the time based cache to be an issue in normal day-to-day usage and I use the watchlist+calendar all the time.

**Comment by roidy** [comment]
Ok, thanks for the explanation, that make sense :thumb:

One quick question, in the calendar lists is there anyway to flatten a tv show that drops all it's episodes on the same day into just one entry with maybe a property that tells you how many episodes have been flattened?

 I'm going to create a new feature request for this.
