### ISSUE TITLE
Remove Next Page from widget

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#609]
When using:-

`plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=0&amp;days=14`

to fill a widget how can I get the full content of the list without having a `Next page` halfway though the list.

I've tried adding `&amp;nextpage=false` to the query and turning off `Show next page item on widgets` from the settings but I still only get half the list with a `Next Page` at the end

**Comment by drinfernoo** [comment]
Is it "Next Page" or "Show More"?

**Comment by roidy** [comment]
Definitely Next Page

**Comment by jurialmunkey** [comment]
I can't reproduce. `&amp;nextpage=false` works correctly for me:

![Honeyview_screenshot00183](https://user-images.githubusercontent.com/4618719/147840472-b3437d1d-ef90-4237-9926-42c050469444.jpg)


Paths (I used 30 days to make sure I was definitely getting more than a page worth)
`plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=0&amp;days=30&amp;nextpage=false`
`plugin://plugin.video.themoviedb.helper?info=trakt_calendar&amp;startdate=0&amp;days=30&amp;nextpage=true`



FYI - You cant get more than 20 items even if nextpage is turned off -- you just get first 20 items but the nextpage item should be hidden. There is deliberately no way to override the 20 item limit because otherwise it will get abused by people trying to display 1000 items at once and my API key will quickly get disabled.


> turning off Show next page item on widgets

This setting only applies if you put `&amp;widget=true` in the path (this gets automatically added to the path if the skinshortcuts dialog is open). Any setting which applies to widgets will only apply if the widget param is present.

**Comment by roidy** [comment]
>I can't reproduce. &amp;nextpage=false works correctly for me:

Yep, after restarting Kodi it now works for me 🤦‍♂️ 

>FYI - You cant get more than 20 items even if nextpage is turned off -- you just get first 20 items but the nextpage item should be hidden. There is deliberately no way to override the 20 item limit because otherwise it will get abused by people trying to display 1000 items at once and my API key will quickly get disabled.

Ok, I understand, thanks :thumb:
