### ISSUE TITLE
add `per_page` number in settings

### ISSUE THREAD

**Issue by fatshotty** [jurialmunkey/plugin.video.themoviedb.helper#612]
Hello
is it possibile to add the `per_page` number in settings?
I mean: browsing to Movies -> watchlist I see 20 items and then "next page". In the next page I see last 10 items.
I wonder: is it possibile to set the `per_page` items number in order to show all my 30 items in only one page?

Thanks

**Comment by jurialmunkey** [comment]
No, pagination limits are there for a reason. This has been covered many times before, e.g. see this comment https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/213#issuecomment-626748356

TMDb has a strict limit of 20 items per page for its lists and that cannot be changed. 

Trakt does allow limit changes but that's only because Trakt only supply item IDs, not item metadata or artwork so it doesn't increase their overhead much. BUT it _does_ increase the overhead to TMDb and FanartTV because each item requires an additional lookup to those services - so even a small increase of 10 items per page means an extra 20 requests per list, so with 10 widgets that's an extra 200 requests.

These services provide this data for free. Opening them up to excessive requests like this is a quick way to have my API keys rate limited or even disabled. Plus we should respect these services so they continue to provide the data for free and don't switch to a paid-only model like TVDb did...

**Comment by jurialmunkey** [comment]
@fatshotty - I've thought about this some more and I think maybe increasing the limits solely for sync data based lists won't be too bad -- i.e. only for Watchlist, Collection, In-Progress and Watched History based lists.

The majority of the items in these lists will already be cached and only new added/watched items will need to be looked-up, so the overhead cost of displaying extra items won't be too bad (except for the very first load). Plus many of these lists share items. Whereas a list like Trending Movies is more of a problem in terms of overhead because the items constantly change.

Can you test latest github (v4.4.55)? It adds an option for sync lists:
`TMDbHelper Settings > Accounts > Trakt > Increase synced lists items per page`

This will increase these lists to 84 items per page (reason for 84 is because 4,6,7,8 are all common factors so it works well for wall views).

**Comment by fatshotty** [comment]
thanks for replies
I'm going to test new version.
Just to sure: I meat to increase `item_per_page` for Watchlist and In-progress only. All other views doesn't need this feature, IMHO

Thanks

**Comment by fatshotty** [comment]
it works very well
many thanks ;)
