### ISSUE TITLE
What's the refresh duration for Trakt Watchlist in widget?

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#613]
Hi @jurialmunkey,

Greetings!

Even though I've set my Trakt Watchlist widget as random for both Movies and TV Shows using TMDB Helper in Arctic Horizon skin, still the widget is not refreshing (changing) randomly every time Kodi reloads. Is there any particular refresh duration for the Trakt Watchlist widget? Kindly let me know.

Thanks,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Anything Trakt sync related (e.g. watchlist / watched history / in-progress / collection) uses activity based caching rather than time based caching. Activity cache will only update if Trakt recorded a change for that sync data - i.e. for watchlist that means you add, remove, or watch an item on the watchlist.

However, as you point out, that's a bit of a problem for random sorting. I'll have a think about the best way to separate it so that the sorting can still update even if the activity hasn't changed.

FYI there has to be _some_ caching of a sorted list, otherwise you wouldn't be able to navigate it because the sorting would reapply after you open a new page -- which would be a mess with randomisation

**Comment by jurialmunkey** [comment]
@ShibajiCh - Randomised sync lists such as watchlist should now correctly refresh sorting if they're on the first page. Can you test latest github version (v4.4.53) and confirm that it's working correctly for you?

Essentially I added a check to refresh the sorting activity cache on reload if `sort_by=random` + `page=1`. 

That way the widget sorting will update every refresh since widgets are the first page but you won't lose your place when navigating other pages inside TMDbHelper; plus all the other non-random sort methods retain the speed advantage of activity based caching of sorting. Best of both worlds!

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thank you so much!
I’ve installed and tested the latest version 4.4.55 of the TMDB Helper from GitHub and it’s working perfectly while refreshing randomised Trakt Watchlists.
Thanks again!

Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Excellent! Let me know if you encounter any issues - but it seems to be working properly for me too so I'll close this one as solved for now.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Sure. I'll let you know if I encounter any issues.
Thanks again!

Regards,
ShibajiCh.
