### ISSUE TITLE
[Question/Bug] Library Integration not updating when lists are changed

### ISSUE THREAD

**Issue by ceefaxer** [jurialmunkey/plugin.video.themoviedb.helper#614]
Hi 
I hope you can shed some light on this problem. I can add lists and run updates, and everything new is added to the library. However, when I remove a list and force an update or simply leave it to update at a given time the content remains. I'm assuming that when a list is deselecvted or completely new list substituted then the update should remove all of the old lists from the library. I have removed the video source then changed what I want to linked cleared caches but this does not remove the reference files. 

So what do you think I could be doing wrong here. I enabled  'allow file renaming and deletion' in kodi settings which I thought might be it. Or is it just a case of deleting all files in the movie folder, clearing cache, rebooting and then re linking lists.

Im running kodi on a shield.

**Comment by jurialmunkey** [comment]
TMDbHelper does not delete files. It is intentionally non-destructive because media folders can have files from sources other than TMDbHelper and automated deletion of the folders could go very bad very quickly... Plus, any items manually added to the library via the context menu would end up getting deleted every time since they wouldn't be in one of your monitored lists.

To delete content from the library:

1. Remove the items from your list
2. Delete the corresponding folders for each movie/show in your source directory - if you need to keep the folders because you've got other content in them, then you will need to delete the `.strm` and `.nfo` files individually. 
3. Clean the Kodi library `Kodi Settings > Media > Library > Clean library`

Optionally, if you want to start fresh, you can delete the entire source folder rather than individual movie/show folders. If you delete the entire source folder then you will need to force an update from TMDbHelper settings after cleaning the library.

I think you're probably missing Step 3. Cleaning the Kodi library essentially removes any library items where the corresponding file no longer exists - if you don't clean the library then all the dead links to non-existent files will remain.

**Comment by ceefaxer** [comment]
Makes perfect sense. I thought it must be a feature and I just hadn't got my head around the updating workflow.
 Thanks for the help and your work.
