### ISSUE TITLE
Crashing with Linux

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#618]
Linux:
TMDB helper causes Kodi to crash when I click on the settings.

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7818880/kodi.log)

[kodi.old.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7818884/kodi.old.log)

Thanks

**Comment by jurialmunkey** [comment]
It's because you're not using the bundled python interpreter that comes with Kodi and are instead using the Linux distro version. Python 3.10.1 has a CPython interpreter bug. Nothing to do with TMDbHelper.
https://bugs.python.org/issue46070

See this thread for a possible fix - 
https://forum.kodi.tv/showthread.php?tid=366000
