### ISSUE TITLE
Hide movies based on JustWatch list of streaming options

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#620]
Could it be possible to add an option to hide movies that are not yet available in a streaming platform based on JustWatch? I don't know their API so this may require too many calls for it to be viable as it could take too long to load and then there would be the problem with filling a page with movies after some of them are filtered out but I would like to see your input on this.

**Comment by jurialmunkey** [comment]
The data is available via tmdb so it actually comes with the details call. Other than the issue with having potentially empty pages, the main problem is that I cache details call for 14 days to avoid unnecessary refreshing of details, so it would potentially lag behind. Plus I'm not certain how often tmdb syncs with just watch (but I expect it's more frequent than that)

You may actually be able to do this with the existing filter key params - or I should be able to adapt the code to make it work with it. I'll do a couple of tests in a bit and let you know

**Comment by juanma-cvega** [comment]
Is it possible to partially update the cache in the background? I was thinking maybe for the movies in the cache run a process on a schedule to update the streaming options only. Or just keep this information separately so its easier to update and use it to filter the movies.

**Comment by jurialmunkey** [comment]
Latest commit (v4.4.60) adds a `ListItem.Property(providers)` listing all available providers in one property and the ability to specify `is_empty` for a filter/exclude value. 

So you can now add `&amp;exclude_key=providers&amp;exclude_value=is_empty` to only get items that have a provider. Alternatively, you cn do `&amp;filter_key=providers&amp;filter_value=provider_name` to get items with a specific provider. You'll need the get tmdb details setting enabled in TMDbHelper > General to retrieve providers.

Examples:

Popular movies with providers
`plugin://plugin.video.themoviedb.helper/?info=popular&tmdb_type=movie&exclude_key=providers&exclude_value=is_empty`

Popular movies available on Netflix
`plugin://plugin.video.themoviedb.helper/?info=popular&tmdb_type=movie&filter_key=providers&filter_value=Netflix`

> Is it possible to partially update the cache in the background? I was thinking maybe for the movies in the cache run a process on a schedule to update the streaming options only. Or just keep this information separately so its easier to update and use it to filter the movies.

There's no point separating the info because TMDb API allows for bundling the different endpoints together as one request, so if TMDbHelper is getting some info for the item it may as well get all of it. Of course it is slightly quicker to get a smaller request with fewer endpoints but the slight speed benefit isn't enough.

Regardless, the main reason for caching is to avoid hitting TMDb with too many requests overall. I'm currently averaging ~3.5 million requests daily via my API key with ~100k unique daily users. If I start refreshing some data everyday that I only previously refreshed every 2 weeks then that number is going to jump massively -- even if each user only views 5 pages of items (i.e. 100 items), that's an extra 10 million requests a day.

**Comment by juanma-cvega** [comment]
Sorry for not coming back to you after you added this feature, I've been out. 
So, if I understand this correctly, if I want to add this filter I need to add it manually to widgets by editing the string in the action, right? Is there any way this can be added by default to the addon? How do you add it so you can navigate through the addon with the filter enabled?

**Comment by jurialmunkey** [comment]
> So, if I understand this correctly, if I want to add this filter I need to add it manually to widgets by editing the string in the action, right?

Yes that's correct - currently the only way to do it.

> Is there any way this can be added by default to the addon? How do you add it so you can navigate through the addon with the filter enabled?

Ah, I was only thinking you'd want to apply it to specific widgets not the entire addon. I'll have to think about best way to add an option - there's some parts where you wouldn't want it applied as it'd hide necessary items that don't have providers because they aren't media (e.g. base directory or the calendar section).

**Comment by jurialmunkey** [comment]
@juanma-cvega - A slightly different approach but relevant here. As of v.4.6.58 the Discover section now allows you to set Watch Providers as a filter rule. You should be able to recreate _most_ TMDb lists using Discover rules.

If you add multiple providers the match value is always ANY (OR) even if the match setting for other rules is set to ALL (AND). That way it is possible to have rules like "Genre is Action AND Comedy" on "Netflix OR Disney+" etc.

Also discover has the advantage of always having a full page of items because filter is applied server side before pagination.
