### ISSUE TITLE
Flatten tv shows with multiple episodes airing simultaneously doesn't seem to be working

### ISSUE THREAD

**Issue by alscaldas** [jurialmunkey/plugin.video.themoviedb.helper#622]
Hello,

I noticed that one of your most recent improvements to this excellent addon is fixing something that has always bothered me. The fact that instead of grouping all episodes of tv shows on lists like "Airing this week" it showed each episode separately.

Well, I'm using tmdb helper 4.4.61 (after the fixes you kindly did [here](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/621) ) and noticed that this feature either isn't working as expected or I didn't understand the way it should be working. 

I'm attaching a screenshot I've just taken that shows what I mean:

![screenshot00002](https://user-images.githubusercontent.com/29403156/148753072-57690de8-6950-4a1b-ba00-e4f6b75d173d.png)

Am I doing something wrong? Given the changes you made wasn't that "Father Brown" to be a single thumbnail instead being repeating itself 4 times?

By the way, I have the option "Flatten tv shows with multiple episodes airing same day" selected.

Again, thank you for your patience and promptness to solve these issues.

**Comment by jurialmunkey** [comment]
The option is applied specifically to the calendar
`TMDbHelper > TvShows > Your Calendar`
`TMDbHelper > TvShows > Next Aired Library`

I'm not sure what this "Airing this week" list is that you're displaying in the screenshot because there's no such list in TMDbHelper. There's "Your Airing This Week" but that displays TV Shows, not episodes.

**Comment by alscaldas** [comment]
Hello,

Sorry, in fact the list is indeed "Your Airing This Week". I have the habit of relabel these widgets. :)

But even considering it's related to TV Shows and not episodes shouldn't it be grouping the tv show and display it as one single occurrence instead of displaying it that many times (which I believe is the number of episodes aired simultaneously)?

Thanks for your assistance.

**Comment by jurialmunkey** [comment]
Ah ok. ~I don't use that list that much but I expected that Trakt would only display one entry per show in that list. I find it odd that they display multiple entries if the show is airing multiple times when it's specifically a list for "your shows airing this week" not _episodes_.~ EDIT: I'm an idiot. I forgot that this list uses the same API calendar episodes endpoint but I convert the episodes into tvshow items - which is why there's duplicates.

Anyway, the stacking function I wrote only applies specifically to episode types in the calendar. I would need to modify the function to stack tvshow types in that list -- which I can and will do, it just needs to be adapted first.

**Comment by jurialmunkey** [comment]
Ok v4.4.64 should stack correctly for this list now. The stacking is forced since I figure it should really always be enabled for this list because there isn't really any point to seeing duplicates of the same tvshow (whereas it makes sense to have an option to stack/unstack individual episodes).

~Note it will only stack shows next to each other. For example, if the show airs on separate days but there's other shows in-between then it will have separate entries. I'm not sure if it's worth the extra overhead of checking across the entire list. It'd only really be an issue with shows that air every night. I'll see how it goes and if it's a problem let me know and I can adjust it.~ EDIT: Scrap that. Thought of a better way to stack the tvshows where it will stack even if there's shows in-between. Added in v.4.4.65

**Comment by alscaldas** [comment]
Hey, it's working perfectly now!

And just to register, I also loved the new "Your In-Progress Episodes" list! 

It's essential to keep track of those tv shows that we watched just a couple of minutes from the 1st episodes to have an idea on the vibe of the series, intend to come back to resume later but just forget it and they get lost somehow among other series.

You've been doing an invaluable work with this addon!

**Comment by jurialmunkey** [comment]
Not sure why I left this issue open. Pretty sure it is working correctly now.
