### ISSUE TITLE
Combine split episodes into a single entry

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#625]
There are some TV shows (especially kids ones) that have shorter episodes that are then combined into a single one on TV (or other media). TMDB and other databases tend to have them split in their database which makes them not match local files. For example, Paw Patrol normally has double episodes on TV (and on Amazon Prime) but they are split on TMDB. I've found that IMDB is the only database (that I know of) that actually keeps double episodes instead of split them for the shows I've checked (basically Paw Patrol and PJ Masks). 
On Kodi, I think you can name the episodes with the pattern E01-E02 and it's clever enough to know it means the 2 episodes so it pulls both from the database but this is not reflected in the addon. 
Would there be any way to merge double episodes into a single entry? I know TMDB doesn't keep this information so maybe there was a clever way to know when to do it. I was thinking maybe by release date given these episodes are normally released on the same date. Then I realised Netflix releases episodes the same day for a season so maybe it could be like an opt-in feature per TV show?

**Comment by jurialmunkey** [comment]
I think things like the Netflix issue makes it particularly difficult. Not super keen on just arbitrarily stacking episodes based only on date - there's just too many what ifs.

Is the main issue not being able to find the matching local file to play? 

Also do you have some specific episode examples where they're stacked on imdb but not tmdb? I'll have a look at the metadata tmdb returns and see if there's anything that might specifically indicate a double episode.

**Comment by juanma-cvega** [comment]
> Is the main issue not being able to find the matching local file to play?

Yes, pretty much, only that instead of local it comes from an Emby server. If I'm lucky, I find the same video for both episodes when the search matches part of the name in the server but this is not guaranteed as the server uses TVDB. Using the player I created that matches TV show ID and release date it works as well but again, it finds the same video for both episodes.

> Not super keen on just arbitrarily stacking episodes based only on date - there's just too many what ifs

I agree, that's why I suggested this as an opt-in feature per tv show so you can verify first on TMDB whether the release date option works.

> Also do you have some specific episode examples where they're stacked on imdb but not tmdb?

As mentioned in the comment, Paw patrol and PJ Masks are split in TMDB (and TVDB and Trakt) but not in IMDB. You can just check the first 2 episodes of season one to see the difference and how the release date is the same for them.

Thinking about it, there would be a side effect problem with Trakt where the second episode wouldn't be marked as watched and you wouldn't see it on the addon to mark it manually from there but I would consider this as a minor problem.

**Comment by juanma-cvega** [comment]
I just double checked and the option I suggested may not work even for my own examples. The first 4 episodes of PJ Masks have the same release date but they cover 2 episodes, not one. IMDB shows these episodes as episodes 1 and 3

**Comment by jurialmunkey** [comment]
> The first 4 episodes of PJ Masks have the same release date but they cover 2 episodes, not one.

Yeah this was one of the "what-ifs" I was thinking about. I imagine this scenario happens fairly often with kids shows. 

> You can just check the first 2 episodes of season one

Ah, didn't realise the entire show was like this - I thought it might only be specific episodes. I'll have a look at the metadata that TMDb gives and see if there's something better than just the date to use.


> The first 4 episodes of PJ Masks have the same release date but they cover 2 episodes, not one. IMDB shows these episodes as episodes 1 and 3

Hmm, interesting that IMDb lists the Ep1-2 and Ep3-4 double episodes as Ep1 and Ep3. Are they listed as 1 & 3 on your Emby server? Or does 1-2 become 1 and 3-4 become 2?

If they're listed as 1 & 3 on the server side then finding a match shouldn't be much of a big deal - it's just a navigation matter of hiding the "inbetween" episodes that make up the second half of the double episode. 

But if they're condensed so that 1-2 becomes 1 and 3-4 becomes 2 then that's going to be _way_ more difficult to manage (probably impossible really - I really can't think of a way to make that scenario work).

**Comment by juanma-cvega** [comment]
> Hmm, interesting that IMDb lists the Ep1-2 and Ep3-4 double episodes as Ep1 and Ep3. Are they listed as 1 & 3 on your Emby server? Or does 1-2 become 1 and 3-4 become 2?

No, they are listed as episodes 1 and 2 actually. The more I look into it the more impossible to implement I see it. According to TMDB, episodes are split on purpose as they can be rearranged by the publisher for each different release format for many different reasons. And episode groups are not a good solution for this either. There could be an episode group that matches the release you have but that won't include (or exclude really) the episodes that come as part of another episode as they are not creating new IDs for them.
The only way I can see this to work is by creating and .nfo file that creates the mapping between the individual episodes returned by TMDB and the videos you have in the library/server/whatever so the addon can combine them. Similar to what Kodi allows you to do by adding the episodes included in the file name with the format E01-E02.
What do you think?

**Comment by jurialmunkey** [comment]
> No, they are listed as episodes 1 and 2 actually. The more I look into it the more impossible to implement I see it.

Ah that's a pain. Yeah that makes things far more difficult.

> The only way I can see this to work is by creating and .nfo file that creates the mapping between the individual episodes returned by TMDB and the videos you have in the library/server/whatever so the addon can combine them.

Hmm. This is an interesting idea.

I could see this working as an addition to the player file since the mapping will potentially differ depending on the player -- that way the items stay intact but you can remap them correctly depending on the player being used. For instance, something like the following added into the player file:
```
"remap_episodes": {
    "12345678": {
          "S1E1": {"episode": 1},
          "S1E2": {"episode": 1},
          "S1E3": {"episode": 2},
          "S1E4": {"episode": 2},
          "S1E5": {"episode": 3},
          "S1E6": {"episode": 3}
    }
}
```

Doing it earlier than at the player stage would be a problem as the items need to have the correct ID and season/episode numbers etc. in order to do the correct details lookups on TMDb and FanartTV etc.

**Comment by jojobrogess** [comment]
(btw idk if any of this works, i don't have split files like this)

There is a Multi-Episode Files naming scheme but I think that has to do with files that have two or more episodes inside of them, rather than sequential files that add up to one episode. But if TMDB shows episode 1 and 2 as separate maybe it'll work? idk 
`Paw Patrol S01E01E02`
reference: https://kodi.wiki/view/Naming_video_files/Episodes

This method would probably work better if you physically combined the episode parts into 1 file and then named them with this naming scheme `Paw Patrol S01E01E02` since TMDB shows them as two different episodes
reference(IS OLD):
https://forum.kodi.tv/showthread.php?tid=67368

***********************************************************************************************************************************

I know this isn't what you want, but if this pans out as extremely difficult to code/work out then maybe this info can help

**Comment by juanma-cvega** [comment]
Just for information, I found there is website that deals with this kind of mapping. https://thexem.info/
Unfortunately, it doesn't seem like there are a lot of TV shows added to the website and it doesn't look like it's simple to create and account and start adding new shows in there. But that's kind of what I had in mind with the local nfo file but using a web service so you don't need to keep maintaining and importing local files every time you do a clean install.
