### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#627]
Hi there,

Ive created a player and it works. Simple player finds links then displays them in a list.

Here is my issue. When I select that player from the list it goes through the motions and before it has finished searching the list of other players comes up again, without that one listed as if the player didn't find anything. If I click cancel then the search continues on. I then get a popup that says Playback Failed. If I then click OK then the links are displayed.

**Comment by jurialmunkey** [comment]
Pretty much impossible to say what the issue is without a debug log and the player file.

If the dialog listing the players pops up then that means one of the steps that you defined in your player file failed. It sounds like the end plugin is not completing all its code in one process properly and doing something weird like using runscript() to call code rather than via a proper internal method.

**Comment by mrXoo** [comment]
please reopen this i will get you a player a log shortly thankyou

**Comment by mrXoo** [comment]
[direct.foxy.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7931158/direct.foxy.txt)
cant upload a json file
[Uploading kodi.log…]()

**Comment by jurialmunkey** [comment]
You haven't uploaded your log. Could you please upload it.

Also where are you getting foxystreams for Matrix? I thought this plugin was discontinued.

**Comment by mrXoo** [comment]
Thanks it still says uploading log so I’ll fix that when at my computer. 
cant remember where I found the matrix fork but I’ll post the zip if I can’t find it.

**Comment by jurialmunkey** [comment]
> Thanks it still says uploading log so I’ll fix that when at my computer. cant remember where I found the matrix fork but I’ll post the zip if I can’t find it.

You need to wait for the file to finish uploading before you press comment. If you comment before it's finished it will never upload.

**Comment by mrXoo** [comment]
Here is a link to the 19 foxystreams
https://github.com/Ebonlore

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7946987/kodi.log)

**Comment by jurialmunkey** [comment]
Here's the problem https://github.com/ruinernin/foxystreams/blob/master/plugin.video.foxystreams/addon.py#L295

Foxystreams uses external Container.Update to rewrite the path to add the search query without actually adding the items to the directory before returning - so everything after the keyboard input is happening in a separate instance. Since it uses this method you should be able to skip the search+keyboard step entirely and just pass the query directly to the path it generates after searching.

e.g. try something like this:
```
"search_episode"    : [
    "plugin://plugin.video.foxystreams/?mode=search&query={name}",
    {"showtitle": "{name}"}
    ]
```

I got the path with the `query=` from your log but you can do the same thing by performing a search normally inside foxystreams and then checking what the end path is by looking at the output of `$INFO[Container.FolderPath]`

Depending on what the plugin does after this point, you might not even need any steps and just the path alone will do e.g.
```
"search_episode"    :  "plugin://plugin.video.foxystreams/?mode=search&query={name}"
```

**Comment by mrXoo** [comment]
I got this when I used foxy directly and it brought up 6 links.
DEBUG <general>: Saving fileitems [plugin://plugin.video.foxystreams/?mode=search&query=yellowstone+s04e10]
DEBUG <general>:   -- items: 6, sort method: 0, ascending: false
however when i used the same format in tmdb helper nothing was found, it just went back to the players list
Would it have something to do with the +

**Comment by jurialmunkey** [comment]
> however when i used the same format in tmdb helper

~How are you setting that format? What's your steps in the player file?~

You need to use encoding on the key:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes

Probably want either `{name_+}` or `{name_url+}`

**Comment by jurialmunkey** [comment]
This worked for me:
```
"search_episode"    :  "plugin://plugin.video.foxystreams/?mode=search&query={name_url+}"
```

Also this is probably best approach for playing directly because it will pop-up a dialog to select from
```
"play_episode"      : [
    "plugin://plugin.video.foxystreams/?mode=search&query={name_url+}",
    {"dialog": "True"}],
```

**Comment by mrXoo** [comment]
The bottom one works great for me, even comes up with specials. Thanks so much for all your help
