### ISSUE TITLE
Custom player not working

### ISSUE THREAD

**Issue by Sourcedine** [jurialmunkey/plugin.video.themoviedb.helper#629]
I wanted to create a player for an addon that I use but I can't get it to work.
I noticed that this is because the name of the addon folder contains capital letters.

I know it's not TheMovieDB Helper's fault because it's recommended by Kodi not to put capital letters in the name of the folder but would it be possible to make a correction so that the player works anyway?

Thank you!

**Comment by mrXoo** [comment]
something like this?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#regex-matching-in-actions

In the YouTube player, the play_movie actions search youtube for {name} and then look for any item with ListItem.Title that begins with the {title} key. The (?i) regex tells the re.match module to ignore case so that, for example, YoUTuBe tiTLe NaME will match YouTube Title.

**Comment by jurialmunkey** [comment]
See mrXoo's suggestion above. You should be able to ignore case by using a `(?i)` regex. The example from the youtube player is here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/matrix/resources/players/youtube.json#L7

**Comment by Sourcedine** [comment]
I tried with the regex but it doesn't work, my problem is in this line: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/c6ee97da3ea288bc60c1bc20fd2448c99287aecb/resources/players/youtube.json#L3

For example, can this code work?
"plugin" : "(?i)plugin.video.youTUBE"

**Comment by jurialmunkey** [comment]
No. Regex only works in the player steps.

Why would you need to do that?

**Comment by Sourcedine** [comment]
Because the addon I'm using has capital letters in its folder name.

When I try to select the player in TheMovieDB Helper it does not list it.

I tried renaming the addon removing the caps and it worked, but I no longer have the updates of the addon now and I have to redo the manipulation each time if I update it manually.

**Comment by drinfernoo** [comment]
@Sourcedine https://kodi.wiki/view/Addon.xml#id_attribute

> It must be unique, and must use only lowercase characters, periods, underscores, dashes and numbers.

**Comment by Sourcedine** [comment]
Yes I know, that's why I said it's not the fault of TheMovieDB Helper :)

I was just wondering if it was possible or not to work around the "problem" of the addon that I use.

**Comment by jurialmunkey** [comment]
> Yes I know, that's why I said it's not the fault of TheMovieDB Helper :)
> 
> I was just wondering if it was possible or not to work around the "problem" of the addon that I use.

Then rename the folder and the addon id in its addon.xml so that it is a valid id.

The ID in the player file is only used by tmdbhelper to check if the plugin is enabled and to retrieve the icon, so you can always point it at some other addon that exists in your system instead. But really the author of the plugin should fix their ID so it's valid as there is absolutely no reason to use capital letters in the ID
