### ISSUE TITLE
Artwork quality

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/plugin.video.themoviedb.helper#632]
Hey there. I am not sure if this is the right way to go about this. But I was wondering what quality artwork this addon grabs from TMDB and fanart.tv? And if there would be any way to set a preference to highest quality artwork? Maybe I am off base here, so please delete if not appropriate. I love the addon by the way. Great work. I use it daily and have never been disappointed!

**Comment by jurialmunkey** [comment]
Fanart from both TMDb and fanart.tv are in the original source image format (i.e. highest quality). Posters from Fanart.tv are also in the original format (i.e. highest). 

Posters from TMDb are w500 (so around 500x735 depending on the poster's aspect ratio). I don't get originals because the default Kodi texture setting will downsample non-fanart images above 720p - i.e. anything outside of 1280x720 box that isn't 16:9 artwork gets scaled down anyway, so there's no point getting high res posters. 
https://kodi.wiki/view/Artwork/Cache#Texture_optimization

Also, contrary to intuition, higher res source images for posters can end up looking worse because Kodi is actually better at upscaling than it is at downscaling.

**Comment by jurialmunkey** [comment]
More detailed history of bad image downscaling in Kodi is available in this thread:
https://forum.kodi.tv/showthread.php?tid=200401

It's not as bad as it used to be, particular into the texture cache itself but it's still a problem for "on-the-fly" downscaling done by the skinning engine -- so you really won't have much advantage getting higher res posters and most likely will end up with it looking worse.

**Comment by ambulancePilot** [comment]
Thank you so much for the detailed answer! That's very helpful to know. Thanks again for the amazing work.

Further to the downscaling issue, I know exactly what you mean. For whatever reason, software finds it easier to upscale than downscale. I've seen super high resolution images get downscaled and look pixelated as a result.
