### ISSUE TITLE
Poster image instead of tmdb helper icon

### ISSUE THREAD

**Issue by Bequiet19** [jurialmunkey/plugin.video.themoviedb.helper#634]
When I tested two versions of tmdb helper new and old 4.4.0, I noticed that in the new version, is a stretched poster is displayed instead of the tmdb helper icon. I only noticed this with tmdb helper. Other adddones display the icon properly.
New
![new1](https://user-images.githubusercontent.com/79144331/152202533-386a1cbe-2439-4605-92ff-acc1e0beff18.png)
Old
![old1](https://user-images.githubusercontent.com/79144331/152202572-a08cffc7-93c6-4f39-9d79-005136cdd65a.png)
New
![new2](https://user-images.githubusercontent.com/79144331/152202609-39843299-9ae2-483d-85d6-f51dbd3d7c65.png)
Old
![old2](https://user-images.githubusercontent.com/79144331/152202639-c03a2b6e-67f6-4668-b4e8-aee9994b8c28.png)

**Comment by jurialmunkey** [comment]
That's a skin issue where they are applying `<aspectratio>stretch</aspectratio>` to poster artwork rather than `scale` or `keep`.

Latest commit will workaround it by not putting the icons in art(poster) but really the skinner should fix it because stretch is the worst approach for resizing posters.
