### ISSUE TITLE
On version 4.5.28 TV shows watchlist all TV shows show up marked as watched

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#639]
Using AuraMod K19.3 Nvidia shield on Android 11 just notice on TV shows watchlist all TV shows show up marked as watched but when you enter the TV show the episodes are correct

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/152715789-7a33f866-f675-4755-bcad-2ad6cc9419eb.jpeg) Watchlist 4.5.31

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/152715828-3be14b10-25e4-41bc-8de9-2c8a3b91bcd8.jpeg)

**Comment by jurialmunkey** [comment]
I can't reproduce using latest github v4.5.31 - works perfectly fine for me. Please test with latest github version.

**Comment by xyzfre** [comment]
I didn't try that version yet 4.5.31 ,,when I was on version 4.5.22 I didn't have this issue ,, but when I get a chance I will definitely try the latest version 4.5.31

**Comment by xyzfre** [comment]
> I can't reproduce using latest github v4.5.31 - works perfectly fine for me. Please test with latest github version.

Just in case if I try the new version and the issue is still there any suggestions that you recommend I should try ,,trying to prepare myself so when I get home I'm hoping it's not on my end everything was working perfectly on version 4.5.22

**Comment by xyzfre** [comment]
Just install the latest version 4.5.31 and for some reason still having the same issue it's only happening with my TV shows watchlist being marked as watched but the movies Watchlist it is working properly none of them are checked off as watched

**Comment by xyzfre** [comment]
So I reverted back to 4.5.26 and I was correct on that version my TV show watchlist shows up correct but not too sure on what version I started getting the issue I noticed it on 4.5.28

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/152849588-b008dd72-d3ae-4854-9214-154ebf389c1c.jpeg) 4.5.26

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/152849744-ba757af4-34b5-4252-9909-3dadbfcf144c.jpeg) 4.5.26

**Comment by xyzfre** [comment]
Using K19.3 AuraMod ,,Nvidia shield 2019 would really appreciate any help love using TMDB Helper

**Comment by matke-84** [comment]
@xyzfre 
I don't have this problem on my skin (titan bingie mod).

**Comment by xyzfre** [comment]
I tried revoking Trakt and re- authorizing but no go don't know what else to try I'm not sure why reverting back to 4.5.26 fixes the issue ,, I wonder if it's a skin issue but then again reverting it 4.5.26 fixes it

**Comment by xyzfre** [comment]
So I did some more testing by checking different versions ,it looks like on my end the issue started after 4.5.26 because that version is also working properly for my TV show watchlist 
So the issue started for me on version 4.5.28 and above hope that makes sense

**Comment by jurialmunkey** [comment]
Try deleting trakt cache from expert settings and then restart kodi

**Comment by xyzfre** [comment]
> Try deleting trakt cache from expert settings and then restart kodi

I just went to settings ,,went to expert under Debug section but all I see is delete cache is that what you're referring to appreciate all this feedback

**Comment by drinfernoo** [comment]
@xyzfre Yes.

**Comment by xyzfre** [comment]
> Try deleting trakt cache from expert settings and then restart kodi

I deleted the Trakt cache excited Kodi right after ,and booted it back up and the same issue

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/152883968-eea89e3a-9cfe-4d35-8394-05c9f7252e54.png) sorry for being a pain but confirm on my end right after this commit is when I started having that issue My apologies this is killing me lol ,, I wonder if anybody using AuraMod latest version is having the same issue

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/152884405-bf1f745f-da76-4fee-9f23-0d7922c52ef2.jpeg) sorry for being a pain but confirm on my end right after this commit is when I started having that issue ,,on 4.5.26 it was still working properly,, I wonder if anybody using AuraMod latest version is having the same issue

**Comment by jurialmunkey** [comment]
It's a skin issue due to faulty logic in their watched indicator variables. Specifically this line:
`
<value condition="Integer.IsGreater(ListItem.Property(TotalEpisodes),0) + Integer.IsLess(ListItem.Property(UnWatchedEpisodes),1) + [Container.Content(tvshows) | Container.Content(seasons)]">indicator/checkmark-fo.png</value>
`

`Integer.IsLess` considers `None` to be the same as `0` so this condition marks as watched even though this property doesn't exist for these items.

More importantly, it is faulty logic to consider unwatched episodes being 0 to mean the show is watched. There are many reasons an unwatched show might have 0 unwatched episodes for instance it hasn't aired yet so no episodes exist to watch or there's simply no data available.

A more correct variable condition to use would be the following which checks that the watched episode count matches the total episode count and that there is at least 1 episode.
`
<value condition="Integer.IsGreater(ListItem.Property(TotalEpisodes),0) + String.IsEqual(ListItem.Property(WatchedEpisodes),ListItem.Property(TotalEpisodes)) + [Container.Content(tvshows) | Container.Content(seasons)]">indicator/checkmark-fo.png</value>
`

You will need to get the skin author to fix this.

**Comment by xyzfre** [comment]
Thank you for your response and for the feedback hopefully it's something that can be addressed because TMDb Helper and AuraMod always have worked well together for me,, and thank you for all your hard work my friend much  respect ✊🏼

**Comment by xyzfre** [comment]
My apologies for commenting on this old issue again but I was just curious why does this only happen with TMDB H and not other add-ons when using AuraMOD with Trakt it seems it only happens with TV shows not movies ,,on version 4.5.26 and below it works without this issue, that's the version I've been on but would love to update to the newer version

**Comment by jurialmunkey** [comment]
> My apologies for commenting on this old issue again but I was just curious why does this only happen with TMDB H and not other add-ons when using AuraMOD with Trakt it seems it only happens with TV shows not movies ,,on version 4.5.26 and below it works without this issue, that's the version I've been on but would love to update to the newer version

Because other add-ons are incorrectly setting a value for unwatched episodes to equal total episodes if they don't have watched episode data.

If you don't know how many episodes have been watched then you don't know how many are unwatched either, so neither value should be set. However, these add-ons are just assuming that "no data" = "none watched" which is not necessarily true.

You can force this type of behaviour by disabling the "Unwatched counts only on in-progress tvshows" setting in `TMDbHelper Settings > Accounts`

**Comment by xyzfre** [comment]
Thank you for your response and your explanation ,and DEFINITELY your work around for this issue ,disabling that option did the trick,feels GREAT!! to be on the latest version of TMDB H I was behind so many updates Thanks again jurialmunkey💯💯💯

**Comment by xyzfre** [comment]
Wow!! 👏🏼🙌🏼GREAT job on the current updates seeing a big speed performance since I last updated everything seems much smoother (using Nvidia Shield 2019 Pro with AuraMOD),thank you @jurialmunkey for your AMAZING work with TMDB Helper
