### ISSUE TITLE
[Bug] Some lists don't work properly

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#640]
I wrote to you on another issue but I think it is better to open a new one. 
As the title says some lists don't work properly in tmdb helper. For example, when I enter in Trakt popular, trending, most played, anticipated movies, top 10 box office, for the first time, everything works, but if I enter again, from the whole list just first or first two pages remain. Also if I want to play a movie nothing happens, more precisely, moves me to root folder. But if first going to information dialog and pressing the play button then play the movie. This happens with only a few trakt lists (movie and tv show). Everything else works properly. I tested these lists in elementum and they work. I reinstalled tmdb helper and the same thing happens. This happens on both platforms, windows and android.
![trakt](https://user-images.githubusercontent.com/74268331/153645287-77bdf700-8104-4749-8c1e-a7e76ca84183.png)

**Comment by jurialmunkey** [comment]
As far as I can tell the TraktAPI has some bug where the header capitalisation is inconsistent on different pages. It's always returned the page details as `X-Pagination-Page` but now on some random subsequent pages it is returning it as `x-pagination-page` instead.

The python requests module has a special dictionary class which makes the headers case insensitive so the first time through after making the request is fine. The problem is that caching the request to disk forces the specific capitalisation to be stored. It was never a problem before because it was always consistent as `X-Pagination-Page`.

Anyway latest version will force the headers to always be lowercase before caching so it should solve the issue.

**Comment by jurialmunkey** [comment]
FYI you'll need to delete your Trakt cache and restart Kodi after installing latest version

**Comment by matke-84** [comment]
@jurialmunkey
This solved half the problem. It still remains that I can't play a movie from these lists. I even tried to set in kodi to go to information dialog first instead of playing the movie, but that function doesn't work in these lists either. As I showed you in the picture, it's go back in the root folder.

**Comment by jurialmunkey** [comment]
> @jurialmunkey This solved half the problem. It still remains that I can't play a movie from these lists. I even tried to set in kodi to go to information dialog first instead of playing the movie, but that function doesn't work in these lists either. As I showed you in the picture, it's go back in the root folder.

It's very unusual. Looks like it was something to do with the delayed cache writing but I'm not sure what exactly. 

I've reverted the delayed cache write in latest version. Can you test and see if it fixes things? You'll need to delete your Trakt cache again -- I think it is just isolated to the Trakt cache so I don't think you'll need to delete the others.

**Comment by matke-84** [comment]
@jurialmunkey
I'd say it works. But unfortunately, this affected on speed of opening lists. 😞

**Comment by jurialmunkey** [comment]
> @jurialmunkey I'd say it works. But unfortunately, this affected on speed of opening lists. 😞

Yes it's very annoying as the delayed disk write definitely helped performance. I'm just not certain exactly what the issue is so I'll need to leave it out for now until I can identify the cause.

**Comment by matke-84** [comment]
@jurialmunkey
I hope you will find where the problem is.

**Comment by matke-84** [comment]
@jurialmunkey 
Maybe it wasn't necessary to revert everything back. I just tried to revert back only trakt api to go without cacahe_manual and I'd say it works and we got a little on speed. Of course if you think that otherwise all this made a problem and you have some other idea then ok.

**Comment by jurialmunkey** [comment]
> @jurialmunkey Maybe it wasn't necessary to revert everything back. I just tried to revert back only trakt api to go without cacahe_manual and I'd say it works and we got a little on speed. Of course if you think that otherwise all this made a problem and you have some other idea then ok.

Without resolving the underlying issue it is likely to cause issues down the line. I'm fairly certain the issue is due to dictionaries being mutable so the object is being modified before it is written to disk cache. The threading makes it even more difficult to track down where exactly that's happening.

However, if I deepcopy the object both to _and_ from the temp memory storage that should ensure it is an entirely separate object before any additional operations occur. It will add more overhead but it definitely still be faster than disk read/writes, and should be faster than using window properties (`deepcopy(obj)` should be faster than transforming to/from string using `eval(repr(obj))` to put into a property)

I've stuck it in a separate branch for the time being just in case there's some other issue that crops up but I'm fairly sure this should solve it and allow for delayed disk caching.

You can test via this branch:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/delaycache

**Comment by matke-84** [comment]
@jurialmunkey 
Okay, I think it's sorted out. But I also noticed some other things.
1. Now we have a problem when we switch TMDb artwork quality, cache has to be deleted and the kodi reset to show all artworks. That was not necessary before.
2. I got this error a few times.
> INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.addon.cache get_cache
                                                   Error Type: KeyError
                                                   Error Contents: ('my_object',)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/addon/decorators.py", line 53, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/files/cache.py", line 36, in get_cache
                                                       return pickle_loads(self._stored[cache_name]['my_object'])
3. I have impression that even after these changes, opening the list it's still a little slower than before. For example, you will see in log an example when opening the season, that season opens in 20 seconds. Then to open only 4 seasons it's need about 4 seconds. You will see in relation to the previous log that there are differences in some cases of about 1 second for other lists. As far as I could noticed, api items are the most time consuming. Note that the actual operation of the list opens about two seconds longer than the measurements in the log file. I may be wrong, but it seems to me that TMDb lists open a little faster than trakt lists.
https://paste.kodi.tv/ipucubiwij
If I notice anything else, I'll let you know. Also, if you need anything else, I'm here to help.

**Comment by matke-84** [comment]
@jurialmunkey
Now I realized one thing. When throw out this error that I wrote you then the season opens long.

**Comment by jurialmunkey** [comment]
Error should be fixed now. I forgot to update a key name before I pushed an update.

**Comment by jurialmunkey** [comment]
> As far as I could noticed, api items are the most time consuming. 

`item_api` is the total time it takes to get the data from TMDb+FanartTV and make the listitem from it.

`item_tmdb` and `item_ftv` are the pure request time for each API -- it is practically impossible to speed these up as it is basically just how long it took to connect to the server and receive the data. If these combined approximately equal item_api time then there isn't much to optimise.

Movies should be faster here because the FanartTV and TMDb request are done at the same time. Tvshows are slower because we're forced to wait for the TMDb request first to be able to get the TVDb id that FanartTV needs.

> Note that the actual operation of the list opens about two seconds longer than the measurements in the log file. I may be wrong, but it seems to me that TMDb lists open a little faster than trakt lists.

Trakt API has been slow past day or so. In your first log entry you can see it took almost 2 seconds just to get the raw list data from Trakt.

**Comment by matke-84** [comment]
> Error should be fixed now. I forgot to update a key name before I pushed an update.

Yes, I think this error has been fixed.

Regarding the problem with settings "TMDb artwork quality", it seems that problem is with artworks from TMDb. For example, if I change from medium to original, I don't get any artworks at all for certain movies or tv shows, no poster, no fanart... If I delete cache and reset kodi then everything works.

![artowrk](https://user-images.githubusercontent.com/74268331/153769753-4edf0e13-5809-4957-82ed-0fd7dd46d796.png)
![unnamed](https://user-images.githubusercontent.com/74268331/153770104-a7c3bff5-f4b4-41d1-a36f-669eb469c398.png)

**Comment by matke-84** [comment]
> `item_api` is the total time it takes to get the data from TMDb+FanartTV and make the listitem from it.

Is there space for improvement here?

> `item_tmdb` and `item_ftv` are the pure request time for each API -- it is practically impossible to speed these up as it is basically just how long it took to connect to the server and receive the data. If these combined approximately equal item_api time then there isn't much to optimise.

Yes, unfortunately, but results aren't so bad here, in terms of logs.

> Movies should be faster here because the FanartTV and TMDb request are done at the same time. Tvshows are slower because we're forced to wait for the TMDb request first to be able to get the TVDb id that FanartTV needs.

I don't think there is any excessive difference, the average time is almost similar when opening movies and tv shows, about 5-6 seconds according to the official measurement.

> Trakt API has been slow past day or so. In your first log entry you can see it took almost 2 seconds just to get the raw list data from Trakt.

Yes, maybe I didn't notice.

**Comment by jurialmunkey** [comment]
> > `item_api` is the total time it takes to get the data from TMDb+FanartTV and make the listitem from it.
> 
> Is there space for improvement here?
> 

Not really. The only real possible area for optimising is cache read/write as that's the next biggest cost after API request speed. Everything else is so minimal now it isn't worth optimising. When I profile everything I typically get between 0.400-1.500s for requests; 0.005-0.150 for caching; and less than 0.005 for the rest of the operations (it often doesn't even hit my 0.001 log threshold so definitely not worth optimising as the gain won't be noticeable).

Cache speed by itself isn't bad. However, considering practically everything goes through the cache, even a small optimisation could have a noticeable improvement. For example, reducing cache times by an average of 0.025 sec at 20 items x 3 caches could give up to a 1.5 second improvement.

> > `item_tmdb` and `item_ftv` are the pure request time for each API -- it is practically impossible to speed these up as it is basically just how long it took to connect to the server and receive the data. If these combined approximately equal item_api time then there isn't much to optimise.
> 
> Yes, unfortunately, but results aren't so bad here, in terms of logs.
> 

I changed how it was being logged so it isn't worth comparing to previous results from older versions. Older versions just looked at the overall cost for each because they used to be separated. 

That's why I added the `item_api` log to compare the overall item builder time versus the api request time so that I can tell if improvements are from optimisation or it is just a slower/fast request from the server.

**Comment by matke-84** [comment]
@jurialmunkey
The latest version of delayed cache write branch worked ok with decent speeds. I haven't noticed any bugs but honestly I haven't tested for a long time. It seems to me that only this change has brought decent results. The average is somewhere around 4.5 seconds, unfortunately now it has gone to over 6 seconds. But I have no doubt that you will find a way to find a solution for some acceleration. 🙂

**Comment by jurialmunkey** [comment]
^^^ I think I've got the delay cache write working properly now. On normal matrix branch.

Also a few of the issues with artwork not refreshing properly after changing quality should be fixed too now.

**Comment by matke-84** [comment]
> ^^^ I think I've got the delay cache write working properly now. On normal matrix branch.
> 
> Also a few of the issues with artwork not refreshing properly after changing quality should be fixed too now.

Yes, I think both work well. We returned to an average of about 4.5-5 seconds, which is much better than over 6-6.5. Great. 🙂 I'll test a little more, so if I notice anything, I'll let you know.
