### ISSUE TITLE
Artworks from fanart.TV in french

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#646]
Hi @jurialmunkey 

I'm running the new betra (v.4..5.71) and Since you made a lot of changes concerning the way artworks are called from TMDb / Fanart.tv, I"m experiencing issues to retrieve Thumbs (Landscaspe display) and Clearart from fanart.tv.

My settings: French langage.. I Know there is not a lot of french artworks on fanart.tv but before the changes, I was abble to retrieve those in english instead. 

I don't know if it is possible, like I set on tmdb python scraper, to chose langage display only for artworks on fanart.tv. Like this, we will be able to have Information in french and artworks in english.

Another point: I set MPAA text to ''Classé '' (french) in TMDbH settings.. But when there is no MPAA ratings, see what's happen in display:
![mpaa-missing](https://user-images.githubusercontent.com/49578130/154397897-6de764b7-98e6-4dd8-9a4f-120da0a29bbc.png)

I also attached my log if it can help:
[kodi.old.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8085279/kodi.old.log)

Thanks a lot for this addon and all your work 👍

**Comment by jurialmunkey** [comment]
> I don't know if it is possible, like I set on tmdb python scraper, to chose langage display only for artworks on fanart.tv. Like this, we'll will be able to have Information in french and artworks in english.

Can you test 4.5.72? Adds an option to allow fallback to English if main language not available. Will be enabled by default and should restore the old behaviour. Should also now be possible to select artwork manually from any language.

> Another point: I set MPAA text to ''Classé '' (french) in TMDbH settings.. But when there is no MPAA ratings, see what's happen in display.

That particular show doesn't have MPAA data on TMDb: https://www.themoviedb.org/tv/11250-pasi-n-de-gavilanes

The visual bug is due to an issue in Arctic Horizon not creating the `| Watched X of Y` text correctly if watchedepisodes is empty (it's just showing the total episode `Y` without the first part). 

You can work around it by disabling `TMDbH Settings > Accounts > Unwatched counts only on in-progress shows` which will cause shows without in-progress data to have unwatchedepisodes set to 0 rather than None.

**Comment by alKODIque** [comment]
Thanks a lot, 
Everything seems to be ok now 👍

I also desactivate `TMDbH Settings > Accounts > Unwatched counts only on in-progress shows` and it work (For media without MPAA) 😉
