### ISSUE TITLE
[Bug] Artwork manager doesn't work with the latest updates

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#651]
Whatever artwork I want to change I can't. For example, I click to change my poster, but nothing happens.

**Comment by matke-84** [comment]
@jurialmunkey
The latest version that worked was 4.5.69. I haven't even noticed the artwork change doesn't work so far.

**Comment by lebigboss** [comment]
For me too
With the 4.5.69
![-1500766351-1645281180000](https://user-images.githubusercontent.com/12912677/154807665-baa4622c-93da-4520-94ea-20e4af29931d.png)



With the 4.6.0
![1960590357-1645281420000](https://user-images.githubusercontent.com/12912677/154807691-9e092bef-4784-4b93-b11a-38851fbddbe6.png)

**Comment by lebigboss** [comment]
it's good for me, I deleted everything and installed again and everything works

**Comment by matke-84** [comment]
@lebigboss
I'm talking about artwork manager. Try with artwork manager to change some artwork (poster, fanart...).

**Comment by lebigboss** [comment]
@matke-84  ok sorry so it doesn't work for me too

**Comment by matke-84** [comment]
@jurialmunkey
Not good. Now we don't get artworks from fanart.tv.

**Comment by alKODIque** [comment]
I think the issue is due to the language that is not include in the cache of the artwork manager.. and the last commit seems to set that! 👍

**Comment by jurialmunkey** [comment]
> @jurialmunkey Not good. Now we don't get artworks from fanart.tv.

Works fine for me

![image](https://user-images.githubusercontent.com/4618719/154824018-37a9e261-008f-4be0-a8ed-8b505b345640.png)

**Comment by alKODIque** [comment]
@jurialmunkey 

I just installed the last beta, but it does'nt work for me.. (no artwork from fanart.tv)
![Screenshot_20220219-195315](https://user-images.githubusercontent.com/49578130/154824214-20186cb3-b488-4492-aa0d-8d44f9fa8884.png)

Only get artworks from TMDb


Here is my log if it can help
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8103265/kodi.log)

See the erro: `ERROR <general>: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://assets.fanart.tv/fanart/tv/360261/tvposter/euphoria-2019-61e39f119e68f.jpg`

**Comment by jurialmunkey** [comment]
> ERROR <general>: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://assets.fanart.tv/fanart/tv/360261/tvposter/euphoria-2019-61e39f119e68f.jpg

That's not a TMDbHelper issue. That's an issue with Kodi's SSL certificates not matching the certificates for FanartTV. Kodi is declining to create an https connection to download the artwork because it believes the connection is not secure.

The URL is correct - you can see that by going to that url.
https://assets.fanart.tv/fanart/tv/360261/tvposter/euphoria-2019-61e39f119e68f.jpg

Likely the FanartTV SSL certificate expired and was updated to a new one but Kodi has not yet updated it's own certificates.

**Comment by jurialmunkey** [comment]
FYI - https://kodi.wiki/view/SSL_certificates#Trust

**Comment by alKODIque** [comment]
Ok so if I understand, maybe I cleared the cache (thumbnails and texture13.db) but kodi did not renew it's SSL certificate yet. So the issue will be resolved by itself when it will be renew by kodi?

**Comment by alKODIque** [comment]
HA!!!
@jurialmunkey ... I think the issue is due to what the main message said on fanart.tv homepage lol: https://fanart.tv/

See: 
![Capture d’écran 2022-02-19 203506](https://user-images.githubusercontent.com/49578130/154824943-4a7da092-0590-46a5-9e36-4cedde3c329b.png)

Last message on their discord server:
_**The database migration is being postponed as the new server has finally been provisioned, so looking to put it straight onto that!
Will pencil the database migration for Sunday instead**_

**Comment by jurialmunkey** [comment]
@alKODIque -  Very interesting! Though if the SSL has expired as a result of the server move then Kodi's certificate will remain out of date - I'm not sure how frequently Kodi updates SSL certificates.

**Comment by alKODIque** [comment]
@jurialmunkey 
I'm sure that one happen in very very rare case haha!! 
Was not easy to findout!!

**Comment by matke-84** [comment]
@jurialmunkey
Hahaha. What a coincidence. We are then waiting for a solution on the other side.

**Comment by alKODIque** [comment]
For information, I see that some other script having the same issue with SSL (other than kodi) and it serms  it’s because fanart.tv are currently using a zero ssl certificate rather than a letsencrypt one.

**Comment by alKODIque** [comment]
it's all resolved for me now, since fanart.tv update the webservice to return "none" https urls ... 
api requests now return the url as `http://assets.fanart.tv`  and it wok for me

**Comment by matke-84** [comment]
Yeap, work again.
