### ISSUE TITLE
Fanart.tv images not populating anymore

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#653]
Hi @jurialmunkey,

There seems to be some changes that have happened recently with the Fanart.tv api due to which the images are not populating anymore. Kode from Fanart.tv team asked me to raise an issue ticket with you and said that you can connect with him on Discord if needed. He'll help you. I'm on TMDB Helper latest version 4.6.5. Please look into the issue when possible. Thanks in advance!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Not a TMDbHelper issue. FanartTV SSL certificate changed and Kodi is rejecting the connection because the certificate it has does not match. See comments here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/651#issuecomment-1046136476

FanartTV have "resolved" the issue by returning http:// rather than https:// image urls. However, that's a poor solution as any image in Kodi which still lists the https:// url will continue to not work - that means you have to reset your entire library database and rescrape if your images are https: urls -- it isn't just TMDbHelper.

TMDbHelper already gives you options to refresh details.

For individual items:
`Context Menu > Manage Artwork > Refresh All Artwork`

OR you can delete the entire ItemBuilder and FanartTV caches to force everything to rebuilt.

**Comment by AakashC2020** [comment]
Thanks @jurialmunkey!

I'll discuss with Kode from Fanart.tv team and see if they can provide a proper resolution to this problem.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
> Thanks @jurialmunkey!
> 
> I'll discuss with Kode from Fanart.tv team and see if they can provide a proper resolution to this problem.
> 
> Thanks and Regards, ShibajiCh.

I think it might be something the needs to be fixed on the Kodi end of things if the certificates no longer match. It sounds like the replacing https with http is just a work around until that happens.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Kode from Fanart.tv has resolved the issue by doing the following:

"the SSL was missing the ca_bundle, I had to install the certificate manually"

You can close this ticket if you want.

Thanks and Regards,
ShibajiCh.
