### ISSUE TITLE
No fallbak to English artwork

### ISSUE THREAD

**Issue by Guillaume5464** [jurialmunkey/plugin.video.themoviedb.helper#654]
Hi,

I am on kodi 19.3 matrix with auramod and tmdb helper, version 4.6.5, the last one I guess and using it in french version, but the fallback to english artwork its not working, actually its taking the first one on the list, when I go to change the landscape, so sometimes its in russia, or deutch... And for some landscape, the french version exits but it dosent take it.
Hope I was clear enough ;-)
Thanks for your help.

**Comment by Guillaume5464** [comment]
And Im with a raspberry pi4 with libreelec, version 10.0.1.

**Comment by jurialmunkey** [comment]
^^^ Can you try v4.6.6? I think that should work. You'll need to refresh the artwork for the item from the context menu `Context > Manage Artwork > Refresh all artwork` -- alternatively , you can delete the "Item Details" cache from expert settings and restart Kodi to force all items to be rebuilt.

**Comment by shkope** [comment]
[https://imgur.com/nMtI43e](url)

**Comment by shkope** [comment]
for example, for the new chainsaw massacre, I don't have a clearlogo, yet I checked "return to English when the main language is not available
tmdb 4.6.6

**Comment by jurialmunkey** [comment]
> for example, for the new chainsaw massacre, I don't have a clearlogo, yet I checked "return to English when the main language is not available
> tmdb 4.6.6

@shkope
Please check the website first. No clearlogo artwork for this movie exists in any language:
https://fanart.tv/movie/632727/the-texas-chainsaw-massacre-9/

**Comment by shkope** [comment]
ok but when I put language US I have the chainsaw massacre clearlogo

**Comment by Guillaume5464** [comment]
Yes ilt's better with the new version, 4.6.6, but the point is when you check all the cases with Fan art from the tmdb settings, the french version does not exist in the fanart website but it does with TMDB, cos I can choose it from the context menu and manage artwork, (for example with the eternals, the matrix ressurections, hotel transylvania).
So can it be possible, to say if french version exists in TMDB, ok and if not go to fan art and if french version exists ok if not fallback to english? I mean if technically its possible or its not too pain in the ass to do that ;-)
Thanks for your job, anyway !

**Comment by alKODIque** [comment]
For ''The chainsaw massacre'' example, the clearlogo comes from TMDb not from Fanart,tv..
The point is if we set ''French'' as main language, the artworks from TMDb that are not avalable in ''French'' will not display at all. Even though they exist in english.

For the new Texas Chainsaw Massacre:
- No clearlogo with Fanart.tv for this movie (in any language)
- No clearlogo in French with TMDb (but there is one in english)

**Comment by matke-84** [comment]
> Yes ilt's better with the new version, 4.6.6, but the point is when you check all the cases with Fan art from the tmdb settings, the french version does not exist in the fanart website but it does with TMDB, cos I can choose it from the context menu and manage artwork, (for example with the eternals, the matrix ressurections, hotel transylvania). So can it be possible, to say if french version exists in TMDB, ok and if not go to fan art and if french version exists ok if not fallback to english? I mean if technically its possible or its not too pain in the ass to do that ;-) Thanks for your job, anyway !

I am now testing in French. I got all the artworks you listed without any problems in French. Delete cache and reset kodi.
@jurialmunkey 
I noticed only that they won't show English fallback clearlogo for some movies, even if has it on tmdb or fanart.tv (Marry me, Kimi, Texas chainsaw massacre, Ted K...). When I return language to English (US), these clearlogos appear.

**Comment by jurialmunkey** [comment]
> So can it be possible, to say if french version exists in TMDB, ok and if not go to fan art and if french version exists ok if not fallback to english?

@Guillaume5464 - Latest version gives an option in the fanart.tv settings that will check TMDb for artwork first
`Prefer artwork from TMDb first if available` 

Preference becomes:
`TMDb lang -> fanart.tv lang -> fanart.tv no lang -> fanart.tv en`

Remember you can also use the manage artwork dialog to set artwork manually if necessary. As long as you don't delete your item details cache, manually set artwork is stored forever.

> The point is if we set ''French'' as main language, the artworks from TMDb that are not avalable in ''French'' will not display at all. Even though they exist in english.

@alKODIque - Latest version will also apply the fallback language option to TMDb as long as you don't enable the prefer artwork from TMDb first option. 

FanartTV first + Fallback =
`fanart.tv lang -> fanart.tv no lang -> fanart.tv en -> tmdb lang -> tmdb en`

FanartTV second + Fallback =
`tmdb lang -> fanart.tv lang -> fanart.tv no lang -> fanart.tv en`

There's no option for checking both for language first and then both for a fallback because that will impact performance (needs a second pass). That's why enabling TMDb to be first disables the fallback for it.

>  I noticed only that they won't show English fallback clearlogo for some movies, even if has it on tmdb or fanart.tv (Marry me, Kimi, Texas chainsaw massacre, Ted K...). When I return language to English (US), these clearlogos appear.

@matke-84 - only Fanart.tv was setup to use fallback language. TMDb was set pull language only. Latest version changes that.

**Comment by matke-84** [comment]
@jurialmunkey
I would change only one thing. For season specific lendsacape I would leave fanart.tv when is turned on prefer artworks from tmdb. TMDb landscape images are actually language backdrops. Tmdb doesn't have landscape images for the seasons but since we set as fallback those images then display them now.

**Comment by matke-84** [comment]
@jurialmunkey
Again english fallback clearlogo doesn't work for these movies as I mentioned. It worked in the previous version, but not in this one.

**Comment by alKODIque** [comment]
@jurialmunkey 
Thanks a lot!

I did like you said and set FRench as main language then:
FanartTV first + Fallback . 

It's now working! 🎉
Ex: TV Show ''All of us are dead'' --> before the last changes, no clearlogo were avalable for FR main language. Now I can see the english one from TMDb in artwork manager 

Same thing with  the new''Texas Chainsaw massacre'' 😉
![Screenshot_20220221-183609](https://user-images.githubusercontent.com/49578130/155038681-e7060184-ce2a-4f14-9eb3-87836d3548dd.png)


Again, thanks for all the changes you made, I realy appreciate your work

**Comment by matke-84** [comment]
@alKODIque @jurialmunkey 
For some reason for these movies don't insert an automatic english fallback clearlogo but the cache must be deleted. Also if prefer artworks from tmdb option is enabled then there is no clearlogo (It cannot be chosen through an artwork manager either) for these movies and if there is on tmdb and on fanart.tv.

**Comment by jurialmunkey** [comment]
> @alKODIque @jurialmunkey For some reason for these movies don't insert an automatic english fallback clearlogo but the cache must be deleted. Also if prefer artworks from tmdb option is enabled then there is no clearlogo (It cannot be chosen through an artwork manager either) for these movies and if there is on tmdb and on fanart.tv.

The Item Details cache for the item builder only stores the "best" artwork of each type for each API. Changing the fallback setting potentially changes the "best" artwork available, so you need to refresh the item cache for the item to force a rebuild.

FYI - No need to delete FanartTV or TMDb caches as these store the _entire_ request. It is only the item details that need to be refreshed to force a rebuild.

Also, it is only fallback settings that require a refresh. With the way the cache is structured and how the process works, quality changes or prefer TMDb first are able to be applied immediately:

1. Cached item retrieved (or built if it doesn't exist)
2. Item details added to listitem
3. Cached TMDb artwork types have path substitution applied according to quality setting and then added to listitem art
4. Cached FanartTV artwork types that aren't blacklisted due to quality settings overwrite existing listitem art
5. Cached Manual artwork types overwrite existing listitem art

The "Prefer artwork from TMDb first if available" option just switches steps 3/4 so that FanartTV is added to the listitem first and then TMDb overwrites rather than the other way around -- that's why it doesn't need a refresh but fallback change does.

**Comment by matke-84** [comment]
@jurialmunkey
Thanks for the detailed explanation regarding caching. 👍
I just didn't understand. When the option is on "Prefer artwork from TMDb first if available" 
does English fallback work then or only work with fanart.tv? I ask because artwork manager, when this option is enabled, also says that clearlogo doesn't exist for these movies and of course it's not there when I refresh artworks.
I don't even use other languages, only English, but I wanted to help with testing. 🙂

**Comment by jurialmunkey** [comment]
@matke-84 

If main language is French, the following options give:

**"Prefer TMDb" + "English Fallback"**
`TMDb French > None` --> `fanart.tv French > None > English`
Use this option if you the main thing you care about is posters in French but don't mind more obscure art like clearart falling back to English

**"English Fallback" + NOT "Prefer TMDb"**
`fanart.tv French > None > English` --> `TMDb French > None > English`
Use this option if the main thing you care about is getting artwork

**"Prefer TMDb" + NOT "English Fallback"**
`TMDb French > None` --> `fanart.tv French > None`
Use this option if main thing you care about is getting French artwork (TMDb typically has more language specific posters)

**NOT "Prefer TMDb" + NOT "English Fallback"**
`fanart.tv French > None` --> `TMDb French > None`
Use this option if main thing you care about is that the artwork is NOT English (fanart.tv has more posters with no text).

**Comment by matke-84** [comment]
> **"Prefer TMDb" + "English Fallback"** `TMDb French > None` --> `fanart.tv French > None > English` Use this option if you the main thing you care about is posters in French but don't mind more obscure art like clearart falling back to English

Ok, so it should show fallback clearlogo in English, which is not case at the moment for some movies (Marry me, Kimi, Texas chainsaw massacre, Ted K...). This should be fixed then.

And please, if at possible, do this.

> @jurialmunkey I would change only one thing. For season specific lendsacape I would leave fanart.tv when is turned on prefer artworks from tmdb. TMDb landscape images are actually language backdrops. Tmdb doesn't have landscape images for the seasons.

**Comment by jurialmunkey** [comment]
> Ok, so it should show fallback clearlogo in English, which is not case at the moment for some movies (Marry me, Kimi, Texas chainsaw massacre, Ted K...). This should be fixed then.

No because Texas Chainsaw Massacre does not have a clearlogo on Fanart TV
https://fanart.tv/movie/632727/the-texas-chainsaw-massacre-9/

Neither does Ted K
https://fanart.tv/movie/660353/ted-k/


"Prefer TMDb" + "English Fallback" does NOT get English fallback art from TMDb. It ONLY gets Language or None.
It ONLY gets English fallback from Fanart.tv

**Comment by matke-84** [comment]
@jurialmunkey 
OK. Now everything is clear. Thanks.

**Comment by Guillaume5464** [comment]
Hey hey, ah yes its much better, thanks a lot 😀, and i've got another issue but its about the title's label, when i change it, it takes my changes but keep the one written in the tmdb, for exemple the title of my widget is : "films populaires(my changes) popular films(tmdb)"
I don't know why.
Thanks

**Comment by Guillaume5464** [comment]
Hey again, actually I noticed, so I checked tmdb first and fallback english, and the landscapes that it find in a french version, there is two titles, the normal one and one on the bottom right corner, as you can see on the picture![IMG_20220222_142825.jpg](https://user-images.githubusercontent.com/85249544/155142926-262c9cae-a273-4bcb-be55-cd965a2aa0e5.jpg)
I don't  why there are the ones on the corner?? 
Do you have any explanation about that?
Thank you

**Comment by matke-84** [comment]
@Guillaume5464 
This is up to the skin, not up to the tmdb helper. You have to ask the skinner about that.

**Comment by Guillaume5464** [comment]
@matke-84 Ok but the only option I found is to enable clearlogos on widgets but whatever I do with it, checked or not checked there are still those "titles" at the bottom right corner.

**Comment by matke-84** [comment]
@Guillaume5464 
This is if I'm not wrong aura mod. I don't think there is an option for that, you have to manually change xml but that's not issue for here as I said. Ask the skin developer.

**Comment by jurialmunkey** [comment]
@Guillaume5464 - matke-84 is correct, those are skin matters (widget label and overlaying logo). TMDbH just supplies the data. How it is displayed is up to the skin.

I think this issue with fallback is resolved now, so I will close it.
