### ISSUE TITLE
[Request] Include player in .strm file

### ISSUE THREAD

**Issue by nroets1** [jurialmunkey/plugin.video.themoviedb.helper#656]
First, thank you very much for this powerful tool. 

I would like to request the feature to select the appropriate player, to be included in the .strm file when adding the show or movie to then library. I've tried to manually add the play_using=amazon.json parameter to a .strm file but it had no effect. 

If {title}, {year}, {showname}, {season}, {episode} and "_{player}_" , could be stored in the .strm file then a second TMDB query, before playing, is actually not needed.

**Comment by jurialmunkey** [comment]
This is an interesting idea. I should definitely be able to do something for manual edits fairly easy 

Doing it automatically on update will be a little bit more difficult - I'll need to think about best way for that.

**Comment by jurialmunkey** [comment]
EDIT: You can do this already - I just forgot the syntax is a little different for `.strm` because it plays via plugin:// not RunScript. It needs to be `player=` for the plugin:// path not `play_using=`

Add `&player=amazon.json` inside the .strm file and it should work. Optionally can add `&mode=search` if you want to use the player's search mode instead of play.

e.g. this worked for me to play 2001: Space Odyssey in IMDb Trailers via strm
`plugin://plugin.video.themoviedb.helper/?info=play&tmdb_id=62&tmdb_type=movie&islocal=True&player=imdbtrailers.json`

**Comment by nroets1** [comment]
Thank you very much. It would be nice to be able to select the player when adding the show to the lIbrary from the GUI.

On 23 Feb 2022, 07:29, at 07:29, jurialmunkey ***@***.***> wrote:
>EDIT: You can do this already - I just forgot the syntax is a little
>different for `.strm` because it plays via plugin:// not RunScript. It
>needs to be `player=` for the plugin:// path not `play_using=`
>
>Add `&player=amazon.json` inside the .strm file and it should work.
>Optionally can add `&mode=search` if you want to use the player's
>search mode instead of play.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/656#issuecomment-1048460959
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by jurialmunkey** [comment]
> Thank you very much. It would be nice to be able to select the player when adding the show to the lIbrary from the GUI.

Yeah that's a little bit more difficult due to automated updates. I'll have a think about the best way to do that. 

Probably will link in with a few other improvements that I've been considering for a while -- in particular, these two: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/401 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/625

**Comment by jurialmunkey** [comment]
Closing this issue to keep discussion to the thread I just pinned since it basically covers this feature request too: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/401
