### ISSUE TITLE
Persisting clearart issue

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/plugin.video.themoviedb.helper#659]
Hi @jurialmunkey 

I noticed today that I have a problem with my cleararts when navigating through all my menus..
If no clearart is present for an item, it automatically keeps  the one that was displayed previously.

**The problem is present everywhere:**
- Inside TMDbH
- Navigation from a widget
- Different menus of my local library and / or other addons.

Here is an example of what's going on:
(I'm using v.4.6.9 of TMDb Helper)
Issue the same on both: my Shield 2017 and 2019 Pro..

https://lesalkodiques.com/tests/Kodi_20220222_193726_Enregistrer.mp4

https://lesalkodiques.com/tests/Kodi_20220222_193522_Enregistrer.mp4

And from my home screen:

https://user-images.githubusercontent.com/49578130/155245205-c30d8e6f-95b4-4742-892d-58bc1974c81c.mp4

Thank you again for your time and helpfull advises

**Comment by jurialmunkey** [comment]
Combination of images loading slowly from fanart.tv and how Kodi handles image controls -- Nothing that TMDbHelper or the skin can do about it.

Image controls that load in the background retain the previously loaded image until the new image loads, so if fanart.tv is slow at providing the data then the old image will stay there. The only thing the skin can do is turn off background loading but that would be horrible as you would need to wait for the image to load before you can scroll to the next item.

I've noticed fanart.tv images have been quite slow to load after they switched to the new server and started returning `http://` rather than `https://` for image urls.

**Comment by alKODIque** [comment]
I'll wait few days to see what's happen...

Curious, seems faster for me first day fanart.tv made the change. 
I have a VIP API key, ethernet connexion and fiber internet. Never had this issue before. Sometimes server side (fanart.tv) was slow, but never got into this ...

On the video, it's a fresh setup with no cache, but my other box it's not the case. I pratically never delete cache and have a great setup for long time. But today, I have exacly the same issue with clearart. :(

No big deal then; I'll check for my log timer report..  Like you said, maybe something go wrong with their new database. 
I can not be faster than their response time, even with a fast internet and a great setup loll

Thanks for replying! I appreciate 👍

**Comment by jurialmunkey** [comment]
> No big deal then; I'll check for my log timer report.. Like you said, maybe something go wrong with their new database.
I can not be faster than their response time, even with a fast internet and a great setup loll

Timer log is irrelevant. The list is already visible on screen. The delay here is how long it is taking Kodi to download the image from the url that TMDbHelper gives.

I'm going to double check with Being the Ricardos as I don't think that has clearart, so it should at least clear.

**Comment by alKODIque** [comment]
Yeah, exactly, 
When item has no clearart, it never clear today. 
Sometime I know fanart.tv is slow... but even when it was: clearart did not stick forever ..

Hope it's a fanart.tv issue... if so, you will not have to work on it :))

**Comment by alKODIque** [comment]
See, I'm pretty sure there is something wrong .. 


https://user-images.githubusercontent.com/49578130/155258323-341c3a65-41df-4f63-8dea-5c70f16a1223.mp4

**Comment by jurialmunkey** [comment]
> Yeah, exactly, When item has no clearart, it never clear today. Sometime I know fanart.tv is slow... but even when it was: clearart did not stick forever ..
> 
> Hope it's a fanart.tv issue... if so, you will not have to work on it :))

Ah yep you're right. It is collecting the artwork from the previous entries because I didn't create a new artwork dictionary. 

I forgot that the method I updated yesterday for the english fallback preference is called directly by the service monitor rather than indirectly via the item builder like the artwork management dialog.

Simple enough fix. Should be working correctly now. 

Confused it with the slow loading issue because I'd also noticed that being a problem on Monday. Looks like today artwork is loading much faster, so the server teething issues must've been sorted out too.

**Comment by alKODIque** [comment]
Awsome!!
No more issue with your last commit.. ❤️
Love my setup again lol

BIG HUG

**Comment by alKODIque** [comment]
,,,It's also great to demonstrate the solved issue ;)


https://user-images.githubusercontent.com/49578130/155261425-9080d4bb-0007-4bc4-8da9-ffbc048b3640.mp4

**Comment by jurialmunkey** [comment]
Excellent! Thanks for reporting the bug and testing!
