### ISSUE TITLE
Question. Context menu

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#665]
Is there any way to edit the order of the context menu? Just curious if its possible to make the TMDBH Trakt options move to the top of the Context menu. It would be a really awesome Kodi feature if we could hide/Edit or move items in the Kodi context menu. Do you think it would be possible for somebody to create an addon or script that would be able to accomplish this??

**Comment by jurialmunkey** [comment]
Unfortunately not possible. All the Kodi default context menu items are hard-coded to go first, then the ones from the plugin get added after. It would require changes in Kodi core and I don't think there's much support in the team for allowing plugins that sort of control over core functions.

Currently, it isn't even possible to control which Kodi default items are displayed or what they do - otherwise I would hide the "mark watched" since it effectively does nothing (or even better would be if I could replace it with the Trakt mark as watched option).

The only thing I have control over is the internal order of TMDbH's items (e.g. Select Player, Browse Lists, Add to Library, Trakt Options, Refresh Details, Manage Artwork) but I can't put them higher than the default Kodi options.

**Comment by JayDee696969** [comment]
> Unfortunately not possible. All the Kodi default context menu items are hard-coded to go first, then the ones from the plugin get added after. It would require changes in Kodi core and I don't think there's much support in the team for allowing plugins that sort of control over core functions.
> 
> Currently, it isn't even possible to control which Kodi default items are displayed or what they do - otherwise I would hide the "mark watched" since it effectively does nothing (or even better would be if I could replace it with the Trakt mark as watched option).
> 
> The only thing I have control over is the internal order of TMDbH's items (e.g. Select Player, Browse Lists, Add to Library, Trakt Options, Refresh Details, Manage Artwork) but I can't put them higher than the default Kodi options.

Yea, exactly what i was thinking with the mark as watched and other stuff. Always wondered if this was possible, thanks for responding.
