### ISSUE TITLE
I can't match "The Walking dead"

### ISSUE THREAD

**Issue by mrXoo** [jurialmunkey/plugin.video.themoviedb.helper#666]
I having trouble matching "The walking dead"

My list pops up all these titles.

"The walking dead"
Fear of the walking dead"
"The walking dead: world beyond"

I think the last one is the issue because it always picks that one.

My player needs the steps so:

`						{"title": ".*Search TV Shows.*"},
						{"keyboard": "{showname}"},
                                                {"title": ".*{showname}.*"},
						{"title": ".*Season.*{season}.*"},
						{"title": "Episode.*{episode}|.*S.*{season}E.*{episode}.*"}`

**Comment by mrXoo** [comment]
I guess there is no way of selecting "the walking dead" as its also included in the bottom one.

**Comment by jurialmunkey** [comment]
Why do you have unlimited wildcards `.*` before and after showname? Your regex basically says any number of characters on either side of {showname} are allowed to match. 

Matches occur in order search results display in the add-on, so if "The Walking Dead: World Beyond" displays before "The Walking Dead" in the add-on search results then it is going to match because that's what your regex rules say.

Same thing for your episode match - why are you matching `Episode.*{episode}` ? That will mean episode `2` also matches `Episode 12`. Your OR pipe `|` doesn't work properly either because you have no groups.

Here's a quick overview of regex rules:
https://www.keycdn.com/support/regex-cheatsheet

What exactly are you trying to do with those regex additions?

**Comment by mrXoo** [comment]
I thought I had to match the list exactly. 
in that the list displays it as “[COLOR white] Episide 2[/COLOR] for example. So the wild card was to match the start and the end.

**Comment by jurialmunkey** [comment]
> I thought I had to match the list exactly. in that the list displays it as “[COLOR white] Episide 2[/COLOR] for example. So the wild card was to match the start and the end.

Ah that makes sense! Those ones are annoying. Does it not have `ListItem.Season` or `ListItem.Episode` numbers that you can match against instead? e.g. `{"season": "{season}", "episode": "{episode}"}` as that would be better.

For your title try something like this:
`{"title": "(?i)^(\\[.*\\])?{showname}(\\[.*\\])?$"},`

- `(?i)` means ignore letter case so we don't need to worry about matching upper/lower exactly
- `(\\[.*\\])?` is to match the `[TAGS]` optionally. `?` means 0 or 1 match of preceding group `( )` so we match either 0 or 1 of `\[.*\]` to allow for titles with or without `[COLOR=]`
- `^$` are the start and end of string to prevent sub-string matching

I think that should solve the title issue. Optionally you could replace `?` with `*` if you sometimes have multiple tags in the title like `[B][COLOR=blue](showtitle}[/COLOR][/B]`

You can do the same thing for your Episode tags e.g.
`{"title": "(?i)^(\\[.*\\])?(Episode.{episode}|Episode.{episode}[^0-9].*|S.?{season}E.?{episode}[^0-9].*)(\\[.*\\])?$"}`

- The `.` means any character so `Episode.{episode}` matches `Episode 2` `Episode.2` `Episode-2` etc.
- The `[^0-9].*` means NOT a 0-9 character but can be followed by other characters e.g. matches `Episode 2 - Title` but not `Episode 21 - Title`

**Comment by mrXoo** [comment]
That was something amazing. Thanks for all your help and patience. I would have never figured that out

**Comment by jurialmunkey** [comment]
> That was something amazing. Thanks for all your help and patience. I would have never figured that out

No worries! Regex used to confuse the hell out of me (and sometimes still does) but once you start getting a grasp on how it works it quickly starts making sense and it's amazing how many cool tricks you can do with it.
