### ISSUE TITLE
[Feature request] Support selfhosted alternatives of Trakt.tv

### ISSUE THREAD

**Issue by Astaoth** [jurialmunkey/plugin.video.themoviedb.helper#692]
Hi,

Would it be possible to add support for [Flox](https://github.com/devfake/flox) and [Mediatracker](https://github.com/bonukai/MediaTracker) beside of Trakt.tv ? I'll rather would like to have the possibility to selfhost most the services I can.

Thanks

**Comment by jurialmunkey** [comment]
I can't see any documentation of a Flox RESTful api and I'm not going to dig through the code to figure out if it is possible. It's integration with PLeX is via a webhook, so won't work with TMDbH.

MediaTracker has proper documentation https://bonukai.github.io/MediaTracker/

The problem is that MediaTracker isn't a one-for-one replacement for Trakt so it would be far too much work to provide as an option. I'd have to rewrite all the Trakt based methods to fit a different API schema. If this enhancement https://github.com/bonukai/MediaTracker/issues/114 is implemented in MediaTracker _then_ it might be a possibility.

At the moment, in its current state, it would be better served by someone writing a separate MediaTracker addon for Kodi and then using  TMDbHelper as a dependency for its play function.

**Comment by Astaoth** [comment]
Hi,

Thanks for your answer, I understand very well you don't want to lose your time for compensing the lack of documentations for implementing a minor feature.

I'm an little disapointed about MediaTracker, but I understand that with a code specifically oriented for Trakt.tv it would not be simple and would take time to support an alternate watchlist.

Thanks for having taken a look into this :)

**Comment by jurialmunkey** [comment]
> Trakt.tv it would not be simple and would take time to support an alternate watchlist.

@Astaoth - Wait is that all you want to use it for? Just watchlist?

Because that's definitely doable. I thought you were talking about replacing things like keeping track of watched status and in-progress shows etc. which is much more complicated.

**Comment by Astaoth** [comment]
I was also talking about the show status, progresses and calendar (but not of suggestions, this is not supported by Mediatracker).
I watch shows on different players (Kodi for my television, and others on smartphones and computers) and it was for keeping track of them and on newly available episodes.

However having only the watchlist part supported is still nice :).

**Comment by hoshsadiq** [comment]
@jurialmunkey I think implementing a trakt compatible API is going to be much harder. Do you know what all is needed on MediaTracker's side to be able to add support for it in TMDBHelper?
