### ISSUE TITLE
[BUG] Empty shows

### ISSUE THREAD

**Issue by djdirty60** [jurialmunkey/plugin.video.themoviedb.helper#694]
**Describe the bug**
All series I open are empty, no episodes.  Tried everything, i even reinstalled kodi from scratch.

**Debug log**
https://paste.kodi.tv/poromaleyo

**Screenshots**
![1650227678816529074432888336867](https://user-images.githubusercontent.com/13561831/163731213-084d08c4-9924-475d-bdb0-dfc3a608eb8f.jpg)
![16502277156774728483326012018182](https://user-images.githubusercontent.com/13561831/163731224-969c01dd-d48c-487d-a531-a4760e2890e3.jpg)
![16502277422121977140290114570717](https://user-images.githubusercontent.com/13561831/163731233-5106d177-5f8b-49f2-b53d-c6ed1f757401.jpg)
![16502277693031856438356227130661](https://user-images.githubusercontent.com/13561831/163731248-2edc24bd-7a39-4c6d-8f1d-d405d1d8c72e.jpg)

**Comment by jurialmunkey** [comment]
I fixed a couple of the errors in your log. However, the main issue is that your cache is either corrupt or there's some write permission issue on your disk preventing writing the cache.

I recommend delete your caches on disk. Ideally you would delete the whole database_v5 folder with Kodi closed so that it is forced to be regenerated next time to Kodi runs (basically fresh start for cache).
`/storage/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v5/`

However, that might be difficult since you're on CoreELEC, so you can try deleting cache entries in TMDbHelper Expert Settings (it will be the Trakt cache for this specific issue but looks like there's problems with the other caches too). 
`TMDBHelper Settings > Expert > Delete Cache`

Not quite as good as it only deletes the entries inside the cache and not the .db file. Which means it will only solve corruption inside the database, not issues with file permissions or disk corruption - but it still might help.

**Comment by djdirty60** [comment]
Fixed, had to specify a location for the cache.
