### ISSUE TITLE
[Question] Library integration

### ISSUE THREAD

**Issue by harristom** [jurialmunkey/plugin.video.themoviedb.helper#695]
Tbh I'm not sure if this is a bug or a feature request as it's not 100% clear to me how the library integration is supposed to work. I have a bunch of local files already stored in my library. I would like TMDB Helper to show new episodes for TV shows that exist already in my library (e.g. I have files and library entries for episodes 1 and 2, TMDB helper would add library entry for episode 3). I have set my library paths in the addon settings, ticked the box to add new episodes, and run the update but nothing gets added.

**Comment by drinfernoo** [comment]
Have you checked your log?

**Comment by jurialmunkey** [comment]
Library integration does not check your library for existing tvshows.

Items are added to the library in one of two ways:
1. Via a monitored Trakt list added in the settings
2. Via the context menu by choosing "Add to library" on a TMDbHelper item or a Trakt user list

The automatic update does two things:
1. It checks your monitored Trakt lists and adds any movies or episodes not in your library
2. It checks tvshows which were added via the context menu and adds any new episodes not in your library

So you have two options: create a custom list on Trakt and add as a monitored list; OR find the tvshows using TMDbHelper's search function and then add the shows via the context menu.

**Comment by harristom** [comment]
Thanks! Suspected that might be it, I'll use Trakt in that case. Maybe it could be an idea for the future though? Though admittedly I'm probably an edge case in wanting to mix local and online sources.

**Comment by jurialmunkey** [comment]
> Thanks! Suspected that might be it, I'll use Trakt in that case. Maybe it could be an idea for the future though? Though admittedly I'm probably an edge case in wanting to mix local and online sources.

I mix local and online sources in my own library. I wouldn't say it's an edge case either.

However, I think *automatically* updating all missing episodes for local sources isn't a great idea. Generally you're going to want to add new local files at some stage - e.g. download; PVR recording; or physical media rip - and if TMDbHelper was  automatically adding missing episodes then that would happen before you had a chance to add your own.

Basically, whenever you wanted to add new local files you would have to first go find and delete the strm file TMDbHelper made, clean the library to remove the database entry, _then_ add your new file and rescan the library. It would be a complete pain for any show that you were currently collecting local files for.

The current method of creating a Trakt subscriptions list (or manually adding individual shows via the context menu) gives you control over which shows update automatically and which ones you update manually.

As a side note - I really recommend that you keep your local file library source in a separate folder from the TMDb library source (you just add two separate sources in Kodi). That way it is much easier to delete whole folders of .strm without having to pick them out amongst your local files.

**Comment by harristom** [comment]
> Basically, whenever you wanted to add new local files you would have to first go find and delete the strm file TMDbHelper made, clean the library to remove the database entry, then add your new file and rescan the library. It would be a complete pain for any show that you were currently collecting local files for.

Sorry, another probably stupid question - why would you need to do that? I thought it automatically plays a local file if one is available?

**Comment by jurialmunkey** [comment]
> Sorry, another probably stupid question - why would you need to do that? I thought it automatically plays a local file if one is available?

Short Answer: You'd end up in a recursive loop of TMDbHelper opening itself because one of the "local files" in the library for the Episode that it is attempting to play is actually a .strm link back to TMDbHelper (in reality there's a safe guard to prevent this loop from happening but the side-effect is that it prevents TMDbHelper playing that Episode from the library).

 
Longer Answer: Consider the below scenario

- A new show starts airing weekly.
- You record (or download) the first episode and save as `NewShow/Season1/S01E01 - Episode One.mp4`
- You scan your library and now Episode One shows up in your Kodi library

Normal so far. However, what happens next week when Episode Two airs?

-  TMDbHelper creates `S01E02 - Episode Two.strm` because it notices it isn't in your Kodi library
- Now both Episode One and Two are listed in your Kodi library where Episode One links directly to an .mp4 file on your harddrive and Episode Two links to a .strm shortcut to TMDbHelper

So far so good. But what if in the meantime you were also recording or downloading Episode Two? TMDbHelper has already beaten you to it and made the .strm file before your recording/download has finished!

- When the recording (or download) is done, you save it as `S01E02 - Episode Two.mp4` and scan your library.
- Now have TWO entries for Episode Two in the library - the link to the .strm version and the link to the .mp4 version
- To remove the duplicate, you'd then have to go into the folder on your hard-drive, delete the .strm, and then clean the library. You'd need to do this every week when you want to add a newly download or recorded file for an existing show.

Worse still, if you don't delete the .strm then TMDbHelper won't be able to see the .mp4 because the first match for that episode in the Kodi library is going to be the .strm -- and since the .strm links to TMDbHelper, the "Play with Kodi" option is not shown because we don't want to end up in a never ending recursive loop of TMDbHelper opening itself.

**Comment by jurialmunkey** [comment]
That's why there is NO option to add missing episodes for local shows automatically and instead you need to specify which shows to track either via a Trakt list or by adding via the TMDbHelper context menu.

**Comment by harristom** [comment]
Thanks for explaining, makes perfect sense :) I thought for some reason that Kodi collapsed the duplicates to one library entry and prefers the local one but now I think about it I'm not sure how that would even work since as you say the .strm is also technically a local file
