### ISSUE TITLE
Movies/Shows Title in Trakt lists is in English regardless of the selected language

### ISSUE THREAD

**Issue by valleycake** [jurialmunkey/plugin.video.themoviedb.helper#698]
With a different language set in TMDbHelper addon settings, if I browse Trakt lists the title of the Movies/Shows is in English instead of the chosen language. But if I browse a list from TMDb, the title is shown in the correct language.

To reproduce this issue, try to change the language to a different language in TMDbHelper (for example Hebrew) and browse some Trakt lists.

Thanks in advance & kudos to you for this great add-on and gorgeous skins!

### **Screenshot showing a list from Trakt with Hebrew language set :**

![trakt](https://user-images.githubusercontent.com/104077982/164274322-ee2fd2ef-11bb-4ff8-b3f1-30536e834ff1.jpg)

### **Screenshot showing a list from TMDb with Hebrew language set:**

![tmdb](https://user-images.githubusercontent.com/104077982/164274405-8713de93-f47f-470b-8ba8-eb557996f5e8.jpg)

**Comment by jurialmunkey** [comment]
Unfortunately the Trakt API doesn't provide a way to specify a different language so the titles in their lists are in English. The rest of the data is filled in by TMDb lookups hence why the plot etc is translated.

I'll have a think about the best way to add an option to override the title with TMDb data - there's just a few scenarios where it might not be suitable because a custom label is used, so I'll need to think about what scenarios that happens in before I implement it.

**Comment by valleycake** [comment]
Thanks for the quick response, I think that it's a great idea to add an option to override the Trakt title with a TMDb data if that is possible and can be implemented correctly. 

Or maybe the best way is to override the title only when a language other than English is set in TMDbHelper add-on settings.

**Comment by jurialmunkey** [comment]
Should be fixed in v4.7.14 - could you test please?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.14

Title override enabled automatically if language is not English.

**Comment by valleycake** [comment]
Yes, v4.7.14 solve the problem completely, thanks again for the quick fix!
