### ISSUE TITLE
Pagination for Liked Lists (trakt)

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#7]
Hi Jurial,

Would it be possible for you to add pagination or remove the limit on the "Liked Lists (Trakt)" directory?  Currently its being limited to 10 "Liked Lists".

Thanks!

**Comment by jurialmunkey** [comment]
Pagination is probably not necessary since it's just text being returned and no details are being looked up.

I've increased the limit to 250 lists. Let me know if you need more or, alternatively, if the increased limit causes performance issues (appears fine for me on my laptop but it has much better specs than my htpc which I haven't tested on yet).

**Comment by skyfsza** [comment]
Just did a quick test and am now seeing all my "Liked Lists".  Testing done on a Shield TV and don't see any noticeable increase on load time.

Thanks!
