### ISSUE TITLE
[BUG] Couldn't open information dialog for movie "Mr. & Mrs. Smith" in movie/people information dialog

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/plugin.video.themoviedb.helper#710]
Couldn't open information dialog for movie "Mr. & Mrs. Smith" in movie/people information dialog, seems related with the "&" character in the title.

>2022-04-26 20:36:20.761 T:6380    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting videodb://movies/titles/?xsp=%7B%22order%22%3A%7B%22direction%22%3A%22ascending%22%2C%22ignorefolders%22%3A0%2C%22method%22%3A%22sorttitle%22%7D%2C%22rules%22%3A%7B%22and%22%3A%5B%7B%22field%22%3A%22title%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%5B%22Mr. & Mrs. Smith%22%5D%7D%5D%7D%2C%22type%22%3A%22movies%22%7D&extended=True

**Comment by jurialmunkey** [comment]
Yeah it's the ampersand. It's a skinning issue with AH1 and isn't really related to TMDbHelper. Unfortunately there's not much that can be done about it using that method because the Kodi skinning engine doesn't have any method to percent encode infolabels.

In AH2 I'm not using this method because of this problem. It was always a bit of a hack anyway to try to get a faster lookup directly from the library rather than asking TMDbHelper to lookup the item.
