### ISSUE TITLE
[Feature] Remove Trakt Playback Progress

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#717]
Would it be possible to add a ‘remove playback progress’ option to tmdb helper’s trakt options in context menu? Your in-progress movies is a really useful widget for me, but over time I often end up with a few films that I’ve half watched and don’t intend to finish. Currently, I can either go into another addon and use its trakt manager to do this, or use https://sharkykh.github.io/tppm/ via my mobile phone, but would be nice if I could do this directly from a tmdb helper widget.

**Comment by jurialmunkey** [comment]
You can mark as unwatched in the trakt options already. Doesn't that work?

**Comment by ghost** [comment]
Unfortunately not. I can mark a film as watched or unwatched but it won’t be removed from your in-progress movies (widget/ within addon). Playback progress is unchanged when checking the trakt playback progress manager link I referred to.    Another addon I use behaved exactly the same way until it introduced a specific ‘remove playback progress’ option. 

Happy for you to close issue - maybe an option to consider down the line if you see the value in it.

**Comment by jurialmunkey** [comment]
Ah, of course! Yeah that wouldn't work because a movie/episode can be both "unwatched" and also "in-progress". For some strange reason I was thinking about it like tvshows progress.

Definitely a useful option. I should be able to add it.

**Comment by ghost** [comment]
Great, yeah that makes sense. I would’ve thought marking a currently unwatched film as watched would remove it from the in-progress list, but it obviously doesn’t work like that.

**Comment by jurialmunkey** [comment]
Could you try v4.7.28? Added "Remove from progress" to trakt options which should remove the movie/episode progress.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.28

**Comment by ghost** [comment]
Works perfectly; expected nothing less to be honest, thank you 🙏 

I notice that resume points are still attached to a movie that has had its playback progress removed (and successfully been removed from in-progress widget). Of course, that’s not an issue at all and may be expected behaviour, but thought I’d let you know just in case. Thanks again.

**Comment by jurialmunkey** [comment]
> I notice that resume points are still attached to a movie that has had its playback progress removed

Yeah it's because Kodi saves the progress locally.

The "Get resume points from Trakt" option only updates the progress of an item in a list if it has a paused at value between 5-95% on Trakt. I found updating anything outside that was really annoying because you end up with resume points only 30 seconds into the movie or in the middle of the credits. 

The side effect is that if you reset the progress to zero then the old resume point stays in Kodi (whereas if you watch the item to the end it gets marked as watched instead).

**Comment by jurialmunkey** [comment]
Decided to make a change to force the progress indicator to always update when loading the list if the " Get resume points from Trakt" option is on rather than only setting for items in the 5-95 range.

I ran a performance timer  and the majority of the cost is getting of the value from Trakt not setting the value in Kodi. Since I have to get the value for every item, may as well reset Kodi's progress to 0 for those outside the 5-95 range rather than skipping.

**Comment by ghost** [comment]
Thanks for the explanation, makes sense now!
