### ISSUE TITLE
"Mark as watched" in context menu doesn't work, must go into "Trakt options" first

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/plugin.video.themoviedb.helper#722]
Hey there. Just wondering if there is something wrong with my setup or if this is a bug.

I'm using 19.4 with latest version of TMDB Helper. Arctic Zephyr Reloaded skin.

When in an episode list, if I select "Mark as watched" from the context menu, the confirmation window doesn't popup and then checking Trakt, nothing has updated and the episode is still unwatched. However if I go into the "Trakt options" item in the context menu and _then_ select "Mark as watched", the expected confirmation window pops up and Trakt has been updated.

Is it just me? Thank you for the great addon!

**Comment by jurialmunkey** [comment]
It's a built in kodi command that marks as watched *in kodi only*. Unfortunately cannot override the behaviour and cannot remove it (kodi forces it to be there).

Plugins can only add to the context menu. Sadly cant remove or modify any of the built in ones which is really annoying because most aren't relevant and it would really help to trim the context menu size down.

So nothing wrong with your setup but not a bug either!

**Comment by ambulancePilot** [comment]
Thank you very much for that explanation! That makes sense.
