### ISSUE TITLE
[BUG] Amazon Player not working

### ISSUE THREAD

**Issue by eyk107** [jurialmunkey/plugin.video.themoviedb.helper#725]
Hi, I try to play different movies and Serie with Amazon VOD but the Playback never starts. 
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8675684/kodi.log)

**Comment by jurialmunkey** [comment]
Are you sure you're able to play the items in the actual Amazon VOD plugin itself?

The Amazon VOD plugin is broken for me at the moment and won't let me play anything via search.

For instance, I just went to the Amazon plugin and searched "Man in the High Castle" (which is a prime original so definitely available) and it won't let me open any seasons to play the episodes.

If you can't open it in the Amazon plugin then TMDbHelper isn't going to be able to open it either.

**Comment by jurialmunkey** [comment]
Also please follow the bug template rules. Without a log I cannot possibly help you.

**Comment by eyk107** [comment]
I added the logfile to my first post. I tried to play a movie with amazon VOD via tmdb helper and it doesn't start. After that, I played the same movie directly via the Amazon VOD addon without any issues.

**Comment by jurialmunkey** [comment]
I see you're using German language. Does the language in TMDbHelper and Amazon match? If you're searching using German language in TMDbHelper but using English in Amazon (or vice versa) then obviously it won't work because the name of the item won't match 

e.g. if TMDbHelper is trying to search "Fast & Furious Neues Modell. Originalteile" but it is called "Fast & Furious" in Amazon then it won't match.

**Comment by eyk107** [comment]
I tested it again with the movie "Tenet", but the result is the same. I'm able to play it directly in the app but not via tmdb helper

**Comment by jurialmunkey** [comment]
Please answer my question about the languages. I am able to ply movies fine using english

**Comment by eyk107** [comment]
I can't change the language in the application. I think the language in the application is comming from my Amazon account. In any case of an language issue, why can I play the movie tenet? It shouldn't make any difference at all? Anyway, wouldn't it make more sense to use the season and the episode than the name? For example S06E01?

**Comment by jurialmunkey** [comment]
> I can't change the language in the application. I think the language in the application is comming from my Amazon account. In any case of an language issue, why can I play the movie tenet? It shouldn't make any difference at all? Anyway, wouldn't it make more sense to use the season and the episode than the name? For example S06E01?

What do season and episode numbers have to do with playing movies?

The reason I specifically asked if the languages match is because the Amazon plugin doesn't provide much data to match movies on other than title and year which is what the player uses. 

If "Tenet" title matches in both languages it is possible that the release year for the region doesn't match or there is some other issue (BTW I can play Tenet fine using Amazon player).

- Install v4.7.33 of TMDbH - https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.7.33
- Enable TMDbH debug logging in `TMDbHelper Settings > Expert > Debug logging`
- Attempt to play Tenet and provide me the Kodi log file

v4.7.33 has additionally debug logging for player steps so this will show exactly where the player is failing.

**Comment by jurialmunkey** [comment]
@eyk107 - Are you able to get me that debug log using v4.7.33+ following the instructions above?

**Comment by eyk107** [comment]
Hi,

please excuse the delay I was on a vacation. I attached the logfile. I first started the movie tenet with the Amazon-application. After that, I tried the same wit the tmdb helper without success.

BR
   Eric

Von: jurialmunkey ***@***.***>
Gesendet: Dienstag, 24. Mai 2022 03:26
An: jurialmunkey/plugin.video.themoviedb.helper ***@***.***>
Cc: eyk107 ***@***.***>; Mention ***@***.***>
Betreff: Re: [jurialmunkey/plugin.video.themoviedb.helper] [BUG] Amazon Player not working (Issue #725)


@eyk107<https://github.com/eyk107> - Are you able to get me that debug log using v4.7.33+ following the instructions above?

**Comment by jurialmunkey** [comment]
You can't attach files via email to github. You either need to upload the log file on github or upload it to https://paste.kodi.tv/ and provide the link.

**Comment by eyk107** [comment]
hastebin - ocecuzujuy (kodi.tv)<https://paste.kodi.tv/ocecuzujuy.kodi>

Von: jurialmunkey ***@***.***>
Gesendet: Montag, 30. Mai 2022 15:31
An: jurialmunkey/plugin.video.themoviedb.helper ***@***.***>
Cc: eyk107 ***@***.***>; Mention ***@***.***>
Betreff: Re: [jurialmunkey/plugin.video.themoviedb.helper] [BUG] Amazon Player not working (Issue #725)


You can't attach files via email to github. You either need to upload the log file on github or upload it to https://paste.kodi.tv/ and provide the link.

**Comment by jurialmunkey** [comment]
`2022-05-30 13:52:26.577 T:799      INFO <general>: CAddonMgr::FindAddons: plugin.video.themoviedb.helper v4.7.23 installed`

You are still on v4.7.23. I asked you to install v4.7.33 or higher.

Please install v4.7.33 or higher and then get me a debug log.

**Comment by eyk107** [comment]
I just saw that I have two repos with your addon, yours and the kodi addon. I’m not sure why it didn’t run an  auto-update?!
Nether less I run an update but the issue still exists. I uploaded the log again:
hastebin - qujofolabe (kodi.tv)<https://paste.kodi.tv/qujofolabe.kodi>


Von: jurialmunkey ***@***.***>
Gesendet: Montag, 30. Mai 2022 16:57
An: jurialmunkey/plugin.video.themoviedb.helper ***@***.***>
Cc: eyk107 ***@***.***>; Mention ***@***.***>
Betreff: Re: [jurialmunkey/plugin.video.themoviedb.helper] [BUG] Amazon Player not working (Issue #725)


2022-05-30 13:52:26.577 T:799 INFO <general>: CAddonMgr::FindAddons: plugin.video.themoviedb.helper v4.7.23 installed

You are still on v4.7.23. I asked you to install v4.7.33 or higher.

Please install v4.7.33 or higher and then get me a debug log.

**Comment by jurialmunkey** [comment]
You didn't turn on debug logging.
`TMDbHelper Settings > Expert > Debug logging`

I need debug logging on because the whole point of using the new version is that it will output extra logging details which will help me diagnose the issue.

Please ENABLE debug logging in TMdbHelper settings, then attempt to play the item, then get me the log.

**Comment by jurialmunkey** [comment]
Either that or you didn't get me the full log. 

With debug logging enabled in TMDbHelper, you should get output like the following which will show me exactly where the player is failing (this is me successfully playing the file)

```
[plugin.video.themoviedb.helper]
PLAYER: amazon.json play_movie true
PLUGIN: plugin.video.amazon-test
FOLDER: plugin://plugin.video.amazon-test/
ACTION: {'file': '(?i).*/search/'}
   Itm: Search
   Key: file = plugin://plugin.video.amazon-test/pv/search/
   Fmt: (?i).*/search/
FMATCH: plugin://plugin.video.amazon-test/pv/search/
KEYBRD: Tenet
FOLDER: plugin://plugin.video.amazon-test/pv/search/
ACTION: {'label': '(?i).*{title}.*', 'year': '{year}'}
   Itm: Tenet
   Key: label = Tenet
   Fmt: (?i).*Tenet.*
   Key: year = 2020
   Fmt: 2020
```

**Comment by eyk107** [comment]
Oh I’m sorry I only enabled the DEBUG-logging in Kodi. I thought you mean that. Now the log looks like you described:
hastebin - eyifasikin (kodi.tv)<https://paste.kodi.tv/eyifasikin.kodi>


Von: jurialmunkey ***@***.***>
Gesendet: Dienstag, 31. Mai 2022 02:43
An: jurialmunkey/plugin.video.themoviedb.helper ***@***.***>
Cc: eyk107 ***@***.***>; Mention ***@***.***>
Betreff: Re: [jurialmunkey/plugin.video.themoviedb.helper] [BUG] Amazon Player not working (Issue #725)


Either that or you didn't get me the full log.

With debug logging enabled in TMDbHelper, you should get output like the following which will show me exactly where the player is failing (this is me successfully playing the file)

[plugin.video.themoviedb.helper]

PLAYER: amazon.json play_movie true

PLUGIN: plugin.video.amazon-test

FOLDER: plugin://plugin.video.amazon-test/

ACTION: {'file': '(?i).*/search/'}

   Itm: Search

   Key: file = plugin://plugin.video.amazon-test/pv/search/

   Fmt: (?i).*/search/

FMATCH: plugin://plugin.video.amazon-test/pv/search/

KEYBRD: Tenet

FOLDER: plugin://plugin.video.amazon-test/pv/search/

ACTION: {'label': '(?i).*{title}.*', 'year': '{year}'}

   Itm: Tenet

   Key: label = Tenet

   Fmt: (?i).*Tenet.*

   Key: year = 2020

   Fmt: 2020

**Comment by jurialmunkey** [comment]
Okay thanks, that's really useful info and also very interesting.

It appears that the Amazon plugin has a different structure for different account regions. It appears that search is a different endpoint. I'm going to be a bit blind trying things here since my account is a different region, so I will need you to test.

Please try v4.8.2
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/tags/v4.8.2.zip

Hopefully the different search function for your region functions in the same basic way (keyboard entry -> list of titles) and the change will fix it. At the very least it should get us a bit closer to a solution.

**Comment by eyk107** [comment]
Thank you very much, that fixes the issue. It is very strange that a different regions have different endpoints. Nether less, thanks a lot for your effort.

Best regards
   Eric

Von: jurialmunkey ***@***.***>
Gesendet: Mittwoch, 1. Juni 2022 04:45
An: jurialmunkey/plugin.video.themoviedb.helper ***@***.***>
Cc: eyk107 ***@***.***>; Mention ***@***.***>
Betreff: Re: [jurialmunkey/plugin.video.themoviedb.helper] [BUG] Amazon Player not working (Issue #725)


Okay thanks, that's really useful info and also very interesting.

It appears that the Amazon plugin has a different structure for different account regions. It appears that search is a different endpoint. I'm going to be a bit blind trying things here since my account is a different region, so I will need you to test.

Please try v4.8.2
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/tags/v4.8.2.zip

Hopefully the different search function for your region functions in the same basic way (keyboard entry -> list of titles) and the change will fix it. At the very least it should get us a bit closer to a solution.
