### ISSUE TITLE
Give a third default action in addon. In addition to 'play' and 'browse' options, add 'info page' option. 

### ISSUE THREAD

**Issue by bigpoppapaul** [jurialmunkey/plugin.video.themoviedb.helper#726]
It would be very handy to have the option to go to the 'Information' page directly when selecting something. So in addition to automatically playing (play) or bringing up the context menu (browse), would it be possible to also add in a third option in the 'default select action in addon' that takes us directly to the 'information' page when selecting any movie/tv show in tmdbhelper? 

![tmdbh settings](https://user-images.githubusercontent.com/20094991/168041364-33ed4b47-2fc8-4627-a4e4-35916e03517b.JPG)

So it takes us directly to THIS page by default when we select any media?

![infopage](https://user-images.githubusercontent.com/20094991/168042135-5e3afc1b-99f6-4735-8de8-1e9c5c1db9d0.JPG)

I have currently done this through the system settings, but that has a lot of other undesirable consequences and errors when trying to open up parts of certain addons. 

I have started learning python so I can make these changes myself without bothering anyone, but I'm not quite there yet. :)

**Comment by jurialmunkey** [comment]
You can already change what the select action does in Kodi's settings
https://kodi.wiki/view/Settings/Media/Videos#Default_select_action
`Kodi Settings > Media > Videos > Default Select Action > Show information`

Changing the action internally via a plugin isn't permitted because it would require override the user's keymap to change the select action and plugins which modify keymaps are not permitted in the official Kodi repo. Any select action changes must be either applied by the user in their keymap or by using the global Kodi setting.

The reason the Browse/Play toggle is permitted is because it only changes the item's path from a filepath (playable item) to a folderpath (browsable item). It isn't changing what the user's select action does.

**Comment by bigpoppapaul** [comment]
Alright, thank you for the answer. I am currently doing it through the system settings as you mentioned (though I had brain fart and said I was doing it through the skin), but it was causing other issues in other addons. Oh well. 

I was using auramod and the home page has that behavior so I was hoping I could make it carry over to your addon for when I leave the homepage. I appreciate the rapid response time and sorry, didn't know it was prohibited. Sorry about that.

**Comment by jurialmunkey** [comment]
No problem at all! It is definitely a reasonable request, just unfortunately not something that is permitted in the repo. And even if it were permitted, there isn't really any good way to do it that isn't hacky.
