### ISSUE TITLE
[Feature] A possible name change?

### ISSUE THREAD

**Issue by mrgsi** [jurialmunkey/plugin.video.themoviedb.helper#727]
Love the add-on, however I wonder if it would be difficult to change the name to something like plugin.tmdb-helper for the jurialmunkey repo. This would differentiate it from the official kodi repo version so we can get automatic updates which I'm assuming is caused by a conflict with the kodi repo. Just my random thought for the day. I'm getting more of those as I get old. lol

**Comment by drinfernoo** [comment]
In `Settings -> System -> Add-ons`, change "Update official add-ons from" to "Any Repositories".

**Comment by kolekan** [comment]
> In `Settings -> System -> Add-ons`, change "Update official add-ons from" to "Any Repositories".

Is this work for you? Cause it doesn't work for me for any addon existing in official kodi repo.

**Comment by mrgsi** [comment]
I always have it set to any repositories. It's only this add-on that gets "detached" from it's repo. When I go into the jurialmunkey repo the "enabled" setting is wiped out even though the add-on is still installed. I can only assume it's because the identical add-on exists in the Kodi repo. I just thought if the add-on was "mirrored" under a different name, the Kodi repo wouldn't see it and mess with it. I won't use the Kodi repo version as it doesn't keep up with the updates and I have FOMO lol. It's not that big of a deal doing manual updates, if I remember to look. Others may not even think to look.

**Comment by drinfernoo** [comment]
@mrgsi Make sure to manually "update" from @jurialmunkey's repo at least once, and it should find updates from there after the fact.

**Comment by jurialmunkey** [comment]
Changing the name would break skin integration, so not possible.

If you have issues with updating automatically then that's a kodi bug that you should report on the official kodi github.

Btw I have a PR for most recent version waiting for code review into official repo. It is just taking a while because it is a big change and a few of the kodi team members that do python reviews are currently unavailable. Once that makes it into the repo I'll be doing more regular updates.
