### ISSUE TITLE
[BUG] Lookup artwork for recently aired tv show episodes on library update

### ISSUE THREAD

**Issue by cecobask** [jurialmunkey/plugin.video.themoviedb.helper#730]
**Describe the bug**
I’ve set up the TMDB helper add-on for Kodi to sync my library with Trakt once a day.

The problem I’m experiencing is that when a tv show is initially added to my library it may have unreleased episodes on the way. In this case their artwork will be empty. The artwork stays empty even after the episodes had aired.

Am I missing something in the settings or it’s not possible to auto-update artwork on library sync?

Here’s a screenshot to show what I’m referring to: https://picbun.com/p/Y5oX7eGL

**Debug log**

**Screenshots**
https://picbun.com/p/Y5oX7eGL

**Additional context**

**Checklist**
- [x] I have described the bug and included steps to reproduce the issue
- [x] I have included a full kodi debug log of the error

**Comment by jurialmunkey** [comment]
This is to do with your library scraper not tmdbhelper.

If you open the info dialog for the item there should be a "refresh" button that will refresh the metadata. 

Also you can stop unaired episodes from being added by hiding unaired episodes in tmdbhelper navigation settings.

**Comment by cecobask** [comment]
That makes sense, thank you for pointing this out, @jurialmunkey.
Are you aware of a way to perform the refresh automatically?
If not, is that a feature that TMDb helper would include in the future?

**Comment by jurialmunkey** [comment]
No you have to do it manually. Official repo rule is that plugins are not permitted to modify the library database. 

Tmdbhelper has nothing to do with the metadata in your library. It only makes the strm files on disk which are shortcuts back to Tmdbhelpers player function . 

The rest of the update is handled by Kodi just like it would if the files were normal videos instead of strm.
