### ISSUE TITLE
[BUG] The right part of 1142 window appear

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/plugin.video.themoviedb.helper#733]
Hi @jurialmunkey, I'm playing a YouTube video with the following code: 

`            <onclick>RunScript(plugin.video.themoviedb.helper,close_dialog=1190)</onclick>
            <onclick>RunPlugin(plugin://plugin.video.youtube/play/?video_id=$INFO[ListItem.Property(video_id)])</onclick>`

The video playback is normal, I can see the left part of the TMDB dialog (1142) disappeared, but the right part of the dialog is still covering the video. it seems very weird. Isn't the "close_dialog" action supposed to close the whole dialog?

I can use the `<onclick>Dialog.Close(1142)</onclick>` to close the whole dialog, but the video playback doesn't work anymore. Is there any way to fix this issue? Thanks!

**Comment by jurialmunkey** [comment]
Close dialog command has nothing to do with custom windows. it just closes video info dialog when tmdbhelper is in window management mode. 

Sounds like an issue with whatever skin you're using.

**Comment by Hawkedon** [comment]
I'm using an AH1 MOD.

Edit: I got this code works:

`<onclick>Dialog.Close(1142)</onclick>
<onclick>RunScript(plugin.video.themoviedb.helper,close_dialog=1190,playmedia='$ESCINFO[ListItem.FileNameAndPath]')</onclick>`

Hi @jurialmunkey, any idea why playing the video through TMDB helper works, but directly with RunPlugin doesn't?

**Comment by jurialmunkey** [comment]
Playmedia() is the builtin you should use for playing items, not Runplugin()

Runplugin sets thread handle to -1 which will have unpredictable results for a plugin passing video via the proper setresolvedurl method (eg like YouTube)

Playmedia sets handle to 0, which is the thread used by the video player so setresolvedurl works properly.

All your tmdbhelper RunScript command does is make sure the things happen in the right order - it tells tmdbhelper to stop managing the info dialog, to close the info dialog and the 1190 custom base window, then to use the PlayMedia() builtin to play the path supplied.

Main reason it is working is because it uses playmedia() not runplugin().

**Comment by Hawkedon** [comment]
Thanks! :)
