### ISSUE TITLE
[BUG] Widget item scroll automatically

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/plugin.video.themoviedb.helper#736]
Hi @jurialmunkey, I added several widgets which are backed by the TMDB Helper addon, but found the items in the widgets scrolled automatically. The scroll seemed randomly, most of them just scrolled to the end of the list, but one of them scrolled to the middle of the list, and several others didn't scroll at all. I tried to enable/disable "Autoscroll widgets" option in skin settings but that didn't help on the issue. I found the issue mainly occurs when AutoWidget refreshed its widgets, but these affected widgets are not from AutoWidgets. I set the widget items count to 25 if that matters and am using AH1 skin.

**Comment by jurialmunkey** [comment]
Skin issue. Plugins don't have any control over skin behaviour, they just provide the listitems for display.

**Comment by jurialmunkey** [comment]
BTW The "Autoscroll widgets" option in skin settings is the only thing that changes scrolling in AH1. However, if I remember correctly (it's been a while since I used the AH1) the "Banner" and also "Fullscreen" widgets always autoscroll unless focused.

Also note Kodi will keep the focus position when a list refreshes. If the new list of items contains the item that was previous focused for that list then Kodi will switch to that position. If the list doesn't contain the previous focused item then Kodi will retain the focus position.

For example:

- I have a widget "Random Popular Movies"
- It contains the movie "Batman" at position 6, which I move to
- After watching something, Kodi refreshes all containers so I end up with a new set of "Random" items
- By chance, Batman is also in that new set of items but is in position 10
- Kodi switches focus in that list to position 10
- Next time it refreshes, the list doesn't contain Batman so Kodi keeps position 10 for that list.


Either way, plugin has no control over the container it is in. Once the items are created for the container, the plugin is no longer active. That is, you only see the items on screen _after_ the plugin script has completed and handed over the items to Kodi.

**Comment by Hawkedon** [comment]
Got it. Thanks @jurialmunkey!
