### ISSUE TITLE
[BUG] Trakt information is retrieving even I didn't enable it

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/plugin.video.themoviedb.helper#739]
Hi @jurialmunkey, to speed up TMDB helper, I unchecked/changed settings that I don't need, but still found Trakt rating requests from log. Is Trakt a mandatary for TMDB helper? I'm using AH1, and changed the "disabletraktrating" skin setting to true, and I can't see any Trakt rating from the skin anymore. seems this rating request is from TMDB helper directly, not from skin.

> DEBUG <general>: [plugin.video.themoviedb.helper]
                                                   HTTP Error Code: 404
                                                   Request: https://api.trakt.tv//shows/tt0946832/seasons/1/episodes/1/ratings
                                                   Headers: {'trakt-api-version': '2', 'trakt-api-key': '', 'Content-Type': 'application/json'}

**Comment by jurialmunkey** [comment]
You can't disable individual rating lookups in the service monitor. Even if you could, it wouldn't really give you any real extra performance because rating lookups occur in a separate thread from other item details.

To see what sections of the service monitor you can disable, please see the wiki
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor

The only thing that might give a real performance increase is disabling extended properties (all the indexed Cast.X.Name type properties if you don't need those). 
`Skin.SetBool(TMDbHelper.DisableExtendedProperties)`

The performance boost it gives is because it skips setting that data to window properties. If you consider all the variations of Cast/Crew/Director/Writer/Editor/Sound/Design etc. and that each one has a Name/ID/Icon/Role, you can see how it can easily go into 1000s of properties having to be set and then cleared when moving to the next item. 

For example, a movie with 50 cast + 50 crew will have 600 properties just for cast/crew (50x4 for cast + 50x4 for crew + 50x4 for individual crew roles).

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey!
