### ISSUE TITLE
Weird issue where I cannot update to 4.8.0

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/plugin.video.themoviedb.helper#743]
I'm not sure what's going on. When I navigate to your repo and hit "Information" then "Versions", I see your repo listed twice and both entries have checkmarks on them. But when I go to "My Add-ons" then "Add-on repos", I only see your repo once.

At the same time, when I force check your repo for updates, 4.8.0 doesn't show up. The version I see is 4.7.40.

Are these issues related?

**Comment by drinfernoo** [comment]
@jurialmunkey squeaked a couple updates past me 😅 The latest version available on the repo *was* 4.7.40, but I've just updated it with 4.8.1.

**Comment by ambulancePilot** [comment]
Oh that's great, thank you! Any insight into the repo showing up twice in the versions list? Also having the same issue with S*r*e* where the addon shows twice in the versions list.

**Comment by drinfernoo** [comment]
Likely you have a different repo installed that "includes" the contents of @jurialmunkey's repo. Often these are repositories for skins (as the developer feels they need to include it for the latest dependency versions), but it could be anything. Unfortunately, this is a pretty common practice amongst third-party repositories, but isn't strictly necessary in most cases, and more often than not, ends up leading to these "oddities" in repository resolution.

EDIT: Also, it appears you may have typed `S_r_e*`, which I can only assume is a thinly veiled attempt at masking a third-party add-on... That symptom is likely caused by the same thing as I mentioned above.

**Comment by ambulancePilot** [comment]
Thanks for your response. I don't think that's the issue however. I have included a screenshot. There is no other place to obtain the repo from in my setup. And you can see it is referring to the same source twice, hence the check mark on both. Correct me if I'm wrong, but if they were from different sources, the checkmark only exists on the source which was last used to install the repo, even if version numbers are the same.

https://imgur.com/a/Wy0nNeA
https://i.imgur.com/5UregJ1.png

This exact thing is happening with the third-party add-on. Checkmarks on both and it is listed twice from the **same** repo.
