### ISSUE TITLE
Question around Library Integration 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/plugin.video.themoviedb.helper#745]
Hey,

I trust you're well.

Due to the fact you're looking at support mdblist.com,
I wanted to give you're library integration another go.

Now, I know I will be wrong as you often correct me, but stay with me here for a moment. 

So, using mdblist, I have created let's say 8 different and separate genres, which are then uploaded into trakt... perfect all there and all ok.

Now, using mdblist, I have all those categories go into 1 list, so for my library integration it makes it easier, as I am only adding one list instead of 8.......

Now, obviously that list on its own, is over the limit for your library integration due to the API(2500) which I totally get your reasoning behind this.
BUT wouldn't it cause my api hits for tmdb to go into 8 separate trakt genres to do a daily update to see what has hit each one, as opposed to it just looking in 1 folder to find if any new movies have been added?

As always I hope I make sense.

**Comment by jurialmunkey** [comment]
Library integration is intended for movies that you are at least considering watching. If you just want to browse things, you should use TMDbHelper's normal browsing functions. 

The point of the limit isn't to force you to split up lists into chunks of 2500 movies. The point of the limit is that expecting to watch 2500+ movies is ridiculous. Even if you watched a movie every single day, it would take you 7 years to get through 2500 movies.

You shouldn't be asking free services to supply you with data and artwork for 1000s of movies that you will never even consider watching just so you can keep an offline catalogue of every movie in existence. I'm not saying you should watch _every_ movie that you add, but there should be at least some curation to keep to things that you are at least vaguely interested in.

**Comment by adamosborne83** [comment]
> Library integration is intended for movies that you are at least considering watching. If you just want to browse things, you should use TMDbHelper's normal browsing functions.
> 
> The point of the limit isn't to force you to split up lists into chunks of 2500 movies. The point of the limit is that expecting to watch 2500+ movies is ridiculous. Even if you watched a movie every single day, it would take you 7 years to get through 2500 movies.
> 
> You shouldn't be asking free services to supply you with data and artwork for 1000s of movies that you will never even consider watching just so you can keep an offline catalogue of every movie in existence. I'm not saying you should watch _every_ movie that you add, but there should be at least some curation to keep to things that you are at least vaguely interested in.

No that is fair, but, I do pay for omdb for the ratings, I pay for mdblist to create, and I'm going to become vip member for trakt.
I totally agree I shouldn't be extensively using their service for free.
I also, buy 'coffee' for developers, a lot of time and work go into what people do, and I get a lot of enjoyment out of it, and yes it is a lot of movies to collect etc.

Anyway appreciate the response.

**Comment by jurialmunkey** [comment]
TMDb is the main provider of the data. The impact on Trakt is very minimal as it only provides textfiles with a list of IDs. The services that provide artwork such as Fanart.TV and TMDb bear the brunt of the traffic.

I don't say these things about artwork usage lightly or without reason. I say it because exactly these types of behaviours are what caused Trakt to disable external artwork requests in 2016. We already lost one really great source of artwork, we don't want to lose others.

You can read more about Trakt's decision to disable artwork requests here: 
https://apiblog.trakt.tv/trakt-api-images-56b43c356427

As a simple example: TMDbHelper has approximately 100,000 daily unique users. If each of those users scanned 2500 movies with 1mb worth of artwork, that is ~250 terabytes of artwork data.

Now obviously this artwork gets cached, so it isn't daily. However, Kodi does refresh cached images from time to time, so lets say artwork cache expires after 2 weeks. That means we're hitting half a petabyte a month of data. In the blog post, Trakt said a petabyte of monthly data usage cost them $20,000 a month...

So you can see why these types of usage patterns are concerning. The only reason my key doesn't get disabled is because obviously only a small minority of users actively try to bypass the reasonable limits I set.
