### ISSUE TITLE
[Feature] Your In-Progress TV shows with All Seasons and All Episodes

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#748]
Hi @jurialmunkey,

Could you please create a list similar to "Your In-Progress" TV Shows where I can see all the Seasons and Episodes, both watched and unwatched, and where they will be first divided into seasons and every season will have their own episodes, unlike now where all the seasons and episodes are merged under the particular TV Show?

The list should be something like "Your recently watched" TV Shows list but where my hidden items are not visible. At present "Your recently watched" TV Shows list is showing both hidden and unhidden Trakt items together. Otherwise that list was also fine.

Is this possible? Kindly advise. Thanks in advance!

**Comment by jurialmunkey** [comment]
Context menu > browse lists > seasons

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Actually, I wanted to use this list as a widget. Something like a Netflix kind of view, where all my unhidden In-Progress/Recently Watched TV Shows will be available, sorted by All Seasons and then by All Episodes under the Seasons. The current Recently Watched TV Shows list was fine, but it is showing my Trakt hidden items also. I want to see only the unhidden items. Is this possible?

**Comment by florence-wolfe** [comment]
An additional use-case with a smaller scope: having an All Seasons list, even paginated, would allow for playing any random episode of a show very easily using the [Play Random Videos add-on](https://kodi.wiki/view/Add-on:Play_Random_Videos) context menu, among probably other helpful functions

**Comment by jurialmunkey** [comment]
> An additional use-case with a smaller scope: having an All Seasons list, even paginated, would allow for playing any random episode of a show very easily using the [Play Random Videos add-on](https://kodi.wiki/view/Add-on:Play_Random_Videos) context menu, among probably other helpful functions

That's not what this issue is about.

In-Progress TV Shows only displays the "Up Next" episodes when you click on a show. ShibajiCh wanted a way to also see the watched episodes when clicking on a show. The watched episodes can be seen by using the Browse Lists > Seasons.

If you want an "All Seasons" folder inside TV Shows, please open a separate feature request.

@francis-robert - Also please note that the "flatten seasons" option already exists. That will make tvshows skip the seasons folder and directly open into an "All Seasons" view.
