### ISSUE TITLE
Database_v? deleted folders

### ISSUE THREAD

**Issue by chapas** [jurialmunkey/plugin.video.themoviedb.helper#752]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/1e39e111e1e6d31951ea85e63c30c7b91403ccd3/resources/lib/monitor/cronjob.py#L17-L19

Then on kodi.log I'm getting errors:

```
ERROR <general>: GetDirectory - Error getting /home/osmc/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database/
ERROR <general>: GetDirectory - Error getting /home/osmc/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v2/
 INFO <general>: [plugin.video.themoviedb.helper]
                 Expecting value: line 1 column 1 (char 0)
ERROR <general>: GetDirectory - Error getting /home/osmc/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v3/
ERROR <general>: GetDirectory - Error getting /home/osmc/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v4/
```

Should this be `DEBUG` or `INFO` instead of `ERROR` ?

**Comment by jurialmunkey** [comment]
It's a clean up of old database folders. It's just kodi throwing a file not found error because it was already previously deleted. 

I could check for the folder first but it's not really worth bothering just to suppress a log mesaage - either file is there and gets deleted or it's not there so nothing happens because can't delete nothing.
