### ISSUE TITLE
Could you try v4.8.9? episode numbers missing 

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/plugin.video.themoviedb.helper#757]
Could you try v4.8.9?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.8.9

Also make sure you have enabled 
`TMDbH Settings > Accounts > Get resume points from Trakt`

@jurialmunkey sorry one more bug I might have noticed is with tmdb helper it doesn't show episode numbers in TV Show Watchlist. Pic below comparing plug in and TVDB. Thank you

TVDB no episodes numbers

![image](https://user-images.githubusercontent.com/63697905/172973981-8866a59d-5415-4452-82df-23ed7aecbbdc.jpeg)

Plug-In showing episode numbers

![image](https://user-images.githubusercontent.com/63697905/172974058-13fc5529-a91d-42cc-8230-d53d7345ca67.jpeg)

**Comment by jurialmunkey** [comment]
Check under tmdbhelper settings for trakt that the setting to show unwatched counts only for inprogress shows is disabled. 

If that setting is enabled you will only see unwatched counts fir shows that you've watched at least one episode for (and since watchlist shows are unwatched you won't see counts)

**Comment by derrgoo** [comment]
Lol that did the trick 👍👍
