### ISSUE TITLE
[BUG] Won’t display links it finds in addons

### ISSUE THREAD

**Issue by bearstalker** [jurialmunkey/plugin.video.themoviedb.helper#760]
if I use tmdb helper to search for links using (as an example) scrubs v2 or nightwing, it will find the links but then reports an error, without displaying the links, directing me to check my log file.
If I use the addon directly it will find and display the links. I first thaught it was the addon (scrubs v2 or nightwing) causing the problem but after checking, it only does it when using tmdb helper and certain addons.
If I use tmdb helper and select the oath addon it searches and displays the links.

**Debug log**
http://paste.ubuntu.com/p/9frZ4nk6cb

I’m sorry if this link isn’t the correct place to upload the full log to, but I’m using a tv box and I’m not sure exactly how to get the log file and upload it to the recommended place. This was the only way I could come up with to upload the full log.

**Screenshots**

![EDB0C451-9E2A-4349-B3AC-2F5490540ECA](https://user-images.githubusercontent.com/107275584/173138849-e8ea6176-d27b-4c15-bab5-fae5e2a93638.jpeg)

**Additional context**
To replicate the error I used tmdb helper, using either scrubs v2 or nightwing addon and search for westworld season 1 episode 1. Its happened a number of times before when searching for other things but I’m using this as a good example.

**Checklist**
- [x] I have described the bug and included steps to reproduce the issue
- [x] I have included a full kodi debug log of the error

**Comment by jurialmunkey** [comment]
Not a tmdbhelper issue. Probably third party player is configured incorrectly.

Most common causes are not using the _url affix for plugin url keys or not setting setresolvedurl to false when the plugin uses hacks to xbmc.player

**Comment by jurialmunkey** [comment]
See wiki for detailed information about making player files and key affixes
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes-for-plugin-uri

**Comment by bearstalker** [comment]
Ok, thanks for replying

**Comment by jurialmunkey** [comment]
@bearstalker I assume that you are using this player file
https://github.com/a4k-openproject/json.openplayers/blob/tmdbhelper/direct.scrubsv2.json

From a quick look I can see that it has several issues. Firstly the parts where it says things like `{title_+}` would likely need to be `{title_url}` (or possibly `{title_url+}` or `{title_escaped}` but usually just `_url` is enough for most plugins) -- same goes for other similar keys like `{clearname_+}` in the plugin:// url.

The second (less important) issue is that it is missing an "is_resolvable" setting. Likely it would need a "is_resolvable": "false", added. However, almost certainly the cause of your problem is the first issue.

**Comment by jurialmunkey** [comment]
Pretty much every player in that repository is going to break as soon as you have special characters or quotes in the metadata (which is why _url encoding is needed on titles/plot etc in the plugin:// url part).

I would recommend mentioning to the maintainers that they need to change their {key_+} keys in the plugin:// urls to {key_url} (I'm not involved in those third party players at all).

I imagine the reason no one bothers fixing these is because it seems like it works for most things -- its only when there's a special character or quote that it breaks.

**Comment by bearstalker** [comment]
I really appreciate you taking a look into this for me, I’m not a coder and don’t really understand much about it, but the way you have explained what the problem is means I now understand and can hopefully  pass this on to someone who can do something about it.

You have my upmost respect.

Thank you!

**Comment by bearstalker** [comment]
I worked out a way to view and edit the player files. I noticed that in the player file for a working addon uses the {title_+} key. 
I manually edited the files from {title_+} to {title_url} and it made no difference, so I’m a little stuck.
I did add the “is_resolvable” : “ false” and it’s stopped the annoying pop up, so that’s some consolation 😝
