### ISSUE TITLE
[BUG] Local videos not playing from TMDBHelper Trakt next up

### ISSUE THREAD

**Issue by roc16** [jurialmunkey/plugin.video.themoviedb.helper#767]
**Describe the bug**
Hi @jurialmunkey - this is similar to a previous issue I raised - https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/339

Some TV shows are not playing from TMDB Helper Trakt Next Up.
Im using version 4.8.12 with Arctic Horizon 2 v 0.1.36
Rolling back to the tmdbhelper version in the kodi repository works fine (4.4.0)
Under players I have it set to automatically play local files

**Debug log**
https://paste.kodi.tv/ujemubuwat.kodi

**Additional context**
If it helps: 

- I first tested with a Seinfeld episode, it just brought up the tmdbhelper player selection box
- I then tested a Modern Family episode and it worked as expected
- I then went into my local library and played the same Seinfeld episode with no issues
- It should all be in the log

**Comment by jurialmunkey** [comment]
@roc16 Could you test the above PR #796 
ZIP: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/heads/fix_incorrect_tvdb_in_player.zip


Below comment more for my future reference as a TODO:

- TVDb has season IDs in addition to tvshow and episode.
- Only _some_ shows on TMDb have this data for the season
- ItemBuild fallback is episode -> season -> tvshow so season ID was taking the place of tvshow.tvdb unique ID
- Current fix is to overwrite this data with the request from Trakt but fallbacks should also be fixed in ItemBuilder (or possibly mapping code -- need to check where it is happening).

**Comment by roc16** [comment]
Thanks @jurialmunkey, at work all day so will test tonight (CET time zone)

**Comment by jurialmunkey** [comment]
No worries at all! Just let me know once you get a chance to test.

**Comment by roc16** [comment]
Working like a charm. Thanks @jurialmunkey !
