### ISSUE TITLE
[question] clarifications about the players 

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/plugin.video.themoviedb.helper#773]
### Is your feature request related to a problem? Please describe.

I am trying to figure out how goes the process when selecting players. I use a low-end device (mi box s) and I have a delay of 4-5 seconds when selecting play until the player (ezra) starts to scrap.  Even on my pc with intel i3 last gen there is some delay of 2 seconds, while when using directly the addon is starts to scrap immediately on box or pc. 

As I see from the  notification, there is some delay at 33% when _"retrieving informations"_. To retrieve the informations moviedb helper start new searches or does already know the necessary info? The information as I see to pass is title, name, year , tmdb id and poster.  [plugin://plugin.video.ezra/?mode=play_media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",]

I suppose that moviedb helper already knows all these info before select to play the item, right? So why it stucks for a while at 33% retrieving these?

*Also, I don't know why is necessary to pass the poster to ezra. Making some tests while having deleted this, it doesn't create any problem. 

### Describe the solution you'd like

I just want to know how exactly works the process and what steps need time and there is some delay and if it could be some workout to make faster. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Without a debug log with TMDbH debug logging setting enabled I can't tell you what is taking time.

When you click play, TMDbHelper does the following

- Get all the player config files from the directory
- Builds the details for the item
  - Retrieves item details from cache (or online if not cached)
  - Formats and encodes item metadata into a format that can be passed to other plugins
- Builds the player dialog
  - Reads each player file and confirms that the corresponding plugin is installed
  - Checks the Kodi library for local file matches (if play with Kodi enabled in settings).
  - Determines player priority and fallbacks based upon provider data, default player, and priority values
- Displays player selection dialog to choose player (or chooses automatically if default player set)
- Follows the rules in the player dialog using the formatted metadata accordingly
- If a playable path is found according to those rules, it is then passed to the appropriate player function depending on the player file is_resolveable flag.

Note that hacky plugins which do not work with is_resolveable=true will be much slower to complete the final handover process because TMDbH is forced to first resolve to a fake video to avoid Kodi errors. Then there is an additional forced delay to avoid a crash, and then the url is passed to Kodi's PlayMedia() to play. The PlayMedia() function requires Kodi to generate another Player thread handle, further delaying things.

Plugins that do things the correct way and work with setResolvedURL will be much faster because this handshake occurs internally using the same Player thread handle that Kodi gave TMDbH when you clicked on the item.

**Comment by georgew21** [comment]
thanks for such detailed answer! this is a log from a testing kodi install on a pc.
* I have set s_resolveable=true as ezra works with this option and also I have disabled to search for match with local files

I chosed two movies to play. In one of them at 00:10:03.385 we have the log "Attempting to play item"and at 00:10:07.137 T:13764  we have the log "finished resolving path to url". 

I don't know if 4 seconds is slow or quick conisdering. I am just wondering if this delay is due to retrieving infromation? 

And if there is a workout or setting to reduce this.

thanks for your time. 

log: https://pastebin.com/gFSq0KCa

**Comment by jurialmunkey** [comment]
I can't access your log. Pastebin says the link expired

**Comment by georgew21** [comment]
[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8955031/kodi.log)
Sorry, I uploaded here.

**Comment by jurialmunkey** [comment]
According to your log, the first time TMDbHelper took 2 seconds. The majority of the time spent is Kodi initializing python and waiting for Ezra. 

The second time it took 4 seconds but there's a lot of Kodi image caching going on in the background so that would be the reason as there would be a CPU and Network bottleneck going on there.

These are the relevant lines from the first time around where there wasn't heaps of texture caching going on.

09:25.787 - You click play and Kodi starts the plugin call routine
```
2022-06-22 00:09:25.787 T:1308    DEBUG <general>: XFILE::CPluginDirectory::StartScript - calling plugin TheMovieDb Helper('plugin://plugin.video.themoviedb.helper/','4','?info=play&tmdb_type=movie&tmdb_id=120','resume:false')
```

09:29.022 - 3 seconds later TMDbHelper router gets command from Kodi (python initializing cost).
```
2022-06-22 00:09:29.022 T:13612    INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.container.router - Attempting to play item
                                                   {'info': 'play', 'tmdb_type': 'movie', 'tmdb_id': '120'}
```

09:31.566 - TMDbHelper hands-over to Ezra. It only took 2 seconds for TMDbH to get item details, build dialog, and follow player instructions to find the correct url
```
2022-06-22 00:09:31.556 T:13612    INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.player - finished resolving path to url
                                                   plugin://plugin.video.ezra/?mode=play_media&media_type=movie&tmdb_id=120&autoplay=false
```

09:31.583 - Kodi starts calling Ezra plugin.
```
2022-06-22 00:09:31.583 T:1308    DEBUG <general>: XFILE::CPluginDirectory::StartScript - calling plugin Ezra('plugin://plugin.video.ezra/','5','?mode=play_media&media_type=movie&tmdb_id=120&autoplay=false','resume:false')
```

09:37.595 - 6 seconds later Ezra plugin does something...
```
2022-06-22 00:09:37.595 T:1308    DEBUG <general>: ------ Window Init (C:\Users\Γιώργος\AppData\Roaming\Kodi\addons\plugin.video.ezra\resources\skins\Default\1080i\yes_no_progress_media.xml) ------
```

So of those 12 seconds spent waiting, 2 were TMDbH, and the rest was python intialization and waiting for Ezra.
