### ISSUE TITLE
[Feature] mode string needed for making an Autowidget shortcut to Authorize Trakt on TheMovieDb Helper

### ISSUE THREAD

**Issue by cg00001** [jurialmunkey/plugin.video.themoviedb.helper#777]
### Is your feature request related to a problem? Please describe.

Autowidget uses something similar to:
plugin://plugin.video.themoviedb.helper/?mode=

But I'm missing the part (if exists) after ?mode= to make it work.

Asgard example:
plugin://plugin.video.asgard?mode=157&url=False

### Describe the solution you'd like

Eg:
plugin://plugin.video.themoviedb.helper/?mode=130

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by cg00001** [comment]
This seems to work but not in Autowidget:
RunScript(plugin.video.themoviedb.helper,authenticate_trakt)

**Comment by jurialmunkey** [comment]
Why would you want a plugin path to authorise Trakt? Either you're authorised and so you can display the list, OR you're not authorised so you can't display the list. Asking for auth on plugin load would be horrible because you'd be reprompted to authorize every time the plugin reloads (i.e. every time you stop watching something) and if you couldn't authorize you'd essentially get locked out in an auth loop.

This sounds like an [XY problem](https://en.wikipedia.org/wiki/XY_problem). Please explain what issue you are trying to solve rather than what solution you think needs to be added.

**Comment by cg00001** [comment]
> Why would you want a plugin path to authorise Trakt? Either you're authorised and so you can display the list, OR you're not authorised so you can't display the list. Asking for auth on plugin load would be horrible because you'd be reprompted to authorize every time the plugin reloads (i.e. every time you stop watching something) and if you couldn't authorize you'd essentially get locked out in an auth loop.
> 
> This sounds like an [XY problem](https://en.wikipedia.org/wiki/XY_problem). Please explain what issue you are trying to solve rather than what solution you think needs to be added.

It's for a Logins folder that helps peeps authorize Trakt & debrid faster, like this:
![k_20220627-102018](https://user-images.githubusercontent.com/38960370/175881884-a2e9a29b-144b-4eb6-af83-3beeed111201.png)

**Comment by cg00001** [comment]
It's an Autowidget issue though, that doesn't handle all Kodi builtins properly.
Closing.
