### ISSUE TITLE
[Feature] Add Select/De-select All for providers selection setting

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/plugin.video.themoviedb.helper#778]
### Is your feature request related to a problem? Please describe.

The list of providers is very long and tedious to select/de-select one by one.

### Describe the solution you'd like

It would be helpful if you could add the ability to select/de-select all on the dialog for selecting which providers are displayed.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
It's not really possible unfortunately due to the way Kodi's multiselect dialog works. 

It could be done with YES/NO dialogs but that would mean that three dialogs are needed because otherwise there is no way to modify your existing choices.

1. Do you want to disable all providers? YES/NO (Y: clears all and goes to 3, N: goto 2)
2. Do you want to enable all providers? YES/NO (Both goto 3 but Y enables all first)
3. Multiselect dialog of providers

I feel like that's really convoluted and not a great solution.
