### ISSUE TITLE
slow menus

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/plugin.video.themoviedb.helper#79]
menus are taking twice as long to load than openinfo or extended info when using menus inside widgets. 
anyway to speed things up to almost match extended or openinfo speed?

**Comment by jurialmunkey** [comment]
What do you mean by "menus"? Are you talking about the context menu?

**Comment by daveftw84** [comment]
content menus, like what movies are trending or what shows are airing today

**Comment by daveftw84** [comment]
using eminence 2 skin and setting widgets to menus in addons takes at least twice as long as "Same" menus in extended info mods

**Comment by jurialmunkey** [comment]
What settings do you have enabled in the addon? A lot of settings increase time considerably.

Do you have any of the following settings enabled? Because all of these increase load times considerably:
`General > Get additional details from kodi library database`
`API Keys > Use fanarttv for additional artwork`
`API Keys > Use fanarttv for widget artwork`
`Accounts > Get watched indicators from Trakt`
`Accounts > Get unwatched episode counts`
`Accounts > Expand trakt list limit to 20 items`

**Comment by daveftw84** [comment]
General > Get additional details from kodi library database

i was trying to have it be a hub for my library

**Comment by jurialmunkey** [comment]
What list are you trying to use because even with everything enabled, it still only takes a couple of seconds at most for the popular list pages to load for me.

**Comment by daveftw84** [comment]
i set API Keys > Use fanarttv for additional artwork
API Keys > Use fanarttv for widget artwork

**Comment by jurialmunkey** [comment]
Yeah fanarttv will slow things down quite a bit, particularly if fanarttv is having connection issues.

**Comment by daveftw84** [comment]
thank you for the great addons. been a fan since eminence on xbmc
