### ISSUE TITLE
[Feature] Display more tv show genres in the TV Genre list section

### ISSUE THREAD

**Issue by metaltermite** [jurialmunkey/plugin.video.themoviedb.helper#792]
### Describe the feature that you'd like

Add additional fundamental genres to the list of tv show genres displayed in *TV Shows > Genres*. The additional genres would be the keywords horror[^ho], romance[^r], thriller[^t], sitcom[^s], history[^h]

### Why is this feature needed? What problem does it solve?

*TV Shows > Genres* provides a list of tv show genres[^genres] from TMDB, but it's very basic and lacks significant genres. I suspect TMDB won't modify their basic list of TV Show genres since they encourage contributors to add them as keywords,

> Feel free to add any "missing" genre as a keyword [...] In the TV section we allow—and encourage!—the use of popular television genres as keywords

So it would be nice if tmdbhelper addon just added these other fundamental genres (keywords) to the genre section: horror[^ho], romance[^r], thriller[^t], sitcom[^s], history[^h]

[^genres]:https://www.themoviedb.org/bible/tv/59f73eb49251416e71000024
[^ho]:https://www.themoviedb.org/keyword/8087-horror/tv
[^r]:https://www.themoviedb.org/keyword/9840-romance/tv
[^t]:https://www.themoviedb.org/keyword/9950-thriller/tv
[^s]:https://www.themoviedb.org/keyword/193171-sitcom/tv
[^h]:https://www.themoviedb.org/keyword/192772-historical-drama/tv

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Why not use discover? You can put any keyword you want into the discover section.

**Comment by metaltermite** [comment]
> Why not use discover? You can put any keyword you want into the discover section.

That's a different use-case that wouldn't work for widgets (that I know of). I use *TV Shows > Genres* to add to a genre widget on AH2.

**Comment by jurialmunkey** [comment]
Have a look at library node editor
https://kodi.wiki/view/Add-on:Library_Node_Editor

Node editor will allow you to make your own library listings

You can create a parent node in the library with child nodes containing whatever TMDbH genre listings and saved discover searches that you want. Then you can add that node as a widget just like any other path.

Mixing keywords and genres inside TMDbHelper is a bad idea because they need different endpoints, so will require special code handling which overcomplicates things. Instead, using a custom library node will allow you to make whatever custom folder of genres/keywords etc. that you want.
