### ISSUE TITLE
[Request] "Trakt Manager"

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#8]
Is it at all possible that in the future we could get the ability to add and/or remove items from lists in Trakt? It would also be great if this included marking watched statuses.

There are a handful of third-party add-ons that have the ability to do this by the Trakt id, which I would imagine this add-on would also have access to 😁

**Comment by jurialmunkey** [comment]
Yeah im actually working on something along these lines.

Basically was thinking of having
Add/Remove to/from collection/watchedhistory/watchlist

I could also do add to custom list. Remove from list is a little more complex and would require a context menu item - so that's a maybe. Reorder item would be a pain and probably better done on trakt website. Same with hide/unhide. 

Are there any other functions that you would need that I've missed?

**Comment by drinfernoo** [comment]
Those all sound good. I can't necessarily think of anything you're missing 👍

**Comment by jurialmunkey** [comment]
Okay I've done Add/Remove to/from collection/watchedhistory/watchlist
Browse to an item in the addon and you will get those options at the bottom. When you add an item to a list, you need to back out and then re-enter for the list to update and show the new details.

Tested with tv/movies, but not episodes yet - I'll have a look at individual episode options tomorrow.

**Comment by jurialmunkey** [comment]
Episodes Watched/Collect should now be working too.

**Comment by jurialmunkey** [comment]
Also added some context menu items for Add/Remove so that it can be done from TMDb Helper widgets.
