### ISSUE TITLE
[Bug] There is no information about the movie or tv show in OSD

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#801]
I noticed one thing. When I turn on tmdb helper option "get resume points from trakt" in osd menu when playing a movie or tv show, skin can't display any information or artwork. Why is this happening? I also tried your skin skin.arctic.horizon.2 same thing happens.

**Comment by matke-84** [comment]
@jurialmunkey OK. This only happens when playing via a skin shortcut on home screen or hub. Also, when I set the player method in the tmdb helper settings to playmedia (false) then I get all info and artworks but we know that is not the solution.

**Comment by matke-84** [comment]
This is a bug though. I have tried many addons, many different scenarios and it definitely only happens when I use tmdb helper as I stated in the first post. When I use the addon directly this bug does not occur.

**Comment by shkope** [comment]
same problem only for movies.
for tv show I have the information in the OSD
I use the BINGIE MOD skin ;)

**Comment by jurialmunkey** [comment]
Setting the resume points via this method is experimental and will have unintentional side effects.

Depending on the timing of when the Kodi DB gets the updated information about resume from JSON-RPC and the item gets set on screen, the items will be blank on occasion. 

Short of significantly delaying the loading of the container to ensure that all resume points have been written and the database closed, there isn't a solution that I've found so far (other than to say to turn off the resume point retrieval which obviously isn't much of a "solution").

**Comment by matke-84** [comment]
@jurialmunkey What is interesting is that when the player is set to PlayMedia (false) everything works as it should (but everything works very slow...). When set to setResolvedURL (true) this problem occurs. Is there any solution here?

**Comment by jurialmunkey** [comment]
> @jurialmunkey What is interesting is that when the player is set to PlayMedia (false) everything works as it should (but everything works very slow...). When set to setResolvedURL (true) this problem occurs. Is there any solution here?

That's just because `setResolvedURL()` attaches the playable video stream path to the original listitem from the container and passes it through to the player all using the same thread handle. 

By contrast PlayMedia() kills that original thread instance and then starts a new thread handle using the end plugin which will then generates a listitem with the attached playable path to pass to the player. 

My assumption as to what causes the blank item is that when JSON-RPC is writing the new resume point, the entry for the item in the database remains open or otherwise appears temporarily blank to Kodi. So when Kodi tries to generate that listitem, it encounters an error and ends up generating a mostly blank item instead of having the properties that TMDbHelper gave it.

With setresolvedURL that blank item just gets passed along (that's the point of setresolvedurl -- it keeps the original item so the details can passthrough to the player). The reason PlayMedia() appears to work is that it forces an entirely new instance that generates a new listitem (and because that's a different listitem it won't appear blank -- but it also means all the original details are lost so the resume point doesn't carry).

As far as I can tell, the only real solution would be to create distance between when the resume point is written and the directory opened -- e.g. a periodic sync could work. Problem is that would then mean writing every single resume point you have, rather than just the ones needed on-demand -- so it could be much slower. It also means that the data won't be available at start-up, so a forced reload of widgets would be needed once the sync completes.

**Comment by matke-84** [comment]
Yes, it's a shame that compromises have to be made. "get resume points from trakt" is a good option but obviously has some drawbacks. I believe that you will find the best solution as always. ;-)
