### ISSUE TITLE
Make Playlist help

### ISSUE THREAD

**Issue by mash2k3** [jurialmunkey/plugin.video.themoviedb.helper#802]
I enabled make_playlist on my player and it does not queue next episodes
Do the players have to be modified to support playlist feature?
Is there there instructions on how to set up make_playlist feature?

**Comment by jurialmunkey** [comment]
Make playlist only works if the player you are using supports setresolvedurl.

Plugins which hack xbmc.player() rather than use the correct setresolvedurl method kodi expects will not work because those hacks overwrite the playlist queue.

**Comment by mash2k3** [comment]
Can you tell me a list of players that support that?

**Comment by jurialmunkey** [comment]
> Can you tell me a list of players that support that?

You would have to look at the code of the plugin or ask the author. I didn't write them so I dont know how they are coded.

I do know that all inputatream adaptive plugins use the correct method e.g Netflix, Amazon and all the slyguy one (Disney, hulu, paramount etc). YouTube, twitch and anything else on the official repo will also do things correctly.

It is only ever banned addons that do things incorrectly because they're all forks of forks doing the same incorrect thing and aren't forced to do things correctly because they never go through code review.

**Comment by mash2k3** [comment]
by setresolvedurl do you mean xbmcplugin.setresolvedurl ()?

**Comment by jurialmunkey** [comment]
> by setresolvedurl do you mean xbmcplugin.setresolvedurl ()?

Yes

**Comment by mash2k3** [comment]
I am still struggling with this, there isnt really much you can get wrong with xbmcplugin.setresolvedurl ()
you import add setresolvedur call with handle, true and list items with stream url arguments

Also for this to work it has to go through tmdb helper?
all my streaming services are added to library via strm that calls the plugin directly
Going through select player is too slow of a process and you cant assign players according to source
hmm could that be an idea, where you can set player according to providor/studio?
Since you cant have more than one default player in tmdb helper maybe we can have another setting for streaming service where it automatically selects a correct player based on provider, given user has enabled setting and the plugin exists.
But the process of streaming service players is a bit slow too, the keyboard auto typing then selecting season then episode

I dont know just ranting at this point

**Comment by jurialmunkey** [comment]
Yes of course you need to go through tmdbhelper for a tmdbhelper function to work. It isn't magic.

If you want a feature in another plugin, then you need to ask that plugin author instead.

Providers are already supported in tmdbhelper. Please read wiki. If the provider is set for the player it gets first priority. There currently isn't a way to autoselect the provider but if you read the other issues you will see that it is planned.


Also you don't need to use the keyboard if the end plugin has a direct search Uri you can use. Or even better, if it has a direct play url you can use. The keyboard method is used in Netflix because it doesn't supply either (or at least it didn't when I wrote the player - I think now it has a search url that can be used directly but not a play url).

If a plugin has a direct play url it will be fastest because it doesnt need to walk directories. Next fastest will be a direct seach url because you can skip the keyboard step and input the query directly into the url. The slowest approach is using tmdbhelper to replicate manually using the plugin.
