### ISSUE TITLE
[BUG] kodi crashes after TV shows

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/plugin.video.themoviedb.helper#806]
### Describe the bug

Good evening,

I trust you're well, I have an issues when playing TV shows.
I am currently on kodi 19.4, using auramod on a firecube.

I will watch an episode, let's say stranger things, get to the end if the episode, then as soon as I go back to my kodi screen, it crashes back to the firecube amazon screen.

### Steps To Reproduce

Trakt trending 
Click on a TV show
Watch show
Finish show

Then blows up my kodi set up.

### Debug log

Https://paste.kodi.tv/fidotesufi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What makes you think this crash is caused by tmdbhelper and not one of your other addons?

**Comment by adamosborne83** [comment]
> What makes you think this crash is caused by tmdbhelper and not one of your other addons?

Good morning, as you know my knowledge Is limited, but, I was asking for help in other places, after much discussion and playing around an numerous crashes, they mention something about Trakt, so they kindly gave me a api.py, to almost stop tmdb helper working as such, but after that no issues at all with crashing..... although obviously nothing in the addonnitself worked.

Sorry if this is too vague.

**Comment by jurialmunkey** [comment]
Yes that is very vague. What is this api.py file that you mention? Where is this discussion?

**Comment by adamosborne83** [comment]
> Yes that is very vague. What is this api.py file that you mention? Where is this discussion?

i commented out the whole get_ratings function in tmdbhelper and made it just return.
but it logs it "'TMDBHelper Would be getting ratings here but commented out'"

Hioefully I will be back with more info soon, apologies again for my vagueness

**Comment by jurialmunkey** [comment]
You're using plugins that set resuselanguageinvoker to true. 
This is broken when using plugins for widgets and will cause Kodi to crash.
https://github.com/umbrellaplug/umbrellaplug.github.io/blob/a62bfb7d9afb93fc0276b4178bc954a9638702f8/matrix/plugin.video.umbrella/addon.xml#L18

I can even see that is the last plugin run in your log, so I suspect that is the source of your crash rather than anything TMDbHelper is doing.

https://github.com/xbmc/xbmc/issues/16844
https://github.com/xbmc/xbmc/issues/21653

**Comment by adamosborne83** [comment]
> 

Thank you so much for the detailed response, May I ask with curiosity, how was this able to work when tmdb helper was on purposely broken as such.

**Comment by jurialmunkey** [comment]
Sorry I don't understand what you're asking.

If you're asking why it still works sometimes -- because the crash only happens if two listings from that same plugin refresh at the same time and the plugin was active immediately before the refresh. On video stop, Kodi refreshes all widgets. It looks like this plugin you're using monitors playback and does something on stop, so it will be active at the moment the containers refresh.

Reuselanguageinvoker reuses the python module name space for subsequent plugin directory listings -- it is an attempt to improve performance by skipping module imports.  I do not know what the exact cause of the crash is, but I suspect that reuselanguageinvoker was only ever tested in the library where plugin directories load one at a time and it wasn't properly tested in an environment where multiple thread instances are all attempting to access the same namespace at the same time.
