### ISSUE TITLE
[Feature] Fallback to english when no synopsis in main language

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/plugin.video.themoviedb.helper#814]
### Describe the feature that you'd like

Fallback to english when no synopsis in main language

### Why is this feature needed? What problem does it solve?

Sometimes there are movies that are only in English. I prefer to read in English than to have a black space.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not possible. The api doesn't provide this option and doing an additional lookup in English per item is way too slow (would double loading time)

**Comment by daviddia5** [comment]
In "Recommendations" when the synopsis is only in English it appears in English. It is when you press to see the complete information when the synopsis disappears.

**Comment by daviddia5** [comment]
When I say synopsis, I mean the plot. The translator 😄

**Comment by jurialmunkey** [comment]
> In "Recommendations" when the synopsis is only in English it appears in English. It is when you press to see the complete information when the synopsis disappears.

Different API call. The lists from TMDb such as Recommendations come with some basic details like plot and title pre-filled for each item. TMDbHelper then merges the information from the detailed item lookup in the language specified for each item. If there's a gap, then the basic details from the base list is used instead (which is why you see the English plot in that case)

When you click an item in Recommendations, the info dialog gets closed so that the new info dialog can open. That means that the Recommendations list is destroyed and that information from the list no longer exists. 

To open the new info dialog, TMDbHelper retrieves the detailed information for the item. Since the original list is destroyed, getting the fallback information would require an additional request in English. Double the amount of requests means the info dialog takes twice as long to open.

**Comment by daviddia5** [comment]
thank you very much for the detailed explanation.
