### ISSUE TITLE
Hide watched in widgets for skins without skin shortcuts. 

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/plugin.video.themoviedb.helper#817]
### Describe the feature that you'd like

So I was trying to figure out why the TMDBH setting was not obeying the "Hide watched in widgets". Assume this is for Trakt watch marks. After poking around I see that it only works with skins that implement skin shortcuts. So for other skins like Xonfluence and others that feature wont work. I see that if I add widget=true to the end of the command it would work. So I was wondering if theres anything you can do to to make this work on non skin shortcut skins? Could there be an option maybe to hide watched for the whole addon and not just widgets maybe? You probably know already that in skins like Xonfluence, you add a section you want as a widget to Kodi favourites, then choose the favorite as a widget to set the widget, so the widget=true tag is not written. Would it cause any harm to make the addon always write widget=true? I dunno, just wanted to find out if theres something you can do. Thanks!

### Why is this feature needed? What problem does it solve?

Would fix "hide watched in widgets" setting for non script.skinshortcuts skins. 

### Steps to reproduce.

Use a no skin shortcuts skin, add the TMDBH section to favorites, choose the favorite as a widget, "Hide watched in widgets" does not work without editing the skin.xxx addon_data/settings.xml to add the widget=true tag.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
> Would it cause any harm to make the addon always write widget=true? 

Yeah that'd be a bad idea.

The widget flag only exists for TMDbHelper to be able to differentiate widget containers from media view containers so that it can apply widget specific settings like hiding the next page item. 

There's no other good way for the plugin to determine this status outside of setting a flag that won't also limit options available to skinners -- e.g. I can't just say all TMDbH containers on the home screen are widgets because then skinners can't use TMDbH for other purposes there.

A lot of things would break if widget specific settings were applied everywhere. It would also limit my ability to add other widget only options in the future because I would always have to consider this corner case scenario.

> I was wondering if theres anything you can do to to make this work on non skin shortcut skins?

I'm fairly hesitant to add workarounds for corner cases. The hack to apply it for skinshortcuts is already ugly. Adding a lot of different workarounds quickly starts getting out of hand and hard to manage.

> you add a section you want as a widget to Kodi favourites, then choose the favorite as a widget to set the widget

Do you have read/write access to your Kodi userdata folder? I know it isn't super convenient but you could edit your favourites manually in a text editor and add the widget param to the path before you add it in the skin.

It's just an xml file, so easy to edit and just pop a `&amp;widget=true` on the end of the path. 

e.g. Here's Star Wars collection in my favourites
`<favourite name="Star Wars Collection">ActivateWindow(10025,&quot;plugin://plugin.video.themoviedb.helper/?info=collection&amp;plugin_category=Star%20Wars%20Collection&amp;tmdb_id=10&amp;tmdb_type=collection&quot;,return)</favourite>`

Just need to add the widget param before the quote end like so:
`<favourite name="Star Wars Collection">ActivateWindow(10025,&quot;plugin://plugin.video.themoviedb.helper/?info=collection&amp;plugin_category=Star%20Wars%20Collection&amp;tmdb_id=10&amp;tmdb_type=collection&amp;widget=true&quot;,return)</favourite>`

**Comment by JayDee696969** [comment]
> Just need to add the widget param before the quote end like so: `<favourite name="Star Wars Collection">ActivateWindow(10025,&quot;plugin://plugin.video.themoviedb.helper/?info=collection&amp;plugin_category=Star%20Wars%20Collection&amp;tmdb_id=10&amp;tmdb_type=collection&amp;widget=true&quot;,return)</favourite>`

Actually yes, that works for me, I can use Super Favorites to accomplish this easily. In SF, theres an Explore Kodi favorites option that opens Kodi favorites, in there I can manually edit the favorite and add the &amp;widget=true to the end, restart Kodi and add the modified Kodi favorite as a widget.
Thanks for the explanation!
