### ISSUE TITLE
[Question] Push items without a date to the end of a list

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#819]
In my Trakt watchlist I have some shows that don't yet have a date. I'm sorting the list using year ascending to get the shows into the correct date order, however any shows without a date ends up at the start of the list. Is there a way to force shows without a data to the end of the list

**Comment by jurialmunkey** [comment]
Can you try v4.10.31? That should push empty year to end when sorting by ascending

I'm assuming you're using TMDbH's internal sorting for Trakt lists and not Kodi's. i.e 
`plugin://plugin.video.themoviedb.helper/?sort_list=True&info=trakt_watchlist&tmdb_type=movie&sort_by=year&sort_how=asc`

**Comment by roidy** [comment]
No, I'm using Kodi's sorting in the list's content. I didn't even know sort_by and sort_how could be added to the query.

The problem is that if used as a widget from skinshortcuts then there's no way to add the sory_by / sort_how to the path, you have to rely on Kodi's list content sorting.

**Comment by roidy** [comment]
Ok, so after some more experimenting the path:-

`plugin://plugin.video.themoviedb.helper?sort_list=True&amp;type=tv&amp;info=trakt_watchlist&amp;sort_by=year&amp;sort_how=asc`

With no sorting of the Kodi list, doesn't work, the list is in a random date order.

With Kodi list sorting `sortby="year" sortorder="ascending"` then the list is correctly sorted in to date order however items with no date are still shown at the start of the list.

**Comment by jurialmunkey** [comment]
I can't do anything about kodi sorting (without putting fake data in which I won't do)

Kodi sort is no good anyway as it only sorts the page.

Internal sort by year works for me but I only tested movies let me double check for tv.

Also tmdbh prompts you to select sorting method of trakt lists when adding via skin shortcuts (unless you use predefined static widgets of course). So something weird is going on if you don't get that option when navigating to the watchlist.

**Comment by jurialmunkey** [comment]
This works correctly for me:
`plugin://plugin.video.themoviedb.helper/?sort_list=True&info=trakt_watchlist&tmdb_type=tv&sort_by=year&sort_how=asc`

Don't forget to swap `&` for `&amp;` if you're applying to xml.

Also check that you aren't applying some other kodi sort method over the top. As long as `<content sortby="" sortorder"">`  then that sorting should be applied correctly. It is also better because the internal sorting of Trakt lists applies to the whole list not just the page.

**Comment by roidy** [comment]
Umm.... This is my Kodi list content:-

`<content sortby="" sortorder="" limit="" target="videos">plugin://plugin.video.themoviedb.helper/?sort_list=True&amp;info=trakt_watchlist&amp;tmdb_type=tv&amp;sort_by=year&amp;sort_how=asc</content>`

This is the result:-

![dateorder](https://user-images.githubusercontent.com/4118048/185566998-d7fb2c50-ef1f-4fc2-8162-794a090b9ded.jpg)

Those dates defiantly aren't in the correct order and I'm not sure why.


> Also tmdbh prompts you to select sorting method of trakt lists when adding via skin shortcuts (unless you use predefined static widgets of course). So something weird is going on if you don't get that option when navigating to the watchlist.

Yep, sorry I completely missed that.... However that only seems to give a sort order of descending (which also still doesn't work for me)

Just to confirm I'm running 4.10.31, I've also tried clearing the cache and deleting the trakt database.

One more unrelated problem, after installing 4.10.31 I've no longer got any TMDBHelper context menu items.

**Comment by jurialmunkey** [comment]
Sort method only applies to year. Sorting by release date is done with `sort_by=released` but it won't work with Trakt watchlist because the sync data only gives years. The premiere dates for watchlist come from the TMDb details which are added after the list is already paginated so not possible to sort internally on that basis. Only option is to use Kodi sort for dates on watchlist.

> One more unrelated problem, after installing 4.10.31 I've no longer got any TMDBHelper context menu items.

I switched to using the proper contextmenu method rather than the hack with item properties that I was using previously. 

Only problem with the proper method is that there's a bug in Matrix where not all context menu items are populated on widgets. However, you can use the context menu add-on to get the missing options for widgets (and also add these items to non-TMDbH listitems too).
https://github.com/jurialmunkey/context.themoviedb.helper

**Comment by roidy** [comment]
> Sort method only applies to year. Sorting by release date is done with `sort_by=released` but it won't work with Trakt watchlist because the sync data only gives years. The premiere dates for watchlist come from the TMDb details which are added after the list is already paginated so not possible to sort internally on that basis. Only option is to use Kodi sort for dates on watchlist.

Ok, thanks for the explanation. I'll just stick to using Kodi's sorting.

>I can't do anything about kodi sorting (without putting fake data in which I won't do)

Could we not have that as an option in the settings. I could then look for the fake year in my skin and replace it with something like 'To Be Confirmed' or 'TBC'

>However, you can use the context menu add-on to get the missing options for widgets (and also add these items to non-TMDbH listitems too).

Thanks, I'll give the context addon a try 👍

**Comment by jurialmunkey** [comment]
@roidy v4.10.32 allows watchlist sync to retrieve extended metadata for expanded sort options

`plugin://plugin.video.themoviedb.helper/?sort_list=True&info=trakt_watchlist&tmdb_type=tv&sort_by=released&sort_how=asc&extended=full`

It is slower than normal sort methods but I think probably not too bad for watchlist since generally you only have a handful of items in it. Hopefully no one ruins it by trying to add thousands of items to their watchlist.

**Comment by roidy** [comment]
Unfortunately it's still doesn't work correctly, the list is now sorted in to the correct date order however the original problem still exists, items with no release date are at the start of the list.

This is the path returned when adding `TV Shows->Watchlist->Watchlist Sort by: Premier` in skinshortcuts

`plugin://plugin.video.themoviedb.helper/?tmdb_type=tv&amp;list_name=Watchlist&amp;tmdb_id=None&amp;info=trakt_watchlist&amp;sort_by=released&amp;sort_how=desc&amp;extended=full&amp;widget=true&amp;reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

Note that `sort_how` is set to descending but the list is returned sorted ascending, which is how I want it anyway, but items without a date still appear at the start of the list.

**Comment by jurialmunkey** [comment]
> Unfortunately it's still doesn't work correctly, the list is now sorted in to the correct date order however the original problem still exists, items with no release date are at the start of the list.

Oops, forgot to add the fallback for premiered.

> Note that sort_how is set to descending but the list is returned sorted ascending, which is how I want it anyway, but items without a date still appear at the start of the list.

That shouldn't happen. It sorts in the correct descending order for me if sort_how=desc is set.

On that topic, I haven't really thought of a good way to allow flipping the order that doesn't end up in an excessive number of levels in the skinshortcuts menu - which is the only real reason why it isn't an option currently.

**Comment by roidy** [comment]
Thanks, that sorted it, and now for some reason desc/asc works as well.

I do think that the default for watch lists (or any release date sorting) should be ascending and not descending. When looking at a watchlist people would want the most recent items first not last.

As to selecting the sort direction could it not just be split at the parent level:-

```
Instead of:-
TV shows -> Watchlist -> Sortby *****

Have:-
TV shows -> Watchlist Ascending -> Sortby *****
         -> Watchlist Descending -> Sortby *****
```

**Comment by jurialmunkey** [comment]
> I do think that the default for watch lists (or any release date sorting) should be ascending and not descending. When looking at a watchlist people would want the most recent items first not last.

Descending *is* most recent items first - e.g. 2022, 2021, 2020, 2019.
Ascending is recent items last - e.g. 2019, 2020, 2021, 2022.

That's why descending is the default because it puts the most recent items first.

> As to selecting the sort direction could it not just be split at the parent level:-

That's what I'm trying to avoid. It already is a bit confusing in skinshortcuts when you get to the sort methods. Adding another level to it will just confuse people more.

**Comment by roidy** [comment]
>Descending is most recent items first - e.g. 2022, 2021, 2020, 2019.
Ascending is recent items last - e.g. 2019, 2020, 2021, 2022.

Sure that's fine for items that are in the past like a recently added list, but in a watched list where dates are in the future you need ascending:-

1 Jan 2022  then 2 Jan 2022 ....... 25 Dec 2022

Nobody wants a Watched list that shows items 6 months away before items that are tomorrow.

>That's what I'm trying to avoid. It already is a bit confusing in skinshortcuts when you get to the sort methods. Adding another level to it will just confuse people more.

I'm not saying add another level. What I said was split the watchlist entry into two different entries so instead of just having one Watchlist entry you'd have two:-

Watchlist Ascending and
Watchlist Descending

![ascdesc](https://user-images.githubusercontent.com/4118048/185654443-7c6d6072-48d6-4b1b-a719-47fe8c61f5b0.jpg)

Just an idea, there may be a better way

**Comment by jurialmunkey** [comment]
> Sure that's fine for items that are in the past like a recently added list, but in a watched list where dates are in the future you need ascending

Ah, I get you. I mostly use my watchlist to trakt movies and shows that I want to watch on the basis of good reviews or friend's recommendations etc. I don't really use it for anticipated items Reversed sort order definitely makes sense if you use the watchlist for anticipated items too.

That actually gives my an idea -- maybe a better solution is an extra option for a "Released Watchlist" that filters out unreleased items (and a counterpart "Anticipated Watchlist"). That mean you can then get newly released shows at the top but skip all the unreleased stuff you can't watch yet.

> I'm not saying add another level. What I said was split the watchlist entry into two different entries so instead of just having one Watchlist entry you'd have two:-

That's an interesting idea. I think it might feel a bit counterintuitive in action though - I think I'd want to choose direction after method rather than the other way around.

I think I might have to bite the bullet and just provide an ascending and descending variants in the list of sort methods. There's probably a few I can skip that only need one option - e.g. I doubt anyone wants to sort with lowest rating/popularity/votes first for any real reason other than curiosity.

**Comment by jurialmunkey** [comment]
Okay v4.10.34 will give some additional directional sorting options. 
It will also give a Watchlist (Released) and a Watchlist (Anticipated) section in addition to the normal Watchlist.

**Watchlist (Released)**
Sorted by Release Descending.
Only contains items where `release < today` AND `release is not None`

**Watchlist (Anticipated)**
Sort by Release Ascending
Only contains items where `release >= today` OR `release is None`

That way both lists should put the most recent items at the start. The standard watchlist will continue to function as normal. Also Watchlist (Anticipated) will ignore hide unaired episode settings so that you can use it even when that's enabled.

**Comment by roidy** [comment]
Perfect, Thanks I really appreciate it 👍
