### ISSUE TITLE
Your in progress TV Shows and Your next episodes do not load

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/plugin.video.themoviedb.helper#822]
### Describe the bug

Noticed today when trying to go into Your next episodes or Your in progress TV shows nothing loads only for those two sections

### Steps To Reproduce

1. Open Trakt section in TMDb  2. When you click on Your in progress TV shows and Your next episodes nothing loads up

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by xyzfre** [comment]
My apologies didn’t get a chance to grab a log was wondering if anybody is experiencing this today or is it a Trakt issue

**Comment by xyzfre** [comment]
https://paste.kodi.tv/omeraxakas.kodi

**Comment by jurialmunkey** [comment]
Should be fixed in v4.10.33

After installing you will need to delete your Trakt cache from `TMDbH Settings > Expert > Delete Cache` and then restart Kodi to force it to refresh the listing immediately.

Otherwise it will resolve itself automatically next time the watched show cache refreshes - i.e. either when an episode is next marked watched on Trakt or the next day when the cache naturally expires (whichever occurs first).


I forgot that the reason I was using full extended metadata there was because Trakt's watched shows sync weirdly doesn't include an aired_episodes count by default. Need the aired episodes count to determine if a show is inprogress (watched < aired) so when I removed that flag it broke. Really wish they would include aired count in the basic request because all the other metadata is completely unnecessary for my purposes and makes it much slower to retrieve when the extended flag is set to full.

**Comment by xyzfre** [comment]
> Should be fixed in v4.10.33
> 
> 
> 
> After installing you will need to delete your Trakt cache from `TMDbH Settings > Expert > Delete Cache` and then restart Kodi to force it to refresh the listing immediately.
> 
> 
> 
> Otherwise it will resolve itself automatically next time the watched show cache refreshes - i.e. either when an episode is next marked watched on Trakt or the next day when the cache naturally expires (whichever occurs first).
> I did exactly as you said both sections are working again ,thank you for fixing this issue and all the hard work that goes into TMDb 
> 
> 
> 
> 
> I forgot that the reason I was using full extended metadata there was because Trakt's watched shows sync weirdly doesn't include an aired_episodes count by default. Need the aired episodes count to determine if a show is inprogress (watched < aired) so when I removed that flag it broke. Really wish they would include aired count in the basic request because all the other metadata is completely unnecessary for my purposes and makes it much slower to retrieve when the extended flag is set to full.

**Comment by xyzfre** [comment]
I did exactly as you said both sections are working again ,thank you for fixing this issue and all the hard work that goes into TMDb
