### ISSUE TITLE
[Questions] library_nextaired limits

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#824]
`plugin://plugin.video.themoviedb.helper/?startdate=0&amp;days=365&amp;info=library_nextaired&amp;widget=true&amp;limit=100&amp;reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

1. Is there a limit to the number of returned items? Regardless of how many days or what limit I set it only returns 27 items which seems to be a rather odd amount.
2. How long is the data cached? When adding new content that should appear in the library_nextaired I always seem to have to delete the trakt database to get it to show.
3.  Why does library_nextaired show all future episodes of a show? By it's very name shouldn't it only return the next airing episode of a show. ie one episode per show

**Comment by jurialmunkey** [comment]
>Why does library_nextaired show all future episodes of a show? By it's very name shouldn't it only return the next airing episode of a show. ie one episode per show

I'll answer this first as I think you're misunderstanding the point of these lists. 

It is not intended to be a list of every next airing episode of every tvshow that you have. The intention is to act as a replacement for the TV Show Next Aired addon's "Guide" calendar - https://kodi.wiki/view/Add-on:TV_Show_-_Next_Aired#TV_Guide

Next Aired guide was a scripted window with a grouplist of lists where each list was one day in the calendar. TMDbH is replicating that behaviour but with the flexibility of providing plugin paths instead of a scripted window so that you aren't forced into a particular layout.

> Is there a limit to the number of returned items? Regardless of how many days or what limit I set it only returns 27 items which seems to be a rather odd amount.

No limit on TMDbH end but definitely a limit on how many items the Trakt calendar returns.

What happens behind the scenes is that TMDbH pulls the ["All Shows" calendar from Trakt ](https://trakt.tv/calendars/shows)for the date range specified. Then it iterates over ever episode from the "All Shows" calendar list and checks if it has a tvshow ID that also exists in the Kodi Db. Every episode with match gets added until it hits the limit specified or the list runs out.

It isn't designed for massive date ranges. It simply won't work well for what you're trying to do

EDIT: Did some tests. Maximum range is one month.

> How long is the data cached? When adding new content that should appear in the library_nextaired I always seem to have to delete the trakt database to get it to show.

6 hours (0.25 days).

**Comment by jurialmunkey** [comment]
Here's an example screenshot of how it is intended to be used which might make it clearer:

![Honeyview_screenshot00156](https://user-images.githubusercontent.com/4618719/185746036-e54ee00f-46fa-47b9-8d13-b460fb9d3b55.jpg)

**Comment by roidy** [comment]
Ok, thanks for the explanation.

So is there a path/widget that will give me the next airing episode for each show in my library, just the next episode and no others, regardless of how far in the future it is?

**Comment by jurialmunkey** [comment]
Unfortunately there isn't really any good way to do it that wouldn't be incredibly slow for larger libraries. Essentially would need to lookup each show in the library individually every day.

Might be a way for trakt watched history/collection  but can't think of any feasible way to do it for the library.

**Comment by roidy** [comment]
Ok, thanks

**Comment by jurialmunkey** [comment]
@roidy - I completely forgot that TMDb also has next aired info - which makes this much simpler to do. Please try v4.10.37
Note if you install manually you also need [script.module.tmdbhelper](https://github.com/jurialmunkey/script.module.tmdbhelper) now (installing from my repo should get it automatically).

Should now have "Library Airing Next" and "Your Airing Next Episodes" options.
`info=library_airingnext`
`info=trakt_airingnext`

Will give a list of the episode airing next for each show in your library (or trakt watched history). It is paginated into pages of 20. Really massive libraries will be slow to calculate. My trakt watched history has just over 260 shows in it though and it wasn't too bad in terms of loading time.

**Comment by roidy** [comment]
Thanks, I'll test those out once I'm back at my computer 👍

**Comment by roidy** [comment]
Just tested, they both work perfectly. That's just what I was looking for, big thanks for that 👍
