### ISSUE TITLE
[BUG] Golden globe rating missing

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#831]
### Describe the bug

I tried to insert golden globe rating into my skin, but it doesn't return anything. I thought it was up to me but I see it doesn't work in AH2 either. I tested by opening a golden globe list and not a single movie gives a golden globe rating.
`$INFO[Window(Home).Property(TMDbHelper.ListItem.GoldenGlobe_Wins),x,  ]`
Small reminder, you forgot to insert some stuff on wiki page, eg golden globe, emmy, top 250.

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Is it in the awards string from omdb? Golden-globes emmys and Oscar counts come from omdb. I don't think omdb gives golden-globes anymore, only emmys and oscars.

**Comment by jurialmunkey** [comment]
@matke-84 - Please try v4.11.2
Getting a lot of additional awards properties from TVDb as an alternative now

'total_awards_won', 'awards_won', 'awards_won_cr', 'academy_awards_won', 'goldenglobe_awards_won',
    'mtv_awards_won', 'criticschoice_awards_won', 'emmy_awards_won', 'sag_awards_won', 'bafta_awards_won',
    'total_awards_nominated', 'awards_nominated', 'awards_nominated_cr', 'academy_awards_nominated',
    'goldenglobe_awards_nominated', 'mtv_awards_nominated', 'criticschoice_awards_nominated',
    'emmy_awards_nominated', 'sag_awards_nominated', 'bafta_awards_nominated'

ie `$INFO[Window(Home).Property(TMDbHelper.ListItem.goldenglobe_awards_won)]`

**Comment by matke-84** [comment]
It works great. 
It's great that you implemented all this fro tvdb. I noticed that only the tvdb lists are behaving a bit strangely. The titles are missing depending on the skin and views, artwork missing in tv shows, instead of plot of movie in the awards lists it says when it was nominated (this is ok, but it would be good if there was a plot), for movies and tv shows, it shows original titles and plots, in the language of movie or tv show...

**Comment by jurialmunkey** [comment]
Tvdb isn't returning a plot for those items. So because I put the award category in the plot field, then when the detailed lookup is done by tmdb it won't merge the plot. It's basically an either of thing - get nomination year details or plot. There's no standard field to put it in, so plot is only real option. 

Also make sure you have get additional details and artwork from TMDb enabled in the settings.

**Comment by matke-84** [comment]
Ok for the plot. But all other things are definitely not right. I also checked with ah2. Go to tvdb list (especially tv show genres)  and check. Landscape row view eg, missing title below images in rows, instead of a landscape image, it shows a poster, shows weird characters for Japanese, Korean.... movies and tv shows.

**Comment by jurialmunkey** [comment]
Yeah I was just looking at this before. I accidentally left some testing code which was forcing the type to movie. Update that fixes that coming shortly. Also added a few additional fixes since TVDb returns original language metadata and I can't see a way to specify a language other than make an additional call for the translation. 

I'm just going to skip that data entirely like plot and title from TVDb and rely on TMDb for it instead. It's a waste of time to do an extra lookup on TVDb for the translations if I've got to do another item detail lookup on TMDb anyway for the rest of the data.

**Comment by matke-84** [comment]
I just tried the new version. Most things have been fixed. However, the title is still missing under the images in the row where the movies are listed, in the lists as well. In ah2 but also in my skin.

**Comment by jurialmunkey** [comment]
Example list? Titles were working fine for me.

EDIT: Nevermind, I see what you're saying. ListItem.Label is empty.

**Comment by matke-84** [comment]
@jurialmunkey It still shows original titles, so it shows empty fields or strange characters for some movies and tv shows.

**Comment by jurialmunkey** [comment]
I have to put the label in when the list is retrieved and only original title is available. Use listitem.title if you need the English title.

**Comment by matke-84** [comment]
Ok.
