### ISSUE TITLE
[Feature] Context menu -> Add to library

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#834]
### Describe the feature that you'd like

Using the context menu 'Add to Kodi Library' could we get the option to just create the base TV show directory without the nfo and strm files.

### Why is this feature needed? What problem does it solve?

I'd like this option so that I can add a show to the library and then use Kodi's 'Hide Empty TV Shows' option so it isn't visible in the library but will still generate next episode data for the 'Airing Next Library' widget.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Why not just make an empty folder yourself?

**Comment by roidy** [comment]
Sure, that's what I'm doing at the moment. But as the addon has an add to library feature it's much more convenient to sit on the sofa in front of the TV and just click the remote rather than have to go to a computer and manually create the folder.

I'll admit, I'm not even sure what the strm files are supposed to do?

--------------------------------------------------------------------------

Actually don't worry about it, I've found a better solution.

**Comment by jurialmunkey** [comment]
The strm files link back to tmdbhelper so that you can have tmdbhelper items mixed directly in your library. Then you can use tmdbhelper to play them via an addon using a player file. 

eg say you want "Stranger Things" in your library to then play via Netflix addon. Tmdbhelper will keep it updated when new episodes drop. Then you can find them in recently added library and play using the Netflix addon via tmdbhelpers player for it. 

Lots of reasons to want addon based content directly in the library and tmdbhelper gives a way to do that without having to worry if each addon you use has that function.
