### ISSUE TITLE
[BUG] Studio logo

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#841]
### Describe the bug

I saw that you made a change to display studio logo. 
But I still can't use it 
$INFO[Window(Home).Property(TMDbHelper.ListItem.Studio),resource://resource.images.studios.coloured/,.png]
still works
$INFO[Window(Home).Property(TMDbHelper.ListItem.Studio.1.Name),resource://resource.images.studios.coloured/,.png]
I don't know if I understood correctly?

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
You need to refresh item details to see the change. Also it is only for the benefit of ListItems not the Service Monitor because those (Name.X.Type) numbered properties are no longer available directly in ListItems without enabling a setting.

ListItem.Studio is a slash separated list `Studio1 / Studio2 / Studio3` etc. so it doesn't work with images. Since `ListItem.Property(Studio.1.Name)` is no longer available from the listitem, I added `ListItem.Property(Studio)` which is the same thing.

It is not necessary to use this from the window properties. Studio.1.Name still exists there. It is purely for the benefit of ListItems

**Comment by matke-84** [comment]
Ohhh. OK. Thank you for explanation.
