### ISSUE TITLE
[BUG] Selecting artwork not working as expected on Apple TV

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/plugin.video.themoviedb.helper#843]
### Describe the bug

This seems to only happen on Apple TV, not on Mac. It just began happening recently. If I try to select artwork, I notice two problems:

1.  After selecting an image, the thumbnail in the dialog does not change
2. After refreshing artwork or selecting new images, widgets are not refreshed to display the new artwork until I kill Kodi and reopen it. 

### Steps To Reproduce

Follow steps above 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
What version of TMDbhelper? Debug log?

**Comment by eengert** [comment]
After updating to v4.11.5 the thumbs now get updated in the dialog, but the artwork on the widget still doesn’t get refreshed until the skin is reloaded.

**Comment by jurialmunkey** [comment]
The widget refreshes correctly for me after choosing a new poster. What widgets are we talking about specifically here?

Also note that TMDbHelper can only automatically force widgets to reload that have the reload parameter on them
`&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]`

If you've edited the widget paths, manually input them, or copied them from somewhere then they may not have that param on the end -- it only gets added when you add items by navigating through TMDbHelper in the skinshortcuts dialog -- if you add widgets some other way it wont be added there. It also won't be on widgets in info dialog or anything like that.

If it doesn't have the param then you need to wait for the widgets to reload normally (i.e. after watching something) or by forcing it with ReloadSkin() to see any change (otherwise Kodi just keeps the old content and metadata loaded).

**Comment by eengert** [comment]
These are widgets that I create by going through the dialogs in AH2 skin settings.  I have one which displays the Trakt Next Episodes from TMDBH, and a couple others which display personal Trakt lists from TMDBH.  I believe that I have seen these widgets refresh immediately after selecting new artwork in the past, but at the moment they won't refresh until I reload the skin.

I guess I could try re-adding the widgets in skin settings and see if that helps.

**Comment by eengert** [comment]
Re-adding the widgets seems to have done the trick.  They now refresh immediately after selecting new artwork.  Thanks.

**Comment by jurialmunkey** [comment]
Hmm that's strange that they lost the property though. Might be something to do with the older version of skinshortcuts.

Unless you've had those widgets set for a long time - then it's possible that you had them set before that property was added in and tmdbh was still using the old method of reloading (change was a few months back). 

The old approach was to force every container to reload on a change, which is a bit of waste for non-tmdbh widgets. This newer property based approach ensures that only tmdbh widgets are reloaded (it adds current timestamp to the property which makes kodi see a new path and refresh the container items)

**Comment by eengert** [comment]
I was a pretty early adopter of AH2 so the widgets have been set for quite a while. That might explain it.
