### ISSUE TITLE
[Feature] Use TMDbHelper clearlogo

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/plugin.video.themoviedb.helper#851]
### Skin section

Fullscreen Video OSD

### Feature description

Not sure if this should be posted here or in TMDbHelper. Also, not sure if this is something you would want to implement. 

I have customized artwork for TMDbHelper where it shows better clearlogo in widgets. But when playing, it uses the artwork that the addon (activated from TMDbHelper players) provides for the OSD.

Would there be a way to instruct the OSD to use the artwork from TMDbHelper instead of the addon? 

### Why is this feature needed? Please justify and explain.

Some addons don't allow the artwork to be customized, so you end up with a really tiny clearlogo, that is multiple lines, rather than one that works well with the skin.

TMDbHelper allows you to customize this artwork, so better clearlogo can be chosen. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Definitely a TMDbHelper matter rather than a skin one.

I guess this only happens when the end player does not use setResolvedURL playback method. With setResolvedURL the metadata should be passed through to the player.

**Comment by jurialmunkey** [comment]
@Kayzels - Please try v4.11.9+ of TMDbHelper
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases

If a cropped logo was previously set and it matches the logo TMDbH has for the playing item, then that logo will be retained. Otherwise TMDbH will fallback to checking the playing item for a logo to crop.

**Comment by Kayzels** [comment]
Thanks for migrating the issue. Also, thanks for trying an implementation in 4.11.9. 

I've tried the latest version of TMDbHelper (4.11.10) on Arctic Horizon 2 (0.4.14) , and it doesn't seem to do it, unfortunately.

I'm not sure if I explained the request properly.

So if I set artwork using the artwork picker in TMDbHelper, then that selects the artwork, and it is used correctly in widgets and when browsing inside TMDbHelper.

If I select an item to play from TMDbHelper, then a player selection dialog comes up. Then I select a player and the item starts playing. However, the artwork that is used in the OSD is the artwork that the addon that the player opens uses.

Instead of the artwork from the addon being called being used, I was hoping there was a way to make the TMDbHelper artwork persist.

That's tricky, though, cuz how does the skin know to use TMDbHelper instead of the addon artwork?

That's why I thought it was a skin issue. My initial thought was that, on playback of an item, the skin could check if a logo exists for the item from TMDbHelper, and use that if it exists. 

With that, even if an item is not played from TMDbHelper, but a custom logo has been chosen in TMDbHelper, that would be used. 

I'm not sure whether that would be a good idea or not, or something you would want to do?

**Comment by jurialmunkey** [comment]
Yeah I understood what you meant. That's what the recent update is meant to do - the logo cropped when in a media window is meant to continue to be used when the player opens as long as tmdbhelper gets the same ID for the item in the player. - if the end player starts playing something else where the ID doesn't match, we don't want to override in case it is a playlist of different items or the player actually got the wrong item. But if tmdbhelper is getting the same ID then the artwork should persist (well technically it gets reset again separately for the player but tmdbh should pick the same art again to crop as long as it was the same ID as before)

Possibly I missed something where a property is clearing before it gets a chance to check it.

Also note that if you change artwork for an item, sometimes it takes a kodi restart for the service monitor (sets the crop) to pick up the changes since that runs in its own continuous thread and the db sometimes persists in memory to reduce disk reads.

**Comment by Kayzels** [comment]
@jurialmunkey  This was working, your change did help. The issue was I had it to use library content. So what happened was:
Plugin artwork loads -> Replaced by TMDb Helper selection -> Replaced by library artwork.
