### ISSUE TITLE
[Feature Request] Having a way to notify us that we have been logged out of Trakt. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/plugin.video.themoviedb.helper#855]
### Describe the feature that you'd like

An option that says "Enable Account Expiry Notifications" that could help and notify us if we have been disconnected from Trakt.

### Why is this feature needed? What problem does it solve?

Reason why i think this feature is needed is cause Trakt sometimes has problems and it can also disconnect users from there services sometimes. 

This problem does not really solve anything except that it would notify us that we have been disconnected and it would help a bunch cause sometimes when i go to recently watched, nothing happens and i have to authenticate it again for some odd reason.  

### Steps to reproduce.

There is really no steps to reproduce cause Trakt is a service that has problems with there site or services sometimes. 

### Screenshots and Additional Info

Hey there, its been a while sense i made a feature request but i was wondering if there was a way to notify us that we have been logged out of Trakt. Sometime Trakt can have outages or the website can be down or something could de-authenticate the user sometimes and i had this happen to me like 3 times and sometimes i don't know about it. if we could have an option that could remind us if our trakt has been expired or disconnected, That would be very much appreciated.  Seren has something like this and it helps me a bunch. 

![image](https://user-images.githubusercontent.com/62456796/189467918-c6564083-46a0-48d4-90d4-298493272ff4.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
The trakt token should automatically get refreshed once it expires. There's no need to reauthenticate unless your settings were corrupted and the token was lost (e.g. you killed Kodi while it was writing to disk) OR if Trakt themselves lost the auth credentials (that would be a very major issue). I haven't needed to reauthorise Trakt at all this year.

If the server is timing out then the server is timing out. There are already notifications when this occurs (the "connection error: suppressing retries" messages). Reauthing Trakt does not solve server timeouts. You're just getting confirmation bias where the server happened to come back online and accept your connection because you were forced to wait while you reauthorised.

If you are having real issues with token refreshes failing, please report the bug so I can fix it. Reauthorising should be entirely unnecessary as Trakt has an endpoint to refresh expired tokens.

**Comment by Goldenfreddy0703** [comment]
Wait so sense you haven't needed to reauthorize Trakt at all this year. Are you able to go to any of the Trakt menus and all without any issues? I sometime had that happen to me but there is a possibility that its just not me.

**Comment by jurialmunkey** [comment]
Yes occasionally the Trakt server will refuse the connection. That will mean you get a blank directory because no data can be retrieved from Trakt. It doesn't mean that you were deauthorised; it simply means that the server was too busy to serve you.

When a connection is refused (timeout, server down etc.), TMDbHelper will suppress any retries to that server for 30 seconds. If you attempt to reopen that directory before that suppression finishes then you will get no response.

TMDbHelper suppresses connection attempts in all threads when this happens because if our requests are being denied, then continuing to flood the server with more requests in other threads isn't going to help us. All it will do is kick us further down the rate limit queue. Instead, TMDbHelper forces a breather to allow the rate limit on the server to reset.

**Comment by Goldenfreddy0703** [comment]
Ohhh ok makes sense, Thank you very much for explaining this to me. I always thought it was a bug or problem but now i understand more. 

Again Thank you very much and sorry for taking a little bit of your time. 
Thank you
