### ISSUE TITLE
[Feature] Mixed content from providers

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#872]
### Describe the feature that you'd like

Is there a widget path to get mixed content from a provider?

Movies->Provider->Netflix - Contains Netflix movies
TV Shows->Provider->Netflix - Contains Netflix TV shows

Mixed->Provider->Netflix - Contains a random mix of movies and shows from Netflix

Is this possible or could it be added?

### Why is this feature needed? What problem does it solve?

I would just like a widget with mixed content from a provider.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Not really unfortunately. The providers section is just a short-cut to discover with the with_watch_providers prefilled and there's no combined discover endpoint on TMDb

The only way to do it would be to fake it by getting two lists and then using zip() to interleave them. Not particularly great as won't be able to apply any sort methods or additional params since most of the discover params aren't transferable between tv and movies. You'd end up with this really sterile list of movie>tv>movie>tv>movie>tv.

**Comment by drinfernoo** [comment]
@roidy You could use Merged Widgets from AutoWidget for this. Essentially, you can merge the contents of two paths together, and should still be able to apply widget sorting, etc...

**Comment by roidy** [comment]
@jurialmunkey Thanks. After interleaving the lists with zip could you not just shuffle it. I don't need any other discover params on the lists, I just need a widget filled with random movies and shows from the same provider.

@drinfernoo Thanks, I've never used AutoWidget before I'll have a look into, however I'd much rather have a solution that doesn't require another add-on.

**Comment by jurialmunkey** [comment]
@roidy - It wouldn't be random. It'd just be page=1 of both lists combined in a random order. Can't get random items from discover - if you want random items, the best way is autogenerated Trakt list via a service like listrr or mdblist

**Comment by roidy** [comment]
Ok, thanks, I'll look into mdblist's
