### ISSUE TITLE
personal trakt list sync deleting movies

### ISSUE THREAD

**Issue by Vincent2601zh** [jurialmunkey/plugin.video.themoviedb.helper#875]
### Describe the bug

When deleting a movie from my private movies list it still keeps popping up in movies library after updating. Also new added movies will not appear in moviedbheper --> trakt --> my list --> movies

### Steps To Reproduce

movidbhelper --> trakt --> my list

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
TMDbHelper cannot delete things from your library. Plugins are not allowed to modify the Kodi database.

After you remove an item from a monitored list, you then need to delete the .strm file and folder that TMDbHelper created in your library source folder. Then you need to clean the Kodi library so that it will remove the entry.
