### ISSUE TITLE
Cropped clearlogo TMDb helper cache

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#878]
### Skin section

Library Views

### Feature description

When using a cropped clearlogo, TMDb helper still saves a cropped version in cache, which doubles the size of the saved clearlogos. Is it possible for TMDb helper to see the clearlogo does not need cropping and so points to the original instead of creating a duplicate in cache?

### Why is this feature needed? Please justify and explain.

Would help on devices that have small storage sizes. As kodi is starting to crash when TMDb cache gets too large (Sony smart tv 8GB storage)

### Screenshots and Additional Info

To reproduce; find an uncropped clearlogo. TMDb helper will then save a cropped version in cache. Then use that cropped version as the clearlogo and clear cache. TMDb helper will then still save a cropped version of the already cropped clearlogo in cache.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Where are these pre-cropped clearlogos coming from? Nearly every clearlogo on fanarttv will have blank space and need cropping.

Are these clearlogos that you've cropped yourself and then saved manually?

**Comment by ghost** [comment]
Hi jurial :)
So the uncropped clearlogos come from fanart.tv, and then I get the cropped version from TMDb helper cropped folder so they are fully cropped (HxW sizes show they are cropped as well). Then using the cropped version as the clearlogo, TMDb helper still then saves another cropped version.

**Comment by jurialmunkey** [comment]
I meant the location where these cropped logos are being stored. Internet? Network drive? Local disk? If it's local disk, I don't really understand why you would save the logos back to the disk if they've already been cropped...

I'm just trying to understand what the actual underlying issue is as the feature request itself sounds a bit like an XY problem
https://en.wikipedia.org/wiki/XY_problem

**Comment by ghost** [comment]
So the clearlogos are stored on a NAS drive. TV has small storage size so the TMDb helper cache starts to slow Kodi down when it gets too big. I thought a solution to that would be to use the cropped TMDb helper versions as the clearlogos on the nas drive, so that TMDb helper does then not need to save cropped versions in the cache.

**Comment by jurialmunkey** [comment]
Ah sorry, I remember now! We tried moving the cache location to the NAS but it didn't work. 

Still, getting an alternative location to work is going to be the only real solution here. Trying to compare the image defeats the purpose of the cache since TMDbHelper would still need to do the image manipulation to check if the clearlogo was cropped.

Can you try v5.0.18? I've added a separate image cache location option and routed it through xbmcvfs which *should* allow for a write to networked storage assuming that you can access the location via Kodi's filemanager and you've added it as source there.
`TMDbHelper Settings > Expert > Cache image location`

**Comment by ghost** [comment]
Updated to 18, location set to NAS, cache cleared and restarted. Blur and crop folders have appeared in NAS and no files are being saved to original cache. Crop is fully working (saving the files to NAS) however blur is not saving any files to the NAS, so flixart are showing as a black blur to top left where logo is. (Which I like to be fair). Legend mate, I don’t know how you do it! Has saved 250mb of cache space.

**Comment by jurialmunkey** [comment]
If you don't want blur in AH2 you just set background to None in customise.

But I want to make sure blur is working because I can't leave it in if it is broken now. ~Can you get me a debug log with TMDbHelper debug logging enabled (expert settings) with the blur~ EDIT: I see the issue

**Comment by jurialmunkey** [comment]
@A3006B - Can you try v5.0.19 and confirm that blur is working properly now for you?

**Comment by alKODIque** [comment]
@jurialmunkey 
I noticed same issue (blur issue) with v 5.0.18... 
I just installed v5.0.19 and it seems working  for me now 👍

**Comment by ghost** [comment]
Yep blur is working on 19 and it is saving them to the NAS

**Comment by jurialmunkey** [comment]
Excellent! Thanks for confirming.

**Comment by ghost** [comment]
Hi jurial :)
Sorry to bother you, TMDb helper updated to v5.0.20 (which I can’t seem to find on GitHub weirdly) and texture maker has updated to v0.2.8. The NAS cache feature seems to have broken. Flixart blur is no longer showing (in the blur folder, the fanart is being saved as temp files but no blur file is being created). And same with the clearlogos (temp files are being created in the crop folder but the logos are not being cropped and enlarged as normal)
