### ISSUE TITLE
Ignore “The” when sorting

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#881]
### Describe the feature that you'd like

There should be an option to ignore the word “The” when sorting lists.

### Why is this feature needed? What problem does it solve?

Most times when sorting “The” is often not used to sort.

### Steps to reproduce.

Go to personal Trakt list > shows are listed including the word The. For example The Bad Batch is shown under T instead of B.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Probably not possible.

TMDb api doesn't have the option afaik, so it wouldn't be possible for TMDb lists. 

Trakt lists might be possible but I'm not sure about performance. It would need to be manually sorted client side. I expect it will be much slower on large lists because a regex would need to be applied to every item.

**Comment by jurialmunkey** [comment]
5.0.17 adds an option in the Trakt settings to "Ignore articles when sorting alphabetically". This will ignore "The" at the start of titles when using the Browse Sorted List: Titles (A-Z) option.
