### ISSUE TITLE
[Feature] Recommendations script video play

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#885]
### Describe the feature that you'd like

It would be good to implement in tmdb helper possibility to return to recommended dialog after the finished or stopped video (trailer). This existed in old extended info. If I'm not mistaken, it's roughly this.
https://github.com/matke-84/script.extendedinfo/blob/d7b4185b312245316e13920f4dad8a955b3cdd6d/resources/lib/WindowManager.py#L247
https://github.com/matke-84/script.module.kodi65/blob/2aa14b26e416ce2217136df375d8c459e5389e8d/lib/kodi65/player.py#L39

### Why is this feature needed? What problem does it solve?

I saw that you applied it to youtube trailers in ah2 custom dialog for video play, but I think this is a much better solution, of course if it's possible.

### Steps to reproduce.

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Returning to the dialog after ending playback is possible and relatively trivial to do - I just think it's a bad idea to take away control from the user and force open a dialog. There's so many ways it can go wrong (e.g. playback fails) or not be the expected behaviour (e.g. user navigates elsewhere).

It's already bad enough when backtracking that you're forced to go back through every dialog -- I don't want to create *more* scenarios where the user is fighting against the controls. If you want to keep the info dialog open to play a trailer, it is relatively trivial to start playback minimised and open a videowindow control *on top of* the dialog.

**Comment by matke-84** [comment]
Ok. It's not big deal. I have already done something.
