### ISSUE TITLE
Documentation for new windows.

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#888]
Is there any documentation for the new script-tmdbhelper-recommendations.xml window? I can't seem to find anything in the wiki.

**Comment by jurialmunkey** [comment]
Not yet. I'll write up something soon. I haven't quite finalised a few things, so I didn't want to give people the impression that it was set in stone yet -- things might still change (though I think I'm fairly happy with it generally at the moment)

Have a look at the comments in the code for a basic outline: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/matrix/resources/lib/window/recommendations.py#L30-L53

There was also very quick discussion in this thread which will give you the basics: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/868

Otherwise, have a look a AH2 for some of the more up-to-date features like passing info via $WINPROP[] (only necessary for working with RTL/BIDI text like Arabic and Hebrew since the RunScript mangles it).

**Comment by roidy** [comment]
Thanks, I did try to follow AH2's code but ended up going down a rabbit hole of nested includes :D I'll have a look at the other resources you pointed to.

**Comment by jurialmunkey** [comment]
FYI - Just added info about wikipedia window.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Wikipedia

Will add docs for recommendations and new service monitor container method soon.

**Comment by roidy** [comment]
> Will add docs for recommendations and new service monitor container method soon.

Thanks 👍

**Comment by jurialmunkey** [comment]
Recommendations
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Recommendations-Dialog

Container Method for Service Monitor
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#container-method

**Comment by roidy** [comment]
Very detailed, thank you 👍
