### ISSUE TITLE
Trakt list default sorting

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/plugin.video.themoviedb.helper#89]
Hi Jurialmunkey. I was adding some Trakt lists as widgets and couldn't work out why lists always don't appear to change, always showing the same items, so I compared them on Trakt and worked out the sorting used in TMBD helper is "Rank" meaning it lists most popular items first but Trakt sorts by "Recently Added" as default meaning the list starts with the newest items first. This is most evident in giladg's "Latest Releases". Could you please consider changing your default sorting to be the same as Trackt. Thankyou.

**Comment by jurialmunkey** [comment]
Trakt api doesn't expose sorting methods except for watchlist unfortunately. There was a discussion about this in a previous issue (I'll link it here when I find it)

**Comment by brentonv** [comment]
Thanks for investigating this. I can sort the list from the Kodi list view screen but sorting options for widgets within AZ2 skin settings have no effect. How does OpenMeta achieve correct sorting using the same list?

**Comment by brentonv** [comment]
I put in a request with Trakt. Hopefully they change it. https://github.com/trakt/api-help/issues/147

**Comment by brentonv** [comment]
I put in a request with Trakt. Hopefully they change it. www\github\trakt\api-help\issues\148

**Comment by jurialmunkey** [comment]
> 
> 
> Thanks for investigating this. I can sort the list from the Kodi list view screen but sorting options for widgets within AZ2 skin settings have no effect. How does OpenMeta achieve correct sorting using the same list?

I think because they have that as a built in list, they would pull the whole list first, sort it in the plugin, cache the results, and then paginate the cached results. It's possible to do (the actual trakt website does client side sorting this way) - the big issue is that the user would need to choose the sorting method *before* the list is opened because it is too time costly to retrieve details for the entire list (whereas on Trakt website they just use their own artwork and details, so it's much quicker - but artwork from Trakt isn't available on the API because a bunch of third parties abused the feature).

Can't sort after as the plugin isn't active once the list is created (control is returned to user/kodi) and built in kodi sort methods only sort the visible page. To do it before is also a problem because how does the user select it - if I show a dialog pop-up when the list loads, then that will pop-up everytime you use a widget.

I can think of one way to do it sort of how like the discover method works (rule configuration page before actually loading the list). That would require a bit of a rewrite but I think I'll look into it as things like latest releases aren't very useful if they ignore their default sorting methods and force sorting by rating for all trakt lists.

**Comment by brentonv** [comment]
I've tried latest release tv and movie widgets and yes they aren't much use as they rarely change. Trakt replied saying they can't change the default because too many apps would be affected. They replied "You should be to handle the sorting in your app and sort using the listed_at value.". I hope you can find a solution. Thankyou

**Comment by jurialmunkey** [comment]
@brentonv - Please test latest version. User lists should now be sorted by when they were listed instead of rating. 

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/de826a840808e0b7e351fed342ce9bfd9abda8de

**Comment by brentonv** [comment]
Omg that was fast. Will let you know. Thank you so much!

**Comment by brentonv** [comment]
Just confirming it works great. Love your work!!! Thanks again

**Comment by jurialmunkey** [comment]
Excellent thanks for confirming!
