### ISSUE TITLE
[BUG] Recommendation "List_All" property doesn't work properly

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#895]
### Describe the bug

As the title says I don't think this is working properly. Since youtube certainly throws out some trailer, you may not have noticed that this container, if it is empty, will not hide. I tested by putting a tmdb videos instead of youtube. The TV show from image doesn't have a trailer on tmdb, but container was left empty in order to hide it like the others.
`[!String.IsEmpty(Window.Property(List_All_Visible)) | !String.IsEmpty(Window.Property(List_All_IsUpdating))]`

![video](https://user-images.githubusercontent.com/74268331/193750377-9e719b37-f5c2-4fac-8274-ae78702dd8d8.png)

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
The List_All_IsUpdating property was removed - I just forgot to update AH2 accordingly. 

The list lookups are threaded now so the property doesn't have any meaningful information. The parent thread will complete before the child threads (and thus the All_IsUpdating property is cleared before they finish updating).

**Comment by jurialmunkey** [comment]
In 5.0.12 I have changed the name of `List_All_IsVisible` to `List_Main_IsVisible`. This property is set once the first list has loaded and the other loading threads have all been started (i.e. so that you can delay a custom container visibility until after all the main threads have started).

**Comment by matke-84** [comment]
Now there is no trailer at all. :-) I installed both updates (tmdb helper and ah2).

**Comment by jurialmunkey** [comment]
That's why I didn't make a release of that change in the skin. But that's only a skin issue. The script is working properly.

**Comment by matke-84** [comment]
I don't know. I tried with:
`!String.IsEmpty(Window.Property(List_Main_Visible))`
without Updating property.
The same thing happens.

**Comment by matke-84** [comment]
If you did a fix for this bug in the last ah2 update, then something is definitely wrong with the script. It simply won't hide empty content.
![bug1](https://user-images.githubusercontent.com/74268331/193879172-f782bc9e-e690-4e04-a931-81f6690c99ac.png)
![bug2](https://user-images.githubusercontent.com/74268331/193879610-913bf69f-5d49-4ac6-94cd-fb663767b00b.png)

**Comment by jurialmunkey** [comment]
Like I said. I didn't make release, so it is not ready for release. There is an issue with the skin code. It's not the script.

**Comment by matke-84** [comment]
Ok. Sorry.

**Comment by jurialmunkey** [comment]
Looking into it further, it's a Kodi problem. Usually the built-in boolean Container.IsUpdating will be True when the window loads and then Kodi will toggle it to False once the container loads. With a scripted window the IsUpdating booleans starts on False and Kodi only sets it to True after a delay.

That means if your visibility is `Container.IsUpdating | !Integer.IsEqual(Container.NumItems,0)` then the container will never load because IsUpdating is false at start and the container needs to be visible to update (unless you force it to always be visible like I was doing).

You can workaround it by ensuring the container remains visible while the scripted containers are loading e.g. by checking checking `String.IsEmpty(Window.Property(List_Main_Visible))` instead.
e.g.
`<visible>Container(ID).IsUpdating | !Integer.IsEqual(Container(ID).NumItems,0) | String.IsEmpty(Window.Property(List_Main_Visible))</visible>`

**Comment by matke-84** [comment]
Yes, this works. Thanks a lot.
