### ISSUE TITLE
Infinite scroll instead of Next page button

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#91]
This is more a question than an issue. Would it be possible to add infinite scrolling for results instead of having to navigate through pages to see videos? I'm under the impression this is more a Kodi limitation than a feature to implement in the addon but I thought it'd be worth asking.

**Comment by jurialmunkey** [comment]
Not possible. It would be loading forever. I've already covered why it's not possible to increase the items past 20 per page: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/56

I guess what you're asking though is that when you reach then end of the list, to automatically load the next page and add it to the end of the list. That's not possible either because once the plugin has loaded the results, the script ends and has no more control. It would need to be a scripted window instead of a plugin and then you wouldn't be able to use anything as a widget and skinners would need to make custom skins for it.
