### ISSUE TITLE
[Feature] TMDb Artwork Select from Other Languages

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/plugin.video.themoviedb.helper#911]
### Describe the feature that you'd like

In the select artwork menu, if there is no artwork for the current language, would it be possible to check for artwork in different languages?

I am currently watching a Swedish show (Young Royals). The title (even in Sweden) is in English. So the clearlogos are classified as Swedish on TMDb. This means that only the primary clearlogo shows up in the select artwork panel. I would like to select different artwork that shows up on the TMDb website, but not in the select artwork panel. Would there be a way to populate this data? I would assume it would be an API request change.

Or rather than populating all the foreign artwork, populate it for the main language of the title, as well as the user language?

### Why is this feature needed? What problem does it solve?

This would allow more artwork to be available. When watching a foreign movie or TV show where the original title is the same as English, artwork from that language should be usable.

### Steps to reproduce.

1. Open context menu for the TV show (in this case, Young Royals)
2. Go to TMDbHelper options
3. Select manage artwork
4. Go to clearlogo
5. One one clearlogo is shown, which is the TMDb primary clearlogo
6. But if you go to the TMDb website, there are five (three Swedish, two Russian)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
You should fix this on the TMDb website. If the logos are English they should be classified as English (or at least should be reuploaded as English in addition to Swedish).

It can be fixed by editing the artwork page (I just uploaded a png for one of the English logos now)
https://www.themoviedb.org/tv/125910-young-royals/images/logos?image_language=sv

There's no way to address this issue from the TMDbHelper end.  There is no API call to get *all* languages - see https://www.themoviedb.org/talk/5aa948870e0a263dc10354db

It is possible to specify _additional_ languages to retrieve but they must be defined individually. It'd probably be unwise to specify all possible language codes otherwise there would already be a wildcard option.
