### ISSUE TITLE
[BUG] Not working "Fallback to english" in Fanart.tv posters

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/plugin.video.themoviedb.helper#914]
### Describe the bug

Not working "Fallback to english when main language unavailable" in Fanart.tv posters. Instead It takes the poster without text (language 00)

![IMG_2022-10-19-18-01-32-527](https://user-images.githubusercontent.com/74454397/196745994-f5ea01a7-af9e-4160-9b11-a9177a94184c.jpg)

It should take the poster with English language (en). When the poster is available in my language it works correctly.

![IMG_2022-10-19-18-03-36-029~2](https://user-images.githubusercontent.com/74454397/196746301-e66054c4-bd05-43c7-a14b-03d8c53064bf.jpg)

### Steps To Reproduce

1. Change language to Spanish (Spain)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by daviddia5** [comment]
This is how it should appear

![IMG_2022-10-19-18-44-48-058](https://user-images.githubusercontent.com/74454397/196754098-a7079d8e-b9be-48ad-9a3f-43fce6c67fac.jpg)

**Comment by jurialmunkey** [comment]
it is working correctly - that is intentional. 

Preference order is always main language then no language. Enabling fallback to English will only fall back if both fail

The point of the option is that some non-English speakers *never* want English artwork and would prefer no artwork over artwork they cant read. Whereas others prefer to have some artwork even if it is in the wrong language.

**Comment by daviddia5** [comment]
Thanks for your kind reply.

I have opened the bug because this only happens to me with fanart.tv.
If I choose TMDB it does put the titles in English on the posters when they are not in my language.

This makes sense because many movies have the same title (Top Gun, Hellraiser...) and English is taken as the universal language.

The same goes for the plot (I already put it in another post) I prefer to see a description in English than to see nothing 🥹

![IMG_2022-10-20-02-39-20-609](https://user-images.githubusercontent.com/74454397/196830064-ce755964-a5ad-43b0-8c3c-9d5f3f830857.jpg)

At the design level, a poster without a title or an empty info screen is not very appropriate. At least in my humble opinion.

**Comment by alKODIque** [comment]
@daviddia5 
The plot and title are provided by Themoviedb.org.. When no information are showing, it's due to the fact that no translation has been done to the website. 
I personnaly write translation  when this happen on my side. 
Once done, you'll see the change ! 
(themoviedb.org is a comunity maintained website. if no one helps with translation, no information will be provided in other language)

**Comment by jurialmunkey** [comment]
When fanarttv is disabled, no additional artwork is added. The fall back setting only applies to fanarttv because that is an additional lookup which retrieves the full list of artwork and then selects based upon rules. 

It isn't relevant to TMDb - if fanarttv is disabled then the poster supplied for the item via the api is used. There is no sorting from a list of artwork to select a "best" choice. The tmdb api determines the poster provided. 

Regardless, you can override artwork choices via the manage artwork context option. The artwork selection process is complicated code in order to merge two different api schemas and there are a lot of corner test cases that need to be considered when changing it. I'm not interested in complicating it further and potentially breaking it again by attempt to provide more fall back options. If you don't like the artwork selected then choose different artwork via the management context option. 

Plot I can't do anything about. It needs to be translated on the website. There is no api option to request a fall back language. Providing a fall back manually would be slow as it would double the requests made so it is not an option. And again, it will excessively complicate the code. The better solution as alkodique points out is to translate the missing text rather than sidestepping it and ignoring it -- the only way these services work is if people bother to contribute to them. Adding workarounds to avoid seeing gaps just leads to neglected entries because there is no motivation to fix the missing data.

**Comment by daviddia5** [comment]
I agree with both, the ideal is to collaborate and that everything is in all available languages.

Only sometimes, in "rare" movies or series (that we discovered thanks to our dear TMDBhelper) this option will never be available.

It is already a matter of priorities in each addon or platform.
For example Elementum uses the main language and if it is not available it always appears in English.
Google TV does the same, prioritizes having information in English before leaving an empty tab. 

Curious fact: In OSD info (AH2), the plot does appear in English if it is not available in my language, thing that I appreciate 😊
ADD: If I'm not mistaken I think it's because it takes the Elementun data

**Comment by jurialmunkey** [comment]
> this option will never be available

Nonsense.

Create an account on TMDb and add the translation yourself.

https://www.themoviedb.org/movie/766220-old-man/edit

There's nothing stopping you from adding the missing translations.  I'm not going to add language fallbacks just so you can avoid contributing.

**Comment by daviddia5** [comment]
Of course I can and will contribute, I'm not trying to avoid anything.
I just think it would be much more complete if it had that option, because you can't always contribute everything.
It's just my opinion, as respectable as your decision to do or not do anything.
Thank you, as always, for your time.

**Comment by jurialmunkey** [comment]
I already explained that the TMDb api does not provide a fallback language option. Retrieving a fallback would require requesting every item twice - once in the main language and once in the fallback language. That would slow things down.

**Comment by daviddia5** [comment]
All clarified 😉 
I understand that we are many and each one has their personal tastes.
I really appreciate your work and your way of doing it globalized, nowadays I can't conceive Kodi without TMDB Helper or AH2.
Thanks again 😊
