### ISSUE TITLE
[BUG] TMDBH adds 10-45 seconds to resume point after scrobbling using Trakt.py 

### ISSUE THREAD

**Issue by rtuRgALp** [jurialmunkey/plugin.video.themoviedb.helper#921]
### Describe the bug

I use TMDBH with the official Trakt add-on and Umbrella as my player. 

I set TMDBH to sync resume points so I am able to resume playback and use the setResolvedUrl to play it back from the Trakt resume point using Umbrella. Scrobbling is turned off in Umbrella and I let the Trakt add on handle that. 

The issue is that for some reason TMDBH keeps fast forwarding my resume point by like 10-45 seconds after a container refresh. If I stay in the In Progress Episodes folder, I am able to resume from the exact point, but the second I leave and come back, the resume point gets fast forwarded for some reason. 

### Steps To Reproduce

1. Install TMDBH
2. Authorize Trakt
3. Set to sync resume points 
4. Install umbrella
5. Set umbrella auto play as default player 
6. Install official trakt add on
7. Authorize with Trakt
8. Play content from Trakt folder in TMDBH
9. Leave folder after stopping playback
10. Come back and see resume point ahead of actual stop point 

### Debug log

https://paste.kodi.tv/umikakazar

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Not a TMDbHelper issue. Everything is working correctly here. That's what Trakt scrobbled as the resume point. Because you enabled the setting to use resume points from Trakt, then Kodi's local resume point is being overwritten with Trakt data.

- When you stop the movie, Kodi saves a resume point for that TMDbHelper playback url to its *local* database.
- Additionally, Trakt add-on scrobbles the resume point to your Trakt account
- When a TMDbHelper directory is (re)loaded, it checks Trakt for a resume point because that's what you told it to do.
- TMDbHelper then follows your setting to *overwrite* Kodi's local resume point with the remote one retrieved from Trakt

When you play the item again immediately you are using Kodi's local resume point - which will be exactly the time you stopped at. When you exit the directory and reopen it, the data will be pulled from Trakt.

The reason it differs on Trakt can be for two reasons

1. Trakt addon didn't scrobble it exactly and was a little off
2. The video duration differs from the "official" duration (progress is a percentage of elapsed time over total duration)

Simple solution - if you play everything via TMDbHelper and don't need to sync resume across multiple devices, then you should disable Trakt resume points as the local resume points should be enough (also syncing Trakt resume back to Kodi is an experimental feature which occassionally causes blank items - also it adds a fair bit of additional loading time, so better to disable it if not needed).

This is the advantage of plugins that use setresolvedURL. Kodi is able to manage the resume point itself automatically.
