### ISSUE TITLE
[Help] Problem returning to DialogVideoInfo from new recommendations xml

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#927]
I'm having a problem when returning from the new recommendations xml to the original DialogVideoInfo xml.

This short video demonstrates the issue (pause to read subtitles):- https://streamable.com/lqsziq

Basically I open DialogVideoInfo from a Kodi Library item and the dialog is populated with info from the Kodi database. I then navigate through the new recommendations window and back to the original DialogVideoInfo, however on return the original DialogVideoInfo is now populated with data from TMDB instead of the original Kodi library data.

I sure it's probably something I'm doing wrong and not a problem with the script, I just can't figure it out.

**Comment by jurialmunkey** [comment]
This is expected behaviour and a small side effect of how the window manager needs to work.

Basically it is impossible to have multiple video info dialogs open, so instead the recommendations dialog stores each listitem in memory and then passes it to xbmcgui Dialog class when backtracking so that it can open that info dialog. 

The problem is that the window manager doesn't have access to the initial listitem since it wasn't opened via the script (kodi opened the original info dialog). So there's no listitem available to save and instead the recommendations dialog reconstructs it using online data.

If you have the setting to retrieve additional details from the library then it should at least merge that data back into the item - - but also possible I've overlooked something when I did a refactor of the container handling code a while back - let me know if that setting doesn't seem to be working for the detailed item and I'll look into it.

**Comment by roidy** [comment]
Thanks, I've tried with retrieve additional details from the library turned on but on return to the original DialogVideoInfo I still get data pulled from TMDb instead of the Kodi library.

Another example after turning on retrieve additional details from the library.
![screenshot00003](https://user-images.githubusercontent.com/4118048/198960391-cfedba84-8901-49eb-98d0-f4861ab1a90b.jpg)

**Comment by jurialmunkey** [comment]
Ah okay definitely not merging properly there as artwork preference is always library first.

You might get some additional online details from the merge (e.g. the writer) but the library metadata should get first preference because the online metadata is pulled first and then the dictionary is updated with library info.

**Comment by jurialmunkey** [comment]
Hmm, I can't reproduce. The details are merging correctly for me. I even tried with this exact show and different artwork setup in library and TMDbH. I'm getting my library artwork.

What library scraper do you use for TV shows?

**Comment by roidy** [comment]
I use the default TMDb TV Shows scraper in Nexus. I'll try clearing out the scripts cache and see if that fixes it.

Edit:- Nope, clearing the cache didn't help.

**Comment by roidy** [comment]
The really strange thing is that the image in the dialog on return doesn't exist on any of the sites as a backdrop????

**Comment by jurialmunkey** [comment]
> The really strange thing is that the image in the dialog on return doesn't exist on any of the sites as a backdrop????

Do you mean for Andor? Because that's actually the background I have. Pretty sure it is on TMDb

EDIT: Yep it's this one
https://image.tmdb.org/t/p/original/exkpAvXB0r9p6pYFll4XjaxcE9u.jpg

You're right though, it isn't showing on the website under the media section. I assume someone is trying to remove it but it'd still be cached in the api

**Comment by roidy** [comment]
Ok, so I completely removed the show Andor from my Kodi library and cleaned the library. I then re-added the show and chose a completely different background.

This is what I get now, original dialog then the version on return:- 
![screenshot00005](https://user-images.githubusercontent.com/4118048/198973603-957edea5-01dd-407f-8114-f5c6722f65a6.jpg)

After digging deeper through my library this is the only show I can find that has this problem, any other show I can change the artwork and it works fine returning the correct artwork on going back the the original dialogvideoinfo.

**Comment by roidy** [comment]
Just to make sure it's not a problem with my skin I tried the show in your AH2 skin, with the same result:-
![screenshot00007](https://user-images.githubusercontent.com/4118048/198975398-10c75ca0-0f68-40ea-92ef-c18a1b0f6bda.jpg)

**Comment by jurialmunkey** [comment]
Can you get me a debug log with TMDbH debug logging enabled. That might give a better understanding of what is happening.

The only way I can replicate this behaviour is if I disable the setting to add library info (which defeats the purpose).

~It's really odd that your return info is saying 0 seasons, as that's not the info on TMDb. Also odd that you've got the older backdrop - I've got that in my library because I scraped it a while back but when I go via TMDbH search I actually get the artwork you've currently got in your library~ EDIT: I see you've already dealt with that.

**Comment by jurialmunkey** [comment]
It's definitely TMDbHelper not merging with the library details. I'm just not sure why. Usually this type of thing happens when the IDs or other info doesn't match up. That's why I asked what scraper because if it was TVDb, then it would probably just be an ID mismatch between the two services -- but with TMDb scraper defintiely should match easily using TMDb IDs.

**Comment by roidy** [comment]
Ok, so after deleting everything from the \addon_data\plugin.video.themoviedb.helper directory except my setting.xml it's now working perfectly. I can change the artwork and it returns the correct version now.

I think I added the show as an empty folder before it aired to track it and that was why I was getting that original backdrop that no longer exists. Thanks for all the help 👍
