### ISSUE TITLE
PVR windows look-ups

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/plugin.video.themoviedb.helper#930]
### Describe the bug

In AH2 skin, TMDBHelper look-ups for PVR windows used to work well, but since the last few updates, fanart in the background and data details has been only been showing for TV shows which has season and episode details in EPG, it's not showing for movies or TV shows with no season and episode number.

### Steps To Reproduce

Under AH2 skin settings - Details - TMDbHelper look-ups for PVR windows option is ticked.
Expected behavior: Movies and TV shoows fanart and data updated under PVR  information windows and as background in the guide.
Actual behavior: fanart and information is updated only for TV shows with full season and episode numbers in EPG, it will not show for Movies and other TV shows. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Yep, as I thought, just messed up one of the variable fallback values. I forgot that getting an empty info label returns an empty string `""` rather than a `None` type value.

Most of the time there's no difference because python treats any empty value as False. The problem is that when it the value gets type converted back to a string the actual name is used (e.g. `None` becomes `"None"` rather than `""`) and so that changes the name it was looking up in the item cache.
