### ISSUE TITLE
[Help] How to hide control until service monitor is ready

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#951]
Using the new container service monitor method, how do you handle hiding a control until the service monitor has new data to display.

In my DialogInfo.xml I have a hidden list to hold the data:-

```
 <control type="list" id="99999">
   <itemlayout />
   <focusedlayout />
   <width>1</width>
   <height>1</height>
   <left>-1920</left>
</control>
```

I then have a label control:-

```
<control type="label">
    <height>120</height>
    <align>top</align>
    <textcolor>TextBright</textcolor>
    <font>InfoLine</font>
    <label>$INFO[Container(99999).ListItem.Property(Cast.1.Name)]</label>
</control>
```

The problem is that every time I open DialogInfo the label contains the old data from the last item until the service monitor has a chance to update then it changes to the new data and it looks really janky.

I've tried hiding the label using both of the following visible conditions but I still get the label with the old data displayed first:-

```
<visible>String.IsEmpty(Window(Home).Property(TMDbHelper.IsUpdating))</visible>
<visible>!Container(99999).IsUpdating</visible>
```

What's the correct way to handle this?

**Comment by jurialmunkey** [comment]
Yeah, IsUpdating will only be True while the service is actively working on the item. If it is still working on a previous request then it won't update immediately.

Best way to confirm if the item in the container is the same as the current item is to compare filenameandpath. That should be unique and is pulled directly from the underlying item rather than being the equivalent TMDbHelper path.
`String.IsEqual(Container(99999).ListItem.FileNameAndPath,ListItem.FileNameAndPath)`

Also worth mentioning that the idle polling interval is set at 200ms. In AH2 I don't bother with a filenameandpath check because the 400ms delay on the infodialog WindowOpen animation is enough to mask the container update the majority of the time.

**Comment by roidy** [comment]
> Best way to confirm if the item in the container is the same as the current item is to compare filenameandpath. That should be unique and is pulled directly from the underlying item rather than being the equivalent TMDbHelper path.
> `String.IsEqual(Container(99999).ListItem.FileNameAndPath,ListItem.FileNameAndPath)`

Unfortunately that doesn't work for either Library content or plugin content:-

![librarycontent](https://user-images.githubusercontent.com/4118048/205701610-7c3c16f9-fc89-4897-99e6-d95e25c3d4c7.png)
![plugincontent](https://user-images.githubusercontent.com/4118048/205701632-6604dd77-5ddf-49eb-bf0e-2bc0ea32f26a.png)

I'll just try to hide the transition with an animation.

**Comment by jurialmunkey** [comment]
Ah sorry I think it's `container(99999).listitem.property(filenameandpath)`

EDIT: Yep, it's **property**(filenameandpath) because Kodi overwrites filenameandpath automatically. I was getting it mixed up with the window property version where it is tmdbhelper.listitem.filenameandpath

This should work:
`String.IsEqual(Container(99999).ListItem.Property(FileNameAndPath),ListItem.FileNameAndPath)`

**Comment by roidy** [comment]
That works perfect, thanks 👍

**Comment by roidy** [comment]
Quick note:-

>String.IsEqual(Container(99999).ListItem.Property(FileNameAndPath),ListItem.FileNameAndPath)

This only works for playable media items, movies and episodes. Both `Container(99999).ListItem.Property(FileNameAndPath)` and `ListItem.FileNameAndPath` are empty for TV Shows, Seasons and Sets.

A working solution is to use FolderPath:-

`String.IsEqual(Container(99999).ListItem.Property(FolderPath),ListItem.FolderPath)`
