### ISSUE TITLE
[Feature] View Trakt Collection as Movie Sets

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/plugin.video.themoviedb.helper#962]
### Describe the feature that you'd like

I'm not sure if there's already a way to achieve this, but I couldn't find one if there is.  I would like to be able to create a widget that displays my Trakt collection but automatically places the movies into their TMDB Sets/Collections.  So the widget would display movie sets/collections that, if clicked on, would then drill down to display the individual movies within that set.  I know that I can view ALL TMDB collections within TMDBH, but I only want to view the TMDB collections that contain movies from my Trakt collection (or even based on a Trakt list, if that's possible).

### Why is this feature needed? What problem does it solve?

This would make navigating through a large list of collected movies easier.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment]
Sorry going to have to reject this request. There's simply no good way to do this that wouldn't be slow and involve 100s of item lookups at once. I would need to retrieve the details for every single item in the list first and then join the items into sets -- so literally retrieving every single page in the list first before displaying anything.

You know how in Kodi scanning a large library takes several hours? We'd be essentially doing the same thing but on-demand. It'd be a bit faster due to threading and TMDbHelper being more efficient than scrapers generally but you get my point -- if you have a collection of 300 items then TMDbHelper would be needing to do 300 item details lookups to combine your sets in the list. That's 15 pages of items to be retrieved.
