### ISSUE TITLE
[Bug] 401 Unauthorised Error - Missing/Invalid TMDB Key Dialog

### ISSUE THREAD

**Issue by SoulTV** [jurialmunkey/plugin.video.themoviedb.helper#97]
![Screen Shot 2020-02-16 at 1 36 14 AM](https://user-images.githubusercontent.com/49368296/74612951-c615ef00-50cf-11ea-9db0-1896b1062074.png)

I see that someone else had this issue with 2.2.63 and cleared addon data to resolve. I've done that multiple times and it hasn't worked

The only error relating tmdbhelper is:

2020-02-16 15:16:46.436 T:123145358065664  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 401

I can get you the entire log but I don't know if I'm allowed to post that here

**Comment by JayDee696969** [comment]
Yes, i had the same issue. And it keeps coming back for me also. Im wondering if it has something to do with the Auto update tv shows on startup setting in TMDBH library settings.

**Comment by JayDee696969** [comment]
When i disable that setting i dont get the error..try it.

**Comment by SoulTV** [comment]
I've had all of the library options unchecked and it still pops on startup

**Comment by SoulTV** [comment]
I feel like maybe the default key is missing. I would replace it with mine in the xmls but I can't remember where it is...

**Comment by jurialmunkey** [comment]
Debug log please.

**Comment by SoulTV** [comment]
@jurialmunkey 
https://pastebin.com/ZbUfF9yz

**Comment by jurialmunkey** [comment]
@SoulTV - Hmm doesn't tell me much, particularly as your kodi debug log level is being reset to normal for some reason.

Can you try with latest git version and get me the new 401 error message from the log? I've added some extra details to the log message which should hopefully give a better indication of what the request is.

**Comment by SoulTV** [comment]
Not sure what changed but I can't replicate it with the newest one on git

Here's a log https://pastebin.com/k51Avr1X

I don't see any errors

Thank you? lol

@JayDee696969 can you check and see if your error is gone with the newest one on git?

**Comment by Demonseeed** [comment]
This is quite an elusive issue lmao

**Comment by jurialmunkey** [comment]
Hmm very odd. If it comes up again please let me know, as I've never gotten a 401 error and I use the plugin everyday on both libreelec and Windows.

**Comment by SoulTV** [comment]
Will do, I use it daily and have never seen it either. Thx for all the work on this and AZ2 man

**Comment by JayDee696969** [comment]
I will keep an eye on it also..

**Comment by Demonseeed** [comment]
I finally have caught it. 

Here my debug log:
https://pastebin.com/QgM6rMKa

This debug log will have the error in there before you added the new debug information, but it finally happened after you added the new debug information that requested in a previous comment in this thread. 

The problem is I cannot recreate it, it seems that every time I wake up Kodi for the day, I’m on TMDb Helper’s Settings. When I leave, I get the error. I don’t get it again, and functionally - everything seems to work.

**Comment by jurialmunkey** [comment]
This call is wrong:
`Request: https://api.themoviedb.org/3/find/tt11003514/?ref_=nv_sr_srsg_0?api_key=a07324c669cac4d96789197134ce272b&external_source=imdb_id&append_to_response=credits,images,release_dates,content_ratings,external_ids,videos,movie_credits,tv_credits&language=en-US&include_image_language=en,null`

That `/?ref_=nv_sr_srsg_0` should not be there. Looks like an error in the IMDB ID that either TMDb or Trakt has for that item. I'm guessing somewhere their parser for imdb id isn't working properly and is adding an extra bit of the imdb url to the field, which is causing the error.

**Comment by Demonseeed** [comment]
Hmm. Luckily it’s not a very intrusive error. 

So there’s not much that can be done from our end, I assume?

**Comment by jurialmunkey** [comment]
@Demonseeed - Hmm maybe this commit will fix the issue: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/2efd20cb1ec64334db44984a5bd7b6187289ee56

I think the problem is because of the `?` in that extra bit of the imdb_id. 

In a url, the question mark needs to be before the first param because APIs use that character to split the base url from the params in the string. Every other param needs to have an ampersand `&` because the API then splits that param string at those characters, and then each param is broken into key and value by splitting again at `=`

So what we end up with is:
`ref_` = `nv_sr_srsg_0?api_key=a07324c669cac4d96789197134ce272b`

So that means we no longer have an api_key being passed and we get the error that it is invalid.

**Comment by Demonseeed** [comment]
I like it, thank you for the detailed explanations that you always do!

I pushed the update to my system and I’ll let you know if I experience it again 😄
