### ISSUE TITLE
[BUG] Library movies/shows get less subtitles than using TMDBh menus

### ISSUE THREAD

**Issue by rdscorreia74** [jurialmunkey/plugin.video.themoviedb.helper#974]
### Describe the bug

I am getting less subtitles options when I try to play a Library movie/show provided by TMDBh than the same movie/show using TMDBh's menus.
I would expect to see the same amount of subs either using TMDBh's menu or Kodi's Library. Is this to be expected?
Thanks in advance.
Cheers

### Steps To Reproduce

1. setup TMDBh's Library integration
2. add TMDBh's Library to Kodi's Library
3. scan Library contents. Movies and TVShows should be added and presented in Kodi's Library
4. open and play a movie/show from Kodi's Library which is pointing to TMDBh's Library folder
5. after the movie/show starts playing, try to add subtitles using opensubtitles.org Kodi subs addon
6. let's say you get 10 subtitles hits
7. now close the movie and open TMDBh addon
8. browse through TMDBh's menu to find the same movie/show we played from steps 1 through 6.
9. after finding it, play it.
10. while playing try to add subs using opensubtitles.org Kodi subs addon
11. you will get a list with a lot more subs than using the library

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
TMDbHelper isn't responsible for subtitles.

There could be any number of reasons for this behaviour but the main reason will likely be because when you have a library item the metadata attached to it comes from whatever library scraper you use whereas an item inside TMDbHelper will use whatever metadata TMDbHelper retrieves for the item.

When you play something via setresolvedurl, the original listitem is passed through to the Kodi player. So play a library item will mean that library metadata is attached to the item that goes to the player. Play an item via TMDbHelper and TMDbHelper metadata will be attached to the item instead. This is standard Kodi behaviour and not something controllable by TMDbHelper.

Differences in metadata could impact subtitle lookups.

It's also possible you will get different behaviour if you have changed expert settings without understanding what they do -- for instance, restricting the dummy resolve method to library strm will cause the library and TMDbHelper have different behaviour when playing an item. Behaviour could be further impacted by the player file used and its associated settings.

Either way this is not a bug related to TMDbHelper specifically because TMDbHelper does not play anything directly and does not lookup subtitles. There is a range of reasonable explanations for the difference in behaviour.
