### ISSUE TITLE
[BUG]? Fullscreen trailer close dialog video info

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#975]
### Describe the bug

When I enter the Recommendations Dialog, and select youtube trailers, I set it to open a full screen trailer with a command
`<onclick>PlayMedia($INFO[Container(5020).ListItem.FileNameAndPath])</onclick>`
With the `<onup condition="Player.HasVideo">Stop</onup>` and `<ondown condition="Player.HasVideo">Stop</ondown>`, I close the trailer and return to Recommendations Dialog. 
That's ok, but when I press the back button to exit from Recommendations Dialog, instead of opening the video info dialog, it closes everything and puts the focus on home menu.
If I use the command to doesn't open in full screen `<onclick>PlayMedia($INFO[Container(5020).ListItem.FileNameAndPath],1)</onclick>`, then everything is ok. But for some reason if I open the trailer like this then I have a problem on android because there is sound without the picture. Is there any solution here?

### Steps To Reproduce

/

### Debug log

/

### Screenshots and Additional Info

/

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
If you play fullscreen (without the 1 flag) kodi forces the info dialog closed. 

The only solution is to use the 1 flag. If there's no video in your overlay that's a kodi or skin issue. 

Sometimes it happens if you have two videowindow controls kodi will only render to one. You probably have another videowindow control visible somewhere (even if you can't "see" it because it is behind the background or in the base window). Animations can sometimes mess with the controls too.

Either way tmdbhelper doesn't control rendering or playback, so that's a skin or kodi issue.
