### ISSUE TITLE
[BUG] Mark as watched dont works after updating to v5.0.46 Nexus

### ISSUE THREAD

**Issue by urs45** [jurialmunkey/plugin.video.themoviedb.helper#977]
### Describe the bug

Using v5.0.47 now but still:
Episodes dont gets marked watched after watching. Also manual marking dont works, status remains unchanged. 

With Version 4.10.14 from Kodi Add-on repo
it works like thought

I downgraded now version by version to find the last working one. It was 5.0.28, so it seems the bug has been implemented with 5.0.29

### Steps To Reproduce

1. Open Tmdbh while using Skin Arctic Horizon 2 or Arctic Zephyr reloaded
2. Go to Episode list of a Serial
3. Right click on an Episode and choose mark as watched
4. Nothing happens and when you right click on the Episode again you can see the status is unchanged

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by ambulancePilot** [comment]
You can't use that context menu item to do what you're trying to do. You have to enter into the tmdb helper options contact menu and then click Trakt options and then click mark watched in there. The mark watched root list item you are referring to is only for the local watched status of library items.

This is of course assuming you are referring to non-library items from a Trakt list and that you are referring to watch the status as per Trakt.

**Comment by urs45** [comment]
> You can't use that context menu item to do what you're trying to do. You have to enter into the tmdb helper options contact menu and then click Trakt options and then click mark watched in there. The mark watched root list item you are referring to is only for the local watched status of library items.
> 
> This is of course assuming you are referring to non-library items from a Trakt list and that you are referring to watch the status as per Trakt.

No this is a wrong info you have and it works fine until v5.0.28. I never used trakt and never had or used local content. It worked fine in the past. The bug has been implemented with v5.0.29

**Comment by jurialmunkey** [comment]
Need trakt for watch status. Mark as watched is Kodi's internal status and only refers to that specific item in the list rather than the movie itself. 

It will do nothing without trakt because play count will always be 0. Matrix uses a flag for setting watched but that's depreciated in nexus which now uses play count instead to determine status (and 5.0.29 is when I brought in the nexus specific changes to address setinfo depreciation) 

I'll have a look and see if I can get Kodi's internal working again but it might not be possible with the new nexus infotag requirements

**Comment by jurialmunkey** [comment]
Sorry didn't mean to close. Clumsy fingers on phone.

**Comment by jurialmunkey** [comment]
Fixed in v5.0.48

Note that if you enable Trakt watched indicators it will override any Kodi internal playcount value. Then "mark as watched" from Kodi's menu will not work and would need to use Trakt menu instead in that case. However, if you don't use Trakt then Kodi's intenal watched count will be used instead.

**Comment by urs45** [comment]
Wow this was fast. Everything works again.
Glad to see that the new Nexus Infotag requirements still allow it to work.
Thanks a lot. Definitely will have to buy you a coffee. Love TmdbH and AH2 so much.
