### ISSUE TITLE
[BUG] can't play local items

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/plugin.video.themoviedb.helper#984]
### Describe the bug

I can play fine items using Fen except from local items (strm files) that have added using library integration.

### Steps To Reproduce

1. Intergrate library with a trakt list.
2. Try to play an item
3.  You got error.

### Debug log

I updated from 5.45 to 5.47 after the log (There isn't any change).

https://pastebin.com/Pc6Un8Nz

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Based on the error it looks like the plugin author is blocking access from any external route.

He's made it clear he doesn't like people using TMDbHelper for whatever reason. I don't really understand what his beef with me is but if he doesn't want you to use his plugins with TMDbHelper and a recent change has broken access then there's not much I can do about it.

**Comment by jurialmunkey** [comment]
BTW In terms of TMDbHelper -- TMDbHelper is functioning correctly and completing its process.

I'm not 100% sure if the external() check in the other plugin is deliberately done to block access or if the error is even preventing playback at all -- could just be an incidental error but the code suggests a check for external access which then force exits.

Looking at your log it is also very possible that you have a misconfigured player file that is not using the correct `_url` encoding for keys expected by the end plugin. A very common issue I see is player files not using `{title_url}` style keys in plugin:// paths when they actually should be.

See wiki for more details about plugin:// url encoding. It almost always is meant to be _url
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes-for-plugin-uri

**Comment by DROIDshield** [comment]
Man, I read through the whole wiki and came away feeling like I've been hit around the head several times with a sauce pan an I work for HP. Thank god you know what you are talking about. It was interesting but lost the room very quickly indeed. Keep doing what you do, you are definitely an asset to the world of coding.

But if we are talking about local files on my personal drive, I have no problem playing them back with tmdb helper.

**Comment by jurialmunkey** [comment]
> But if we are talking about local files on my personal drive, I have no problem playing them back with tmdb helper.

georgew21 is talking about something different.

TMDbHelper has a library integration function which generates .strm files that are shortcuts to the TMDbHelper player function. These .strm files can be scanned to the library so that TMDbHelper links appear alongside local files.

It's useful for tvshows or movies you might watch on a streaming service but you want to have a link in your library. When you click the .strm in the library it will play the item via TMDbHelper.

> Man, I read through the whole wiki and came away feeling like I've been hit around the head several times with a sauce pan

Wiki is not intended to be a tutorial. It is simply a resource documenting all the features of TMDbHelper.

It covers many advance topics. If you go in with the mindset of reading it from start to end then you'll end up very confused. That's like trying to learn how to drive a car by reading the service manual.

**Comment by DROIDshield** [comment]
I get you and the .strm Icon I've seen. Now I know why and what it doe's. I'm going to try this later too.
