### ISSUE TITLE
Incorrect airdate in "Your Next Episodes" trakt list.

### ISSUE THREAD

**Issue by woodside007** [jurialmunkey/plugin.video.themoviedb.helper#999]
### Describe the bug

The airdates listed for all episodes in the "Your Next Episodes" widget are showing airdates a day ahead of the the actual airdate.
For instance, in the attached images one is a screenshot from trakt "Your Next Episodes" and the other is from trakt airing "Last Week".

In the "Your Next Episodes" list, the airdate shows as airing 02/04/2023 and in the airing "Last Week" widget it shows the correct airdate as 02/03/2022. The "Your Next Episodes" widget is a day ahead. How can I fix that? Thanks.

### Steps To Reproduce

Browse to trakt "Your Next Episodes". Browse to "Last Week" trakt calendar. See the different airdates.

### Screenshots and Additional Info

![next_episodes_day_ahead](https://user-images.githubusercontent.com/8515006/216818488-f3c23d43-fa5a-45d0-ab98-c62d7bca172d.jpg)
![last_week_episodes_airdate](https://user-images.githubusercontent.com/8515006/216818491-71cb3f00-ccee-44ec-a0be-c008d779682b.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
~Do you have correct region set in kodi settings?~ The air date/time is utc and then adjusted according to your region settings in kodi. 

EDIT: Region adjustment for dates are only done for calendar views. I don't bother converting it in other areas as exact date/times are only really important in the calendar. Even if I "fix" it for Your Next Episodes it will still show the unadjusted date elsewhere (e.g. season/episode view) as that info is coming in from TMDb rather than Trakt in those places.

**Comment by woodside007** [comment]
Okay. No problem. It's just that if I use the next up episodes widget from the Umbrella addon (I think it's called "Progress" or something like that in his addon but it's the same next up episodes trakt list) it shows the correct airdates so I was a bit befuddled. I only want to use TMDbHelper widgets so I guess the date it shows doesn't matter that much and I'll just deal with it. Thanks.

**Comment by woodside007** [comment]
@jurialmunkey  Do you mind revisiting this? Shouldn't the airdate label be the same as it shows on the trakt website? I'm confused as to why all the airdates on all episodes of shows would be a day ahead on a widget from your addon if it's being drawn from trakt's API with my credentials (authenticated account). It shows the correct airdate on episodes if I browse their website and look at my progress. Also, it shows the correct airdate if I use the same widget from another authenticated addon drawing from the same trakt API. I don't think it's a regional issue as region is set correctly in Kodi and also in my trakt settings. Thanks.

**Comment by jurialmunkey** [comment]
It's because the data from Trakt is unmodified GMT (UK time utc0). The time needs to be manually adjusted client side according to region. Their website does that adjustment according to your settings which is why you see the time there but the api server does not. 

I only do it for the calendar because I don't want to add extra overhead calculating it elsewhere (it's a small overhead but it's still costs cpu cycles to convert the time stamp)
